### ISSUE TITLE
Excessive RAM allocation

### ISSUE THREAD

**Issue by ghost** [jsdom/jsdom#1151]
The jsdom module is allocating about 50 to 65 mb of ram just by being required. Running the garbage collector has no affect after requiring it.

**Comment by domenic** [comment]
I mean, it contains a lot of code. I'm not sure what you expect to happen here.

**Comment by mrseth** [comment]
It contains less code than the mongod driver and yet it uses over 5 
times the RAM.
I use 6 dependencies on my project, jsdom is using 50% of all RAM used 
by the whole project.

**Comment by domenic** [comment]
How did you measure the code?

**Comment by mrseth** [comment]
http://imgur.com/2oIzHcS 
Did you even bother to measure it before implying it has 50mb of code?

**Comment by domenic** [comment]
Obviously I'm not talking about the on-disk size, but the in-memory size.

**Comment by domenic** [comment]
Anyway, if you'd like to be constructive, it would be great to get a memory profile of jsdom in an idle state, and start making targeted changes as guided by that data.

**Comment by Zirro** [comment]
This issue does not identify a specific problem we can resolve. I'll close this in favour of the other memory-related issues which have more productive discussions.
