### ISSUE TITLE
document.outerHTML shouldn't exist

### ISSUE THREAD

**Issue by djcsdy** [jsdom/jsdom#141]
<code>document.outerHTML</code> shouldn't exist. It's not implemented by any browser or any other DOM implementation that I know about, and it isn't defined by any spec (HTML 5 defines <code>innerHTML</code> and <code>outerHTML</code> on <code>Element</code>, but definitely not on <code>Document</code>). Is there a reason why it was put in?

The same goes for <code>doctype.toString</code>, which I see was put in only to support <code>document.outerHTML</code> (#134). If <code>document.outerHTML</code> is staying then I will fix <code>doctype.toString</code> to work properly!

**Comment by Liberateur** [comment]
Hey hi !

Sorry, but... `jsdom.serializeDocument(document) || document.documentElement.outerHTML`return just domain in html dom string...

All my research for get HTML string with jsdom arrived here.

Script
```
const jsdom = require('jsdom');
jsdom.env({html:'google.fr', done:function(err,win)
{
  console.log(jsdom.serializeDocument(win.document));
  console.log(win.document.documentElement.outerHTML);
  win.close();
}});
```

Return
```
<html><head></head><body>google.fr</body></html>
<html><head></head><body>google.fr</body></html>
```

**Comment by Sebmaster** [comment]
@Liberateur You're using `html` instead of `url`. Of course your link will end up un the resulting output HTML.

**Comment by Liberateur** [comment]
I'm tard, but i love u <3. Thanks !
