### ISSUE TITLE
Add mocks for element scrolling methods

### ISSUE THREAD

**Issue by just-boris** [jsdom/jsdom#1422]
Element prototype has several methods to scroll it, but those methods are commented in [the sources](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/Element.idl#L56-L63).

Why did you do this? For example [window.scrollTo](https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/Window.js#L382) is a function that does nothing, just prints warning in console. I think that it would be okay for `Element.prototype.scroll()` method as well.

**Comment by domenic** [comment]
PR welcome

**Comment by M3kH** [comment]
How far is this issue to be close?

**Comment by thenikso** [comment]
I also needed this, I ended up doing something like this:

```javascript
const el = dom.window.document.querySelector(
    '.myScrollingElement',
  );
el.scrollTop = 12345;
el.dispatchEvent(new dom.window.Event('scroll'));
```

**Comment by jordantomax** [comment]
This affecting me to. I've tried many variations of to override it, such as:

```
Object.defineProperty(window.Element.prototype, 'scrollIntoView', {
  writable: true,
  value: jest.fn()
})
```

But I either get an error that I can't override, or it does nothing. Am I doing something wrong?

**Comment by jessethomson** [comment]
I know this is old, but are you all still open to a PR to change this? 

If scrollX, scrollY, etc are all hardcoded to 0, it seems like it makes sense that `scroll`, `scrollBy`, and `scrollTo` functions on the window object are just stubs. Let me know!

https://github.com/jsdom/jsdom/pull/2626

**Comment by domenic** [comment]
We need to tackle this problem comprehensively. Let's roll discussions into https://github.com/jsdom/jsdom/issues/2751.
