### ISSUE TITLE
`features` and `defaultDocumentFeatures`: different behavior

### ISSUE THREAD

**Issue by vsemozhetbyt** [jsdom/jsdom#1514]
`features` object in the config parameter of `jsdom.jsdom()` redefines only the default properties that are defined in it.

``` js
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

const features = {
  FetchExternalResources: false,
}

const doc = jsdom.jsdom(
  '<html><body><script>console.log("test");</script></body></html>',
  {virtualConsole, features}
);
```

`FetchExternalResources` does not change `ProcessExternalResources` and the script is executed with `test` output.

However, any property not defined in the `defaultDocumentFeatures` seems to be reset to `false`.

``` js
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

jsdom.defaultDocumentFeatures = {
  FetchExternalResources: false,
};

const doc = jsdom.jsdom(
  '<html><body><script>console.log("test");</script></body></html>',
  {virtualConsole}
);
```

No `test` output — `ProcessExternalResources` seems to be `false`.

Moreover, no type check of `defaultDocumentFeatures` is performed. This code does not throw any errors or warnings and all the features seem to be reset to false as well.

``` js
const jsdom = require('jsdom');
const virtualConsole = jsdom.createVirtualConsole().sendTo(console);

jsdom.defaultDocumentFeatures = 0; // or null, or '', or {} etc.

const doc = jsdom.jsdom(
  '<html><body><script>console.log("test");</script></body></html>',
  {virtualConsole}
);
```

If this is a deliberate difference, maybe it should be documented more clear in the **Flexibility** chapter.

**Comment by domenic** [comment]
I'd welcome a pull request fixing this, but I have no intention of further working on the old "features" API. [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) is going to do something quite different and IMO much better.

**Comment by domenic** [comment]
Closing as old API is being deleted in the upcoming v12.
