### ISSUE TITLE
memory/resource leak

### ISSUE THREAD

**Issue by JerrySievert** [jsdom/jsdom#154]
moving over from weld:

```
var fs = require('fs'),
  jsdom = require('./jsdom');

var html = fs.readFileSync("/vms/bricks/test.html", 'utf8');
for (var i = 0; i < 10000; i++) {
  jsdom.env(html, [
    __dirname + "/jquery.js"
  ],
  function(error, window) {
    var $ = window.jQuery;

    $("#key").text("Test");
    $("#value").text("hello");
    console.log($("#test").html());
  });
}
```

let me know if i need to move this up the food chain.  could be a jquery issue, or html5 library.

**Comment by ddeath** [comment]
Well window.close() seems not to work on 0.12.5 :/

**Comment by domenic** [comment]
Node.js is not supported,  for precisely these kinds of reasons (having an outdated VM which does not reliably manage memory)

**Comment by ddeath** [comment]
Well with iojs v 2.3.1 and jsdom v4.0.5 it still not releasing memory.
