### ISSUE TITLE
<base> tag breaks local file injecting by inserting the remote uri in the file path

### ISSUE THREAD

**Issue by stagas** [jsdom/jsdom#156]
This is the code that causes this issue, in level2/html.js lines 14-27:

```
load: function(element, href, callback) {
  var ownerImplementation = element._ownerDocument.implementation, url;

  if (ownerImplementation.hasFeature('FetchExternalResources', element.tagName.toLowerCase())) {
    url = URL.parse(href);
    if (url.hostname) {
      this.download(url, this.enqueue(element, callback));
    }
    else {
      var file = this.resolve(element._ownerDocument, url.pathname); // <-- THIS
      this.readFile(file, this.enqueue(element, callback, file));
    }
  }
},
```

and lines 59-68:

```
resolve: function(document, path) {
  var baseElements = document.getElementsByTagName('base'),
      baseUrl      = document.URL;

  if (baseElements.length > 0) {
    baseUrl = baseElements.item(0).href; // <-- AND THIS
  }

  return URL.resolve(baseUrl, path).replace(/^file:\/\//, '');
},
```

**Comment by thorn0** [comment]
The idea of mixing normal URLs and local files together in one array looks doubtful to me. E.g. let's say we have
```
jsdom.env({ scripts: ["../vendor/jquery.js"], ... });
```
It works until the `url` parameter is added:
```
jsdom.env({ scripts: ["../vendor/jquery.js"], url: 'http://localhost:7531/', ... });
```
The script isn't loaded any more. Moreover it's not very clear how we can make it work again. Prepending `file://` to a relative path doesn't help. Only a custom resource loader helps.

I would definitely much prefer to have a `localScripts` entry in the config parameter, which would work always the same way, that is, by loading the specified files from the file system, regardless of whether the document has a base URL or not.

**Comment by domenic** [comment]
Closing as old API is being deleted in the upcoming v12.
