### ISSUE TITLE
skipExternalResources not working

### ISSUE THREAD

**Issue by PhilippMi** [jsdom/jsdom#1567]
using regex for skipExternalResources does not work.

From what I found out during a bit of debugging, the problem seems to be this line of code: https://github.com/tmpvar/jsdom/blob/13b2326b57ec621c4b75a64966ea23d89d8fce99/lib/jsdom.js#L299
The features are copied using JSON but in the process the Regexps are destroyed. Hence, the check at https://github.com/tmpvar/jsdom/blob/13b2326b57ec621c4b75a64966ea23d89d8fce99/lib/jsdom/living/nodes/DOMImplementation-impl.js#L162 is failing.

**Comment by domenic** [comment]
Nice find.

We'll accept a PR for fixing this, but I at least don't plan on working on this myself; instead I'm focused on [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md) which will obsolete these confusing options.

A workaround in the meantime would be to use a custom resource loader and just return empty bodies, or errors, for the URLs you don't want to pass.

**Comment by PhilippMi** [comment]
Thanks for your help. I was able to use a custom resource loader as a workaround. Something like this:
```javascript
jsdom.env({
    ...
    resourceLoader: function (resource, callback) {
        if (resource.url.hostname === badHost) {
            return callback(null, '');
        } else {
            return resource.defaultFetch(callback);
        }
    }
});
```

**Comment by domenic** [comment]
Closing as old API is being deleted in the upcoming v12.
