### ISSUE TITLE
Few questions: config.done before resourceLoader completes; timeout; scalability; serverless

### ISSUE THREAD

**Issue by VoidMonk** [jsdom/jsdom#1569]
Hey guys, I'm evaluating jsdom for a project, and I have a few questions based on my initial testing:
1. Readme doc mentions that when config.done is invoked: "window will be a fully-loaded window, with all external resources downloaded and scripts executed." But tracing config.done and config.resourceLoader shows that config.resourceLoader is still invoked for scripts even after config.done, which means that not all external resources have been downloaded and scripts executed (as stated in the doc) but config.done called early. Is this expected lifecycle behaviour?
2. Tracing config.resourceLoader shows that sometimes the process just stalls for several seconds on a few scripts (e.g.: stalls after utils.js on https://globalcareers-dynatrace.icims.com/jobs/search?ss=1). Is there a way to specify a timeout for the request/processing of external resources?
3. I guess that jsdom's startup time and upfront resource allocation is small (specially when compared to something like PhantomJS), but if jsdom was to be run at scale (thousands of concurrent requests), then is it alright to just stick to runtime invocation, or would it be better to have some sort of a swarm/pool ready before processing begins?
4. Also, is it possible (and suitable) to host a node.js script with npm modules like jsdom as a serverless function on AWS Lambda? If so, would anyone know how to go about doing so?

Any suggestions or tips will be helpful.

Cheers!

**Comment by TimothyGu** [comment]
Hmm, it's unfortunate that we weren't able to get to this question. In the interim, many things have changed in jsdom (like the new API) that make much of the issue obsolete.

For 3 and 4, I don't think any of us have had experience deploying jsdom in that fashion. Experimentation would probably be the best option.
