### ISSUE TITLE
jsdom throws when an XHR is made for a nonexistent file:// uri

### ISSUE THREAD

**Issue by jcavanagh** [jsdom/jsdom#1579]
When using jsdom with the file: configuration, any relative URLs will throw if they do not exist.

The EventEmitter created in xhr-utils has no error event handler and so EventEmitter rethrows the error.  

Shouldn't jsdom attempt to continue in this case?  A nonexistent file does not necessarily indicate a failure of the page to load, and this makes for a very fragile experience.

**Comment by domenic** [comment]
Yeah, it should act like any other 404. Agreed this is a bug.

**Comment by unional** [comment]
Likely I'm experience similar issue. Repro here: https://github.com/unional/some-issues/tree/jsdom-sys-throw

I call `SystemJS.import()` on a directory with no `package.json`, the error is:

```sh
Error: EISDIR: illegal operation on a directory, read
```

It also break off the flow and exit. Resulting "Uncaught Exception" in the test.

```ts
test('uncaught', async t => {
  let thrown
  try {
    await window.SystemJS.import('plugins/no-package')
  }
  catch (e) {
    // not reached
    thrown = e
  }

  // not reach. Error escaped from the flow.
  t.not(thrown, undefined)
})
```

**Comment by unional** [comment]
I can see that it exit because of this: https://github.com/tmpvar/jsdom/blob/f77cc1e3a9eb38fb7db6affa5a9c3d2acca1b351/lib/jsdom/living/xhr-utils.js#L86

But don't know what's need to be done to fix it. 🌷

**Comment by unional** [comment]
Any idea on how to get this fixed?

**Comment by domenic** [comment]
You could try stepping through the debugger and comparing what code path it goes down for http: 404s vs. file: 404s. Then, working on a patch to fix that so they go down the same path.

**Comment by pascalbayer** [comment]
I guess that could be easily fixed by checking for file existence with `fs.existsSync` before L163 `const readableStream = fs.createReadStream(filePath, { encoding: null });`. This is a show blocker for all our tests that check for proper error handling in case that a file does not exist. Is there any plan to fix that issue soon? I'm also willing to create a PR if there is no plan yet to fix it.

**Comment by pascalbayer** [comment]
```
let readableStream;

if (fs.existsSync(filePath)) {
    readableStream = fs.createReadStream(filePath, { encoding: null });
} else {
    response.emit("error", 'File does not exist');
    client.emit("error", 'File does not exist');
}
```
seems to properly fix the issue

**Comment by domenic** [comment]
Note: some of the earlier posts here stated it should behave like a 404. It appears browsers mostly treat missing file: URL fetches as network errors, not 404. In particular they get an error event, whereas 404s get a load event with responseCode = 404.

Separately, browsers generally don't seem to allow fetching from or to file: URLs with XHR at all. We may want to investigate that in a future (breaking) release.
