### ISSUE TITLE
window.eval undefined in done callback in jsdom.env

### ISSUE THREAD

**Issue by i8-pi** [jsdom/jsdom#1582]
``` javascript
const jsdom = require('jsdom');

jsdom.env('', {
    done: function(err, window) {
        window.eval();
    }
});
```

gives an error

```
TypeError: window.eval is not a function
```

window.eval is present in both the browser from jsdom.jsdom

``` javascript
const jsdom = require('jsdom');

var window = jsdom.jsdom().defaultView;
window.eval();
// Runs successfully
```

**Comment by domenic** [comment]
You have to enable running scripts for window.eval to exist:

```
  features: {
    FetchExternalResources: ["script"],
    ProcessExternalResources: ["script"],
    SkipExternalResources: false
  }
```

In [newapi](https://github.com/tmpvar/jsdom/blob/newapi/lib/newapi1.md), this should become a lot clearer... I hope I have time to merge that into master soon.

**Comment by i8-pi** [comment]
Ah, that works perfectly, thanks. I thought "external" meant "downloaded from the web" when I read the documentation.

Perhaps it would be better if `eval` still existed when not enabled, but is a stub which throws an error describing how to enable it

**Comment by domenic** [comment]
That's a good idea. I'm trying to not invest any more effort into the old API, but I'll remember it for newapi. Cool.

**Comment by Sebmaster** [comment]
> I thought "external" meant "downloaded from the web" when I read the documentation.

That's also the correct understanding. Sadly it implicitly enables both. You could try to disable `FetchExternalResources`, but I'm pretty sure that still enables inline scripts.

**Comment by domenic** [comment]
Closing as old API is being deleted in the upcoming v12.
