### ISSUE TITLE
querySelectorAll throws a syntax error when using the :scope selector

### ISSUE THREAD

**Issue by nilssolanki** [jsdom/jsdom#1607]
The following test-case works in browsers which support the `:scope` selector, but fails in jsdom:

http://jsbin.com/vozebogoja/edit?html,js,output

The error message:

```
SyntaxError
    at HTMLUListElementImpl.<anonymous> (/test/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:83:11)
    at HTMLUListElementImpl.querySelectorAll (/test/node_modules/jsdom/lib/jsdom/utils.js:133:45)
    at HTMLUListElement.querySelectorAll (/test/node_modules/jsdom/lib/jsdom/living/generated/ParentNode.js:39:62)
    at Object.<anonymous> (/test/t.js:15:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

**Comment by dperini** [comment]
I am currently working on additional Selector Level 4 compatibility.
:scope is one of the targeted features I will add asap.

**Comment by GianlucaGuarini** [comment]
@dperini any progress on this? Do you need any help?

**Comment by dperini** [comment]
Any help would be greatly appreciated ... for this specific selector (:scope) several tests are needed. The one proposed above is good but is absolutely insufficient to proceed.

Also most browsers (IE, Safari, Opera and Chrome) do not fully support it (ex: in CSS rules) so using that today is risky and may lead to rendering differences on different engines.

For an example of these differences see: [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope) (open this page in different browsers). Note that atop of this page even Mozilla warns about it's usage:
> "This is an experimental technology
> Because this technology's specification has not stabilized, check the compatibility table for usage in various browsers. Also note that the syntax and behavior of an experimental technology is subject to change in future versions of browsers as the specification changes." 

Also no mentions about :scope at: [Can I use ?](http://caniuse.com/#search=%3Ascope)

However I already said it will be added as soon as I can (if possible), given that there are other priorities I am working on currently.

So if you already have a patch or ideas about it and want to take for it you are welcome.

There are a couple of internal things you should be aware if you go for it:
- nwmatcher already works in a limited "scoped" mode that mimics this new selector behavior
- the "match()" method is especially built with this concept and can be readily used for this
- "Selectors Level 4" additions are already collected in src/modules/nwmatcher-webforms.js

As a last note here is a link to a "gist" showing how I would solve the suggested test on normal browsers (thus not for 'jsdom' as the OP asked): [scope-test.js](https://gist.github.com/dperini/7089c33e443480300633cac3099147c9)
maybe this could raise ideas or suggestions.

**Comment by jlongster** [comment]
Most browsers seem to support `:scope` now. I just ran into this problem of jsdom not supporting it, would be great to get it supported!

**Comment by jlongster** [comment]
Wow, that's extremely exciting! jsdom has made amazing progress and is unlocking some pretty incredible workflows. Keep up the good work.

**Comment by Zirro** [comment]
We have support for the `:scope` selector now. https://github.com/jsdom/jsdom/issues/2359 covers adding more tests for it.
