### ISSUE TITLE
Add addEventListener options argument support

### ISSUE THREAD

**Issue by GianlucaGuarini** [jsdom/jsdom#1609]
jsom does not support the addEventListener options argument https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

It would be great to see at least the support for the `once` flag

**Comment by GianlucaGuarini** [comment]
@domenic are you already working on it? Otherwise I will be glad to help making a pull request

**Comment by domenic** [comment]
A pull request would definitely be welcome.

**Comment by GianlucaGuarini** [comment]
@domenic you got it ;) https://github.com/tmpvar/jsdom/pull/1618

**Comment by domenic** [comment]
After https://github.com/tmpvar/jsdom/pull/1618, the remaining work is to add the passive flag. \o/!
