### ISSUE TITLE
9.5 doesn't seem to allow querying into noscript

### ISSUE THREAD

**Issue by daniel-white** [jsdom/jsdom#1611]
I'm trying to use jsdom to munge with an html file to prepare it for a CDN. However, I'm not able to select into an element inside of a `noscript`. I have `ProcessExternalResources` set to `false`.

```
<noscript><img href="..." /></noscript>
```

```
var document = jsdom('path', {features: {ProcessExternalResources: false}});
var els = document.querySelectorAll('[href]');
els.length === 0;
```

**Comment by Sebmaster** [comment]
From my testing in FF this does indeed seem like a bug.

**Comment by Zirro** [comment]
For future reference, this looks to be due to the same reason as issue #1802 and can be resolved when https://github.com/inikulin/parse5/issues/192 has been merged.
