### ISSUE TITLE
Secondary events not firing when fired on children of label

### ISSUE THREAD

**Issue by lPadier** [jsdom/jsdom#1614]
I modified https://jsbin.com/woyeqideya/1/edit?html,console,output from https://github.com/tmpvar/jsdom/issues/1079 to add a span inside the label.
https://jsbin.com/yomegejewu/edit?html,console,output

Dispatching `click` on the span should still toggle the input.

In jsdom however, the input is not toggled.

**Comment by Zirro** [comment]
This is fixed by https://github.com/jsdom/jsdom/pull/2450.
