### ISSUE TITLE
document.querySelector('svg:not(:root)') inconsistency

### ISSUE THREAD

**Issue by RyanZim** [jsdom/jsdom#1750]
Assuming the HTML:
```html
<svg xmlns="http://www.w3.org/2000/svg" width="150" height="100" viewBox="0 0 3 2">
  <rect width="1" height="2" x="0" fill="#008d46" />
  <rect width="1" height="2" x="1" fill="#ffffff" />
  <rect width="1" height="2" x="2" fill="#d2232c" />
</svg>
```
Running:
```js
window.document.querySelector('svg:not(:root)')
```

Returns `null` in jsdom, but returns `[object SVGSVGElement]` in Firefox. `querySelectorAll()` behaves similarly. Isn't this a bug?

**Test cases:**

- JSBin for browser testing: http://jsbin.com/hecijisuri/edit?html,js,console,output
- jsdom test case: https://runkit.com/57ebc041d4a27f140028fd78/58b5eef1aa8fd000138fc178

**Comment by RyanZim** [comment]
@domenic @Sebmaster ping?

**Comment by domenic** [comment]
Why are you pinging us? You've reported a bug, which is helpful. Do you have a pull request we should be reviewing?

**Comment by RyanZim** [comment]
There was no response and the issue wasn't labeled. I wanted to make sure this was actually a bug and not an oversight on my part.

**Comment by domenic** [comment]
I mean, my guess is that we don't implement the `:root` selector.

**Comment by RyanZim** [comment]
> my guess is that we don't implement the :root selector.

There seems to be some kind of basic support; `window.document.querySelector(':root')` returns an `HTMLHtmlElement`: https://runkit.com/57ebc041d4a27f140028fd78/58b83fcdc6f704001445507b

**Comment by domenic** [comment]
Ah interesting. Yeah, not sure what the bug is then.

**Comment by ArmorDarks** [comment]
@domenic @Sebmaster Maybe someone else who knows internals of `jsdom` will have time to look into it? Can you invite someone here? `:root` element and `:not`, and everything related to it becomes daily more and more used, so it's crucial to support it properly.

Besides, right now it is massive blocking issue for important PR of uncss: https://github.com/giakki/uncss/pull/280#issuecomment-291378455.
