### ISSUE TITLE
I got an error "Error: Could not load script: "c:\Users\ADMINI~1\AppData\Local\Temp\1489417241938-0\jquery.js""

### ISSUE THREAD

**Issue by LittleCherry722** [jsdom/jsdom#1768]
Hi, 
i just followed this turorial https://www.scala-js.org/tutorial/basic/ and got problem in step6

i installed jsdom like this "npm install jsdom"

and wenn I run my project I got 

> run
[info] Running tutorial.webapp.TutorialApp
[error] Error: Could not load script: "c:\Users\ADMINI~1\AppData\Local\Temp\1489417241938-0\jquery.js"
[error]     at D:\Frontend\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:44:23
[error]     at Object.check (D:\Frontend\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:89:11)
[error]     at ReadStream.<anonymous> (D:\Frontend\node_modules\jsdom\lib\jsdom\living\nodes\Document-impl.js:108:12)
[error]     at ReadStream.wrappedEnqueued (D:\Frontend\node_modules\jsdom\lib\jsdom\browser\resource-loader.js:255:16)
[error]     at emitOne (events.js:96:13)
[error]     at ReadStream.emit (events.js:191:7)
[error]     at fs.js:1877:12
[error]     at FSReqWrap.oncomplete (fs.js:114:15) { Error: ENOENT: no such file or directory, open 'D:\Users\ADMINI~1\AppData\Local\Temp\1489417241938-0\jquery.js'
[error]   errno: -4058,
[error]   code: 'ENOENT',
[error]   syscall: 'open',
[error]   path: 'D:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\1489417241938-0\\jquery.js' }
[error] d:\Frontend\target\scala-2.12\frontend-fastopt.js:1576
[error]   (0, $m_Lorg_scalajs_jquery_package$().jQuery$1)((function($this) {
[error]                                                  ^
[error]
[error] TypeError: (0 , $m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a function
[error]     at $c_Ltutorial_webapp_TutorialApp$.main__V (d:\Frontend\target\scala-2.12\frontend-fastopt.js:1576:50)
[error]     at $c_Ltutorial_webapp_TutorialApp$.$$js$exported$meth$main__O (d:\Frontend\target\scala-2.12\frontend-fastopt.js:1597:8)
[error]     at $c_Ltutorial_webapp_TutorialApp$.main (d:\Frontend\target\scala-2.12\frontend-fastopt.js:1606:15)
[error]     at Object.onload ([stdin]:59:95)
[error]     at process.nextTick (D:\Frontend\node_modules\jsdom\lib\jsdom.js:322:18)
[error]     at _combinedTickCallback (internal/process/next_tick.js:73:7)
[error]     at process._tickCallback (internal/process/next_tick.js:104:9)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js with JSDOM exited with code 1
        at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:107)
        at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:156)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:684)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:771)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$60$$anonfun$apply$43$$anonfun$apply$44.apply(ScalaJSPluginInternal.scala:765)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js with JSDOM exited with code 1
[error] Total time: 15 s, completed 2017-3-13 16:00:44

I dont know why it want to open the file in "D:\Users\ADMINI~1\AppData\Local\Temp\1489417241938-0\jquery.js'. It should be in C:\ not D:\

Can you please help me?

**Comment by inash** [comment]
I've run in to the same problem. After looking into it a bit, I found that (in Windows) the filePath parameter in method readFile in file lib/jsdom/browser/resource-loader.js receives a supposedly absolute path in unix format without the Windows drive prefix, e.g: /Users/Inash/AppData/Local/Temp/1491673609951-0/jquery.js.

When resolving this path, the current drive where the project lives is prepended, i.e: in your case D:/ instead of where actually it has to be C:/. The temporary work around I found for this is if you move your project to C:/, the error should go away.

The resolution should be to provide the absolute path with drive letter in Windows to this method (readFile). Cheers.

**Comment by mumutu66** [comment]
@inash it seems the issue still exists..so how to solve it ..any suggestion?

**Comment by vi-kas** [comment]
Yes, facing the same issue, any alternatives to this?

**Comment by 14sxlin** [comment]
ecounter same issure  today, issure goes away moving the project to C:/

**Comment by domenic** [comment]
Closing this old issue as it doesn't provide anything we can use to reproduce. If people run into a similar thing, please file a new issue, but be sure to use the issue template, in particular the part about a minimal reproduction case that does not use third-party software like scala-js.
