### ISSUE TITLE
Highcharts gets InvalidCharacterError when parsing DOM.

### ISSUE THREAD

**Issue by ram4nd** [jsdom/jsdom#1791]
Trying to run tests using jest. When highcharts is trying to be loaded it gets an error.

The exception from validate-names.js:
`5 '"<div filled="f" stroked="f" style="position: absolute;left:0;top:0;width:1px;height:1px;visibility: hidden"/>" did not match the Name production: Unexpected syntax in top\nLine 1:\n<div filled="f" stroked="f" style="position: absolute;left:0;top:0;width:1px;height:1px;visibility: hidden"/>\n^^^'
`

The error from jest:
```> jest

 FAIL  app/__tests__/chart/Chart.jsx
  ● <Chart /> › calls componentDidMount

    InvalidCharacterError

      at exports.name (node_modules/jsdom/lib/jsdom/living/helpers/validate-names.js:11:11)
      at DocumentImpl.createElement (node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:686:5)
      at Document.createElement (node_modules/jsdom/lib/jsdom/living/generated/Document.js:92:59)
      at a.createElement (node_modules/highcharts/highcharts.js:17:221)
      at Object.init (node_modules/highcharts/highcharts.js:92:155)
      at Object.createElement (node_modules/highcharts/highcharts.js:63:3)
      at Object.createElement (node_modules/highcharts/highcharts.js:107:525)
      at Object.init (node_modules/highcharts/highcharts.js:101:44)
      at Object.B (node_modules/highcharts/highcharts.js:109:320)
      at Object.getContainer (node_modules/highcharts/highcharts.js:252:329)

**Comment by domenic** [comment]
Can you produce a repro that does not depend on any external libraries? An example is https://jsbin.com/jewoxec/edit?js,output

**Comment by ram4nd** [comment]
An example of setting timeouts? Do you have an example setup of running code through jsdom? If that is what you are asking for, a bit unclear due to the example?

**Comment by domenic** [comment]
Sorry, I meant to link to https://github.com/tmpvar/jsdom/issues/1779 as an example of a good minimal repro that requires no libraries besides jsdom.

**Comment by mshenfield** [comment]
@domenic Here's a short repro

```js
const jsdom = require('jsdom').jsdom
const document = jsdom()
document.createElement('<div filled="f" stroked="f" style="position:absolute;left:0;top:0;width:1px;height:1px;visibility: hidden"/>')
```

jsdom version: 9.9.1
node version: 7.10.0

**Comment by mshenfield** [comment]
Better minimal repro:

```js
document.createElement('<div/>')
```

This seems to be HighCharts misusing [the `createElement` API](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement). I get similar exceptions running the above code in Chrome and Firefox.

**Comment by mshenfield** [comment]
Found the underlying issue. Because JSDOM doesn't support SVG (#1423), HighCharts [falls back to VML](https://github.com/highcharts/highcharts/blob/master/js/parts/Globals.js#L15) (an IE8< hack) to render. I assume that passing a full HTML string is correct for IE8 VML `createElement`, but it errors out correctly when passed to jsdom.

I wonder if the HighCharts SVG renderer would run on jsdom.

**Comment by mshenfield** [comment]
HighCharts has a case study [that modifies jsdom<10 to work with highcharts](https://github.com/highcharts/highcharts/blob/907307ca7f20046dd198f9b11054c9df40d6ba64/studies/highcharts-jsdom/highcharts-jsdom.js)

**Comment by dereklin** [comment]
Updating hightcharts to 6.0.7 fixes this problem

**Comment by domenic** [comment]
Glad to hear that this is now working better :). Also, we have some very basic SVG support now, so maybe that helped?
