### ISSUE TITLE
Enhancement: `ArrayBuffer.transfer`

### ISSUE THREAD

**Issue by brettz9** [jsdom/jsdom#1838]
It'd be nice to have `ArrayBuffer.transfer` support.

(Sorry for lack of a PR but currently just documenting issues we could use in IndexedDBShim in Node environments.)

**Comment by domenic** [comment]
Unfortunately that's not something we can implement, as it's not a web API, it's a nonstandard Firefox API.

I have vague hopes that we can add this to the JS language; /cc @samuelgoto. If you could write up a brief paragraph on why this would be useful to you, that'd help us justify it to the committee :)

**Comment by brettz9** [comment]
A `postMessage` polyfill could leverage it to ensure the original array buffer was consumed.

**Comment by brettz9** [comment]
(Came across this in running https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/idb-binary-key-detached.htm with [IndexedDBShim](https://github.com/axemclion/IndexedDBShim), our polyfill of IndexedDB for Node and the browser.)

**Comment by brettz9** [comment]
We could also use access to the `[[Detached]]` slot and to `IsDetachedBuffer`.

**Comment by brettz9** [comment]
Also, I might add my general feeling that the Structured Cloning Algorithm is something that ought to be well-supported in ES beyond HTML. As it is employed by the one mechanism for databases on the browser, it would be ideal to have full parity (including optionally reusing the same IndexedDB API as we attempt to do in our polyfill) in other environments like Node.

The algorithm's uses would I think particularly become more expansive if https://github.com/w3c/IndexedDB/issues/64#issuecomment-298591208 could be implemented, a means for serializing structured clones to JSON.

**Comment by TimothyGu** [comment]
This is not in jsdom’s power to implement, but rather Node.js or V8’s.
