### ISSUE TITLE
Element.matches does not match when element has a namespace

### ISSUE THREAD

**Issue by vandenoever** [jsdom/jsdom#1846]
### Basic info:

- **Node.js version:** v6.9.5
- **jsdom version:** 10.1.0

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const doc = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`).window.document;
doc.createElementNS("urn:ns", "h").matches("h")
false
doc.createElementNS("urn:ns", "h").matches("*|h")
SyntaxError
```

### How does similar code behave in browsers?

```js
document.createElementNS("urn:ns", "h").matches("h")
true
document.createElementNS("urn:ns", "h").matches("*|h")
true
```

"E if no default namespace has been declared for selectors, this is equivalent to *|E."
https://www.w3.org/TR/css3-selectors/#typenmsp

**Comment by domenic** [comment]
Thanks. Can you check to see what the result is in v10.1.0? We have definitely gotten better selectors and XML since last year.

**Comment by vandenoever** [comment]
@domenic sure, I updated the issue.

**Comment by aristov** [comment]
This error appears in 11.11:

```js
const { JSDOM } = require('jsdom')
const { window } = new JSDOM

console.log(window.document.createElementNS('', 'element').matches('element')) // => false, but must be true
```

It works properly in 11.10.

**Comment by domenic** [comment]
@aristov can you open a new issue, since having an empty namespace is not the same as the OP's issue?

**Comment by aristov** [comment]
Done: https://github.com/jsdom/jsdom/issues/2247
