### ISSUE TITLE
Implement Element.insertAdjacentElement

### ISSUE THREAD

**Issue by Treora** [jsdom/jsdom#1890]
From the [whatwg dom spec](https://dom.spec.whatwg.org/#dom-element-insertadjacentelement). See also on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentElement).

**Comment by valishah** [comment]
Hi @Treora : I see it's not been taken care. Is anyone working on it currently?

**Comment by Treora** [comment]
Not that I know of; but I am not involved in this project, just complaining about its imperfections. ;)

**Comment by valishah** [comment]
Oh, Sorry then @Treora. Even I'm looking for the fix of `insertAdjusentElement`. Thinking to make the changes in the code base and open a PR so people will use it.

**Comment by Treora** [comment]
Cool; for reference, you may want to look at (and perhaps share code with) the implementation of [insertAdjacentHTML](https://github.com/jsdom/jsdom/blob/ae4ab59f44918245c8427ec585ecd69a104f7d3b/lib/jsdom/living/nodes/Element-impl.js#L434) (and its discussion in #1355)

**Comment by valishah** [comment]
Sure @Treora: Thanks for the information.
