### ISSUE TITLE
Help me please parse this URL

### ISSUE THREAD

**Issue by iq-dot** [jsdom/jsdom#1906]
Hi Guys,

I have been using JSDOM for a while with great results but I am recently stumped on a certain URL which I just can't seem to figure out how and if its possible to get JSDOM to parse it.

The URL in question is: https://mainichi.jp/articles/20170609/dde/035/050/038000c

The site seems special in the sense it loads no content when originally hit and then uses JS to populate things in some sort of unique way.

When using JSDOM the original template response that has no content is returned, rather than the final JS populated article.

I am using the JSDOM.fromURL option and have tried passing in `runScripts: dangerously`, have also tried `esources: usable` option.

Perhaps there are other options / settings required or this site just not compatible with JSDOM ?

fairly simple code:

```
JSDOM.fromURL(url).then(dom => {
        console.log(dom.window.document.documentElement.innerHTML); // gives wrong HTML
```

Much appreciate the help

**Comment by Sebmaster** [comment]
If the site loads content asynchronously, fromURL will fire before the content has loaded (it's attached to window.onload internally), so you'll have to manually either timeout, or wait for an element to be available and can't use the promise resolving as-is.

**Comment by iq-dot** [comment]
Ok so I am making some progress, with a timeout I do see an error 'Not implemented: HTMLFormElement.prototype.submit'

**Comment by Zirro** [comment]
I'll close this as the original question has been answered. The second problem here is that we don't support form submission, which is known since before.
