### ISSUE TITLE
jsdom is not loading jQuery

### ISSUE THREAD

**Issue by leepowers** [jsdom/jsdom#192]
test3.js modified from the Hacker News example at: https://github.com/tmpvar/jsdom#readme

<pre>
// Print all of the news items on hackernews
var jsdom = require('jsdom');
jsdom.env('http://news.ycombinator.com/', [ 'http://code.jquery.com/jquery-1.5.min.js' ], function(errors, window) {
    var $ = window.$;
    if (typeof $ == 'undefined') {
        console.log("JQUERY IS UNDEFINED");
    } else {
        console.log("jQuery as been loaded");
    }
    console.log('HN Links');
    $('td.title:not(:last) a').each(function() {
        console.log(' -', $(this).text());
    });
});
</pre>

When run provides me with the following output:

<pre>
lee$ node test3.js 
JQUERY IS UNDEFINED
HN Links
</pre>

I'm running jsdom@0.2.0 and nodev0.5.0-pre on OSX

How do I trouble shoot this?

**Comment by loudar** [comment]
same here on v19.0.0
