### ISSUE TITLE
images download automatically on a template

### ISSUE THREAD

**Issue by molant** [jsdom/jsdom#2041]
### Basic info:

- **Node.js version:** 8.9
- **jsdom version:** 11.3

### Minimal reproduction case

The same code with a `package.json` is in https://github.com/molant/template-tests

```js
// Server configuration

const templateWithImage = `<template>
<img src="/image.svg" />
</template>`;

const svg = `svg version="1.1"
baseProfile="full"
width="300" height="200"
xmlns="http://www.w3.org/2000/svg">
<rect width="100%" height="100%" fill="red" />
<circle cx="150" cy="100" r="80" fill="green" />
<text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>
</svg>`;

const express = require('express');
const app = express();

app.get('/', function (req, res) {
    console.log('Server: HTML requested');
    res.send(templateWithImage);
});

app.get('/image.svg', function (req, res) {
    console.log('Server: image requested');
    res.send(svg);
});

// jsdom API tests

function newApi() {
    const jsdom = require('jsdom');
    const { JSDOM } = jsdom;
    console.log('---------------');
    console.log('Testing new API\n');

    JSDOM.fromURL('http://localhost:3000', {
        retendToBeVisual: true
    });
}

function oldApi() {
    const oldApi = require('jsdom/lib/old-api.js');
    console.log('---------------');
    console.log('Testing old API\n');

    oldApi.env('http://localhost:3000', {
        resourceLoader: function (resource, callback) {
            console.log(`jsdom resource loader: ${resource.url.href}`);
            return resource.defaultFetch(callback);
        },
        features: {
            FetchExternalResources: ["img"],
            SkipExternalResources: false
        },
        done: function (err, window) {
            newApi();
        }
    });
}

app.listen(3000, oldApi);
```

The current output is:

```
---------------
Testing old API

Server: HTML requested
jsdom resource loader: http://localhost:3000/image.svg
Server: image requested
---------------
Testing new API

Server: HTML requested
```

### How does similar code behave in browsers?

The problem is that `old-api` automatically downloads the image in the `template` tag. The new API behaves as expected.

Any browser with `template` support behaves as expected (no image downloaded).

**Comment by domenic** [comment]
My guess is the new API also misbehaves if canvas is installed and downloading of usable resources is enabled. We don't generally patch the old API, but if this occurs in the new API we can try to fix that.

**Comment by molant** [comment]
The repo with the minimal test uses canvas-prebuilt. I only see one request in express to the image that comes from the old API so it looks like the new API behaves as expected (although it will be great if you could double check).

Is there something similar to resourceLoader in the new API? If not, anything specific I should have in mind if I get the time to implement it?

**Comment by molant** [comment]
Hi @domenic, I'm going to try to add `resourceLoader` to the new API after thanks giving. We've seen other errors that do not repo with the new API so I'd rather spend my time adding a new feature than trying to reduce what's going on and fix it in the old API😊

Something I should know before I start? Things to do or avoid?

**Comment by domenic** [comment]
Hi, I don't think we have a design for resourceLoader that we are comfortable with yet. The old one is really bad. So designing it is the first step. Let's not write code until we have the design in mind.

**Comment by molant** [comment]
OK, is the design something you want to do or should I give it a try? If so, what are the things you don't like from the first time?

**Comment by domenic** [comment]
I'd appreciate help. Let's take it to a new issue where I'll dump my notes from last time I thought about this.

**Comment by molant** [comment]
@domenic I've updated the code in the repo and now both APIs behave the same (forgot to add `resources: 'usable'` in the new API):
Images are downloaded automatically if they are inside a template. This does not happen on browsers that support the `template` tag.

I've updated the title of the issue. Let me know if you want me to update also the description to reflect the changes.

**Comment by domenic** [comment]
Ah, great, that does explain it. So the issue here is that we don't implement the template contents owner document semantics. I don't *think* that'll be too hard, but we just have to do the work. Lots of web platform tests disabled because of that, too.
