### ISSUE TITLE
New API resource loader design

### ISSUE THREAD

**Issue by domenic** [jsdom/jsdom#2050]
Continued from https://github.com/tmpvar/jsdom/issues/2041#issuecomment-345143720; /cc @molant

These are my notes from last time I thought about this problem:

### New design

- A new class, `jsdom.ResourceLoader`.
- It has one method, `fetch(url, { headers, ...other stuff maybe })`
  - `url` must be an absolute URL, not relative.
  - I'm not sure what type `url` should be. In general I prefer public APIs to be strings, [per convention](https://url.spec.whatwg.org/#url-apis-elsewhere), but this might lead to a lot of spurious conversions of string -> URL -> string -> back to URL inside this API. We'll see, but lean toward string...
  - I'm not sure how much the callers should have to manually set headers, e.g. Referer and Accept, or whether we should allow them to be inferred from a Window that is part of the other stuff.
- The method returns a `Promise<Buffer | null>`. `null` indicates skipping that resource load. Callers must take care of decoding to strings according to the appropriate specs. ResourceLoader does not concern itself with decoding.
- To make the fetch abortable, for the first round we just tack on `.abort()` on the returned promise. Later, we make a breaking change to add `AbortSignal`, when we implement that in jsdom.
- Similarly, over time we can make breaking changes to make this use more Fetch API-like stuff, e.g. maybe `headers` starts out Node.js style, but later uses the web platform `Headers` class.
- jsdom's `resources` option accepts a `ResourceLoader` in addition to the string `"usable"`. Perhaps `"usable"` triggers a specific built-in `ResourceLoader` instance? It'd be good to figure out how to build a `ResourceLoader` that emulates the behavior of `"usable"`; this may inform some of the `...other stuff maybe` above.
- To get custom resource loading, you subclass `ResourceLoader`, override `fetch()`, and use `super.fetch()` as appropriate.
- This would also be a good place to add support for customizing the options to `request`; this capability was lost in the new API. I am thinking that becomes a property, `requestOptions`, and the default `fetch()` consults `this.requestOptions`. Thus you can create a subclass that just overrides `requestOptions`. Currently the defaults I have written down (which we should double-check with jsdom's code) are `{ strictSSL: true, pool: { maxSockets: 6 }, agentOptions: { keepAlive: true, keepAliveMsecs: 115 * 1000 } }`, which are supposed to roughly match browser behavior.

### How to implement

- This requires some pretty massive internal cleanup. Fortunately, if we do this right and get parity with old API's capabilities, we can completely get rid of old API at the same time, so we don't need to support both APIs with one resource loader.
- The current resource-loader.js is a mess. A bunch of places in jsdom use various parts of it in confusing ways. It does things like URL resolution, load event firing, data URL decoding but only sometimes, byte to string decoding... We need to move the rest of jsdom to just using a single entry-point, fetch(), as explained above. It'll be accessed via something like `this._ownerDocument._defaultView._resourceLoader.fetch` or similar. This single entry point will handle data URLs, but not URL resolution, not load events, and not bytes to strings. All those must be handled by callers as appropriate.
- We'll need to write nice, clean, new-style tests for this. Part of the goal is to ensure we have parity with the old resource loader. We should look at what old-API tests are appropriate to port to inspire this.
- Optionally, we can do a lot of cleanup after deleting old API. E.g. all the _features stuff can be gotten rid of. That doesn't need to be done as part of this work.

**Comment by Sebmaster** [comment]
> Later, we make a breaking change to add `AbortSignal`, when we implement that in jsdom.

Signals didn't seem like a big change to implement. You reckon we can do that quickly before doing resource loader?

**Comment by domenic** [comment]
We could, I just haven't been able to find the time, and I didn't want to tell @molant that we wouldn't accept his work unless he also did AbortSignal work :).

**Comment by Sebmaster** [comment]
I'm gonna see if I can implement it very soon. It seemed like it added very little without general web platform support, so I held off, but if we can use it for something, I'll get to it.

**Comment by kapouer** [comment]
It's barely related, but reading
```
self.addEventListener('fetch', (event) => {
  // try to find response object in the cache
  // associated with current request
  event.respondWith(caches.match(event.request)
    .then((cachedResponse) => {
      // if there's cached response, give it back
      if (cachedResponse) {

        return cachedResponse;
      }
      // if no, try to fetch it from the network
      return fetch(event.request.clone())
        .then((networkResponse) => {
          // if response is “bad”,
          // just pass it back into the app
          if (!networkResponse || networkResponse.status !== 200 ||
              networkResponse.type !== 'basic') {

            return networkResponse;
          }

          // if response is ok, cache it and
          // give it back into the app
          caches.open(OFFLINE_CACHE)
            .then((cache) => cache.put(
              event.request, networkResponse.clone()));

          return networkResponse;
        });
    }));
});
```
i thought 'hey that would be some way to plug into resource loading in jsdom too'.

**Comment by domenic** [comment]
Yeah, one day I would like this to be replaced by some variant of the service worker API, but implementing that is a whole 'nother bunch of work.

**Comment by TimothyGu** [comment]
Note: `Headers` class doesn't work well with a server-side context, where headers like `Set-Cookies` should not be combined (e.g. https://github.com/bitinn/node-fetch/issues/251).

**Comment by domenic** [comment]
I don't really see a problem with combining them in jsdom's case.

**Comment by wisec** [comment]
Hi, I am writing a spider,
it would be absolutely useful to have a callback fingerprint similar to jsdom v9:
```
resourceLoader: function(resource, callback){}
```
in particular the resource argument telling which is the element requesting the resource would actually be propedeutic to the use of this new version
Thanks

**Comment by domenic** [comment]
Although we're certainly not going to use callbacks, we can indeed try to include some kind of initiatorElement or something in the `...other stuff maybe` from the OP.

**Comment by Zirro** [comment]
I agree with nearly all the notes and ideas in the first post. The only part I'd think twice about is `requestOptions` and the dependency on `request` which it creates for the API.

I believe it would be wise to not expose options from a specific dependency in the default ResourceLoader. With `request` in particular we've had the ambition to move an implementation of the [Fetch Standard](https://fetch.spec.whatwg.org). While it will take a while before we get there, this API design will most likely be with us still.

To avoid locking both us and API users to the internals of `request`, I believe we should either expose new options with names based on the Fetch Standard that are then passed on to `request`, or at least only a subset of `request` options that we know that we are likely to support in a future Fetch Standard implementation as well.

Meanwhile if someone does need access to an option that only `request` can be expected to offer, this sounds like the perfect case for a custom ResourceLoader based on `request`. If we wanted to we could even maintain it ourselves as a separate package, and use it as a test case for custom ResourceLoader logic.

Doing this now will make it a lot easier for us to replace `request` with another dependency in the future, with minimal or no breaking changes to the API or users experiencing a loss of features.

**Comment by tmeasday** [comment]
> Meanwhile if someone does need access to an option that only request can be expected to offer, this sounds like the perfect case for a custom ResourceLoader based on request. If we wanted to we could even maintain it ourselves as a separate package, and use it as a test case for custom ResourceLoader logic.

As an example of why you might be interested in being implementation aware, we are interested in [tracking request progress](https://github.com/tmpvar/jsdom/pull/2083). 

I would be more than happy to implement a custom resource loader for this case, however in the old API, as I read it, it doesn't really seem possible to write a custom version of JSDOM's [`download` function](https://github.com/tmeasday/jsdom/blob/fd2cccfeb3eb28d59b79d17821c5ceabd3077083/lib/jsdom/browser/resource-loader.js#L157) that has the same behavior as the default (as a lot of inputs are closed over in the default implementation, so a custom implementation cannot access them).

By the sounds of it a classical inheritance based API won't suffer from this problem, but I just wanted to flag that this is a rough edge in the old API that would be good to smooth over.

**Comment by domenic** [comment]
Fixed by https://github.com/jsdom/jsdom/pull/2279; v12 will be coming out soon!
