### ISSUE TITLE
Activation behavior events should not be cancelable

### ISSUE THREAD

**Issue by domenic** [jsdom/jsdom#2062]
This is a pretty easy bug to fix. In HTMLInputElement-impl.js's _activationBehavior, we make input and change events cancelable. They should not be, per spec:

- https://html.spec.whatwg.org/#checkbox-state-(type=checkbox):input-activation-behavior
- https://html.spec.whatwg.org/#radio-button-state-(type=radio):input-activation-behavior

This will require finding or writing web platform tests, and also ensuring that the spec matches browsers in this regard.

**Comment by Zirro** [comment]
This was fixed in https://github.com/jsdom/jsdom/pull/2352.
