### ISSUE TITLE
node.children not defined

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [jsdom/jsdom#2127]
form HTMLFormElement {}
TypeError: form.children is not a function
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children

Missing the method for node.children

**Comment by Zirro** [comment]
If you were to look at the link you provided, you would see that `children` is indeed not a function as the error is telling you. It's a read-only property.

If you file more issues in the future, don't ignore the issue template. Let us know which version of Node.js and jsdom you are using, provide a testcase and most importantly - make sure that the testcase actually works in a browser first!
