### ISSUE TITLE
Support for node-canvas 2.x

### ISSUE THREAD

**Issue by tribetiki** [jsdom/jsdom#2135]
Please add support for node-canvas 2.x versions:
https://github.com/Automattic/node-canvas
https://github.com/node-gfx/node-canvas-prebuilt

**Comment by domenic** [comment]
Dupe of https://github.com/jsdom/jsdom/pull/1964

**Comment by tribetiki** [comment]
I did a search for "canvas" from open issues - didn't realize to check pull requests. Cheers! 👍
