### ISSUE TITLE
setAttributeNode is not working, set/get attribute from node

### ISSUE THREAD

**Issue by dsadhanala** [jsdom/jsdom#2148]
I'm using JSDOM for testing custom elements using `document-register-element` polyfill, I found tests are throwing only in JSDOM but not in browsers, hyperHTML library code was trying to cloneNode from attribute node and looks like it's undefined in JSDOM environment.

Can you help understand if this is something caused due to missing API feature?

Here is the original thread from hyperHTML repo for reference.
https://github.com/WebReflection/hyperHTML/issues/190

PS: tests are running as expected and rendering custom elements if I remove cloneNode and use workaround to verify.

**Comment by domenic** [comment]
Sorry, this doesn't appear to follow the issue template, in particular by providing a minimal reproduction case without third party software. As such we're not able to help.
