### ISSUE TITLE
Single Quotes in URL  = Bad Request - Invalid URL

### ISSUE THREAD

**Issue by khadlock** [jsdom/jsdom#2149]
We're attempting to load working site URLs and are receiving a "Bad Request - Invalid URL" response from jsdom. Here's an example: http://www.dominionpost.com/‘Rise-up’-Sen--Capito-vis--its-M

You can see that the site address loads in a browser, but if you attempt to load via jsdom you'll get this error.

Is there a URL option that would resolve this for us?

Thank you and we appreciate your assistance!

**Comment by domenic** [comment]
Unfortunately this issue did not follow the issue template, so we cannot help with it. Please update to follow the template, then drop another message in this thread, and we can reopen it.

**Comment by khadlock** [comment]
We're attempting to load working site URLs and are receiving a "Bad Request - Invalid URL" response from jsdom. Here's an example: http://www.dominionpost.com/‘Rise-up’-Sen--Capito-vis--its-M

You can see that the site address loads in a browser, but if you attempt to load via jsdom you'll get this error.

Is there a URL option that would resolve this for us?

Please see the sample code below.

- **Node.js version:** 9.4.0
- **jsdom version:** 9.12.0

```js
const { JSDOM } = require("jsdom");

jsdom.env({
                    url: "http://www.dominionpost.com/‘Rise-up’-Sen--Capito-vis--its-M",
                    contentType: "text/html",
                    scripts: ["http://code.jquery.com/jquery.js"],
                    done: function (err, window) {});

```

**Comment by Zirro** [comment]
That's an outdated version of jsdom. Can you reproduce it with the latest release, 11.6.2?

**Comment by khadlock** [comment]
The new version seems to be working, thank you. However, I have a new question; how can we inject scripts using the fromURL? We were using the "scripts" option in the "env" function in the previous versions of JSDOM.
