### ISSUE TITLE
on* event handlers are null after assignment

### ISSUE THREAD

**Issue by l0b0** [jsdom/jsdom#2157]
### Basic info:

- **Node.js version:** 9.5.0
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

let element = (new JSDOM()).window.document.createElement("a");
element.onmousedown = "location='http://example.org'";
console.log(element);
console.log(element.onmousedown);
```
Logs "HTMLAnchorElement {}" and "null".

```js
let element = (new JSDOM("<body><a onmousedown='location=\"http://example.org\"'>whatever</a></body>")).window.document.body.children[0];
console.log(element);
console.log(element.onmousedown);
```

Logs "HTMLAnchorElement {}" and "null". `console.log(element.onmousedown);` on such an element in Firefox returns a `function` object as expected.

**Comment by domenic** [comment]
The second case is expected since a `JSDOM` is not an `Element`.

But the first case seems like it should be working... will investigate.

**Comment by l0b0** [comment]
Fixed the second case, thanks!

**Comment by domenic** [comment]
Actually, this is working as intended. You seem to have not tested in Firefox after all?

In my Firefox, the following code logs null:

```js
let element = document.createElement("a");
element.onmousedown = "location='http://example.org'";
console.log(element.onmousedown);
```

**Comment by l0b0** [comment]
OK, that was unexpected. My code checks for the existence of that attribute, and it works, but I'm having trouble [testing it](https://github.com/l0b0/insecure-links-highlighter/commit/167ff23fb733dfc8015f8081a234e8d44b996113#diff-31a8b1307cd30ddf4cc82056f635c43e). I thought I was following the instructions in your README:

> However, event handler properties, like `div.onclick = ...`, will function regardless of `runScripts`.

**Comment by domenic** [comment]
I don't think this has to do with runScripts. You just can't assign strings to those properties, either in browsers or in jsdom.
