### ISSUE TITLE
Internal scripts not evaluating when resources: "usable" option set. 

### ISSUE THREAD

**Issue by medhir** [jsdom/jsdom#2161]
### Basic info:

- **Node.js version:** node v8.9.4
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const samplePage = `
<html>
 <head>
   <title>intro to d3</title>
   <script src="https://d3js.org/d3.v4.min.js"></script>
 </head>
 <body>
   <hgroup></hgroup>
   <script>
        const addHeading = function () {
            d3.select('hgroup')
              .append('h1')
              .text("Hello, world");
        };

        addHeading();
   </script>
 </body>
</html>
`
const dom = new JSDOM(samplePage, {
    runScripts: "dangerously", 
    resources: "usable"
});

console.log(dom.window.d3); // undefined since window not loaded

const d3 = await new Promise((resolve, reject) => {
    dom.window.addEventListener("load", () => {
        console.log(dom.window.addHeading); // returns 'undefined'
        resolve(dom.window.d3); // now d3 loaded
    })
});

const jsdom = require("jsdom")
const { JSDOM } = jsdom;
const samplePage = `
<html>
 <head>
   <title>intro to d3</title>
   <!-- This <script> allows us to call "d3" in our code: --> 
   <script src="https://d3js.org/d3.v4.min.js"></script>
 </head>
 <body>
   <hgroup></hgroup>
   <script>
        const addHeading = function () {
           d3.select('hgroup')
              .append('h1')
              .text("Hello, world");
        };
        addHeading();
   </script>
 </body>
</html>
`
const dom = new JSDOM(samplePage, {
    runScripts: "dangerously", 
    resources: "usable"
});

const d3 = await new Promise((resolve, reject) => {
    dom.window.addEventListener("load", () => {
        console.log(dom.window.addHeading); // returns 'undefined'
        
        // try loading using window.eval
        dom.window.eval(`
                const addHeading = function () {
                    d3.select('hgroup')
                      .append('h1')
                      .text("Hello, world");
                };

                addHeading();
        `);
        
        console.log(dom.window.addHeading); // still undefined
        
        resolve(dom.window.d3); // now d3 loaded
    });
});
```

### How does similar code behave in browsers?
https://runkit.com/medhir/jsdom/1.0.2

I'm using JSDOM as part of a testing suite for an online course, and am attempting to evaluate d3 code within jsdom. After a fair bit of research, I understand that I have to wait for the window to completely load before running any d3 code. 

I am running into an issue where if I set the `resources: "usable"` option, the `<script>` tags found within the document body do not evaluate. Furthermore, running the same scripts using `dom.window.eval()` does not work either. 

Am I missing something on how to run internal vs external scripts simultaneously? All behavior documented at the RunKit link. Thanks!

**Comment by TimothyGu** [comment]
If you try running this code in the browser, you will discover the issue:

![screenshot from 2018-02-28 15-47-04](https://user-images.githubusercontent.com/1538624/36819539-b6ab4158-1c9e-11e8-8d7c-31d8abe23961.png)

Blocked-scoped variables executed in the global scope will not actually add the function to the global object. That's why attempting to get `dom.window.addHeading` will result in undefined.

There are a few ways to fix this.

1. You could just declare the function as `function addHeading() { ... }` or `var addHeading = function () { ... }`. In most cases, creating block-scoped (`const`/`let`) variables in the global scope probably doesn't have the behavior you want.
2. You could use `dom.window.eval('addHeading')` instead of `dom.window.addHeading`.

**Comment by medhir** [comment]
**DOH** that makes total sense... I'm new-ish to ES6 after being out of web dev for a few years, forgive the confusion. 

In this case, I was interested checking for `addHeading` being defined. The testing functionality is designed to be server-side and uses jsdom to check DOM structure. Thanks for clarifying.
