### ISSUE TITLE
cannot simulate click event in jsdom

### ISSUE THREAD

**Issue by Gillis86** [jsdom/jsdom#2162]
I'm new to jsdom, so maybe I'm missing something.

node: 8.1.3
jsdom: 11.6.2

I have a application with some progress bar, when the application load their width is set to 0, when a specific element is clicked, they took a specific width (the value is stored in a json file). Now I'm trying to recreate this behaviour with jsdom and simulant.js in order to check if this click event change the width of all progress bars.

First of all i grab the index.html file which contain one main script (bundle.js), remove that script and create another script with the same content (it will be a script internal of the page):

```
const fs = require('fs');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const simulant = require('jsdom-simulant');

const html = fs.readFileSync('src/index.html','utf8')
const dom = new JSDOM(html,{ runScripts: "dangerously",resources: "usable" });
const oldScript = dom.window.document.getElementsByTagName('script')[0];
dom.window.document.body.removeChild(oldScript);
const script = dom.window.document.createElement('script');
const requireJSFile = fs.readFileSync('src/dist/js/bundle.js','utf8');
script.innerHTML = requireJSFile;
dom.window.document.body.appendChild(script);
```
then i launch the test:

```
describe("About page test", function() {
  const progressBars = Array.from(dom.window.document.querySelectorAll('.about__skills__list__item__progress-bar'));


  it("check progress bar width initial value",function(){
    progressBars.forEach(function(progress){
      expect(progress.style.width).toBe('');
    })
  })
  it("check progress bar width after click event", function(){

    const aboutButton = dom.window.document.getElementById('about-button');
    simulant.fire(aboutButton,"click");
    progressBars.forEach(function(progress){
      expect(progress.style.width).not.toBe('');
    })
  })
});
```
the first test pass (the initial value is set to '') but in the second i get the error (for all progress bar):

`Expected '' not to be ''.`
so seems I'm not able to recreate the click event, I tried also with MouseEvent api but I get the same result..

**Comment by Gillis86** [comment]
ok, in the suite test if i do:

```
aboutButton.addEventListener('click',function(){
    console.log('hola')
  })
```
and then launch the click simulant I get hola printed out, so seems jsdom not reading the content of bundle.js, have I to use something like window.eval?

**Comment by Gillis86** [comment]
ok my fault, i would wrap the second test in a setiTimeout because the width doesn't change immediately, everything works as expected now

**Comment by denikov** [comment]
@Gillis86 I know this is a bit old but I'm struggling with the same thing.  Did you get that scenario to work?  I think the proper way to get something like this to work is to directly call the function that handles updating the progress bars and bypassing the click entirely?

**Comment by G3ra1d0** [comment]
Hello friend jsdom only handles static html, to make the click event you will need a headless browser for scraping the web. There are several one of them is the Puppeter that uses the chorme in the background.


Repository: https://github.com/puppeteer/puppeteer
