### ISSUE TITLE
Request and Node-Pre-Gyp dependencies causes security risk

### ISSUE THREAD

**Issue by lyndsey-ferguson** [jsdom/jsdom#2163]
### Basic info:

- **Node.js v6:**
- **jsdom 11.6.2**

### Minimal reproduction case

We are seeing security issues related to a vulnerability in `request` and `node-pre-gyp` due to their reliance on `hawk` which uses the vulnerable `hoek`. I am opening up this issue so that when `request` and `node-pre-gyp` updates to v7.x.x of `hawk`, `jsdom` can be updated. 

`jsdom@11.6.2` > `node-pre-gyp@0.6.39` > `hawk@3.1.3` > hoek@2.X.X`
`jsdom@11.6.2` > `request@2.83.0` > `hawk@6.0.2 > hoek@4.2.0`

https://nodesecurity.io/advisories/566
https://hackerone.com/reports/310439

**Comment by domenic** [comment]
We don't depend on node-pre-gyp, so this seems pretty bogus to me.

**Comment by nrkn** [comment]
Regardless, it's not just `node-pre-gyp`, it's `request` as well:

```
+-- request@2.85.0
| +-- hawk@6.0.2
| | +-- boom@4.3.1
| | | `-- hoek@4.2.1 deduped
| | +-- cryptiles@3.1.2
| | | `-- boom@5.2.0
| | |   `-- hoek@4.2.1 deduped
| | +-- hoek@4.2.1
```

We're receiving security multiple vulnerability notifications on our packages that use js-dom
