### ISSUE TITLE
Unable to executing script inside jsdom

### ISSUE THREAD

**Issue by Gillis86** [jsdom/jsdom#2164]
**Basic Info**
node: 8.1.3
jsdom: 11.6.2

I'm trying to execute scripts inside js dom, I have many js files that are processed into a main bundle.js file via gulp:

```
gulp.task('testJs',()=>{
  return browserify({
    entries: ['./src/js/main.js'],
    debug:true
   })
  .bundle()
  .pipe(source('bundle.js'))
  .pipe(buffer())
  .pipe(babel({
    presets: ['env'],
    compact: true
  }))
  .pipe(gulp.dest('./spec'))
  .pipe(browserSync.stream());
});
```

this task basically creates a copy of the bundle.js and send it to the spec folder, now my intent is to recreate the dom with jsdom, this is a test file I create:

```
const fs                           = require('fs');
const jsdom                        = require("jsdom");
const simulant                     = require('jsdom-simulant');



//CREATE THE DOM
const { JSDOM } = jsdom;
const html = fs.readFileSync(__dirname + '/test.html','utf8') // i create a copy of the html file

const { window } = (new JSDOM(html,
  {
    runScripts: "outside-only",
    resources: "usable"
  }));


const script = window.document.createElement('script');
script.src = "bundle.js"
window.document.body.appendChild(script)

const aboutButton = window.document.getElementById('about-button')


describe('test',function(){
  beforeEach(function(){
      simulant.fire(aboutButton,'click')
  })
  it('test1',function(){
    window.onModulesLoaded = () => {
      expect(window.document.body.classList.value).not.toBe('');
      console.log('ok')
      done();
    }
    
  })
})

```

doing in this way the test pass, because the block inside window.onModulesLoaded is never executed, am I missing something, thanks!

**Comment by domenic** [comment]
Unfortunately this did not follow the issue template and seems to involve several external libraries which we cannot help you debug, such as gulp, something called simulant, and whatever's supplying the describe/it globals.

Please boil this down to a testcase involving only jsdom, of the sort shown in the issue template, and we can consider reopening.
