### ISSUE TITLE
Could not parse "/url" as a URL - relative path

### ISSUE THREAD

**Issue by popkutty** [jsdom/jsdom#2167]
### Basic info:
Using jsdom with Jest framework. When I try to run my test which has relative URL as in the code, I'm getting parse error.
- **Node.js version:** v8.9.4
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
window.location.href = '/url'
```

error

```
Could not parse "/url" as a URL - relative path
```

**Comment by TimothyGu** [comment]
Hi! Unfortunately, we cannot debug this issue without a reproduction case that doesn’t depend on third-party modules like Jest. Please make sure to edit the issue to follow the [issue template](https://github.com/jsdom/jsdom/blob/master/.github/ISSUE_TEMPLATE.md), and we’ll reopen this issue.

**Comment by Knagis** [comment]
Solution for the random dev (like me) happening upon this thread - add the following to your jest configuration:

```
    "testEnvironment": "jsdom",
    "testEnvironmentOptions": {
        "url": "https://some.random.url/",
    },
```

jsdom does everything correct and knows how to parse relative url, just it requires the absolute url to be set before that will work.
