### ISSUE TITLE
Error: Could not load script: "//cdn.ronghub.com/protobuf-2.1.6.min.js"

### ISSUE THREAD

**Issue by MichaelPriebe** [jsdom/jsdom#2168]
I'm just loading a string with a single script tag to use a browser api in Node.js.

When the string is loaded through `new JSDOM` it gives me the above error.

When its loaded through `JSDOM.fromFile` it works perfectly.

I can also load it through a string if I set the url option to `file:`

I believe all its doing is trying to open the script locally instead of the cdn, because the forward slashes mess it up.

**Comment by domenic** [comment]
Unfortunately this does not follow the issue template, so it is not something we can debug. Please follow the issue template for future issues.
