### ISSUE TITLE
Update dev dependencies which cause nsp warnings

### ISSUE THREAD

**Issue by Rambobafet** [jsdom/jsdom#2169]
### Basic info:

- **Node.js version**: v9.3.0
- **jsdom version**: v11.6.2

### Minimal reproduction case

```js
{
"dependencies": {
    "jsdom": "11.6.2",
    "nsp": "^3.2.1",
}
}

$ nsp check --reporter checkstyle
```

Node Security Project is reporting a vulnerability due to the dependency `ws` used by jsdom (+ the one reported here : https://github.com/jsdom/jsdom/issues/2163).

```
Type: Denial of Service  
Plugin name : ws  
CVSS: 7.5 (High)  
Installed: 1.1.1  
Vulnerable: <1.1.5 || >=2.0.0 <3.3.1  
Patched: >= 1.1.5 <2.0.0 || >=3.3.1  
Path:  jsdom@11.6.2 > ws@1.1.1  
More Info: https://nodesecurity.io/advisories/550  
```

**Comment by Zirro** [comment]
This advisory only applies to ws 1.x which is included by a dev dependency, and not ws 4.x which is the version used by releases of jsdom. Therefore it does not have an impact for users of this package.

I'm not sure if we need to keep this issue open until we do, but this will be resolved when we update `karma` as the problematic dependency chain is:
`karma@1.7.1 > socket.io@1.7.3 > engine.io@1.8.3 > ws@1.1.2`

**Comment by domenic** [comment]
Let's close this; more spurious auto-reported "security" bugs, ugh.
