### ISSUE TITLE
new EventTarget() fails to call listeners when dispatchEvent is called

### ISSUE THREAD

**Issue by mysterycommand** [jsdom/jsdom#2173]
This is a reproduction of facebook/jest#5800, I think this is a bug in jsdom and not Jest (though I came across it in Jest first). I'll try and get a jsdom-only reproduction when I can (I'm about to be away from wifi for a couple days).

**Do you want to request a _feature_ or report a _bug_?**
Report a bug 🐛

**What is the current behavior?**
Here is a test that I think should pass, but doesn't:

```js
describe('EventTarget', () => {
  it('triggers listeners', () => {
    const eventTarget = new EventTarget();
    const addEventListenerSpy = jest.spyOn(eventTarget, 'addEventListener');
    const dispatchEventSpy = jest.spyOn(eventTarget, 'dispatchEvent');

    const type = 'mouseenter';
    const init = { clientX: 1, clientY: 1 };

    const onMouseEnterMock = jest.fn(event => {
      // this is never called
      expect(event).toBeInstanceOf(MouseEvent);
      expect(event.type).toBe(type);
      expect(event.clientX).toBe(init.clientX);
      expect(event.clientY).toBe(init.clientY);
    });

    eventTarget.addEventListener('mouseenter', onMouseEnterMock);
    eventTarget.dispatchEvent(new MouseEvent(type, init));

    expect(addEventListenerSpy).toHaveBeenCalledTimes(1);
    expect(dispatchEventSpy).toHaveBeenCalledTimes(1);
    // this is never called
    expect(onMouseEnterMock).toHaveBeenCalledTimes(1);
  });
});
```

Jest version 22.4.2 … I guess this might be a jsdom issue? I couldn't find anything particularly relevant in their issues either. In a Chrome console I'm able to do like this and it works:

```js
const eventTarget = new EventTarget();
// undefined
eventTarget.addEventListener('mouseenter', console.log);
// undefined
eventTarget.dispatchEvent(new MouseEvent('mouseenter', { clientX: 1, clientY: 1 }));
// MouseEvent {isTrusted: false, screenX: 0, screenY: 0, clientX: 1, clientY: 1, …}altKey: falsebubbles: falsebutton: 0buttons: 0cancelBubble: falsecancelable: falseclientX: 1clientY: 1composed: falsectrlKey: falsecurrentTarget: EventTarget {}defaultPrevented: falsedetail: 0eventPhase: 0fromElement: nullisTrusted: falselayerX: 1layerY: 1metaKey: falsemovementX: 0movementY: 0offsetX: 1offsetY: 1pageX: 1pageY: 1path: []relatedTarget: nullreturnValue: truescreenX: 0screenY: 0shiftKey: falsesourceCapabilities: nullsrcElement: EventTarget {}target: EventTarget {}timeStamp: 37384427.39999998toElement: nulltype: "mouseenter"view: nullwhich: 1x: 1y: 1__proto__: MouseEvent
// true
```

**If the current behavior is a bug, please provide the steps to reproduce and
either a repl.it demo through https://repl.it/languages/jest or a minimal
repository on GitHub that we can `yarn install` and `yarn test`.**
Here's a repl.it: https://repl.it/@mysterycommand/DimFormalForce

**What is the expected behavior?**
The test should pass/listeners should be called … for background, I stumbled onto this while trying to test that a class updated some properties after certain events were triggered.

**Please provide your exact Jest configuration**

```json
"jest": {
  "collectCoverage": true,
  "collectCoverageFrom": [
    "source/**/*.ts",
    "!source/script.ts",
    "!**/node_modules/**"
  ],
  "coverageThreshold": {
    "global": {
      "branches": 100,
      "functions": 100,
      "lines": 100,
      "statements": 100
    }
  },
  "moduleFileExtensions": [
    "ts",
    "js",
    "json"
  ],
  "moduleNameMapper": {
    "^.+\\.s?css$": "identity-obj-proxy"
  },
  "testMatch": [
    "<rootDir>/source/**/?(*.)test?(s).ts"
  ],
  "transform": {
    "^.+\\.ts$": "ts-jest"
  }
}
```

**Run `npx envinfo --preset jest` in your project directory and paste the
results here**
```sh
$ npx envinfo --preset jest
npx: installed 1 in 2.958s

  System:
    OS: macOS High Sierra 10.13.3
    CPU: x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 8.10.0
    Yarn: 1.5.1
    npm: 5.7.1
  npmPackages:
    jest:
      wanted: 22.4.2
      installed: 22.4.2
```

Let me know if I can provide any more information, or help out at all.

**Comment by domenic** [comment]
THanks, but this did not follow our issue template, and depends on us, the maintainers of jsdom, running a third-party library, jest. So, we need to close.

Just judging based on the title, this seems likely to be caused by #2156 (i.e. we don't implement `new EventTarget()` at all currently, and the fact that apparently it sometimes works is a bug).
