### ISSUE TITLE
Is label.control unsupported?

### ISSUE THREAD

**Issue by kentcdodds** [jsdom/jsdom#2175]
### Basic info:

- **Node.js version:** v8
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
const {JSDOM} = require('jsdom');
const dom = new JSDOM('');
const {document} = dom.window;

var div = document.createElement('div');
div.innerHTML = '<label>hi<input /></label>';
console.log(div.firstChild.control); // undefined
```

### How does similar code behave in browsers?

In the browser it references the input. Copy/paste this into your browser's developer tools:

```javascript
var div = document.createElement('div');
div.innerHTML = '<label>hi<input /></label>';
console.log(div.firstChild.control); // references the input node
```

**Comment by domenic** [comment]
It looks like this is indeed unimplemented. A pull request would be welcome!

**Comment by FrecksterGIT** [comment]
#2217 brings support for HTMLLabelElement.control and *.labels where needed.
This can be closed now.

**Comment by Zirro** [comment]
@FrecksterGIT Nice work. Thanks!

**Comment by kentcdodds** [comment]
That's wonderful! Thanks @FrecksterGIT
