### ISSUE TITLE
jsdom gets stuck for a specific website

### ISSUE THREAD

**Issue by steverandy** [jsdom/jsdom#2176]
### Basic info:

- **Node.js version:** 8.9.4
- **jsdom version:** 11.6.2

### Minimal reproduction case

```js
let {JSDOM} = require("jsdom");

console.log("starts")
JSDOM.fromURL("https://leanpub.com/").then((dom) => {
  console.log(dom.serialize());
});
```
I have created an example repo for test purpose: https://github.com/steverandy/jsdom-example
The code is identical to the above snippet.
If you run the code, the promise never resolve or throw any error. The process seems to just stuck and I'm getting 100% cpu usage.

**Comment by dpilafian** [comment]
It looks like this test case is now passing (at least when I try it).

If jsdom gets stuck, two things to try are:

**1) Disable keep-alive**
In a mocha test that uses `JSDOM.fromURL()` to load a website from **localhost**, I encountered:

    Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called;
    if returning a Promise, ensure it resolves.

and fixed it by disabling `keep-alive` on the server with:

```javascript
const staticOptions = { setHeaders: (response) => response.setHeader('Connection', 'close') };
const app = express();
app.use('/', express.static('web-root', staticOptions));
```

You can verify the headers with the `curl -I -X GET http://localhost:3000/` command.

**2) Close the jsdom window**
Execute `dom.window.close()` to [terminate all running timers and remove any event listeners](https://github.com/jsdom/jsdom#closing-down-a-jsdom).

For example:

```javascript
const { JSDOM } = require('jsdom');
const url = 'https://leanpub.com/';
console.log(url);
const getStatus = (dom) => dom.window.document === undefined ? 'Gone!' : 'Still here.';
JSDOM.fromURL(url).then((dom) =>
   console.log(dom.serialize().length, getStatus(dom), dom.window.close(), getStatus(dom)));
```

outputs:

    https://leanpub.com/
    3199170 'Still here.' undefined 'Gone!'

**Comment by steverandy** [comment]
Thanks for the reply. Got the test case to pass now.
