### ISSUE TITLE
TypeError: Cannot set property '_eventListeners' of undefined

### ISSUE THREAD

**Issue by lookfirst** [jsdom/jsdom#2181]
### Basic info:

jsdom latest

      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:448:51)

### Minimal reproduction case

Difficult because this is a weird failure I'm seeing in jest and I don't know how to resolve (yet), but I can see how this line could fail...

Window.js:
```
    idlUtils.implForWrapper(this)._eventListeners = Object.create(null);
```

`idlUtils.implForWrapper(this)` could return null. Seems like handling that case in Window.js would be a good idea?

**Comment by domenic** [comment]
Unfortunately this report doesn't follow our issue template, and so isn't something we can debug. Please let us know when you have a reproduction case, and we will reopen.

**Comment by lookfirst** [comment]
@domenic It is pretty simple.

`idlUtils.implForWrapper(this) could return null`

**Comment by Sebmaster** [comment]
@lookfirst It never _should_ return null if the object is set up properly.

**Comment by lookfirst** [comment]
@metrue Sorry, I don't remember how it was fixed... I probably started doing something else.

**Comment by nakkam** [comment]
> idlUtils.implForWrapper(this) could return null

where am writing this one ?
