### ISSUE TITLE
Feature Request: Supporting code coverage

### ISSUE THREAD

**Issue by chriscapaci** [jsdom/jsdom#2183]
The old API allowed the loading of source files so that code coverage tools would be able to use them. The new API does no have this, and as such code coverage tools don't work. Is there any way you can add this back in? 

I see there is at least one other old issue requesting this that has been closed, without any answer or resolution. If you're not going to do, it please let me know. I will have to try a different tool then, but would prefer to stick with jsdom.

**Comment by TimothyGu** [comment]
There have been some interesting experiments being done with the Inspector API over at [c8](https://github.com/bcoe/c8) which may work for this purpose (with some glue code). This is much more implementable than instrumentation-based code coverage tools like Istanbul/NYC proper.

**Comment by chriscapaci** [comment]
@domenic: loading scripts isn't until issue, it's getting them loaded in a way that Istanbul knows about. 

@TimothyGu: I'll check that out, thanks.

**Comment by chriscapaci** [comment]
@TimothyGu C8 works great! Thanks for the suggestion.

To anyone looking for code coverage while using JSDOM, just run your tests wrapped in C8 and you'll get Istanbul formatted code coverage report.

**Comment by domenic** [comment]
Glad to hear this worked!
