### ISSUE TITLE
request@2.85 breaks jsdom

### ISSUE THREAD

**Issue by michalcafe** [jsdom/jsdom#2189]
### Basic info:

- **Node.js version:** 8.5
- **jsdom version:** 11.7.0

### Minimal reproduction case

Install `jsdom`
```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
```

output:
```
    TypeError: Cannot read property 'prototype' of undefined

      at module.exports (node_modules/request-promise-core/configure/request2.js:34:47)
      at Object.<anonymous> (node_modules/request-promise-native/lib/rp.js:15:1)
      at Object.<anonymous> (node_modules/jsdom/lib/api.js:6:17)
```

`npm install request@2.83` is a temporary solution.

I came across a similar issue which had been closed: https://github.com/jsdom/jsdom/issues/2040

**Comment by domenic** [comment]
I am not able to reproduce this on my computer with the minimal reproduction case provided. Please ensure you have created a new folder, and that you are only running the code shown.
