### ISSUE TITLE
Setting visibilityState

### ISSUE THREAD

**Issue by iofjuupasli** [jsdom/jsdom#2190]
How to set `document.visibilityState` to any value?

It says `Cannot set property visibilityState of [object Document] which has only a getter`

I need to test code that relies on different values in `document.visibilityState`

**Comment by domenic** [comment]
How would you do it in the browser?

(Hint: use Object.defineProperty.)

**Comment by kapouer** [comment]
[Here's how](https://github.com/kapouer/express-dom/blob/22ebab1417a13078070e06655dc73686a1b620fc/lib/plugins.js#L98-L101)
and also just a word to say visibilityState's prerender property is something i've seen running live in safari and it amazed me how little people knew that (when searching from url bar, cached document are prerendered). So my little page state toolbox uses it at https://github.com/kapouer/express-dom/blob/22ebab1417a13078070e06655dc73686a1b620fc/lib/plugins.js#L98-L101.
Standards are so way ahead of us sometimes ;)

**Comment by iofjuupasli** [comment]
Thank you, it works

**Comment by victor-enogwe** [comment]
``` ts
Object.defineProperty(window, 'visibilityState', {
  configurable: true,
  get: () => 'visible',
});

window.dispatchEvent(new Event('visibilitychange'));
```
thanks @kapouer
