### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by Progyan1997** [jsdom/jsdom#2196]
### Basic info:

- **Node.js version:** 6.12.3
- **jsdom version:** 11.6.2

### Minimal reproduction case

* Test
```js
import { spy } from "sinon";
import SaveBtn from "../../../app/component/SaveBtn";

const onClickSpy = spy(SaveBtn.prototype, "onClick");

const SaveBtnTest = describe("Testing Submit Button component", function () {
    const SaveBtnElement = renderComponent(SaveBtn);
    ...
    it("should call the submit handler when clicked", function () {
        SaveBtnElement.find("button").simulate("click");
        assert(onClickSpy.calledOnce, true);
    });
});
```

* Configuration
```js
const jsdom      = new JSDOM("<!DOCTYPE HTML><html><body></body></html>");
global.window    = jsdom.window;
global.document  = jsdom.window.document;
global.navigator = {
    userAgent: "node.js"
};
...
```

* Component
```js
...
onClick() {
    const blob = new Blob([ this.props.code ], {
        type: "text/plain;charset=ascii"
    });
    ...
}
```

**Comment by Sebmaster** [comment]
See https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global. This is the exact problem you're going to run into.

**Comment by Progyan1997** [comment]
@Sebmaster Thank you so much for your response. I was curious, is there any way I can make sure that the `onClick` handler method is being called without actually calling it, i.e., using _fake handler_?

**Comment by domenic** [comment]
There probably is, but that question is more suitable for StackOverflow than here, sorry.
