### ISSUE TITLE
I found an important mistake in your HTMLCanvasElement.toBlob() method

### ISSUE THREAD

**Issue by challakoushik** [jsdom/jsdom#2200]
line 71 in https://github.com/jsdom/jsdom/blob/2e90c57c282eb06023fab09304e29622268b91cb/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js#L62-L86

the quality being passed for image/jpeg is 
`Math.min(0, Math.max(1, qualityArgument)) * 100`

which is always supposed to be 0, I think the correct line would be 
`Math.max(0, Math.min(1, qualityArgument)) * 100`

**Comment by Sebmaster** [comment]
Looks like this should be exactly the other way around. Replace min by max and max by min.

**Comment by challakoushik** [comment]
yep! updated my comment

**Comment by challakoushik** [comment]
I didn't clone the repo yet. I guess its better if one of you guys working on this repo could file a PR, since it is just one line of change

**Comment by TimothyGu** [comment]
You can do it without having to clone the repo :)

Go to https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js and click on the Edit button next to History and you can just edit it from there.

But if you don't have time to do that, one of us will eventually get to it, but the time frame is not guaranteed at all.

**Comment by challakoushik** [comment]
Ok cool! Filed a pull request https://github.com/jsdom/jsdom/pull/2203
