### ISSUE TITLE
jsdom cannot recognize installed canvas-prebuilt

### ISSUE THREAD

**Issue by Ailrun** [jsdom/jsdom#2201]
### Basic info:

- **Node.js version:** v8.11.1
- **jsdom version:** v11.8.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`<body></body>`);

const canvas = dom.window.document.createElement('canvas');
const ctx = canvas.getContext('2d');
ctx.fillRect(0, 0, 1, 1);
```

Reproduction repository: https://github.com/Ailrun/jsdom-canvas-prebuilt-bug

This code throws an error with message `TypeError: Cannot read property 'fillRect' of null`, and also gives a warning about uninstalled canvas package. However, as you can see in the repository, I install `canvas-prebuilt@2.0.0-alpha.12`.

Wierdly, this code works with `canvas-prebuilt@2.0.0-alpha.5`, but does not with any version above it.

### How does similar code behave in browsers?

https://codepen.io/ailrun/pen/PewgGJ
(Of course, it does nothing, but also does not throw any error.)

**Comment by challakoushik** [comment]
As discussed in https://github.com/jsdom/jsdom/pull/1964 jsdom guys are still waiting for canvas2.x to get out of alpha state before merging it . For now, you should use the first version of canvas if you wanna mix it with jsdom
`npm install canvas
`
Secondly, Fixed the browser codepen you gave. In the browser you need to append the canvas into the body, also rectangle of width and height 1 would hardly be visible
https://codepen.io/anon/pen/rvVgme

**Comment by Ailrun** [comment]
Oh... I didn't know it, since it works with `canvas-prebuilt@2.0.0-alpha.5`.
I just want to show that there's no error in my browser example. That's why I make that 'minimal' example.
