### ISSUE TITLE
HTMLInputElement's value property should be reflected in the value attribute (through getAttribute and outerHTML)

### ISSUE THREAD

**Issue by ryan-petrich-mpf** [jsdom/jsdom#2208]
### Basic info:

- **Node.js version:** 9.11.1
- **jsdom version:** 11.9.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<input id="test">`);
const input = dom.window.document.getElementById("test");
input.value = "content";
assert.equal(input.getAttribute("value"), "content");
assert(/content/.test(input.outerHTML));
```

### How does similar code behave in browsers?

Any updates to an input element's `value` property should be reflected in its `value` attribute and `outerHTML` property.

**Comment by rpetrich** [comment]
An incomplete patch I've been using in my software to workaround this bug, for the subset of the API it uses:
```js
const HTMLInputElementPrototype = document.createElement("input").constructor.prototype;
const oldDescriptor = Object.getOwnPropertyDescriptor(HTMLInputElementPrototype, "value");
if (oldDescriptor) {
	const descriptor = Object.create(oldDescriptor);
	const oldSet = descriptor.set;
	descriptor.set = function(value) {
		oldSet.call(this, value);
		this.setAttribute("value", value);
	};
	Object.defineProperty(HTMLInputElementPrototype, "value", descriptor);
}
```

**Comment by Sebmaster** [comment]
This seems incorrect. See this jsbin: http://jsbin.com/funonoyiyu/edit?html,js,console

**Comment by ryan-petrich-mpf** [comment]
Hmm... right you are. I've been building a DOM server-side and was expecting updates to `value` to be  represented in `dom.serialize()`, but it seems this should not be the case.

Closing.
