### ISSUE TITLE
When parsing XML, JSDOM should produce CDATASection and Comment nodes even when their content is the empty string

### ISSUE THREAD

**Issue by lddubeau** [jsdom/jsdom#2213]
### Basic info:

- **Node.js version:** 8.11.1
- **jsdom version:** 11.10.0

### Minimal reproduction case

```js

const { JSDOM, VirtualConsole } = require("jsdom");

const vc = new VirtualConsole();
vc.sendTo(console);

const { window } = new JSDOM("", { virtualConsole: vc });

const { DOMParser, Node } = window;

function assert(msg, actual, expected) {
  if (actual !== expected) {
    console.log(`${msg}: got ${actual} but expected ${expected}`);
  }
  else {
    console.log(`${msg}: passed`);
  }
}

function assertCDATA(node, value) {
  try {
    assert("CDATA node", node.nodeType, Node.CDATA_SECTION_NODE);
    assert("CDATA node content", node.textContent, value);
  }
  catch (ex) {
    console.log(`Failed with: ${ex}`);
  }
}

function assertComment(node, value) {
  try {
    assert("comment node", node.nodeType, Node.COMMENT_NODE);
    assert("comment node value", node.textContent, value);
  }
  catch (ex) {
    console.log(`Failed with: ${ex}`);
  }
}

const parser = new DOMParser();
const doc = parser.parseFromString(
  "<doc><![CDATA[]]><!----></doc>",
  "text/xml");
const de = doc.documentElement;

function check() {
  assert("content", de.textContent, "");
  assert("length", de.childNodes.length, 2);
  assertCDATA(de.childNodes[0], "");
  assertComment(de.childNodes[1], "");
}

check();
```

`check` fails because the CDATA and comment nodes are missing.

### How does similar code behave in browsers?

In Chrome and Firefox `check` does not fail. In those browsers, the result of parsing the XML shown above includes a CDATA section that has the text "" and a comment with the text "", whereas in JSDOM the nodes are just not created.

The XML standard does not prescribe a behavior. It specifies what a CDATA section is, and what a comment is but does not specify whether such constructs should be seen by client applications if the data they contain is the empty string. It is up to the parser to decide whether it shows them to the client code or not. I did not see anything in the DOM or HTML living standards that mandates one behavior or another.

Although I've not found a specification that mandates creating the nodes, I have two arguments:

1. Chrome and Firefox create a CDATA node that has for data an empty string and the same for Comment.

2. When using JSDOM to parse HTML, an empty comment in the source results in a Comment node with empty text in the resulting DOM. For the sake of consistent behavior, XML parsing should behave the same. (CDATA is not allowed in HTML so we cannot compare how it is handled when parsing HTML.)

In my mind that's enough of a justification, but I'd like to know whether the folks here are in agreement before I put in a PR for [sax](https://github.com/isaacs/sax-js) to add an option to require that it produces events for CDATA and comment even when their data is an empty string.

**Comment by lddubeau** [comment]
I'll create a WPT.

Is there a contingency in place for getting the fix used by JSDOM if the PR for sax does not get merged in a timely manner? It would be a shame to leave the issue open in JSDOM because the PR for sax ends up being held up. Unfortunately, that would mean having JSDOM depend on a custom version of sax. I try to avoid doing this as much as possible in the projects I'm responsible for but sometimes I cannot wait for a PR to get merged.

**Comment by lddubeau** [comment]
@domenic If I cannot get the fixes merged into sax in a timely manner, I'm going to produce a fork. Irrespective of what happens with JSDOM, I use sax directly in some of my projects and I need it fixed for those projects.

**Comment by domenic** [comment]
Great, if that happens, feel free to submit a PR to switch to it!

**Comment by lddubeau** [comment]
I got no action on the PRs I submitted on sax. So it looks like I'm going to have to fork sax.

Since my last comment, I looked closer at the code of sax, and found additional issues. I need to ensure that the XML I parse is well-formed. However, sax does not currently enforce well-formedness, even in strict mode. It catches some malformedness errors but not all of them.

Unless I missed something somewhere, jsdom relies on sax to find malformedness errors. So the lack of proper well-formedness checks is also a problem for jsdom.

I've started investigating how I can run sax over the [XML conformance suite](https://www.w3.org/XML/Test/) so that I can end up with a tool that guarantees well-formedness.

**Comment by Zirro** [comment]
@lddubeau As you've noticed, our handling of XML has always been rather lacking. If you have the time and dedication to resolve those issues, that'd be excellent.

Expanded testing is also good news, though I should caution that the tests (and specs) from that time do not necessarily reflect what browsers actually ended up implementing. If in doubt, make sure to check that a test in question actually passes in current browsers too.

**Comment by lddubeau** [comment]
The conformance suite is [out](https://github.com/lddubeau/xml-conformance-suite).

The sax fork, named saxes, is [out too](https://github.com/lddubeau/saxes).

I'll put together a PR for jsdom as soon as I can.

**Comment by domenic** [comment]
Hey @lddubeau, no rush, but we're all looking forward to integrating saxes into jsdom! Any updates?

**Comment by lddubeau** [comment]
Unfortunately, the work I do on saxes and jsdom currently does not go into the "paid work column" so the attention I can give them is only sporadic.

However, it so happens that I did get back to the specific issue of moving jsdom from sax to saxes last week. I ran into an issue: parsing XML fragments. As it stands, jsdom does not do anything special to parse XML fragments: it just hands fragments off to sax as it would a hand off to sax a complete document. This *sometimes* works. For instance, doing `el.innerHTML = ""` works because sax does not care if you give it an empty document. It won't report any error, though according to the XML spec the empty string is not a well-formed XML document. However, if you do `el.innerHTML = "foo"`, you run into trouble because sax will treat the string `"foo"` as non-whitespace text outside of the document root, which is a well-formedness constraint that sax decided to check. So this second example results in an error.

Saxes complains about both cases above. In jsdom's test suite, there's a call to `window.close()` which has for effect to set the `innerHTML` of the `body` element to `""` and thus triggers a parsing error. So as soon as I ran jsdom's suite, I ran into bunches of errors due to this.

I figured it would be useful for saxes to be able to parse XML fragments so I've worked on adding that capability to saxes. I've not pushed out the modifications yet but I've added a flag which sets the initial parser state to expect content that is acceptable in an element (that is, any content that could appear between the opening and closing tags in `<foo></foo>`), and turns off some checks about the document root. And I've added an option which allows pre-defining prefix-to-namespace bindings known before parsing starts. These two additions together allow saxes to provide the results expected by the [XML fragment parsing specs](https://html.spec.whatwg.org/multipage/xhtml.html#parsing-xhtml-fragments).

I expect the changes to saxes to go out today, and have a PR for jsdom today too.

**Comment by domenic** [comment]
Great stuff! And yeah, I totally understand how this stuff takes time due to being off-work hours; same for me. Just wanted to let you know we were still excited about things :).

**Comment by lddubeau** [comment]
I've made good progress, but the PR won't be ready today I'm afraid. I'm seeing some bizarre things in the way `script` is handled, which II need to figure out before I submit a PR. Unfortunately, I probably won't have an opportunity to work on this again for a few days. :-/

**Comment by lddubeau** [comment]
Managed to find some time, so: PR filed: https://github.com/jsdom/jsdom/pull/2340
