### ISSUE TITLE
 ReferenceError: Node is not defined (via Node.TEXT_NODE)

### ISSUE THREAD

**Issue by colinrcummings** [jsdom/jsdom#2220]
### Basic info:

- **Node.js version:** 8.11.1
- **jsdom version:** 11.8.0

### Minimal reproduction case

```js
// jsdom setup
if (typeof window === 'undefined') {
  const { JSDOM } = require('jsdom');

  const { document } = new JSDOM(
    '<!doctype html><html><body></body></html>'
  ).window;

  const win = document.defaultView;

  global.document = document;
  global.window = win;

  propagateToGlobal(win);
}

function propagateToGlobal(window) {
  for (let key in window) {
    if (!window.hasOwnProperty(key)) continue;
    if (key in global) continue;
    global[key] = window[key];
  }
}

// code reproducing the problem
function getNodeText(node) {
  return Array.from(node.childNodes)
    .filter(
      child => child.nodeType === Node.TEXT_NODE && Boolean(child.textContent), // ReferenceError here
    )
    .map(c => c.textContent)
    .join(' ')
}

const p = document.createElement('p');
p.textContent = 'Hello';
document.body.appendChild(p);

getNodeTextTest(document.querySelector('p'));

```

### How does similar code behave in browsers?

`getNodeTextTest` returns `'Hello'` vs. throwing `ReferenceError: Node is not defined`.

**Comment by Sebmaster** [comment]
See https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global. These are exactly the problems you get when ignoring that advice.

**Comment by colinrcummings** [comment]
Thank you, @Sebmaster. I was not aware of this. For posterity, our initial JSDOM configuration came from [here](https://jaketrent.com/post/testing-react-with-jsdom/); revising it to [this one](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md#using-enzyme-with-jsdom) resolved the issue.

**Comment by TimothyGu** [comment]
@colinrcummings FYI, the one you switched to has the exact same problems as https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global.

**Comment by colinrcummings** [comment]
Thank you, @TimothyGu. I'm aware, but need the document in the global scope until we migrate all of our tests touching `react` from `enzyme` to `react-testing-library`, which is where `getNodeText` is from.

**Comment by Javarome** [comment]
I have the same problem. I can understand the need for using window scopes, but I don't understand how to get runtime _types_ through this. Could you provide an example that would make use of the `Node` type? Thanks

**Comment by bmaupin** [comment]
Similar to the example, I didn't have a DOM instance in the scope of where I wanted to access the `Node` types, so as a hacky workaround I added this to the top of my file so I could access them from anywhere:

```javascript
const Node = new JSDOM('').window.Node;
```
