### ISSUE TITLE
Non-HTML Elements Moved From <head> to <body>

### ISSUE THREAD

**Issue by ArronFerguson** [jsdom/jsdom#2221]
I'm using Node.js to create some simple templating code where the HTML document read in has non-HTML elements that can be found both in the head as well as the body of the HTML document. However, when I read it in via JSDOM (version 11.10.0), the non-HTML elements are moved from the HTML head element and into the HTML body element.

So the following Node.js JavaScript code:

```
const jsdom = require('jsdom');
const { JSDOM } = jsdom;
// where templateFile = name of some local file to load
let contents1 = fs.readFileSync(templateFile, "utf8");
let f1dom = new JSDOM(contents1);
// out to console to see the document:
console.log(f1dom.window.document.documentElement.outerHTML);
```

Will produce:
```
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    </head><body><frag id="m2">REPLACE ME</frag>
    <frag id="meta">
      <title>MAIN TEMPLATE</title>
      <meta charset="utf-8">
      <style>
      </style>
    </frag>

    <frag id="header">
      <p>Header to be replaced.</p>
    </frag>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
    /*<![CDATA[*/
        $(document).ready(function() {


            //console.log("Document is now ready.");

        });
    /*]]>*/
    </script>
    <frag id="footer">
      <p>Footer to be replaced.</p>
    </frag>
</body></html>
```

When in fact the original document in the file system is:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <frag id="m2">REPLACE ME</frag>
    <frag id="meta">
      <title>MAIN TEMPLATE</title>
      <meta charset="utf-8"/>
      <style>
      </style>
    </frag>

  </head>
  <body>

    <frag id="header">
      <p>Header to be replaced.</p>
    </frag>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
    /*<![CDATA[*/
        $(document).ready(function() {


            //console.log("Document is now ready.");

        });
    /*]]>*/
    </script>

    <frag id="footer">
      <p>Footer to be replaced.</p>
    </frag>

  </body>
</html>
```

So the non-HTML (well, XML elements really) are being moved out of the head and into the body.

**Comment by domenic** [comment]
This is working as intended. Try that document in your browser and you'll see the result.

http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5936

**Comment by ArronFerguson** [comment]
Wow, you are right. I didn't know that the browsers would move them out of the head and into the body. Sorry about that!

**Comment by geraltrivyan** [comment]
> This is working as intended. Try that document in your browser and you'll see the result.
> 
> http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=5936

I guess this is NOT woking as intended now?
