### ISSUE TITLE
Doesn't parse IDs that begin with number

### ISSUE THREAD

**Issue by samueleaton** [jsdom/jsdom#2233]
### Basic info:

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.
– [HTML 5 spec](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id)

- **Node.js version:** 9.2
- **jsdom version:** 11.10.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { document } = (new JSDOM(`<div><div id="1234">yo yo</div></div>`)).window;
const text = document.querySelector("#1234");
//=> SyntaxError: The string "#1234", is not a valid CSS selector
```

Adding a letter to the front if ID does not raise error:

```js
const { JSDOM } = require("jsdom");

const { document } = (new JSDOM(`<div><div id="a1234">yo yo</div></div>`)).window;
const text = document.querySelector("#a1234");
```

---

Thank you for this awesome project.

**Comment by domenic** [comment]
You ommitted the most important part of the template: how does similar code behavior in a browser? As you can see if you try it, it also throws in browsers.

Just because an ID is allowed to start with a number, doesn't mean querySelector works with that ID.
