### ISSUE TITLE
style property garbled 

### ISSUE THREAD

**Issue by FernandoCesarS** [jsdom/jsdom#2239]
### Basic info:

- **Node.js version: 8.9.4** 
- **jsdom version: 11.10.0**

### Minimal reproduction case

After parsing an html file the following div tag

`<div style="text-align:center; font-family:" Gill Sans ", "Gill Sans MT ", "Myriad Pro ", "DejaVu Sans Condensed ", Helvetica, Arial, sans-serif; font-size:12px;">`

changed to

`<div style="text-align:center; font-family:" gill="" sans ",=" " "gill="" sans="" mt ",=" " "myriad="" pro ",=" " "dejavu="" condensed ",=" " helvetica,=" " arial,=" " sans-serif;=" " font-size:12px;"="">`

'=' signs and comas were added. This is not standard HTML/CSS.

**Comment by Sebmaster** [comment]
Your input html is invalid; you need to escape your quotes.
