### ISSUE TITLE
Vulnerability found

### ISSUE THREAD

**Issue by evheniy** [jsdom/jsdom#2241]
### Basic info:

- **Node.js version: 8.9.4**
- **jsdom version: 11.10.0**

### Minimal reproduction case

```
nsp check
```
 1 vulnerability found
jsdom@11.10.0 > request@2.85.0 >  stringstream@0.0.5 

https://nodesecurity.io/advisories/664

**Comment by domenic** [comment]
Let me close this until you can provide a reproduction case of this being used to attack jsdom users, instead of stringstream users.
