### ISSUE TITLE
Performance regression in 11.11

### ISSUE THREAD

**Issue by bterlson** [jsdom/jsdom#2244]
### Basic info:

- **Node.js version:** 10.1 (also true in various versions of 8 and 9)
- **jsdom version:** 11.11

### Minimal reproduction case

Sadly this is the most minimal I can do at the moment:

* Clone the ECMA262 repository (git clone https://github.com/tc39/ecma262)
* `npm install` (which should give you ecmarkup v3.14.4 which has a fixed dep on JSDom 11.10.
* `npm run build` should give you a nice spec in around a minute.
* replace the jsdom dep with 11.11
* `npm run build` is now extremely slow

The regression occurs in the "walk" phase which you can see [here](https://github.com/bterlson/ecmarkup/blob/master/src/Spec.ts#L671). Most of the jsdom interaction is DOM traversal via nextSibling and friends and using the TreeWalker. I am also making heavy use of textContent.

**Comment by domenic** [comment]
Rolling back to 56dddf069cb9b32620a58daa1d62973eb9669c43 fixes, making it likely the culprit is the switch from nwmatcher to nwsapi. (Although it's hard to imagine how, looking at the problematic code---I don't see how selectors would get involved.) Working full confirmation next...

**Comment by domenic** [comment]
Confirmed. Just reverting 38b868b0ca2a127a55c8a59a0e1320e032074118 (the selector engine switch) fixes the slowdown. OK, now, why...

**Comment by Zirro** [comment]
I'm currently talking to @dperini. We'll look into it.

**Comment by Zirro** [comment]
@bterlson nwsapi 2.0.1 has been released with a fix for this issue, and the ecma262 build process should be just as fast as before. If everything looks good on your end, this issue can be closed.
