### ISSUE TITLE
window.postMessage doesn't work

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [jsdom/jsdom#2245]
### Basic info:

- **Node.js version:** 8.9.0
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
window.addEventListener("message", e => console.log(e.data));
window.postMessage("message from same of child frame", "*");
```
in browser env will output:
```
message from same of child frame
```
in jsdom test env `message` event is never fired.

### How does similar code behave in browsers?

Works as expected.

### Findings 

I found that bug is introduced with `setTimeout` method in this commit:
> https://github.com/jsdom/jsdom/blob/eca4167b171709b085e0d81962963f30ed165133/lib/jsdom/living/post-message.js#L33

Once `setTimeout` is removed all will start working as expected.

this code:
```js
  event.initEvent("message", false, false);

  setTimeout(() => {
    this.dispatchEvent(event);
  }, 0);
```

become: 
```js
  event.initEvent("message", false, false);
  this.dispatchEvent(event);
```

**Comment by domenic** [comment]
Cannot reproduce. https://runkit.com/domenicdenicola/5b083681cd866200120d374f

**Comment by vukasin-nikodijevic** [comment]
@domenic  try this one - it doesn't work with `jest`:

```
$ vim testPostMessage.spec.js 
test("window.postMessage", () => {
	window.addEventListener("message", function(e){
		console.log(e.data);
	});

	window.postMessage("bla bla blah", "*");
});
```

```
$ npm install jest@latest
$ ./node_modules/.bin/jest
```

my test env:
```
$ node --version
v8.11.2
$ ./node_modules/.bin/jest --version
23.0.1
$ cat /etc/*release*
Fedora release 26 (Twenty Six)
```

**Comment by Zirro** [comment]
@vukasin-nikodijevic If it only happens when Jest is involved, it's likely that Jest is doing something which breaks jsdom. If that's the case I'd recommend that you create an issue in their repository.

**Comment by vukasin-nikodijevic** [comment]
Actually it isn't problem with `jest` - it is really strange implementation of window.postMesasge() in jsdom.

I would really like to understand why dispatching of message event is wrapped with setTimeout ?

So here is problem:


and here is workaround:

* Test must be async
* test execution must be blocked for some amount of time.  `await new Promise(resolve => setTimeout(resolve, 100));` must have higher waiting time then setTimeout from `window.postMessage()` implementation - which is 0.

```
test("window.postMessage", async function() {

        expect.assertions(1);

        window.addEventListener("message", function(e){
                expect(e.data).toEqual("bla bla blah");
        });

        window.postMessage("bla bla blah", "*");

        await new Promise(resolve => setTimeout(resolve, 100));
});
```

**Comment by TimothyGu** [comment]
That’s not because our implementation is weird – that’s because that’s how browser works. See https://html.spec.whatwg.org/multipage/web-messaging.html#dom-window-postmessage

**Comment by vukasin-nikodijevic** [comment]
@TimothyGu thanks for explanation - you are right. 

MDN explains this as well:
> https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

```
postMessage() schedules the MessageEvent to be dispatched only after all pending execution 
contexts have finished. For example, if postMessage() is invoked in an event handler, 
that event handler will run to completion, as will any remaining handlers for that same 
event, before the MessageEvent is dispatched.
```

**Comment by DmitriyWebDev** [comment]
@vukasin-nikodijevic 

`jsdom` actual `setTimeout()` source code - https://github.com/jsdom/jsdom/blob/main/lib/jsdom/browser/Window.js#L815
