### ISSUE TITLE
jsdom cannot load the base64 image .(data:image/webp;base64,xxxxx)

### ISSUE THREAD

**Issue by gclinux** [jsdom/jsdom#2254]
### Basic info:

- **Node.js version:8.9 
- **jsdom version:** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};

const dom = new JSDOM(`
  <img src=data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoBAAEAAgA0JaQAA3AA/vuUAAA=">
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by dagadbm** [comment]
I am also trying to test image upload using a base64 string but the onLoad is not being triggered (kind of a different use case but I passed in the resource: usable flag using jest.

**Comment by domenic** [comment]
When I run this code in Node.js, I get a syntax error. So this did not follow the issue template, by providing a full example we can debug. I will close this, but please feel free to edit and re-ping the thread if you update it with a minimal debuggable example. At that time, please also fill out the rest of the issue template, including how it works in browsers, and the jsdom version in use.
