### ISSUE TITLE
function reference tromped by button with the same ID

### ISSUE THREAD

**Issue by ericprud** [jsdom/jsdom#2259]
### Basic info:

- **Node.js version:** 6.11.3
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom")

  let dom = new JSDOM(`
<!DOCTYPE html>
<html>
  <head>
    <script src="https://www.w3.org/scripts/jquery/2.1.4/jquery.min.js"></script>
  </head>

  <body>
    <button id="validate">validate (ctl-enter)</button>
    <script>
    // window.onload = function () {
        function validate (done) {
          console.log('called')
        }
        
        document.getElementById("validate").onclick = function (evt, done) {
          console.log(validate)
          validate();
        };
        window._testCallback()
    // }
    </script>
  </body>
</html>
                      `, {
    runScripts: "dangerously",
    resources: "usable"
  })
  dom.window._testCallback = e => {
    dom.window.document.getElementById('validate').click()
    done(e)
  }
```
I'm using mocha, jsdom and some wiring in my browser scripts to test said scripts.
I [saw success](https://travis-ci.org/shexSpec/shex.js/builds/388324515) on node 8.0.0 and 10.3.0 but a failure on node 6.0.0.
The reference to the `validate` function was being replaced by a ref to the `#validate` button.
I worked around it by [giving them different names](https://github.com/shexSpec/shex.js/commit/b39a4c180f006195f5dc820d5fa5c75f146eb975) but thought I'd minimize and report here.
Note that uncommenting the `window.onload` works around the problem so it's be difficult to see whether it's an interaction with jquery.

### How does similar code behave in browsers?

I can't reproduce this in a browser as they all run more modern nodes.

**Comment by Zirro** [comment]
Thanks for the report. We have seen similar issues in our tests, and as you mention it doesn't happen in later releases of Node.js.

Unfortunately I don't think this is something we can (or should try to) fix, as the bug most likely exists in Node.js v6 rather than in jsdom. I can only recommend running this test specifically in recent versions of Node.

**Comment by domenic** [comment]
Indeed. A legit bug, but one we wan't fix, so let's close this.
