### ISSUE TITLE
querySelectorAll returns incorrect result

### ISSUE THREAD

**Issue by smercadomx** [jsdom/jsdom#2260]
### Basic info:

- **Node.js version:** 8.5.0
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
  <button>First Button</button>
  <span tabindex="-1">I'm a span</span>
  <div tabindex="-1">I'm a div</div>
`);

console.log(dom.window.document.querySelectorAll('button, *[tabindex]'));
```

The above code returns only the button:
`NodeList { '0': HTMLButtonElement {} }`

 Instead of all 3 elements:
`NodeList {
  '0': HTMLButtonElement {},
  '1': HTMLSpanElement {},
  '2': HTMLDivElement {} }
`

### How does similar code behave in browsers?

It returns the 3 elements(button, span and div).

**Comment by Zirro** [comment]
@dperini, could you look at this when you have time?
