### ISSUE TITLE
Docu for jsdom.env migration

### ISSUE THREAD

**Issue by ain** [jsdom/jsdom#2266]
### Basic info:

- **Node.js version:** v8.8.1
- **jsdom version:** 11.11.0

### Minimal reproduction case

Any code that uses `jsdom.env` for Mocha, expecting a `done` callback to conclude on a test, e.g.

```js
        jsdom.env({
          html: `<!doctype html><html><head></head><body class="ui-page"></body></html>`,
          scripts: SCRIPTS,
          done: function(err, window) {
            global.document = window.document;
            global.window = window;
            done();
          }
        });
```

The migration to v2 API with the reasonable replacement for `jsdom.env` is not clearly documented. There are hints in closed issues, but they're not conclusive. I've tried several scenarios now, but I'm getting a myriad of errors from JSDOM and the resolution seems to be as nearly as tricky as for Selenium with headless Chrome.

I'd call for documenting this exclusively in README since also the current backlog is loaded with issues that refer to `jsdom.env` use.

**Comment by domenic** [comment]
The situations are so different, there's generally no straightforward mapping. I'd suggest reading the new README documentation and figuring out it works, ignoring all previous usage of .env. Or, continue using the old API, as documented there.

Also, [don't stuff jsdom globals onto the node global](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global).
