### ISSUE TITLE
`HTMLElement.prototype.draggable` descriptor is missing

### ISSUE THREAD

**Issue by caridy** [jsdom/jsdom#2268]
### Basic info:

- **Node.js version:** v10.1.0
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const jsdom = require("./");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<body></body>`);

const HTMLElement = dom.window.HTMLElement;
const draggable = Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'draggable');

console.log(draggable); // yields undefined
```

Documentation:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

### How does similar code behave in browsers?

```js
Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'draggable');
```

It yields `{get: ƒ, set: ƒ, enumerable: true, configurable: true}` in all major browsers.

**Comment by Zirro** [comment]
Like the case with [`isContentEditable`](https://github.com/jsdom/jsdom/issues/1670), this is probably something we shouldn't expose until we have support for the rest of the HTML Drag and Drop API (the parts that can be observed without interactions/rendering, anyway).

**Comment by caridy** [comment]
Yeah, I get that. We found this one in a piece of code that was reading the descriptor to extract the setter/getter of that property so it can use it even when they are patched, or poisoned by someone else.

It seems that having the property and attribute reflection should be good enough, even though the Drag and Drop API is not ready yet.
