### ISSUE TITLE
Why I can't run this example remotely

### ISSUE THREAD

**Issue by Fazendaaa** [jsdom/jsdom#2286]
### Basic info:

- **Node.js version:** 9.8.0
- **jsdom version:** 11.11.9

### Minimal reproduction case

The following code doesn't work:

```ts
const { JSDOM } = require("jsdom");

const dom = new JSDOM(``, {
  url: "https://example.org/",
  referrer: "https://example.com/",
  contentType: "text/html",
  userAgent: "Mellblomenator/9000",
  includeNodeLocations: true
});

console.log(dom.window.document.querySelector("p").textContent); 
```

But when I use the following:

```ts
import { readFileSync } from 'fs';
import { JSDOM } from 'jsdom';
import { join } from 'path';

const htmlPath = join(__dirname, './example.html');
const html = readFileSync(htmlPath);
const dom = new JSDOM(html);

console.log(dom.window.document.querySelector('p').textContent);
```

Works just fine. Why?

**Comment by TimothyGu** [comment]
You passed an empty string to the first code sample. What happens is that the initialized Document will *think* it's `https://example.org`, but will not contain the content of https://example.org/.

See documentation of the [`url` option](https://github.com/jsdom/jsdom#simple-options). You probably want to use something like [`JSDOM.fromURL()`](https://github.com/jsdom/jsdom#fromurl).

**Comment by Fazendaaa** [comment]
Worked just fine, thanks!

But I'm having another issue trying to access a variable named foo, is an object in the window... After fetching the URL that I want I can access all of the HTML without any a headache. But the website in the first <script> sets the window.foo = ['bar']. When I tried to access window.foo say's it's undefined.

**Comment by TimothyGu** [comment]
Why don’t you submit another issue with the template filled out with a minimal test case?

**Comment by Fazendaaa** [comment]
Sure, thanks.
