### ISSUE TITLE
Fetching a window variable

### ISSUE THREAD

**Issue by Fazendaaa** [jsdom/jsdom#2287]
### Basic info:

- **Node.js version:** 9.8.0
- **jsdom version:** 11.11.0

### Minimal reproduction case

I have the following HTML:

```html
<!doctype html>

<html lang="en">

<head>
  ...
  <script>
    window.productList = [{
        "id": "0000",
        "category": "foo",
        "available": true
     }];
  </script>
</head>
  ....
</html>
```

And I've been trying to access the productList as follows:

```js
...
  const { window } = await fromURL(process.env.URL, {
      resources: 'usable',
      runScripts: 'dangerously'
  });
  const { document, productList } = window;

  console.log(productList);
...
```

But the productList is being printed as undefined. What am I doing wrong?

note: I can access all of the HTML content, so I know that the fromURL is working properly.

**Comment by sneko** [comment]
Just wanted to add a custom solution to interpret static global variables without `runScripts: 'dangerously'` when relying on third-party content.

https://gist.github.com/sneko/72f1a6deb9efdf47b952fb3dd31660c6
