### ISSUE TITLE
Input number validation error for decimal steps due to floating-point arithmetic

### ISSUE THREAD

**Issue by paradoxxxzero** [jsdom/jsdom#2288]
Consider this input:
```html
<input type="number" min="0" value="12.50" step="0.01" />
```
in a browser this is valid but with jsdom (current version) it sets the stepMismatch validation error and therefore I get the "Constraints not satisfied" error.
I traced it till this line: https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLInputElement-impl.js#L823
which computes 
`12.5 % -0.01 = 0.00999999999999974` even though `1250 * 0.01 = 12.5`.

**Comment by oliverjam** [comment]
Yeah I have the exact same problem. `<input type="number" min="0" max="3.5" step="0.01" />` triggers a step mismatch validation error with any value I try (it's fine in browser)

Here's a minimal repro with react-testing-library and Jest

```js
const React = require("react");
const { render, fireEvent } = require("react-testing-library");

function Input() {
  return React.createElement("input", {
    "aria-label": "price",
    type: "number",
    min: "0",
    max: "3.5",
    step: "0.01"
  });
}

test("Input validation", () => {
  const { getByLabelText } = render(React.createElement(Input));
  const input = getByLabelText("price");
  fireEvent.change(input, { target: { value: "3" } });

  expect(input.value).toBe("3");
  expect(input.validity.stepMismatch).toBe(false);
});
```

[Repo here](https://github.com/oliverjam/jsdom-validityState-bug). `npm it` in that to see the failing test.

You can actually run the same test in Codesandbox and see it pass because that uses the actual DOM rather than jsdom

https://codesandbox.io/s/ko2z4jvjq7

**Comment by kontomondo** [comment]
@domenic is there a higher precision arithmetic library available in jsdom ? An alternative solution is to normalise both the step and the value by multiplying by a factor that yields integer values - `multiply by 10^n` where `n` - total nr. of floating digits on the `step` and `value`.

**Comment by domenic** [comment]
No, sadly, nothing available. We could try the multiplication business, although I'm sure that'll fail in some other interesting case... [Chrome apparently has a decimal library and some other decomposition into before/after the decimal point to handle this](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/forms/number_input_type.cc?type=cs&g=0). Very interesting.

We could pull in one of https://www.npmjs.com/search?q=decimal if it helps.

**Comment by kontomondo** [comment]
@domenic I took a quick look, and decimal.js seemed like something that's simple and well supported. created a PR.

**Comment by lordoffreaks** [comment]
Hi!

I'm finding the same error ocurring for me using `jsdom` 16.2.0 see https://codesandbox.io/s/dark-bird-bf18s ... could you advise please?

Thanks

**Comment by domenic** [comment]
File an issue using the issue template. Comments on closed issues are not tracked.
