### ISSUE TITLE
can't use reconfigure to change referrer

### ISSUE THREAD

**Issue by samdsherman** [jsdom/jsdom#2289]
### Basic info:

- **Node.js version:** 7.2.1
- **jsdom version:** 11.5.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  url: 'https://www.example.com',
  referrer: 'https://www.google.com',
};
const dom = new JSDOM(``, options);

dom.window.referrer === 'https://www.google.com'; // true
dom.reconfigure({
  url: 'https://www.facebook.com',
  referrer: 'https://www.example.com',
});
dom.window.referrer === 'https://www.example.com'; // false
dom.window.referrer === 'https://www.google.com'; // true
```

i have some tests that care about referrer and i'd like to be able to change it using reconfigure.

**Comment by domenic** [comment]
This is not supported by reconfigure(). Instead, use normal JavaScript methods to change a property, i.e. Object.defineProperty().

**Comment by samdsherman** [comment]
when i use Object.defineProperty() i get an error
`Object.defineProperty(window.document, 'referrer', { value: referrer })`
```
TypeError: Cannot redefine property: referrer
        at Function.defineProperty (<anonymous>)
```

**Comment by domenic** [comment]
Can you produce a complete example, like the OP?

**Comment by samdsherman** [comment]
I'm using jest 23.2.0 with testEnvironment jest-environment-jsdom-global 1.1.0
```js
      describe('referrer', () => {
        const setReferrer = (referrer) => {
          Object.defineProperty(window.document, 'referrer', { value: referrer })
          // jsdom.reconfigure({ // this is what i wish i could do
          //   url: 'https://www.zumper.com',
          //   referrer,
          // })
        }
        test('should save if not from zumper/padmapper', () => {
          setReferrer('https://www.potato.com/whatever') // throws the above error
          ls.addTrackingToLocalStorage()
          expect(ls.getx('_referrer')).toBe('www.potato.com')
        })
```

**Comment by samdsherman** [comment]
here's the code i'm trying to test:
```js
    if (window.document.referrer) {
      m = window.document.referrer.match(/^https?:\/\/([^/]+)/i)
      if (m && !/\b(?:padmapper|zumper)[.]com$/i.test(m[1])) {
        this.setx('_referrer', m[1], 7)
      }
    }
```

**Comment by samdsherman** [comment]
previously i was using mocha instead of jest and I had this test working by just creating another JSDOM object for every test, like `global.dom = new JSDOM('', { referrer })`

**Comment by domenic** [comment]
It looks like the issue is that you're using defineProperty multiple times, but you're not setting configurable: true. It's hard to tell though without an isolated example in the same style as the issue template. We can't really debug third-party frameworks like Jest which may be complicating things.

**Comment by samdsherman** [comment]
that was it! thanks for your help :)
