### ISSUE TITLE
User-Agent string contains `undefined` in browserified build

### ISSUE THREAD

**Issue by Zirro** [jsdom/jsdom#2294]
The [default user agent string](https://github.com/jsdom/jsdom/blob/master/lib/api.js#L20) for jsdom makes use of `process.platform` which is not supported by browserify's `process` shim, resulting in this:

`Mozilla/5.0 (undefined) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.11.0`

There's an open issue for it [here](https://github.com/defunctzombie/node-process/issues/55), but based on the discussion I don't think we can expect a fix to be merged any time soon. Should we provide our own fallback value when `process.platform` is undefined?

**Comment by Zirro** [comment]
Another option is to stop advertising `process.platform` in the user agent altogether (or to replace it with a static value in order to maintain a similarity with other User-Agent strings).

The values returned from Node's `process.platform` already don't match what browsers put there, and we return the empty string for [`navigator.platform`](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/navigator/NavigatorID-impl.js#L17).

Since custom user-agent strings can be set through the API, it shouldn't be a problem for anyone who needs a specific value.

**Comment by domenic** [comment]
Keeping this information seems vaguely valuable. I'm thinking maybe we should do a fallback of "unknown OS" in the browser.
