### ISSUE TITLE
`querySelector` multi-selector string invalid result after altering node

### ISSUE THREAD

**Issue by codingmatty** [jsdom/jsdom#2296]
When using a multi-string selector (i.e. `'button, a, select, input'`) passed into `querySelector` or `querySelectorAll` after altering the element (using `innerHTML` or `appendChild`), the results include the node that is being queried. It _should_ exclude the node being queried, and only query the children.

### Basic info:

- **Node.js version:** 8.9.3
- **jsdom version:** 11.11.0 (does not occur in 11.10.0)

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM();
const document = dom.window.document;

const button = document.createElement('button');
console.log(button.querySelector('*'));                 // returns null
console.log(button.querySelector('button'));            // returns null
console.log(button.querySelector('button, span'));      // returns null
console.log(button.querySelectorAll('*'));              // returns NodeList {}
console.log(button.querySelectorAll('button'));           // returns NodeList {}
console.log(button.querySelectorAll('button, span'));   // returns NodeList {}
button.innerHTML = 'text';
console.log(button.querySelector('*'));                 // returns null
console.log(button.querySelector('button'));            // returns null
console.log(button.querySelector('button, span'));      // returns HTMLButtonElement {}
console.log(button.querySelectorAll('*'));              // returns NodeList {}
console.log(button.querySelectorAll('button'));         // returns NodeList {}
console.log(button.querySelectorAll('button, span'));   // returns NodeList { '0': HTMLButtonElement {} }
```

### How does similar code behave in browsers?

https://jsbin.com/toralofadu/edit?js,console

**Comment by dperini** [comment]
@codingmatty 
the bug is confirmed for the selector you reported in the issue.
However the bug has already been identified and fixed in `nwsapi` repository.
A review is needed and a complete test must be performed by the `jsdom` team.
After these steps a new minor version (2.0.6) will be pushed and made available on `npm`.

Thank you for reporting the issue.

**Comment by Zirro** [comment]
Thanks for the report @codingmatty, and @dperini for the quick fix! With all the existing tests passing, it should be fine to release 2.0.6 now. I'll keep the issue open until I've written a new test to cover this.
