### ISSUE TITLE
A href urls are not encoded

### ISSUE THREAD

**Issue by ghinda** [jsdom/jsdom#2297]
### Basic info:

Browsers encode special chars in `<a>` `href` urls. `jsdom` returns the url with the original/decoded chars.

- **Node.js version:** 10.6.0
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const {JSDOM} = require("jsdom");
const dom = new JSDOM(`
  <a href="http://{{var}}/one?two=2&three=3" />
`);
console.log(dom.window.document.querySelector('a').href)
```

Returns `http://{{var}}/one?two=2&three=3`.

### How does similar code behave in browsers?

Special chars in the url are encoded by browsers.
Browsers return `http://%7B%7Bvar%7D%7D/one?two=2&three=3`

http://jsbin.com/kiyocobiqi/edit?js,output

**Comment by domenic** [comment]
Firefox does not encode these. Neither does the [URL Standard](https://url.spec.whatwg.org/), which we follow. So, this is not a jsdom bug.

If you think the standard should be changed (which is quite possible given that there's not a lot of browser interop here), you can file an issue at https://github.com/whatwg/url.
