### ISSUE TITLE
Can we publish the package as precompiled because npm production builds are failing because module has failed to compile

### ISSUE THREAD

**Issue by atulsingh0913** [jsdom/jsdom#2298]
### Basic info:

- **Node.js version:**  8
- **jsdom version:**  9.12

### Minimal reproduction case

I am trying to use d3-node along with react js to plot chorolpleth maps. But it is not able to compile properly. It is failing because of jsdom dependency not getting resolved properly.

I am getting the following error

Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/d3-node/node_modules/jsdom/lib/jsdom/living/generated/utils.js:5 
Can we have this package pre compiled. Or is there any way to resolve this issue ?

**Comment by domenic** [comment]
No. If your tools cannot deal with the jsdom source code, you should file a bug on those tools.
