### ISSUE TITLE
calling cloneNode on DOCUMENT_NODE creates document with XML type

### ISSUE THREAD

**Issue by OleksiiKukuruza** [jsdom/jsdom#2299]
### Basic info:

- **Node.js version:** 10
- **jsdom version:** 11.11.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM();

const newDocument = new dom.window.DOMParser().parseFromString(`
  <body><section></section></body>
`, 'text/html');
const clone = newDocument.cloneNode(true);
const section  = clone.querySelector('section');

section.innerHTML = 'hello world';
```

HTMLToDOM constructor was called on cloneNode(true) and parser was set to sax and calling innerHTML will use sax as parser
https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/node.js#L19

**Comment by domenic** [comment]
Sorry for letting this sit for so long.

The example you give doesn't actually show any unexpected results. Can you include something that, e.g., logs an expected value, and then also include a link to a jsbin or similar showing it behaving differently in browsers? It's not clear what you're actually expecting here.

**Comment by OleksiiKukuruza** [comment]
Fixed in https://github.com/jsdom/jsdom/commit/f47f9e217c07c06c56d79a97d283ec7182434180
