### ISSUE TITLE
Does JSDOM serialization transform auto-closing tags to "classic" tags?

### ISSUE THREAD

**Issue by dotlouis** [jsdom/jsdom#2302]
Does JSDOM serialization transform auto-closing tags to "classic" tags?
Quick question that I brought up here:
https://github.com/Munter/subfont/issues/38

For example
`<input type="text" />` becomes `<input type="text">`
or `<img src="..." />` becomes `<img src="...">`

I saw JSDOM respects the [HTML spec](https://html.spec.whatwg.org/multipage/syntax.html#start-tags) which states that:
`Then, if the element is one of the void elements, or if the element is a foreign element, then there may be a single U+002F SOLIDUS character (/). This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.`

There is a "may be" here so is this considered normal behavior?
Thanks

**Comment by Sebmaster** [comment]
Yes, for HTML docs this is expected. We don't have a proper XML serialization yet, but that would keep them in XML docs.

**Comment by domenic** [comment]
"may be" in that part of the spec is explaining what code it is acceptable for authors to write, without validators like https://checker.html5.org/ complaining that they wrote bad code.

The relevant part of the spec for serialization is https://html.spec.whatwg.org/multipage/parsing.html#serialising-html-fragments . As you can see, it always serializes to the canonical form, which does not include any extra random characters like `/`.
