### ISSUE TITLE
Jest: SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by csvan** [jsdom/jsdom#2305]
### Basic info:

- **Node.js version:** 
10.7

- **jsdom version:** 
11.12

### Minimal reproduction case

Setup a simple Jest test case, see https://jestjs.io/docs/en/getting-started

As of 11.12, all our Jest (which ships with jsdom) have started failing with:

`SecurityError: localStorage is not available for opaque origins`

Rolling back to 11.11 seems to work, and I am not sure if this is a jsdom or Jest issue.

**Comment by tangjinzhou** [comment]
+1

**Comment by r0b1n** [comment]
Duplicate. See: https://github.com/jsdom/jsdom/issues/2304

**Comment by csvan** [comment]
@r0b1n apologies, closing.
