### ISSUE TITLE
localstorage is not available

### ISSUE THREAD

**Issue by SamuelBrucksch** [jsdom/jsdom#2306]
### Basic info:

- **Node.js version:** 10.7.0 and 8.11.3
- **jsdom version:** 11.12.0

Error message:
```
 SecurityError: localStorage is not available for opaque origins

      
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)

          at Array.forEach (<anonymous>)
```

### Minimal reproduction case

We dont use it directly, but its a dependency from jest framework. So it happens on every run. Not sure the exact code position. But check error message above. Seems to be related to the latest version from ~3h ago.

Thanks for investigating.

Kind regards

Samuel

**Comment by r0b1n** [comment]
Duplicate. See: https://github.com/jsdom/jsdom/issues/2304

**Comment by SamuelBrucksch** [comment]
Thanks for info
