### ISSUE TITLE
The new 11.12.0 version breaks Jest

### ISSUE THREAD

**Issue by dvago** [jsdom/jsdom#2309]
### Basic info:

- **Node.js version:**  9.0.0
- **jsdom version:** 11.12.0

### Minimal reproduction case

Given the dependencies 
```
    "jest": "^23.4.1",
    "jest-serializer-vue": "^2.0.2",
    "jest-vue-preprocessor": "^1.4.0",
```
The new jsdom package makes every test within jest failing

```
> jest --config test/unit/jest.conf.js --coverage
FAIL src/components/atoms/Button/Button.spec.js
   ● Test suite failed to run
     SecurityError: localStorage is not available for opaque origins
      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
```
where some bits of the test are fairly basic:

```js
import { mount } from '@vue/test-utils';
import Button from './Button';

describe('Button', () => {
  const wrapper = mount(Button, {
    attachToDocument: true,
  });

  it('renders button tag by default', () => {
    expect(wrapper.is('button')).toBe(true);
  });

```

I had to pin the package back to 11.11.0 to stop breaking the unit test coverage.
Would you mind to check if there is something wrong/not covered in the last release, please?

**Comment by Zirro** [comment]
See: https://github.com/jsdom/jsdom/issues/2304#issuecomment-408320484
