### ISSUE TITLE
insertAdjcentHTML is not working in JsDOM.

### ISSUE THREAD

**Issue by satyapendem** [jsdom/jsdom#2313]
JSDOM version : 11.11.0.

When we are trying to use insertAdjacentElement in jsdom it is not working and I'm getting an error like insertAdjacentElement is not a function. How I can resolve this issue?

**Comment by Zirro** [comment]
This does not follow our [issue template](https://github.com/jsdom/jsdom/blob/master/.github/ISSUE_TEMPLATE.md). I'll close this until you provide a minimal example of code that can be used to reproduce the issue.
