### ISSUE TITLE
localStorage implementation can't be spied on. webidl converter issue?

### ISSUE THREAD

**Issue by vlad0** [jsdom/jsdom#2318]
### Basic info:

- **Node.js version:** v9.11.2
- **jsdom version:** 11.12.0

### Minimal reproduction case

In the latest release `11.12.0` jsdom implemented localStorage and sessionStorage support. That's really awesome and great but the issue I am experiencing is that we can't spy On it or mock it during testing with `jest`.

I've created a simple repo for the use case at: https://github.com/vlad0/jest-localstorage-issue 

As much as I hate to do this but I'd like to give a link to the `jest` issue I've created https://github.com/facebook/jest/issues/6798

and mainly because of the setter implementation(webidl I guess):

```
What I have discovered is that in ./node_modules/jsdom/lib/jsdom/living/generated/Storage.js the issue is with the set method of the Proxy

Currently the code below is on line 278.
``` 

```js
if (ownDesc === undefined) {
          const parent = Reflect.getPrototypeOf(target);
          if (parent !== null) {
            return Reflect.set(parent, P, V, receiver);
          }
          ownDesc = { writable: true, enumerable: true, configurable: true, value: undefined };
        }
```
```
if we remove receiver from return Reflect.set(parent, P, V, receiver); we will be able to spy on it. But I guess that's coming from webidl converter
```

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
In general, the question to ask is, how would you spy on these methods in the browser? That's how you need to do it in jsdom. We aim to provide what the browser provides---no less, and no more.

**Comment by Zirro** [comment]
Closing this given the conclusion above.

**Comment by TimothyGu** [comment]
You could just wrap the Proxy with another Proxy. It's definitely nontrivial to implement, but that's how it is in browsers too.

**Comment by SimenB** [comment]
JSDOM behaves differently from browsers here (at least Chrome).

See the following snippet:

```js
console.log("before", localStorage.setItem);
localStorage.setItem = (...args) => console.log(...args);
console.log("after", localStorage.setItem);
```

Running this in Chrome (v68) prints the following:

```
before ƒ setItem() { [native code] }
after (...args) => console.log(...args)
```

You can paste this into runkit to run with JSDOM: https://npm.runkit.com/jsdom

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const { window } = new JSDOM(``, {
  runScripts: "outside-only",
  url: "https://example.org/",
});

window.eval(`
console.log("before", localStorage.setItem);
localStorage.setItem = (...args) => console.log(...args);
console.log("after", localStorage.setItem);
`);
```

Running it gives the following:

```
"before"
function setItem()
"after"
function setItem()
```

As you can see, replacing the function works in Chrome, but not in JSDOM.

**Comment by domenic** [comment]
Thanks. Unfortunately I guess this is an area where Chrome is not compatible with the Web IDL standard; if you test the same code in Firefox, for example, it will not work. I will file a Chrome bug to get them to fix it.

**Comment by SimenB** [comment]
Safari behaves the same as Chrome, FWIW. However, Edge matches Firefox.

Is it possible at all to replace `localStorage` or any of its functions? Assigning to, or using `Object.defineProperty` on, `window.localStorage` does nothing

**Comment by SimenB** [comment]
That works in Chrome, but not JSDOM.

```js
console.log("before", localStorage.setItem);
Object.defineProperty(window, 'localStorage', {value: {}})
console.log("after", localStorage.setItem);
```

Chrome:
```
before ƒ setItem() { [native code] }
after undefined
```

JSDOM:
```
"before"
function setItem()
"after"
function setItem()
undefined
```

**Comment by fernandopasik** [comment]
The ideal situation would be to being able to spy the methods, but it seems we can't replace the whole localStorage either

**Comment by domenic** [comment]
@SimenB your example works fine in jsdom from what I can see: https://runkit.com/embed/tyjajqz5j8hu

**Comment by SimenB** [comment]
@domenic sorry about the slow response! You can modify it from the outside, but not from the inside.

That is, your example works (modifying the returned `window` from jsdom), but not this one (modifying the window from an `eval`-ed script): https://runkit.com/simenb/5b9ea048f459f700125e9fbc

**Comment by domenic** [comment]
Ah, I see! That's a Node.js bug then. @TimothyGu was tracking it down last I heard... curious what the latest is.

**Comment by paradite** [comment]
Hi, can we re-open this issue, or create a new issue for `window.localStorage` cannot be mocked or substituted?

I have tried the following but all don't work as expected (cannot substitute `getItem` method):
```
global.localStorage = {
  getItem: () => 'false',
  setItem: () => {},
  TEST: 'test',
};
```
which gives
```
console.log(window.localStorage);
// -> Storage {}
```

And
```
Object.defineProperty(window, 'localStorage', {
  value: {
    getItem: () => 'false',
    setItem: () => {},
    TEST: 'test',
  },
});
```
which produces
```
console.log(window.localStorage);
// -> Storage {}
```

And
```
global.localStorage.TEST = 'test';
global.localStorage.getItem = () => 'false';
```
which gives
```
console.log(window.localStorage);
// -> Storage { TEST: 'test' }
window.localStorage.setItem('KEY', 'true');
console.log(window.localStorage.getItem('KEY'));
// -> 'true'
```

**Comment by domenic** [comment]
No, since this is a Node.js issue outside our control, the best place to have an open issue would be on their issue tracker, not here.

**Comment by feimosi** [comment]
For anyone who still struggles with this issue, using `Object.defineProperty` does work.
Here's how we use it:
```js
import Storage from 'dom-storage';

const dom = await JSDOM.fromFile(`${BASE}/index.html`, {
  runScripts: "dangerously",
  resources: "usable",
  pretendToBeVisual: true,
});

const mockedLocalStorage = new Storage(null, { strict: true });
Object.defineProperty(dom.window, 'localStorage', { value: mockedLocalStorage });

```

We use the `dom-storage` package to address the error:
```
Error: Uncaught [SecurityError: localStorage is not available for opaque origins]
```

**Comment by domenic** [comment]
Just set a url when constructing your JSDOM instance...

**Comment by feimosi** [comment]
@domenic really? Do you think I didn't try it? Now tell me how to solve importing HTML assets without running a server, when you get a bunch of:

```
Error: Could not load script: "https://localhost/js/app.js"
  at onErrorWrapped (.../node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
  at Object.check (.../node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
  at .../node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:124:14
  at processTicksAndRejections (node:internal/process/task_queues:96:5) {
	  type: 'resource loading',
	  detail: Error: connect ECONNREFUSED 127.0.0.1:443
	      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1142:16) {
	    errno: -111,
	    code: 'ECONNREFUSED',
	    syscall: 'connect',
	    address: '127.0.0.1',
	    port: 443
	  }
  }
```

**Comment by domenic** [comment]
Use a file URL.
