### ISSUE TITLE
Element is not passed to a custom resource loader.

### ISSUE THREAD

**Issue by sarvaje** [jsdom/jsdom#2338]
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** v12

### Minimal reproduction case

```js
const ResourceLoader = require('jsdom').ResourceLoader;

export class CustomResourceLoader extends ResourceLoader {
    fetch(url, options) {
        console.log(options.element);
    }
}
```

**Comment by sarvaje** [comment]
@domenic I will take care of this.

**Comment by mariusrak** [comment]
I guess this should be better documented. From current docs it is not clear how to use the `CustomResourceLoader` class.
