### ISSUE TITLE
[TS] The document property only contains a "location" property.

### ISSUE THREAD

**Issue by Outpox** [jsdom/jsdom#2341]
Hey there, I'm having trouble getting a node when using the `fromUrl()` function. The `window.document` property only contains `location` and `querySelector` 's always return null. 

### Basic info:

- **Node.js version:** `10.9.0` 
- **jsdom version:** `12.0.0` 
- **TypeScript version:** `3.0.1`

### Minimal reproduction case

Typescript
```ts
import { JSDOM } from 'jsdom'

JSDOM.fromURL(`https://freatle.com/`)
    .then(dom => {
      console.log(dom.serialize())
      console.log(dom.window.document.querySelector('.control'))
      console.log(Object.keys(dom.window.document))
    })
```
Javascript
```js
const jsdom = require("jsdom")
const { JSDOM } = jsdom

JSDOM.fromURL(`https://freatle.com/`)
    .then(dom => {
      console.log(dom.serialize())
      console.log(dom.window.document.querySelector('.control'))
      console.log(Object.keys(dom.window.document))
    })
```
```
[...] The serialized DOM is correctly returned with the node I'm looking for. [...]
null
[ 'location' ]
```

### How does similar code behave in browsers?
Firefox 61.0.1
![image](https://user-images.githubusercontent.com/3439246/44410989-cdede500-a565-11e8-9668-f74d466899bb.png)

**Comment by Sebmaster** [comment]
The loaded page does not contain an element matching that selector. The `Object.keys` example is proper behaviour.

**Comment by Outpox** [comment]
How it is that Firefox returns a node then?  
The node is visible in the `dom.serialize()` and I tried to set such options:
```
{
    resources: "usable",
    runScripts: "dangerously"
}
```

Kinda rude of you to not even bother to read the issue and close it immediately...

**Comment by Sebmaster** [comment]
> Kinda rude of you to not even bother to read the issue and close it immediately...

I actually bothered to run your example, which is how I noticed that that element is not in the DOM tree of the document in the example you gave.

If you provide an example that actually shows the issue, we could maybe provide better advice.

**Comment by Outpox** [comment]
My apologies then, really.
Let me fix the example by providing you the URL where I first encountered this issue (that I just reproduced): 
```js
JSDOM.fromURL(`http://bugmenot.com/view/drupal.com`)
    .then(dom => {
      console.log('dom.serialize() : ', dom.serialize())
      console.log('Object.keys(dom.window.document) : ', Object.keys(dom.window.document))
      console.log(`querySelector('.success_rate') : `, dom.window.document.querySelector('.success_rate'))
    })
```

The full log that I have is:
```
dom.serialize() : <!DOCTYPE html><html lang="en"><head>
<meta charset="utf-8">
<title>drupal.com passwords - BugMeNot</title>
<meta name="description" content="Access and share logins for drupal.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="/cdn-cgi/apps/head/mPdWsXAd1cEP0B8kRdBvE_p4nFk.js"></script><link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/2.1.0/normalize.min.css">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700|Ubuntu+Mono">
<link rel="stylesheet" href="/assets/bmn.css">
<link rel="shortcut icon" href="/favicon.ico">
</head>
<body>
<div id="page">
<header>
<div class="inner">
<a id="logo" title="Return to BugMeNot homepage" href="/"><img src="/assets/img/logo.png" alt="BugMeNot"></a>
<form class="search_form">
<input type="text" name="search_query" id="search_query" placeholder="Enter domain or url..." value="drupal.com"><button id="search_button"><span>Get Logins</span></button>
</form>
</div>
</header>
<div id="content"> <h1>drupal.com logins</h1>

<article class="account" data-account_id="491651"><dl><dt>Username:</dt><dd><kbd>bugmenot22</kbd></dd><dt>Password:</dt><dd><kbd>123456</kbd></dd><dt class="stats">Stats:</dt><dd class="stats"> <ul> <li class="success_rate success_70">65% success rate</li> <li>17 votes</li> <li>5 years old</li> </ul></dd></dl><form method="post" action="/vote.php"><input type="hidden" name="account" value="491651"><inputtype="hidden" name="site" value="186505"><input type="hidden" name="vote" value=""><fieldset><legend>Did this login work?</legend><button class="vote_yes" value="Y"><span>Yes</span></button><button class="vote_no" value="N"><span>No</span></button></fieldset></form></article><div id="share-it"><p>To add a login to this list: register a fake account then <a href="/submit.php?seed=drupal.com">share it</a>.</p></div>
</div>
<footer>
<ul>
<li><a href="/terms.php">Terms Of Use</a></li>
<li><a href="/removal.php">Removal</a></li>
<li><a href="http://trendsmap.com/">Twitter Trends</a></li>
<li><a href="http://cushycms.com/">Easy CMS</a></li>
<li><a href="http://lifx.co/">Wifi Light Bulb</a></li>
</ul>
</footer>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="/assets/bmn.js"></script>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-47291280-1', 'bugmenot.com');
    ga('send', 'pageview');
  </script>

</body></html>
Object.keys(dom.window.document) : [ 'location' ]
querySelector('.success_rate') : HTMLLIElement {}
```

You'll have to scroll right on the `<article>` node to see the node I'm querying, but what I see is:
`<li class="success_rate success_70">65% success rate</li>`  
Altough the querySelector returns null.

**Comment by fleur** [comment]
I'm having this issue as well.  And it's weirder.  The below is literally copy/pasted from my terminal just now.  I make a brand-new directory, `npm init`, `npm install --save jsdom` and literally echo 2 import lines, an instantiation with no arguments and a `console.log` of `dom.window.document` to node, and all I get is the one property:
```
Last login: Fri Oct 19 01:03:23 on ttys006
eshe:rug fleur$ mkdir jsdom-wtf
eshe:rug fleur$ cd jsdom-wtf/
eshe:jsdom-wtf fleur$ ls
eshe:jsdom-wtf fleur$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (jsdom-wtf) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /Users/fleur/work/rug/jsdom-wtf/package.json:

{
  "name": "jsdom-wtf",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
eshe:jsdom-wtf fleur$ npm install --save jsdom
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN jsdom-wtf@1.0.0 No description
npm WARN jsdom-wtf@1.0.0 No repository field.

+ jsdom@12.2.0
added 93 packages from 121 contributors and audited 133 packages in 1.56s
found 0 vulnerabilities

eshe:jsdom-wtf fleur$ echo "
> const jsdom = require('jsdom');
> const {JSDOM} = jsdom;
> const dom = new JSDOM('');
> console.log('dom.window.document:', dom.window.document);
> " | node
dom.window.document: Document { location: [Getter/Setter] }
```
I've tried various variations of html strings and options to the constructor, with the same results.

Also:
```
eshe:jsdom-wtf fleur$ npm list -g --depth 0
/usr/local/lib
├── nodemon@1.18.4
└── npm@6.4.1
eshe:jsdom-wtf fleur$ node --version
v10.11.0
```
I then did a `brew upgrade node` to 10.12.0 and tried again, with the same results.

@Outpox did you find a solution?  Or @Sebmaster can this be reopened, or should I create a new issue.

Thanks.

**Comment by Outpox** [comment]
@fleur I was just working on a small experiment, found nothing and just used another language (Dart) to do that. :-/

**Comment by Zirro** [comment]
@fleur `console.log()` won't reveal everything in this case. Try the following code, and you should see that the methods and properties you'd expect are there after all:

```JavaScript
console.log(dom.window.document.querySelector("body"));
console.log(dom.window.document.children);
console.log(dom.window.document.contentType);
```

**Comment by fleur** [comment]
Ok, thanks @Zirro , didn't realize that.  I'm getting a document.createElement is not a function elsewhere and was aiming for a small test case, and missed.  Back to debugging then.  Never mind.

**Comment by octalpixel** [comment]
Hi,
I am getting this issue. Were you able to find anything out?

**Comment by mslereo** [comment]
2021 and getting this issue. Anyone found the solution or why this happens? I've used this in another project and didn't have this problem 🤷🏻‍♀️

**Comment by MSoup** [comment]
2022 and getting this issue. 
It has been pretty hard to pinpoint what I'm doing wrong, but here are some logs:

```
    const res = await axios.get(songUrl)
    const {JSDOM} = jsdom
    const dom = new JSDOM(res.data)

    console.log("CONTENT: ", dom.serialize()) // can confirm that contents exist per below
    console.log("KEYS:", Object.keys(dom.window.document)) // only location exists
    console.log(dom.window.document.querySelector("body")); // nonexistent
    console.log(dom.window.document.children); // nonexistent
    console.log(dom.window.document.contentType);
```

```
... a ton of content

</script>

</body></html>
KEYS: [ 'location' ]
HTMLBodyElement {}
HTMLCollection {}
text/html
```

Would love any advice.

**Comment by ketakilolage** [comment]
I solved this by using .textContent:
`console.log(dom.window.document.querySelector("li").textContent);`

Thanks to [this reddit post](https://www.reddit.com/r/webscraping/comments/lflozw/im_new_to_web_scraping_and_need_some_help_with/)

**Comment by UsVfxArtia** [comment]
> 2022 and getting this issue. It has been pretty hard to pinpoint what I'm doing wrong, but here are some logs:
> 
> ```
>     const res = await axios.get(songUrl)
>     const {JSDOM} = jsdom
>     const dom = new JSDOM(res.data)
> 
>     console.log("CONTENT: ", dom.serialize()) // can confirm that contents exist per below
>     console.log("KEYS:", Object.keys(dom.window.document)) // only location exists
>     console.log(dom.window.document.querySelector("body")); // nonexistent
>     console.log(dom.window.document.children); // nonexistent
>     console.log(dom.window.document.contentType);
> ```
> 
> ```
> ... a ton of content
> 
> </script>
> 
> </body></html>
> KEYS: [ 'location' ]
> HTMLBodyElement {}
> HTMLCollection {}
> text/html
> ```
> 
> Would love any advice.

same in console log, any advice?

**Comment by minsiam** [comment]
2023 and getting the issue, 🙂
