### ISSUE TITLE
Support for Shadow DOM 

### ISSUE THREAD

**Issue by pmdartus** [jsdom/jsdom#2343]
I have been working over the last few weeks on the implementation of Shadow DOM API in JSDOM. You can find the current implementation here: https://github.com/jsdom/jsdom/compare/master...pmdartus:shadow-root

There are still a handful of tests failing, but most of it is there. I am currently looking for guidance/help from the JSDOM core team and community to make this real. 🎉 

There are multiple outstanding issues with this branch:

* With the introduction of Shadow DOM comes `HTMLSlotElement` and `ShadowRoot`. Since those objects are used in multiple places in the codes, it creates circular dependencies. In order to avoid this issue, I lazy require those when needed, however, I am looking for a better pattern now.
* I have spent a lot of time on the [dispatch event](https://dom.spec.whatwg.org/#concept-event-dispatch). With dispatching the events during the CAPTURE_PHASE. I can speak in more details if someone is interested to debug that with me.
* Performance! The addition of slots and slotable has a non-negligible performance impact on the DOM update. I solved some of the low-hanging fruits (without those wpt takes more than 2 hours to run), but I still feel that the test are slower to run.
* And much more ...

**Comment by domenic** [comment]
I'll try to take a look in more detail soon, but can you speak more about the performance? That seems like the most dangerous issue. What parts of the spec require doing work that impacts non-shadow-DOM using pages?

**Comment by pmdartus** [comment]
After profiling the expensive tests in wpt, the main performance regression introduced by the Shadow DOM addition is in the [insert algorithm](https://dom.spec.whatwg.org/#concept-node-insert). Now for each insert we need to run *assign slotables for a tree* (7.6.), which was really expensive. 

I added a simple optimization, now before running the *assign slotables for a tree* the code [checks if the root is a `ShadowRoot`](https://github.com/jsdom/jsdom/commit/b7a8b0720aa3d83a9842b69f3c8bcbcbaaa37f73#diff-68e848a8a703c1c5f9b1dba64506bae1R142), so we don't pay the performance penalty in a non-Shadow DOM context. With this optimization the numbers look way closer to the baseline. 

----

Here is the comparison table when running the performance benchmark locally:

**Command:** `yarn benchmark -s dom/tree-modification,dom/inner-html`

**Environment:** Node v8.11.3, Macbook Pro 2015 2.8 GHz 16 GB RAM

**Results:**

| Benchmark | [master](https://github.com/jsdom/jsdom/commit/d6f8a97b5fb7709d6ad0215c1ae95fd4cab58489) | [pmdartus:shadow-root](https://github.com/jsdom/jsdom/commit/24a46a88c2a07fe731a82c826e559f2e65893e2f) |
|--|--|--|
| **dom/tree-modification/appendChild: many parents** | 43.37 ops/sec ±0.59% (53 runs sampled) | 51.84 ops/sec ±0.81% (61 runs sampled) |
| **dom/tree-modification/appendChild: many siblings** | 710,495 ops/sec ±22.90% (10 runs sampled) | 616,525 ops/sec ±38.10% (10 runs sampled) |
| **dom/tree-modification/appendChild: no siblings** | 473,013 ops/sec ±15.92% (8 runs sampled) | 234,067 ops/sec ±79.44% (8 runs sampled) |
| **dom/tree-modification/insertBefore: many siblings** | 395,491 ops/sec ±28.28% (8 runs sampled) | 329,501 ops/sec ±10.42% (9 runs sampled) |
| **dom/tree-modification/removeChild: many parents** | 111 ops/sec ±4.56% (33 runs sampled) | 139 ops/sec ±2.36% (40 runs sampled) |
| **dom/tree-modification/removeChild: many siblings** | 199,395 ops/sec ±18.66% (16 runs sampled) | 195,312 ops/sec ±22.50% (15 runs sampled) |
| **dom/tree-modification/removeChild: no siblings** | 174,255 ops/sec ±25.20% (8 runs sampled) | 172,739 ops/sec ±28.08% (8 runs sampled) |
| **dom/inner-html/tables** | 0.19 ops/sec ±10.78% (5 runs sampled) | 0.18 ops/sec ±3.44% (5 runs sampled) |
