### ISSUE TITLE
Async scripts depending on sync scripts can fail.

### ISSUE THREAD

**Issue by sarvaje** [jsdom/jsdom#2344]
An async script can be executed before a sync script declared before in the dom.
If the async script depends on something defined in the sync file, it could fail.

This issue can be reproduced with the url http://github.com.

I have some solutions:
1. Remove the `async` scripts queue. The async scripts will be going to the general queue.
1. Run the async queue when the las sync script has run (similar to what happened to the defer queue)
1. Implement something to know when an async script can be run safely.

Async scritpts are not not officialy supported by `jsdom`, so maybe 1 or 2 is the best option for now.

Thoughts?

I will open a PR with the solution.

### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** v12

### Minimal reproduction case

```html
<script src="https://cdn/script1.js"></script>
<script async src="https://cdn/script2.js"></script>
```

```js
// script1.js
window.something = () => {
   return 8;
};
```

```js
// script2.js
var x = window.something();
```

### How does similar code behave in browsers?
The first script is executed before the second one.

**Comment by domenic** [comment]
Great catch. I guess either 1 or 2 is fine. I am happy to trust your judgement.

We should add a dont-upstream web platform test like your minimal example, with a big comment explaining the situation so that we don't regress. (We'd make it "dont-upstream" since it's definitely covered in the existing test suites, probably just in a more complicated way, and is kind of easy to miss.)

**Comment by sarvaje** [comment]
Perfect!! I will work on that.

Where should I create a "don't-upstream" test? (I just see the folder to-upstream)

**Comment by domenic** [comment]
Somewhere within the "to-upstream" folder, confusingly. You can see some others with the filename suffix "dont-upstream". We should make that pattern a big clearer, I think, but for now it's what we have.

**Comment by sarvaje** [comment]
Ok, perfect!
