### ISSUE TITLE
Performance regression in version >= 11.6 (5x slower than 11.5)

### ISSUE THREAD

**Issue by weijarz** [jsdom/jsdom#2350]
### Basic info:

- **Node.js version:** 
v8.11.4

- **jsdom version:** 
11.6.x - 12.0.x

### Minimal reproduction case

Checkout this repo:
https://github.com/weijarz/jsdom-perf-bug

```
[jsdom-slow]$ npm i jsdom@11.5
[jsdom-slow]$ node test.js 
parse-0: 896.238ms
parse-1: 641.438ms
parse-2: 539.048ms

[jsdom-slow]$ npm i jsdom@12
[jsdom-slow]$ node test.js 
parse-0: 3739.243ms
parse-1: 3626.432ms
parse-2: 3859.575ms
```

```js
const fs = require('fs')
const jsdom = require('jsdom')

const h = fs.readFileSync(__dirname + '/bug.html', 'utf8')
for (let i = 0; i < 3; i++) {
  console.time(`parse-${i}`)
  let opts = {
    url: 'http://example.com',
    runScripts: 'outside-only'
  }
  dom = new jsdom.JSDOM(h, opts)
  console.timeEnd(`parse-${i}`)
}
```

**Comment by Zirro** [comment]
The document provided in this case includes an enormous inline stylesheet. When it's removed, the remaining markup parses as fast as expected. The regression is probably a consequence of the changes in https://github.com/jsdom/jsdom/pull/2098, or the fixes that followed.

Some early profiling suggests that the slowdown comes from the [`replaceData()`](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/CharacterData-impl.js#L54)-method in `CharacterData-impl`. It's not that it's slow per se, as it usually finishes in much less than a millisecond. However, in this test case it ends up being executed 81276 times in total, which adds up over time.
