### ISSUE TITLE
jsdom error with React-native component testing using jest

### ISSUE THREAD

**Issue by skathayat** [jsdom/jsdom#2353]
### Basic info:

Installed jsdom 12.0.0

Intention is to use jsdom with Enzyme mount to do React-native component testing with jest

### Minimal reproduction case
In jest test cases, 

While doing
`import jsdom from 'jsdom';`
causes error like this
```
/Users/surkat/Sources/Clients/webviewdemo/node_modules/jsdom/lib/jsdom/living/generated/ErrorEvent.js: missing super() call in constructor

         9 | 
        10 | class ErrorEvent extends Event.interface {
      > 11 |   constructor(type) {
           |   ^
        12 |     if (arguments.length < 1) {
        13 |       throw new TypeError(
        14 |         "Failed to construct 'ErrorEvent': 1 argument required, but only " + arguments.length + " present."
```

and while doing this 
`require('jsdom')`
causes error like this
```
        10 | class ErrorEvent extends Event.interface {
      > 11 |   constructor(type) {
           |   ^
        12 |     if (arguments.length < 1) {
        13 |       throw new TypeError(
        14 |         "Failed to construct 'ErrorEvent': 1 argument required, but only " + arguments.length + " present."
```
Any clues will be appreciated!

**Comment by Sebmaster** [comment]
`jest` comes with jsdom built in, so you don't need to require it yourself. Please check the jest docs.

**Comment by skathayat** [comment]
What about the first cast, why it fails on normal import?

**Comment by skathayat** [comment]
Are you closing the issue just reduce your ticket counts or?

**Comment by Sebmaster** [comment]
> What about the first cast, why it fails on normal import?

Just tried reproducing your test case and it doesn't fail for me. So this might be your test setup or something.

> Are you closing the issue just reduce your ticket counts or?

We're closing issues if they're caused by some third party dependency, unless there's a very convincing reason that the actual bug is in jsdom.
