### ISSUE TITLE
:scope selector does not work correctly

### ISSUE THREAD

**Issue by hikoma** [jsdom/jsdom#2359]
### Basic info:

- v8.11.4 
- v12.0.0 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<!DOCTYPE html><div><p><span>hello</span></p></div>`);
const div = dom.window.document.querySelector("div");

console.log(div.querySelector(":scope > p") !== null);    // false
console.log(div.querySelector(":scope > span") === null); // false
```
### How does similar code behave in browsers?

```js
var div = document.createElement("div");
div.innerHTML = "<p><span>hello</span></p>";

console.log(div.querySelector(":scope > p") !== null);    // true
console.log(div.querySelector(":scope > span") === null); // true
```

**Comment by ahmadalfy** [comment]
Happening to me as well, whenever I try it I always get `null`

**Comment by ahmadalfy** [comment]
I think I figured out, `:scope` refers to the first child by mistake not to the element itself

**Comment by Zirro** [comment]
This should be fixed as of https://github.com/dperini/nwsapi/commit/c82644732294add196647960734a4a7bf3e4857d, but we'll need tests for this.
