### ISSUE TITLE
Extract pre-insertion validity steps out of NodeImpl.prototype.insertBefore

### ISSUE THREAD

**Issue by pmdartus** [jsdom/jsdom#2364]
In order to match more closely to the spec, the [ensure pre-insertion validity](https://dom.spec.whatwg.org/#concept-node-ensure-pre-insertion-validity) should be extracted out of the [NodeImpl.prototype.insertBefore](https://github.com/jsdom/jsdom/blob/dbff7dd4e54d2a256a658a80eb5832812be7aec1/lib/jsdom/living/nodes/Node-impl.js#L164).

This is necessary for implementing the Range spec (#317).

**Comment by domenic** [comment]
Fixed by https://github.com/jsdom/jsdom/pull/2395!
