### ISSUE TITLE
resourceloader can not work with http requests sent by xmlhttprequest ?

### ISSUE THREAD

**Issue by lovetingyuan** [jsdom/jsdom#2371]
### Basic info:

- **Node.js version:** v8
- **jsdom version:** v12.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
class ResLoader extends jsdom.ResourceLoader {
  fetch(url, options) {
     // url only contains resource in html tags, not includes requests sent by xhr
  }
}
const options = {
  resources: new ResLoader,
  // resources: 'usable',
  runScripts: 'dangerously',
  pretendToBeVisual: true,
  contentType: 'text/html',
  // includeNodeLocations: true,
  storageQuota: 10000
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

for example, when I request an API from backend in my javascript code using `XMLHttpRequest`, I want to use my own `fetch` method defined in `class ResLoader extends jsdom.ResourceLoader ` to handle the `xhr` (or `fetch`) request, not only the static resources declared in html file.

thanks!

**Comment by lovetingyuan** [comment]
#https://github.com/jsdom/jsdom/issues/1393

**Comment by lovetingyuan** [comment]
#1393

**Comment by domenic** [comment]
Yeah, known issue, which I would love to fix. Let's discuss in #1393.
