### ISSUE TITLE
Suggesting fix/workaround for obscure Jest/JSDOM/request issue

### ISSUE THREAD

**Issue by neil-quadrant** [jsdom/jsdom#2375]
### Basic info:

- **Node.js version:** 9.8.0
- **jsdom version:** 12.0.0

Summary: I am requesting that in xhr-utils, the options to request() include simple: false.

The long story: 
I am using Jest + jsdom (manually imported, not auto-imported via Jest) to test a proprietary node server. When the server returns 500 (or any non-200 response), this triggers an unhandled promise rejection that is caught by Jest but triggers  an automatic test failure.

The exact fault isn't clear to me, but it appears that both Jest and the "request" library use stealthy-require in a way that messes up the node cache. JSDOM's resource-loader requires "request-promise-native", while xhr-utils requires plain "request". Somehow I don't think those two module imports are getting namespaced properly, and resource-loader/request-promise-native's monkey-patching hooks get blended into the same global environment as xhr-utils/request. Since xhr-utils uses event callbacks to monitor the request rather than a promise, the request gets set up without a rejection handler. Request objects that are marked as simple (the default) reject when the response is non-200, and therefore BANG the xhr request blows up on server 500.

To make a long story short (too late), setting simple:false on the request options triggers request to resolve rather than reject on non-200 response, and thus my test passes, which after several hours of wracking my brain makes me happier than I was 5 minutes ago.

Clear as mud? Now that I've thoroughly confused everything I expect this will get marked as not-repro or go-complain-to-others. I get it. But just know that this issue was very important to me in this brief moment in time, especially because I can't monkey-patch around it.

### Minimal reproduction case

Apologies, the bug is too complex, I don't have time to put together a repro right now.

### How does similar code behave in browsers?

n/a

**Comment by larsrh** [comment]
I was stumbling over the same bug in connection with unfetch. For unfetch to work, it requires a global `XMLHttpRequest`. Here's the setup code in our project:

```javascript
const jsdom = new JSDOM();

global.XMLHttpRequest = jsdom.window.XMLHttpRequest;

process.on("unhandledRejection", (reason, p) => {
    p.catch((err) => {
        if (typeof err === "object" && err.name === "StatusCodeError") {
            // do nothing;
        } else {
            console.dir(err);
            process.exit(1);
        }
    });
});
```
