### ISSUE TITLE
Mocha : SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by imbudhiraja** [jsdom/jsdom#2383]
### Basic info:

- **Node.js version:**  10.9.0
- **jsdom version:**  11.12.0 / 12.1.0
- **jsdom-global:** 3.0.2
- **Mocha version:**   5.2.0
- **mock-local-storage:** 1.0.5
- **enzyme:** 3.4.4
- **enzyme-adapter-react-16:** 1.2.0

When I run a mocha with my test cases. It shows the following error when I upgrade the package. In my test cases, there is no localStorage is used. How can I fix this problem?

 SecurityError: localStorage is not available for opaque origins at Window.get localStorage 
[as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15) at Array.forEach (<anonymous>)

**Comment by domenic** [comment]
We can't debug issues with third-party dependencies like mocha, enzyme, etc. Please follow the issue template, creating an example that does not use third-party dependencies, so we can be sure this is an issue with jsdom.

**Comment by KyleGalvin** [comment]
This response seems to fall a little short when there was a large discussion on the same issue in jest:
https://github.com/jsdom/jsdom/issues/2304

This change of behavior broke a lot of tests and since your v11.12.0 there is no clear way to get jsdom localstorage working in mocha.

**Comment by timothyjellison** [comment]
@KyleGalvin What worked for me with Mocha was adding a url property to the JSDOM constructor. This ended up being equivalent to [updating the testUrl property in jest's config](https://github.com/jsdom/jsdom/issues/2304#issuecomment-408324623). As noted in this same issue you reference, the value of the url or testUrl doesn't matter; I've chosen localhost arbitrarily.

```javascript
const dom = new JSDOM(``, {
  url: "http://localhost"
});
```

**Comment by tiagoangelods** [comment]
> @imbudhiraja @KyleGalvin What worked for me with Mocha was adding a url property to the JSDOM constructor. This ended up being equivalent to [updating the testUrl property in jest's config](https://github.com/jsdom/jsdom/issues/2304#issuecomment-408324623). As noted in this same issue you reference, the value of the url or testUrl doesn't matter; I've chosen localhost arbitrarily.
> 
> ```js
> const dom = new JSDOM(``, {
>   url: "http://localhost"
> });
> ```

perfect works for enzyme and mocha.

**Comment by mikelyons** [comment]
Encountered this issue following this guide: https://semaphoreci.com/community/tutorials/getting-started-with-tdd-in-react
This worked to fix it for me, thanks!: https://github.com/jsdom/jsdom/issues/2383#issuecomment-442199291

**Comment by maxwellbenton** [comment]
This solution also works for mocha-jsdom:

`jsdom({html, src, url: "http://localhost"})`

**Comment by phillt** [comment]
What do you do with the dom var? I'm still getting the error after:

```
new JSDOM({
    url: "http://myurl.com"
})
```

**Comment by phillt** [comment]
Can someone be explicit as to where in the code the fix goes?

**Comment by shadowusr** [comment]
> Can someone be explicit as to where in the code the fix goes?

In your `.mocharc.js` file, you may have:
```js
module.exports = {
    require: ["./test/setup"],
};
```

Then in your `test/setup.js` you can do something like this:
```js
require('jsdom-global')(``, {
    url: 'http://localhost'
});
```

If you don't use jsdom-global package, pass options some other way to jsdom constructor.
