### ISSUE TITLE
wpt file/File-constructor-endings.html and blob/Blob-constructor-endings.html fail on Windows

### ISSUE THREAD

**Issue by zbjornson** [jsdom/jsdom#2396]
### Basic info:

- **Node.js version:** 8.12.0
- **jsdom version:** master at 7d0a7065

### Minimal reproduction case

These two tests fail on Windows:

```
yarn test-wpt --fgrep endings

  web-platform-tests
    FileAPI
      1) blob/Blob-constructor-endings.html
      2) file/File-constructor-endings.html
```

**Comment by domenic** [comment]
I've noticed this myself. Maybe we should skip them on Windows. I think the tests are written to assume they always run on Linux.

**Comment by zbjornson** [comment]
They appear to be intended to work on all platforms:

https://github.com/web-platform-tests/wpt/blob/732cc9161d1302127fd4b99a50c13bdff7e253ce/FileAPI/file/File-constructor-endings.html#L9-L11

but jsdom's `navigator` always returns `""` for `platform`. This diff fixes it (but idk if jsdom is allowed to use node's modules?):

```diff
diff --git a/lib/jsdom/living/navigator/NavigatorID-impl.js b/lib/jsdom/living/navigator/NavigatorID-impl.js
index 50aac66..511c445 100644
--- a/lib/jsdom/living/navigator/NavigatorID-impl.js
+++ b/lib/jsdom/living/navigator/NavigatorID-impl.js
@@ -14,7 +14,7 @@ exports.implementation = class NavigatorIDImpl {
   }

   get platform() {
-    return "";
+    return require("os").platform() === "win32" ? "Win32" : "";
   }

   get product() {
```
