### ISSUE TITLE
Bluebird warnings about runaway promise in the code

### ISSUE THREAD

**Issue by fgarcia** [jsdom/jsdom#2397]
I am getting a warning from Bluebird which seems to catch a runaway promise in JSDom code as described [here](https://github.com/jsdom/jsdom/pull/2379#issuecomment-427601652)

Just adding a `return null;` would make clear in the code that it is not intended to chain the promise with `item.check()` and solve the warning with Bluebird

```
    return request
      .then(data => {
        item.fired = 1;
        item.data = data;
        item.check();
+       return null;
      })

```
### Basic info:

- **Node.js version:** v8.12.0
- **jsdom version:** 12.2.0

### Minimal reproduction case

I made a repo at:

https://github.com/fgarcia/jsdom-bluebird

**Comment by domenic** [comment]
This seems like a bug in Bluebird; our valid code is causing warnings. I suggest using native promises instead of overriding the global in that way.
