### ISSUE TITLE
ReferenceError: PromiseRejectionEvent is not defined

### ISSUE THREAD

**Issue by yordis** [jsdom/jsdom#2400]
### Basic info:

- **Node.js version:** `10.10.0`
- **jsdom version:** `jest-environment-jsdom@23.4.0, jsdom "11.5.1"`

I know that it is not `v12` because I depend on `jest-environment-jsdom` but, I tried to find the class and I couldn't find it, sorry if I didn't do a good job on the search.

### Minimal reproduction case

I am using `jest-environment-jsdom` so I am not actually sure how they do it, sorry.

### How does similar code behave in browsers?

You can find more information about this class over here https://developer.mozilla.org/en-US/docs/Web/API/PromiseRejectionEvent

**Comment by domenic** [comment]
Thanks for reporting, but without something we can debug, and with an outdated version of jsdom that we don't maintain anymore, there's nothing that we the maintainers can help with here. So, we'll close this issue.

**Comment by yordis** [comment]
@domenic would be possible to have a conversation about it?

I tried to find the implementation of `PromiseRejectionEvent` in the package and I couldn't find it.

Fair enough, there is no code example and I am not using the latest version, but maybe trying to help rather than close an issue because I couldn't meet the requirements.

I tried if that is valuable to you.

Maybe I am wrong, but the issue wouldn't be the dependency or my environment but that is why I am asking you to support me on this rather than just close the ticket.

Again, sorry if I couldn't meet your requirements.

**Comment by domenic** [comment]
Sorry, we only have limited time to work on jsdom in our spare time, and a conversation on how to debug old versions of the library with no code to start with is not a good time investment for us.

**Comment by yordis** [comment]
@domenic but again, you are getting cut out in details that maybe are not the issue. 

I searched on `master` for this definition and it doesn't exist, it is what I am trying to explain.

Issue: PromiseRejectionEvent is not defined on `jsdom`.

Would you report it if I use the latest one with some code example?
