### ISSUE TITLE
 JSDOM constructor is showing Empty page when load local/hosted HTML file

### ISSUE THREAD

**Issue by mh884** [jsdom/jsdom#2404]
### Basic info:

- **Node.js version:** v8: '6.2.414.50'
- **jsdom version:** 12.1.0
### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
   url: "https://example.org/",
    referrer: "https://example.com/",
    contentType: "text/html",
    includeNodeLocations: true,
    storageQuota: 10000000
};
const dom = new JSDOM(``, options);

dom.window.document.body is only showing **`outerHTML:"<body></body>"`**

**Comment by Zirro** [comment]
The `url` option doesn't load the page by itself - it only sets the value of certain properties.

You can try the [`fromURL()`](https://github.com/jsdom/jsdom#fromurl) method instead, or download the document outside jsdom before you pass it to the `JSDOM()` constructor.

**Comment by mh884** [comment]
I tried to load a local page but it gives me the same results, fromFile worked inside methods which I need it to be global use to give JQuery plugin access to the page
 `const { window } = new JSDOM('', {
    url: "file:///grunt/test/data-templates/formBuilerWithMatrixSections.html",
    referrer: "file:///grunt/test/data-templates/formBuilerWithMatrixSections.html",
    contentType: "text/html",
    includeNodeLocations: true,
    storageQuota: 10000000
  }).window;`
