### ISSUE TITLE
TypeError: 'parseFromString' on 'DOMParser':'applicaiton/xml' is not SupportedType

### ISSUE THREAD

**Issue by maple-leaf** [jsdom/jsdom#2415]
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** 13.0.0

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const { window } = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
const abc = new window.DOMParser();
const cd = abc.parseFromString('<test>xx</test>', 'applicaiton/xml');
```

This will throw TypeError: `Failed to execute 'parseFromString' on 'DOMParser': parameter 2 'applicaiton/xml' is not a valid enumeration value for
 SupportedType`

**Comment by Sebmaster** [comment]
Seems like you typo'd the mime type?

**Comment by maple-leaf** [comment]
sorry about that~~
