### ISSUE TITLE
Program doesn't stop

### ISSUE THREAD

**Issue by ericzzh** [jsdom/jsdom#2417]
### Basic info:

- **Node.js version: *8.12.0* 
- **jsdom version:*12.2.0* 

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom')

urll = 'http://sh.lianjia.com/ershoufang//ditiefang/li143685036/a1/'

JSDOM.fromURL(urll,{ runScripts: "dangerously", resources:'usable', pretendToBeVisual: true  }).then( dom => {
    dom.window.document.onload =  function() { 
        console.log("After request..............................")
        console.log(dom.window.document.getElementsByClassName('house-lst-page-box')[0].innerHTML)
     }
})
```

I fetched a URL by running all scripts and resource, but at end the program doesn't stop.
I don't know if it falls in a forever loop, or some waiting mechanism of async process?
(Sorry, there are some Chinese characters, I hope it won't affect the problem description :-))

![image](https://user-images.githubusercontent.com/9389005/48115567-48452000-e29e-11e8-9445-1a3b075c01a2.png)

### How does similar code behave in browsers?

The page is normally loaded in browser.

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
Have you tried window.close(), per the readme?

**Comment by ericzzh** [comment]
I tried and it works. thanks!
So I guess it isn't an issue, just in a normal event listening loop.
