### ISSUE TITLE
Long filepath issues - has spaces, hyphens, brackets, etc... does not work with jest

### ISSUE THREAD

**Issue by DanielGillett** [jsdom/jsdom#2421]
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** jest 22.2.2 and 22.4.4
- VsCode using built-in cmd terminal
- Windows 7 x64

### Minimal reproduction case

**My project filepath...**
"C:\Users\Daniel\Documents\By Resource\Udemy\Node.js - The Complete Guide to Build RESTful APIs (2018)\SECTION 12 - UNIT TESTING\165. Writing Your First Unit Test\11.6- Writing Your First Test\testing-demo\tests"

**My Result when I run npm test in terminal's cmd prompt...**
No tests found
In C:\Users\Daniel\Documents\By Resource\Udemy\Node.js - The Complete Guide to Build RESTful
APIs (2018)\SECTION 12 - UNIT TESTING\165. Writing Your First Unit Test\11.6- Writing Your First Test\testing-demo
  7 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)(spec|test).js?(x) - 1 match
  testPathIgnorePatterns: \\node_modules\\ - 7 matches
Pattern:  - 0 matches
npm ERR! Test failed.  See above for more details.

**My Workaround works but I prefer to keep my file structure...**
**I moved my project to the desktop**
 PASS  tests\lib.test.js
  √ Our first test (2ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.215s
Ran all test suites.

C:\Users\Daniel\Desktop\testing-demo

(sorry if I haven't formatted this correctly.)

**Comment by domenic** [comment]
This seems unrelated to jsdom as far as I can tell. We are not a testing library.

**Comment by DanielGillett** [comment]
Thanks for your reply, Dominic.

25 Years in IT but somewhat new to modern JavaScript ...so I am not confident to try and debug this myself yet.  However, moving the project directory closer to the route fixes this particular issue.

Perhaps you could then point me in the right direction; where jest is told where to look?

Cheers,
Daniel
