### ISSUE TITLE
Using inside a worker

### ISSUE THREAD

**Issue by o-t-w** [jsdom/jsdom#2427]
I noticed the readme says: 

> jsdom works well inside a web worker.

I would like to use JSDOM inside a Cloudflare Worker (which uses V8 and replicated the service worker API), which means I have to use Webpack as Cloudflare Workers can only be one file. 

When I run Webpack I am getting the warning 
```
WARNING in ./node_modules/jsdom/lib/jsdom/utils.js 171:19-38
Critical dependency: the request of a dependency is an expression
```
I am also getting several of the same error about different packages: 
```
ERROR in ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js
Module not found: Error: Can't resolve 'child_process' in '/Users/owo3732/random/jsdomworker/node_modules/jsdom/lib/jsdom/living'
 @ ./node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js 4:22-46
 @ ./node_modules/jsdom/lib/jsdom/browser/Window.js
 @ ./node_modules/jsdom/lib/api.js
 @ ./src/index.js
```

**Comment by domenic** [comment]
I guess we didn't mention, but we use browserify for this. If webpack is missing some of the browserify features that make it possible to use jsdom in a web worker, it's probably best to file a feature request on webpack for those. In the meantime, I'll leave this open to track updating the docs to direct people to browserify.
