### ISSUE TITLE
JSDOM is not a constructor

### ISSUE THREAD

**Issue by xeroxstar** [jsdom/jsdom#2429]
### Basic info:

- **Node.js version:** 10
- **jsdom version:** 13.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(html);

I have this warning:
`
index.js?bed3:153 ./node_modules/jsdom/lib/jsdom/utils.js
216:21-40 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/jsdom/lib/jsdom/utils.js
 @ ./node_modules/jsdom/lib/jsdom.js
 @ ./src/components/IStore.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
`


I am not sure how to fix it, it's doesn't show me what dependency i need to update or install.

**Comment by domenic** [comment]
When I run that code in a file named `test.js` in Node.js version 10, I do not get an error.

**Comment by mlda065** [comment]
I have this same issue.

Node 10, working off the master branch.

**Comment by domenic** [comment]
Last time we saw this it was because people were using TypeScript, so the minimal repro in the OP did not apply.

**Comment by DespertaWeb** [comment]
Hi guys, 
it is happening to me in Node v13.11.0 and Javascript ( no Typescript)
Any solution?

**Comment by domenic** [comment]
If you can post a code block which, when pasted into a file named `test.js` and ran directly with `node test.js` exhibits this error, we can investigate.

**Comment by LinusLing** [comment]
> If you can post a code block which, when pasted into a file named `test.js` and ran directly with `node test.js` exhibits this error, we can investigate.

1. new directory named 'node_test' with test.js 

test.js
```
const jsdom = require("jsdom");
const { window } = new JSDOM('<body></body>');
```

2. `npm i jsdom`
and then followed the guide to install `canvas`、`bufferutil` and `utf-8-validate`

3. `node test.js`
it still shows the error `ReferenceError: JSDOM is not defined`

-----------
I suspect the error is related to this: 

jsdom's definition jumped to folder `~/Library/Caches/typescript/3.8/node_modules/@types/jsdom/ts3.1`

![image](https://user-images.githubusercontent.com/9403316/84867740-3d738380-b0ae-11ea-9037-a4acd9795d0c.png)

any ideas? thanks.

**Comment by LinusLing** [comment]
After the debug, following code can be normal to use jsdom 🤩
```
const jsdom = require("./node_modules/jsdom");
const { window } = new jsdom.JSDOM('<body></body>');
```

However, I can't imagine why the basic usage of jsdom is not work 🤷‍♂️

**Comment by domenic** [comment]
Compare your code to the readme.

**Comment by DespertaWeb** [comment]
I've ended up using http://pdfmake.org/

It works just fine, but you have to parse everything into the expected format thoug. 

Plus **be aware:** is Heavy as hell!
