### ISSUE TITLE
How can I externally inspect/subscribe/await/cancel outstanding requests?

### ISSUE THREAD

**Issue by evan-king** [jsdom/jsdom#2431]
Title says it all.  There are various use-cases for all forms of such interaction (events, per-request await/cancel, queue-wide await/cancel):
 - test suite cleanup: such as shutting down a server providing the test backing, which triggers errors for ongoing requests that don't matter
 - testing results of an in-page operation: such as inserting an image node and wanting to verify the request details (not yet) received by the server
 - restrict page activity: such as throwing an error in a test suite that generates unexpected requests
 - simulate user hiting escape key which cancels outstanding requests in a browser
 - simulate various forms of request failure (doable externally in my case, but more complicated and not a very broad solution)

These are all based on my usage scenario of jsdom as a test platform, but it seems to me the use cases would arise more generally as well.

It's not obvious from the readme whether interacting with the request queue in any manner is possible, so please interpret this as either a documentation/help question or a set of closely related feature request as appropriate.

**Comment by domenic** [comment]
Does the ResourceLoader documentation not answer these questions?

**Comment by evan-king** [comment]
As far as I can tell, it only shows how to customize the resolution of requests.  Implementing these external controls appears possible through ResourceLoader, but would be essentially duplicating the internal RequestManager by adding yet another queue and API methods that might be better placed elsewhere to maintain separation of concerns.  (Plus, there's a third set of responsibilities on top of that, using these controls to automatically validate test case expectations.)

It's also unclear whether cancelling a request made via `request-promise-native` will result in an error on the VirtualConsole.  This would be palatable in my "test suite cleanup" scenario if there's also a way to turn off the VirtualConsole's output as well, but perhaps not in the more general case.

To be sure there are lots of ways I could get what I need, but they involve either mixing of concerns on a single interface, significant external augmentation (and not as a convenience layer, but just for basic control of JSDOM), or hacking into undocumented private implementation details.

So since I take it these controls are currently not offered, would there be any interest in adopting them into the JSDOM instance API as a _separate_ public interface or set of top-level functions?  It seemed a much more daunting proposition before digging into it, but I still consider it functionality that should come standard, and I would rather design my solution to more closely match something that would find its way upstream.

**Comment by domenic** [comment]
I think ResourceLoader is going to be our general extension point, and the internals of the request manager are not something we plan to expose. I'd encourage you to focus on using that, and if there are specific scenarios where it does not suffice, bringing more concrete code examples back to this thread. (There probably are such scenarios; ResourceLoader is relatively new and unproven, as the readme notes!)

**Comment by evan-king** [comment]
Understood.
