### ISSUE TITLE
Remove dependency array-equal 

### ISSUE THREAD

**Issue by StephenLynx** [jsdom/jsdom#2435]
It's an abandoned dependency with barely 8 LOC that haven't been touched in 5 years with over 2 million weekly downloads.
It's a potential attack vector just like https://github.com/dominictarr/event-stream/issues/116 got hijacked to do something malicious.

**Comment by domenic** [comment]
Thanks, but I'd rather keep using it; the benefit of cleanly factored dependencies is worth more than the potential risk to me. I understand if that's not the case for your project, and if you choose to use an alternative to jsdom because of that

**Comment by StephenLynx** [comment]
You really think a dependency is worth saving 8 LOC? is not even a dozen LOC so you can say it has that much. Have you seen how often it is used?

**Comment by StephenLynx** [comment]
It is used LITERALLY ONCE on ./jsdom/lib/jsdom/living/window/navigation.js:3:const arrayEqual = require("array-equal");

**Comment by StephenLynx** [comment]
Which in turn is referenced LITERALLY ONCE on ./jsdom/lib/jsdom/living/window/navigation.js:83:      !arrayEqual(a.path, b.path) ||

**Comment by StephenLynx** [comment]
So please, could you reconsider it? The potential harm is enormous and the changes would be negligible.

**Comment by i-avalos** [comment]
maybe keep the dependency but remove the caret?

**Comment by StephenLynx** [comment]
If you remove it entirely you save other headaches, like the package being erased like it happened with left-pad and in general make installing and loading a bit more efficient.
