### ISSUE TITLE
Inline style of the element is not returned anymore with `.style` 

### ISSUE THREAD

**Issue by minas90** [jsdom/jsdom#2437]
### Basic info:

- **Node.js version:** 10.13.0
- **jsdom version:** 13.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM('<a style="display:none;color:red;" href="https://google.com">google.com</a>');

console.log(document.querySelector('a').style)
```

Hi there,
It's no longer possible to get style of the element with `.style`, as a workaround `el.getAttribute('style')` works properly, but `.style` breaks our code in many places.

**Comment by domenic** [comment]
How does this code work in browsers? Can you produce an example that tests something, instead of just logging something?

**Comment by minas90** [comment]
Hi @domenic,
In browsers it returns CSSStyleDeclaration.

For example here is a basic usage:
```
let a = document.querySelector('a');
if (document.querySelector('a').style.display == 'none') {
    a.style.display = 'block'
}
```
It's checking if it's a hidden tag via display property and makes it visible by changing it's value to `block `

**Comment by minas90** [comment]
It works properly on version 12.2.0, it's broken only on 13.0.0

**Comment by minas90** [comment]
Yes, the log will not hit, downgrading to 12.2.0 fixes that.
I'm also not sure what changed, but it broke our code in many places, we are removing hidden elements by checking if `a.style.display === 'none'`

**Comment by Zirro** [comment]
This is due to the `_attrModified` hook added in https://github.com/jsdom/jsdom/commit/064527e2cbc003debe0bc826f893519f1ceb64bc, where I missed the need to include `super._attrModified`. I'll create a fix for this later today.
