### ISSUE TITLE
window.Date is undefined

### ISSUE THREAD

**Issue by pladaria** [jsdom/jsdom#2446]
### Basic info:

- **Node.js version:** > 9
- **jsdom version:** 13

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

console.log(!!dom.window.Date); // logs false
```

https://repl.it/repls/WellinformedSmartFiles

I'd expect `Date` to exist in `dom.window`. We use `jsdom` for testing and in our environment setup, we have:
```js
global.window = dom.window
```
That makes tools like [this one](https://github.com/TheBrainFamily/wait-for-expect/blob/master/src/index.ts#L13) fail.

The workaround is easy:
```js
dom.window.Date = Date;
```

But perhaps `jsdom` should include that by default.

**Comment by Xeppy** [comment]
Seconded, having the same issue, it has a ripple effect into libraries like `wait-for-expect` and other libraries which expect a real or simulated DOM and use the window's date.

**Comment by Sebmaster** [comment]
You need to use `runScripts: "outside-only"`. If you don't specify that setting, we're not contextifying window, which means JS natives aren't set up on it.

**Comment by domenic** [comment]
We should consider updating the documentation to make this clearer, as I must admit that I didn't know how this could be happening until @Sebmaster pointed it out. Now it's obvious to me, but I can underestand how people would get confused.

Reopening and adding "documentation" tag.

**Comment by pladaria** [comment]
A question out of curiosity, why aren't those object/functions added to window by default?

**Comment by Sebmaster** [comment]
> A question out of curiosity, why aren't those object/functions added to window by default?

Contextifying the object is very expensive, so to reduce startup costs we avoid it (since if you don't specify `runScripts`, we assume you don't need it).
