### ISSUE TITLE
clicking span inside a submit button does not submit the form

### ISSUE THREAD

**Issue by kentcdodds** [jsdom/jsdom#2449]
### Basic info:

- **Node.js version:** >=8
- **jsdom version:** 13

### Minimal reproduction case

[Repl.it](https://repl.it/@kentcdodds/jsdom-submit-bug)

```js
const {JSDOM} = require('jsdom')


const {window, window: {MouseEvent, document}} = new JSDOM(`
<!doctype html>
<html>
  <body>
    <form>
      <button type="submit">
        <span>submit</span>
      </button>
    </form>
  </body>
</html>
`)

const form = document.querySelector('form')
const submit = document.querySelector('span')

let calls = 0

form.addEventListener('submit', event => {
  event.preventDefault()
  console.log('submitted')
  calls++
})

const clickEvent = new MouseEvent('click', {bubbles: true, cancelable: true, button: 0})
submit.dispatchEvent(clickEvent)

console.assert(calls === 1, 'the form was not submitted')
```

### How does similar code behave in browsers?

[jsbin](https://jsbin.com/recekor/edit?html,js,console)

In the browser, firing a click event on the span within a submit button will call the form's submit handler. In jsdom it does not.

Note that if I select the button instead of the span and fire the click event on the button then the form is submitted just fine. It's just when I select something within the button.

Real world situation: https://github.com/kentcdodds/react-testing-library/issues/234

Thanks!

**Comment by Zirro** [comment]
@kentcdodds Thanks for the detailed report! https://github.com/jsdom/jsdom/pull/2450 should fix it and be ready for merge once I've written a new test.

**Comment by kentcdodds** [comment]
Well that's awesome of you @Zirro! Thank you for working on this so quickly <3

**Comment by kentcdodds** [comment]
Woo! Thank you 🎉

**Comment by iwakoscott** [comment]
Do you know if this has been resolved? I am still having issues clicking on a `button` with a `span` child. I have to do `fireEvent.click(buttonNode.parentNode)` to submit the form. (I am using material UI for context)

```jsx
<button>
  <span>Submit</span>
</button>
```

Here is a [link](https://github.com/iwakoscott/button-issue) to my repository.

**Comment by kentcdodds** [comment]
I think your version of jsdom is old.

**Comment by iwakoscott** [comment]
This might be a dumb question but how do I update to the latest `jsdom`? Do I just do a simple `npm install jsdom`? Thanks!

**Comment by kentcdodds** [comment]
Unfortunately because you're using react-scripts to run your tests you don't get to control anything. You could use jest directly though.

**Comment by mpareja** [comment]
In order to use the latest version of `jsdom` under Jest: 

1. `npm i --save-dev jest-environment-jsdom-thirteen`
2. Update your jest configuration to use `jsdom-thirteen` test environment. `package.json` example:
    ```
    {
      "jest": {
      ...
        "testEnvironment": "jsdom-thirteen"
      }
    }
    ```
