### ISSUE TITLE
JSDOM Support in the Browser?

### ISSUE THREAD

**Issue by Marak** [jsdom/jsdom#245]
It occurs to me it might make sense  to port JSDOM to the browser so we can have the same DOM like APIs when interacting with HTML on the browser. 

I've been reading up on the browserify library. I think it might be useful in getting JSDOM working in the browser. https://github.com/substack/node-browserify

@substack do you have any idea on how to pull this off? could be really powerful...

**Comment by danvitoriano** [comment]
Any update on this issue? I'm facing the same problem with require on browserify. Tks!

**Comment by domenic** [comment]
Nobody had provided a separate issue with repro steps. Our CI runs jsdom in the browser using browserify every day so it probably is not broken.

**Comment by bogas04** [comment]
It's 2016, can browsers get their DOM now ?

**Comment by Joris-van-der-Wel** [comment]
sure, jsdom even works in Web Workers

**Comment by bogas04** [comment]
@Joris-van-der-Wel only for browserify bundles or even for webpack ? Coz I'm getting fs module not found when I use it in one of my module

**Comment by Joris-van-der-Wel** [comment]
We only test (CI) jsdom with browserify at the moment, I've never tried webpack. browserify automatically translates node.js core modules to a browser equivalent, which is what jsdom expects. I am not sure if webpack supports that.

However you could use browserify to generate a standalone bundle of jsdom (the generated bundle will try to detect what module system you are using), and then include that in webpack. 

Here is something that you can try:

 `browserify -r jsdom -s jsdom -o jsdom.js`
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <script src="jsdom.js"></script>
    </head>
    <body>
        <p>hi</p>
    </body>
</html>
```
Now open the developer tools in chrome, and you can try typing something like `jsdom.jsdom('<div>foo</div>').documentElement.outerHTML` in the console

**Comment by bogas04** [comment]
This is awesome. Thank you so much!!
