### ISSUE TITLE
document.activeElement and contentEditable

### ISSUE THREAD

**Issue by liajoy** [jsdom/jsdom#2472]
### Basic info:

- **Node.js version:*8.10.0* 
- **jsdom version:*13.1.0* 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM;
const div = dom.window.document.createElement('div');
div.contentEditable = true;
div.focus();
console.log(dom.window.document.activeElement === div); // false
div.tabindex = 1;
div.focus();
console.log(dom.window.document.activeElement === div); // true
```

### How does similar code behave in browsers?
`document.activeElement` should be the `div` element if the `div` has the `contenteditable` attribute with true even without `tabIndex` set.

**Comment by artyomtrityak** [comment]
Also it looks like tabIndex is required even for default focusable elements such as `<a>`

**Comment by TimothyGu** [comment]
See https://html.spec.whatwg.org/multipage/interaction.html#tabindex-value, in particular the "it is suggested that the following elements should be considered as focusable areas:" part, which includes [editing hosts](https://html.spec.whatwg.org/multipage/#editing-host). Any modifications should probably be done in https://github.com/jsdom/jsdom/blob/87fcce674447d0468285f3ef70f068f274d1b36a/lib/jsdom/living/helpers/focusing.js#L16
