### ISSUE TITLE
 module "miniprogram_npm/jsdom/path" is not defined 

### ISSUE THREAD

**Issue by MRzyb** [jsdom/jsdom#2483]
Use NPM in WeChat applets:
error message： thirdScriptError 
 sdk uncaught third Error 
 module "miniprogram_npm/jsdom/path" is not defined 
 Error: module "miniprogram_npm/jsdom/path" is not defined

**Comment by Sebmaster** [comment]
That doesn't look like a jsdom issue to me. We only support node and webworker environments.
