### ISSUE TITLE
Jsdom not save generated html after javascript proccessing

### ISSUE THREAD

**Issue by Dronax** [jsdom/jsdom#2491]
### Basic info:

- **Node.js version 10:** 
- **jsdom version: 12** 

### Minimal reproduction case

I have html with tables and in html I included js script bom.js:

    $(document).ready(function() {
    setTimeout(function() {
        var nums = [];

        $('#table_Serv tr td.serv-nomer').each(function (elem, ind) {
            nums[parseInt($(this).text())] = elem + 1;
            // nums.newNum[elem] = elem + 1;
            // nums.oldNum[elem] = parseInt($(this).text());
            $(this).text(elem + 1);
        });

        $('#test1234 tr td:nth-child(2)').each(function() {

            // extract each number in an array
            const numbers = $(this).html().split(',').map(x => Number(x));
            // var sortednum = [];
            var arrs = []
            for(var i = 0; i <= numbers.length; i++) {

                arrs[numbers[i]] = nums[numbers[i]];

            }
            // console.log(sortednum);
            // // Sort the numbers
            const sorted = arrs.sort((a, b) => a > b);
            ;
            const stringArray = sorted.reduce((tmp, x) => `${tmp},${x}`);

            // Insert the string back in the td
            $(this).text(stringArray);
        });
    }, 1000);
    });

When I go to html page, script working and get me table with changes by javascript. When jsdom get this html, jsdom is not executing javascript and get me clean html.

My index.js:

    'use strict';

    const jsdom = require("jsdom");
    const { JSDOM } = jsdom;
    var fs = require('fs');
    
    const options = {
        resources: 'usable',
        runScripts: 'dangerously',
    };
    
    var url = process.argv[2] !== undefined ? process.argv[2] : 'http://google.ru';
    
    JSDOM.fromURL(url, options).then(dom => {
     
        setTimeout(function() {
            var cont = dom.window.document.getElementsByTagName('html')[0].innerHTML;
            console.log(cont);
            var file = url.split('/');
            var filename = file[file.length - 1];
            fs.writeFile("file.html" + filename, cont, function(err) {
                if(err) {
                    return console.log(err);
                }
            
                // console.log("The file was saved!");
            }); 
        }, 1000)
       
    });

How I can resolve this solutions? I need save html after javascript processing. Get html by javascript. How I can do it?

I tryied this:

    JSDOM.fromURL(url, options).then(dom => {
 
    dom.window.onload = function() {
        var cont = dom.window.document.getElementsByTagName('html').[0].innerHTML;
            console.log(cont);
            var file = url.split('/');
            var filename = file[file.length - 1];
            fs.writeFile("file.html" + filename, cont, function(err) {
                if(err) {
                    return console.log(err);
                }
            
                // console.log("The file was saved!");
            }); 
        };
       
    });

Not working :( `window.onload` method is not want working..

(Link to a jsbin or similar suggested.)

**Comment by leegee** [comment]
You have a typo:
`dom.window.document.getElementsByTagName('html').[0].innerHTML;`

should read

`dom.window.document.getElementsByTagName('html')[0].innerHTML;`

because `getElementsByTagName` is returning an array, of which you require the first element.
