### ISSUE TITLE
ValidityState patternMismatch is incorrectly implemented

### ISSUE THREAD

**Issue by brophdawg11** [jsdom/jsdom#2494]
### Basic info:

- **Node.js version:** 8.11.3
- **jsdom version:** 13.1.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM('<input pattern="[a-z]+" value="abc123">');
const el = dom.window.document.querySelector("input");
console.log('input pattern:', el.pattern);
console.log('input value:', el.value);
console.log('patternMismatch:', el.validity.patternMismatch);
```

This example incorrectly reports `patternMismatch=false`

### How does similar code behave in browsers?

`patternMismatch` should be `true` in this case.  Per the spec, [the `pattern` is to be matched against the entire value](https://html.spec.whatwg.org/multipage/input.html#the-pattern-attribute):

> _This implies that the regular expression language used for this attribute is the same as that used in JavaScript, except that the pattern attribute is matched against the entire value, not just any subset (somewhat as if it implied a `^(?:` at the start of the pattern and a `)$` at the end)._

Code Pen: https://codepen.io/brophdawg11/pen/pqXJPE?editors=1111

**Comment by kontomondo** [comment]
@brophdawg11 Good catch!

@domenic Two obvious ways to solve this that come to mind are:

1. Add `^` at the start and `$` to the end of the provided `pattern`. It does feel a bit odd to be modifying the provided pattern. 
2. Use `match` instead of `test` and verify that the length of the returned array is exactly 1 and the matched value is the original value.

Thoughts?

**Comment by domenic** [comment]
I think following the spec's suggest strategy of adding `^(?:` at the beginning and `)$` at the end probably is the way to go. Apparently [that's what Chrome does](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/html/forms/base_text_input_type.cc?l=81&rcl=e94614267ff49a6c5fbc3482c2a025a901e088a3).
