### ISSUE TITLE
JSDOM accepts a buffer but doesn't allow to set a content type encoding and defaults to windows-1252

### ISSUE THREAD

**Issue by mrtcode** [jsdom/jsdom#2495]
### Basic info:

- **Node.js version: 8.10
- **jsdom version: 13.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(buffer, {
  contentType: res.headers['content-type'], // Doesn't use the charset from content-type
  encoding: 'UTF-8' // Doesn't use the passed encoding
});
```

It should either automatically extract charset from `options.contentType`, or it should allow to pass `options.encoding`.

Internally it's using `transportLayerEncodingLabelHiddenOption` to pass the encoding, therefore `fromURL` method works correctly.

https://github.com/jsdom/jsdom/blob/master/lib/api.js#L33

**Comment by domenic** [comment]
This is intentional. If you pass a buffer, we act like the browser does, and do encoding sniffing on it. To set the encoding, use meta charset inside the HTML that is encoded in that buffer.

**Comment by mrtcode** [comment]
Well, it's good that JSDOM is guessing encoding from the content, but isn't the browser also using the encoding from the `content-type` header? Doesn't it has a higher priority?

For example let's take [this](https://www.ynet.co.il/articles/0,7340,L-5037054,00.html) website as an example. If I pass it as a buffer, it will be incorrectly decoded. But if I pass the URL to `fromURL` method, JSDOM is internally using the encoding from the `content-type` [header](https://github.com/jsdom/jsdom/blob/master/lib/api.js#L135), and decodes succesfully. So why JSDOM is able to pass the encoding with internal `transportLayerEncodingLabelHiddenOption`, but the client script doesn`t have a way to pass the correct encoding from header?

This limitation makes it impossible to correctly decode some websites, and the only way is to move the content encoding guessing logic to the client script and pass JSDOM the already decoded string instead of the buffer. Which doesn't sound right. So I really think the smartest way to solve this would be to make JSDOM to watch into `content-type` header encoding.

**Comment by domenic** [comment]
Well, the `contentType` option is not the same as a content-type header. You can't supply headers with a `Buffer`.

But, maybe we should treat it similarly, instead of only treating it as an XML vs. HTML mode switch. Hmm.

**Comment by mrtcode** [comment]
It would be great. And it feels quite natural to pass `content-type` header from i.e. `request.js` response to `contentType` option. And generally, for those who are using JSDOM to process random websites, the `buffer` mode seems to be the only way to correctly decode and process the website if an external HTTP client like `request.js` is necessary. Unless they would do all the `content-type`, `BOM`, `meta` decoding thing before passing the content to JSDOM, but then the `buffer` mode wouldn't be necessary at all.

**Comment by mvolz** [comment]
Sorry to be annoying, but would it be possible to get a definitive answer on if jsdom wants to support this or not, so we have an idea where along the development path a patch should be applied? :)

(It's a high priority issue for us because we're supporting a large number of languages where windows-1252 commonly does quite badly, such as Chinese, Czech, Hebrew and Arabic. More info here: **https://phabricator.wikimedia.org/T212490**)

(Also would it be possible to consider a different fallback? Would utf8 do better)?

**Comment by mrtcode** [comment]
Many international websites are experiencing encoding issues:

- http://www.amazon.fr/Candide-Fran%C3%A7ois-Marie-Voltaire-Arouet-dit/dp/2035866014/ref=sr_1_2?s=books&ie=UTF8&qid=1362329827&sr=1-2
- https://www.amazon.cn/%E5%9B%BE%E4%B9%A6/dp/B007CUSP3A
- https://www.amazon.co.jp/gp/product/0099578077
- https://www.derbund.ch/bern/stadt/der-letzte-stapi-geht/story/21950637
- https://www.nytimes.com/2015/05/10/nyregion/manicurists-in-new-york-area-are-underpaid-and-unprotected.html?_r=0
- https://de.reuters.com/article/deutschland-koalition-csu-idDEKBN1GH2GW
- http://www.scielosp.org/scielo.php?script=sci_arttext&pid=S0034-89102007000900015&lang=pt
- http://www.taz.de/!5124174/

Besides not looking for encoding into `contentType`, it seems that encoding sniffing doesn't work properly because some of the websites still have a meta tag with a charset.

**Comment by csmr** [comment]
Am I understanding correctly: the html5-documents meta-tags Content-Type with charset=UTF-8 is ignored when "handling a buffer"?

It seems to me, that this will destroy your document unless it is encoded with the default charset.

Also, please note that a browser will look for the <meta http-equiv="Content-Type"> for information , and if it is found, re-parse the document with the specified encoding.

With that, it seems to me this is not a desired feature.
