### ISSUE TITLE
Disabling and re-enabling button breaks click handler

### ISSUE THREAD

**Issue by ChadFong** [jsdom/jsdom#2496]
### Basic info:

- **Node.js version: 11.7.0** 
- **jsdom version: 13.1.0** 

### Minimal reproduction case

```
var jsdom = require("jsdom");

const dom = new jsdom.JSDOM(`
    <!DOCTYPE html>
        <button id="test" onclick="console.log('test')">
        </button>
`, { runScripts: "dangerously" });

var btn = dom.window.document.querySelector('#test');

// Logs correctly
btn.click();

// Will not log because button is disabled
btn.disabled = true;
btn.click();

// Button has been re-enabled, but does not log
btn.disabled = false;
btn.click();
```

### How does similar code behave in browsers?

Setting disabled to false should re-enable the click handler
[Runkit example showing issue with JSDOM](https://runkit.com/embed/zj8w7fj3y9h8)
[JSBin showing expected behavior with DOM](https://jsbin.com/jepuhuriga/1/edit?html,js,console)

**Comment by domenic** [comment]
Yeah, just noticed this myself in https://github.com/jsdom/jsdom/pull/2463#discussion_r247629359. We should fix that method to match the spec.
