### ISSUE TITLE
Don't convert Named HTML Entities to special characters

### ISSUE THREAD

**Issue by markb-trustifi** [jsdom/jsdom#2501]
### Basic info:

- **Node.js version:** v8.11.1
- **jsdom version:** v13.2.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(`<div>&lt;hello&gt;&bdquo;&reg;&copy;&ldquo;</div>`);
console.log(doc.window.document.body.innerHTML);
```
It is printed as:
`<div>&lt;hello&gt;„®©“</div>`

### How does similar code behave in browsers?
It is printed as:
`<div><hello>„®©“</div>`

### Issue
I would like to have some flag that will allow me to keep all named html entities as is without converting them to special characters.
May be something to skip calling `HTMLDencode` (not existing anymore) from https://github.com/jsdom/jsdom/blob/v0.2.14-patch2/lib/jsdom/browser/htmlencoding.js

**Comment by domenic** [comment]
Sorry, the feature you're asking for does not exist in browsers, and we are not interested in supporting it. See https://github.com/inikulin/parse5/issues/261#issuecomment-401389295
