### ISSUE TITLE
What is the right way to create instance of jsom while working with ES6?

### ISSUE THREAD

**Issue by PavelKastornyy** [jsdom/jsdom#2514]
I use jsdom 13.2 and ES6. On [npm page](https://www.npmjs.com/package/jsdom) the following example is given:

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
```

When I changed this code to:

```
import { jsdom } from "jsdom";
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
```

I got error.

The only way I made it work is:

```
import { JSDOM } from 'jsdom';
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
```

However, I didn't find anyone used the same way. Is this a right way?

**Comment by domenic** [comment]
jsdom works with Node.js, which does not support that syntax. So this issue doesn't make sense.

If you are using some nonstandard tool to work with jsdom, you need to file this help request on them.

**Comment by PavelKastornyy** [comment]
@domenic There are such things as [babel](https://github.com/babel/babel), so this issue does make sense.

**Comment by PavelKastornyy** [comment]
@domenic Besides, node.js developers already work at adding es6 modules and it is already possible to use it in [experimental mode](https://nodejs.org/api/esm.html). So, again, this feature does make sense.

**Comment by vinyll** [comment]
Same demand here. My tests are stuck running ES6 modules while the whole node project run with `import`.
Not sure either to hack or change lib

**Comment by jkhsjdhjs** [comment]
> The only way I made it work is:
> 
> ```
> import { JSDOM } from 'jsdom';
> const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
> ```

Sadly this doesn't work for me.  
The following works with nodejs 10.0.0:
```js
import jsdom from "jsdom";
const dom = new jsdom.JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
```
When I try to import `jsdom` with nodejs 11.13.0 however, I get the following error:
```
internal/modules/cjs/loader.js:683
      module.reflect.onReady((reflect) => {
                     ^

TypeError: Cannot read property 'onReady' of undefined
    at Module.load (internal/modules/cjs/loader.js:683:22)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
    at Function.Module._load (internal/modules/cjs/loader.js:604:3)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/jkhsjdhjs/steam-stats/node_modules/psl/index.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:612:12)
```

**Comment by PavelKastornyy** [comment]
@jkhsjdhjs In [this file](https://github.com/PavelKastornyy/script4j/blob/master/modules/script4jfx.graphics/test/script4jfx/scene/NodeTest.ts) I test jquery, so you can find a working configuration. This is `script4jfx.graphics` module of [script4j](https://github.com/PavelKastornyy/script4j). Please, note, that every module has its own `package.json`.

**Comment by jkhsjdhjs** [comment]
@PavelKastornyy Which nodejs version do you use? And since it's a typescript file, maybe the typescript transpiler converts import statements to require? I've never used typescript, so I don't know whether it does or not.

**Comment by PavelKastornyy** [comment]
@jkhsjdhjs I use nodejs v11.12.0. No, typescript doesn't convert `import`s to `require` because `import`s are ES6 feature. However, to use this ES6 feature [babel compiler](https://github.com/babel/babel) is used.

**Comment by jkhsjdhjs** [comment]
Ah ok. I tested it with `node --experimental-modules`, meaning without any kind of transpiler.

**Comment by Javarome** [comment]
with `--experimental-vm-modules` node option, jsdom 20.0.2 this TypeScript code works for me:
```ts
import {JSDOM} from "jsdom"

const dom = new JSDOM("<div>some HTML</div")
const doc = dom.window.document
```
