### ISSUE TITLE
queueMicrotask

### ISSUE THREAD

**Issue by quasicomputational** [jsdom/jsdom#2518]
The HTML spec defines a `queueMicrotask` function on `WindowOrWorkerGlobalScope`, and it'd be nice if jsdom included it. Recent Node versions provide the same thing and `process.nextTick` is a good substitute on older ones; I don't know what the best alternative for browsers is, though.

**Comment by domenic** [comment]
Fixed in https://github.com/jsdom/jsdom/commit/31eb938fdaa5d446e194c9ec4f0d6b46b4354954
