### ISSUE TITLE
ResourceLoader and Jest

### ISSUE THREAD

**Issue by davewthompson** [jsdom/jsdom#2520]
My apologies for this issue, but I am looking for documentation on how to use the ResourceLoader in a Jest environment. Can the developers behind JSDOM provide some advice or some feedback?

Jest requires configuration to be passed to JSDOM via a serialisable configuration - so customising ResourceLoader won't work there.

**Comment by Sebmaster** [comment]
> Jest requires configuration to be passed to JSDOM via a serialisable configuration - so customising ResourceLoader won't work there.

How are we supposed to do anything about this? jest needs to expose this as a config option.

**Comment by domenic** [comment]
We don't maintain Jest here, and don't know much about it, so this is not the right place to ask for support on Jest. I suggest using the Jest issue tracker for Jest-related questions.
