### ISSUE TITLE
Creating FormData from form fails on input with no value set

### ISSUE THREAD

**Issue by nrkn** [jsdom/jsdom#2523]
### Basic info:

- **Node.js version:** v10.11.0
- **jsdom version:** v13.2.0

### Minimal reproduction case

```js
import { JSDOM } from 'jsdom'

const jsdom = new JSDOM( `<!doctype html>` )
const { document, FormData } = jsdom.window

const form = document.createElement( 'form' )
const input = document.createElement( 'input' )

input.type = 'text'
input.name = 'foo'

form.appendChild( input )

const formData = new FormData( form )
```

### How does similar code behave in browsers?

The formData object is created and entries contains [ "foo", "" ]

In jsdom, when building the formDataset, for an input element with no value set, when _getValue() is called, it returns null:

https://github.com/jsdom/jsdom/blob/16d3913eea0360c7757e75f7e266c3873c85b7dd/lib/jsdom/living/xhr/FormData-impl.js#L149

This is then passed to normalizeToCRLF, which expects a string:

https://github.com/jsdom/jsdom/blob/16d3913eea0360c7757e75f7e266c3873c85b7dd/lib/jsdom/living/xhr/FormData-impl.js#L163

```
xxx\node_modules\jsdom\lib\jsdom\living\helpers\form-controls.js:63
  return string.replace(/\r([^\n])/g, "\r\n$1")
                ^

TypeError: Cannot read property 'replace' of null
    at exports.normalizeToCRLF.string (xxx\node_modules\jsdom\lib\jsdom\living\helpers\form-controls.js:63:17)
```

**Comment by thatbudakguy** [comment]
reproduced this with node v10.5.0 and jsdom v15.1.1.
