### ISSUE TITLE
Return name of all div's ids

### ISSUE THREAD

**Issue by sscaetite** [jsdom/jsdom#2526]
Can I get name of all divs ids of a JSDOM object?

**Comment by domenic** [comment]
I don't know exactly what this is asking, but it did not follow the issue template, so we'll need to close it. If you can edit it to follow the issue template, we can reopen.

In the meantime, I suggest asking yourself how you would accomplish this task in the browser (one of the fields in the issue template asks this), and then applying the same code in jsdom.
