### ISSUE TITLE
view the request log through fiddler

### ISSUE THREAD

**Issue by gyh9457** [jsdom/jsdom#2537]
### Basic info:

- **Node.js version:** stable
- **jsdom version:** latest

### Minimal reproduction case
How can I view the request log through fiddler ? 

I use it in `Jest`, and had set the proxy

``` js
  "testEnvironmentOptions": {
    "resources": "usable", 
    "proxy": "https://127.0.0.1:8888",
  }
```
But this seems useless.

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
I don't know what fiddler is, so I don't know how to help with this. Maybe you should ask the maintainers of fiddler? We generally don't provide support for third-party software, whether it be Jest or fiddler.
