### ISSUE TITLE
File object doesn't expose `size` and `type`

### ISSUE THREAD

**Issue by ryuran** [jsdom/jsdom#2540]
### Basic info:

- **Node.js version:** v10.15.1
- **jsdom version:** v11.12.0 (used by up to date Jest-cli) 

### Minimal reproduction case
I have an issue with File constructor in jsdom.
```js
new File(['test'], 'imageTest.jpg', { type: 'image/jpg' })
```
in jsDom:
```
File { path: 'imageTest.jpg' }
``` 

I need access to `size` and `type` properties to test if it's a valid File

### How does similar code behave in browsers?

In Chrome:
![Capture d’écran 2019-03-21 à 15 30 01](https://user-images.githubusercontent.com/1309340/54759561-9e33b800-4bee-11e9-836f-3ee374dcc169.png)

In Firefox:
![Capture d’écran 2019-03-21 à 15 40 27](https://user-images.githubusercontent.com/1309340/54760124-b8ba6100-4bef-11e9-8a71-7d87cd423b04.png)

**Comment by domenic** [comment]
Please produce a code sample, not a screenshot or a log output. For example, it would be a bug if `someFile.size === undefined`. But I doubt that is the case.

**Comment by ryuran** [comment]
https://jsbin.com/fagupecoge/edit?js,console @domenic I edit

**Comment by domenic** [comment]
As I said, console logs are not interesting. Please write a test that shows the property of the object, instead of logging an object to the console.

**Comment by domenic** [comment]
I'll try to be clearer, you should be reporting bugs by talking about code behavior, e.g.

```js
assert(file.size !== undefined);
```

or similar things that could cause tests to fail. Screenshots or `console.log()` outputs are not a good way of reporting bugs.

But, I guess you figured it out in the end.

**Comment by ryuran** [comment]
@domenic yes, I understand
Keep this issue close.
It's not a bug here.
My mistake, `console.log` do not display every properties, the File object is complete.
