### ISSUE TITLE
querySelector cannot match attribute selectors if the value contains a dash surrounded by spaces (regression)

### ISSUE THREAD

**Issue by JaSpr** [jsdom/jsdom#2542]
### Basic info:

- **Node.js version:** 10.15.3 (also fails in 8.7.0)
- **jsdom version:** 14.0.0

### Minimal reproduction case

```js
const {JSDOM} = require('jsdom');

const html = (`
<html lang="en-us">
<head><title>test repro</title></head>
<body>
    <a title="test">Test One</a>
    <a title="test with space">Test One</a>
    <a title="test with - dash and space">Test One</a>
    <a title="test-with-dash">Test One</a>
    <input name="test-with-dash"/>
    <a>Test Two</a>
</body>
</html>
`);

const dom = new JSDOM(html, {});

const window = dom.window;
const document = window.document;

function logMatches(selector) {
    console.log ('\nsearching for: ' + selector);

    const results = document.querySelectorAll(selector);
    console.log(`found ${results.length} matches:`);

    Array.from(results).forEach(a => console.error(`* ${a.outerHTML}`));
}

logMatches('a');
logMatches("a[title='test']");
logMatches("a[title='test with space']");
logMatches("a[title='test with - dash and space']");
logMatches("a[title='test-with-dash']");
logMatches("input[name='test-with-dash']");

console.log('\n\nDONE');

```

### Output of above test
```

searching for: a
found 5 matches:
* <a title="test">Test One</a>
* <a title="test with space">Test One</a>
* <a title="test with - dash and space">Test One</a>
* <a title="test-with-dash">Test One</a>
* <a>Test Two</a>

searching for: a[title='test']
found 1 matches:
* <a title="test">Test One</a>

searching for: a[title='test with space']
found 1 matches:
* <a title="test with space">Test One</a>

searching for: a[title='test with - dash and space']       <-- this one should match 1 element
found 0 matches:

searching for: a[title='test-with-dash']
found 1 matches:
* <a title="test-with-dash">Test One</a>

searching for: input[name='test-with-dash']
found 1 matches:
* <input name="test-with-dash">


DONE


```

Note that the failing query ("a[title='test with - dash and space']") used to work.  We've been on jsdom ^11.11.0 for a while, and I upgraded yesterday to 14.0.0 to get the ability to search by `option:checked`.  I got that, but lost the ability to search by attribute when that attribute contains a dash surrounded by spaces.

This query works properly in browsers and in jsdom ^11.11.0

**Comment by domenic** [comment]
@dperini?

**Comment by JaSpr** [comment]
Interesting, it only seems to be a problem with spaces aroudn the dash.  `test-with-dash` works.

**Comment by vityas-off** [comment]
seems to be same problem https://github.com/jsdom/jsdom/issues/2528

**Comment by dperini** [comment]
I am looking into this issue. Need to find the regression point in history.
Was this working in previous versions ? If yes which one ?
Thank you for reporting the problem.

**Comment by vityas-off** [comment]
regression is 11.10 -> 11.11

**Comment by JaSpr** [comment]
I don't believe that regression point is correct.  We previously had `jsdom` in our `package.json` set to ^11.11.0 for many months, and this bug was not present.

**Comment by vityas-off** [comment]
I binary tested with my example #2528, it may be different bug then, but it looks very related.

**Comment by dperini** [comment]
@JaSpr @vityas-off thank you for the help.
I believe I have found the bug and I am going to commit the fix to my repo.
Next, as soon as I have reviewed the fixes with the team, I will push a new release to npm.
