### ISSUE TITLE
querySelector behaves differently in Chromium

### ISSUE THREAD

**Issue by marval2** [jsdom/jsdom#2551]
### Basic info:

- **Node.js version:** v8.10.0
- **jsdom version:** 14.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<input name="User">`);

const result = dom.window.document.body.querySelector("input[name*=user i]");

console.log(result);

```

https://codesandbox.io/s/98zkx1x3np

### How does similar code behave in browsers?

When using `body.querySelector("input[name*=user i]")` in Chromium `v73`, result contains `querySelector` matches input with `name="User"`

**Comment by dperini** [comment]
@marval2 
the issue should have been fixed by this commit in https://github.com/dperini/nwsapi/commit/5872e811feca0720aa5462fe0acad62b0f7d06f4.
I will be publishing a new release on npm as soon as possible.
Thank you for reporting the issue.
