### ISSUE TITLE
JSDOM dosn't change textarea value when key is pressed

### ISSUE THREAD

**Issue by PashaTurok** [jsdom/jsdom#2552]
I want to simulate keypress to change textarea value. This is my code:

```
let textArea: HTMLElement = $('<textarea/>')[0];
console.log("textArea:" + textArea);
const document: Document = dom.window.document;
document.body.appendChild(textArea);
textArea.focus();
var event = new window.KeyboardEvent("keypress", {key: "z"} as any);
textArea.dispatchEvent(event);
console.log("DOM:" + dom.serialize());
console.log("Value:" + (<HTMLInputElement> textArea).value);
```

And this is the ouput:

```
textArea:HTMLTextAreaElement@0-3ea7c1a9
DOM:<!DOCTYPE html><html><head></head><body><textarea></textarea></body></html>
Value:
```
As you see, in spite of pressing z key the value of the textarea doesn't change. Is this a bug or I do something wrong?

**Comment by domenic** [comment]
I'm sorry, but this issue doesn't follow the issue template, so we can't debug it. Please edit it to follow the template, then ping the thread and we can re-evaluate whether there's an issue here.

**Comment by PashaTurok** [comment]
@domenic I updated the issue.

**Comment by PashaTurok** [comment]
@domenic If there is still no necessary information, please, say and I will add it.

**Comment by domenic** [comment]
Thanks, but that code does not run in Node.js; it uses syntax which is not supported. It also seems to use lots of third-party libraries, and jsdom has no DOMWindow export.

Please produce a file that can be run with `node file.js`, with no third-party libraries, to illustrate the problem.

**Comment by PashaTurok** [comment]
@domenic Done.

**Comment by domenic** [comment]
I get the same result in jsdom as in the browser: https://jsbin.com/rosawamenu/edit?html,console,output
