### ISSUE TITLE
JSDOM is not a constructor

### ISSUE THREAD

**Issue by alexolotl** [jsdom/jsdom#2556]
Using jsdom 14.0.0 and Node 10.15.3 (via nvm), I get the following error:

```js
TypeError: JSDOM is not a constructor
    at Object.<anonymous>
```

My code in Node is as follows:

```js
const jsdom = require('jsdom');
const {JSDOM} = jsdom

const document = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`)
```

In node_modules/jsdom/lib/api.js there is a module export of a JSDOM class, so it does seem to exist - any idea why it's not working?

------------------------------------------------------------------------------

Some extra console logs which may be useful:

console.log(jsdom)

```js
{ createVirtualConsole: [Function],
  getVirtualConsole: [Function],
  createCookieJar: [Function],
  nodeLocation: [Function],
  reconfigureWindow: [Function],
  changeURL: [Function],
  defaultDocumentFeatures: [Getter/Setter],
  jsdom: { [Function] jQueryify: [Function], env: [Function] },
  jQueryify: [Function],
  env: [Function],
  serializeDocument: [Function],
  blobToBuffer: [Function],
  evalVMScript: [Function] }
```

console.log(jsdom.jsdom)

```js
{ [Function] jQueryify: [Function], env: [Function] }
```

console.log(JSDOM)  // is undefined

**Comment by domenic** [comment]
It looks like you have some older version of jsdom, since those exports you console.log don't exist anymore (since v12). Probably some issue with the project setup where `require('jsdom')` is not retrieving the file you think it does.

**Comment by alexolotl** [comment]
Ah I see, you're right it wasn't importing the version I expected because of my project structure while running this small test. All good now. Thanks!
