### ISSUE TITLE
Can i use jsdom with android? Can i login to my Website and click on javascript links

### ISSUE THREAD

**Issue by beshoo** [jsdom/jsdom#2574]
Dear support.
I am almost desperate.
I want to run Headless scraping on an android app on the background while the phone is locked.

I know that android support WebView which we can use it as a headless browser, but once the app sent to the background, all UI thread will be paused by the android system.

chrome does not support headless mode for android,  Puppeteer Nodjs is a great option but it has no android version 
https://github.com/GoogleChrome/puppeteer/issues/4362 

I need to do DOM and javascript Scraping with cookies, so Curl/Wget/fetch will not help.
My target is the following :
I wont to log in to my Instagram profile.
Then I will Save the cookies, then pass it to "jsdom" 
**I don't find a way to pass Headers !**
when jsdom ask for the website URL , there is a javascript will redirect to my profile. (I can not change this redirection)
this url has tons of Javascript.

I need jsdom to include/inject some other js libs to the body of the loaded page in order to my profile. 

This injected scripts will do some clicks on some buttons, this clicks will trigger Javascript to send ajax request to the server.

Sometimes I need to use window.location to go to another url on the same website, and do other staff. and same injected script most remain in the DOM 

Well, Can jsdom help me to do that?
I sow some users embedded nodeJs within the app. I think I can do that. but will jsdom serve my needs?

Are there any samples who to do that?

Thank you and best regards

**Comment by Sebmaster** [comment]
> Well, Can jsdom help me to do that?

Probably not (easily). A setup like this would be highly experimental, require a lot of work and even so might not be able to do what you want it to.

In any case, it is totally unsupported.

**Comment by beshoo** [comment]
@Sebmaster i installed domjs on android and it works. 

Can i do the scrabing part,? 
Lets say i want to login to my instagram, can i do that? 

Next i will test passing my cookies.

**Comment by ketansp** [comment]
@beshoo what js engine did you use? Can you please share details around which version of jsdom did you use and how did you got it working?
