### ISSUE TITLE
Some questions to understand how to work with JsDom

### ISSUE THREAD

**Issue by beshoo** [jsdom/jsdom#2575]
- **Node.js version:** 10
- **jsdom version:** 15

I am totally new to **jsdom** and I have some questions, I tried to search but i don not find what I am looking for.

I have a privet Instagram profile, and I want to list my family photos.
I logged in my profile from chrome, and copy my cookies in order to pass it to jsdom "some how"

Now I found no way to add Headers to the **JSDOM.fromURL**  since there is more than userAgent to add.
Now I tried this code :
```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const virtualConsole = new jsdom.VirtualConsole();
const cookieJar = new jsdom.CookieJar();
      cookieJar.setCookieSync('ig_cb=1; mcd=3; mid=XBuVeQAEAAFxIpv6K22zwy3FWh8M; fbm_124024574287414=base_domain=.instagram.com; csrftoken=JLlCPzXYgfqGdopHXJDFhTENAl0B6krj; ds_user_id=2110732275; sessionid=2110732275%3AyPEB15hgEaToyd%3A2; shbid=13627; shbts=1557025365.3020725; rur=ATN; urlgen="{\"80.82.77.12\": 202425}:1hN7Qu:qAjK3IvszxAMUywjHx2RQnXScIU"', "https://instagram.com/");
const resourceLoader = new jsdom.ResourceLoader({
  strictSSL: false,
  userAgent: "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36",
});

JSDOM.fromURL("https://www.instagram.com/myprofile",  { pretendToBeVisual: true,resources: resourceLoader ,runScripts: "dangerously",virtualConsole,cookieJar  }).then(dom => {
  console.log(dom.serialize());
});
```

I am not sure if i am using **cookieJar** in correct way, please help me with this.
Now the qustions
1- How to pass Headers with "**JSDOM.fromURL**" like : 
```
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
DNT: 1
```
2- How to inject Javascript from local file "jquery + qunit" to the loaded page and run the script after dom is loaded. 
in the doc there is : 
`If you want to execute external scripts, included via <script src="">, you'll also need to ensure that they load them. To do this, add the option resources: "usable".`
but i don't know how to implemnt that. please help 

4- I understand that jsdom does not support navigation , `window.location` and any other type of navigation.
What is the final workaround if the remote website use any kind of "**window.location**".

5- If i send any request to the remote website via Ajax "While im in the WINDOW" , will that requset sent with respect to the session , i mean will nodejs send the  cookie?

I hope this thread will help me and other who just start with this Wonderful headless lib.

**Comment by domenic** [comment]
1. fromURL does not allow setting custom headers. To do that, request the content yourself using your favorite HTTP request library, then pass the resulting binary data to the `new JSDOM()` constructor.

2. You can insert scripts into JSDOM-created DOMs the same way as the browser, using `document.createElement('script')`, etc.

4. If a website uses these in a way that is important for your use cases, then jsdom is not usable for you.

5. It's hard to tell exactly what you're asking, but I think the answer is yes.

**Comment by beshoo** [comment]
> 1. fromURL does not allow setting custom headers. To do that, request the content yourself using your favorite HTTP request library, then pass the resulting binary data to the `new JSDOM()` constructor.

@domenic Thank you so much for your reply, Well let's say I click on a link on the page to load my photos
This will trigger some kind of ajax call to Instagram website.

What will happened hear, usually Chrome send headers and sessions to the remote website, Is this the case here?

I mean, let's say I logged to Instagram via var `request = require('request');`

something like :

```
function ScrapeInstagramPage (args) {
    dout("ScrapeInstagramPage for username -> " + args.username);
    var query_url = 'https://www.instagram.com/' + args.username + '/';

    var cookieString = '';
    var options = {
        url: query_url,
        method: 'GET',
        headers: {
            'x-requested-with' : 'XMLHttpRequest',
            'accept-language'  : 'en-US,en;q=0.8,pt;q=0.6,hi;q=0.4', 
            'User-Agent'       : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36',
            'referer'          : 'https://www.instagram.com/'+args.username,
            'Cookie'           : cookieString,
            'Accept'           : '*/*',
            'Connection'       : 'keep-alive',
            'authority'        : 'www.instagram.com' 
        }
    };
```
Now after login i will have HTML , this HTML has to be passed to 
`const dom = new JSDOM(html, { runScripts: "dangerously" });`

But if I click anything in the DOM via javascript this will be outside of the session! how can I solve this problem?

**Comment by beshoo** [comment]
Well it seems I am using  cookieJar  wrong way, Please kindly advise what the correct way to pass cookieJar to the  **fromURL**

**Comment by beshoo** [comment]
SOLVED by : https://github.com/jsdom/jsdom/issues/2577
