### ISSUE TITLE
How to avoid the xmlns on xmlSerializer.serializeToString()?

### ISSUE THREAD

**Issue by Lcfvs** [jsdom/jsdom#2576]
### Basic info:

- **Node.js version:** v12.1.0
- **jsdom version:** v15.0.0

### Minimal reproduction case

Is there a way to avoid that attribute, please?

```html
<html xmlns="http://www.w3.org/1999/xhtml">
```

**Comment by domenic** [comment]
This didn't follow the issue template, in particular the very important section showing how to reproduce, and what similar code does in browsers. Closing until such a comparison is provided.

**Comment by Lcfvs** [comment]
@domenic Hi,

The steps to reproduce are simple:

```js
import {JSDOM} from 'jsdom'

const XMLSerializer = new JSDOM('').window.XMLSerializer

const fragment = JSDOM.fragment(`
  <div></div>
  <div></div>
`)

console.log(new XMLSerializer().serializeToString(fragment))
```

Actual result:

```html
  <div xmlns="http://www.w3.org/1999/xhtml"></div>
  <div xmlns="http://www.w3.org/1999/xhtml"></div>
```

Desired result:
```html
  <div></div>
  <div></div>
```

**Comment by domenic** [comment]
When I run that code in Node.js, I get the following error:

```
import {JSDOM} from 'jsdom'
       ^

SyntaxError: Unexpected token {
```

**Comment by Lcfvs** [comment]
Sorry, I used the `esm@3.2.22` [npm module](https://www.npmjs.com/package/esm)

`node -r esm ./jsdom.test.js`

**Comment by domenic** [comment]
Ok. We can't support third party tools, so let us know when (per the issue template) you have a reproduction case involving only jsdom.

**Comment by Lcfvs** [comment]
The pure jsdom version:

```js
const JSDOM = require('jsdom').JSDOM

const XMLSerializer = new JSDOM('').window.XMLSerializer

const fragment = JSDOM.fragment(`
  <div></div>
  <div></div>
`)

console.log(new XMLSerializer().serializeToString(fragment))
```

**Comment by Lcfvs** [comment]
The `esm` module only changes how the module are loaded, not relevant, then ;)
