### ISSUE TITLE
Question: how to bypass `canvas` issue from codebase that depends on JSDOM?

### ISSUE THREAD

**Issue by jeffkamo** [jsdom/jsdom#2582]
### Basic info:

- **Node.js version:** 8.10.0
- **jsdom version:** 14.0.0 and 15.0.0

### Minimal reproduction case

I built a small example that showcases how my team uses JSDOM [here](https://github.com/jeffkamo/jsdom-use-case).

**Use case summary**:
My team built an SDK library that includes JSDOM as a dependency. Specifically, we use JSDOM as part of a server class that our customers extend to build server-side rendered JS apps. Our SDK is **not** bundled with webpack, it's distributed as is. However, the customer bundles their project with webpack, which of course includes our SDK and JSDOM as dependencies.

**Issue summary**:
When our customers compile their project code with Webpack, they run into the `canvas` dependency issue that's been reported elsewhere (i.e. #2508).

### Possible solutions?

I'm aware of some solutions that others have discussed (in particular [this one](https://github.com/jsdom/jsdom/issues/2508#issuecomment-480537179) seems quite effective), however those suggestions require changes at the project level. This is problematic for our use case because it means our SDK's upgrade to newer versions of JSDOM is effectively a breaking change (i.e. it breaks the project, and fixes must be made at the project level).

I recognize that our use case uses JSDOM in a strange way (i.e. the project bundles it with webpack) and that JSDOM itself is working as intended (it dynamically depends on canvas for a reason). So I understand that there is little incentive for a fix to made in JSDOM itself.

So what I'm wondering: is there a fix that I've overlooked that can be made at the SDK level that avoids the need for any additional changes at the project level?

**Note:** We've considered altering our SDK such that when the project bundles, JSDOM isn't included. This would probably work, but it's a complex change for us, making it more of a long-term solution. It's my hope that there's a shorter term solution that we've overlooked 🤞 

### ~~How does similar code behave in browsers?~~

_(issue is unrelated to browser behaviour)_

**Comment by Sebmaster** [comment]
Bundlers should allow you to explicitly mark dependencies as not installed, which should cause that code to behave correctly. You'll need to verify that's possible and providing an example with your SDK should help.

**Comment by jeffkamo** [comment]
Thanks @Sebmaster. Our SDK is private, so I can't share it. I can only share my mock sdk repo.

Are you suggesting a fix like [this](https://github.com/jeffkamo/jsdom-use-case/pull/1)? That looks to work, but it requires changing the project itself. Unfortunately for me and my team, we didn't have the foresight to do something like include base webpack configs in the SDK.

**Comment by Sebmaster** [comment]
That'd be it.

**Comment by danielschwartz85** [comment]
Just in case anyone needs a jsdom version without canvas, we published one here:
https://www.npmjs.com/package/@applitools/jsdom
