### ISSUE TITLE
I messed up the web platform tests submodule pointer

### ISSUE THREAD

**Issue by domenic** [jsdom/jsdom#2584]
Just logging so other collaborators don't get confused. https://github.com/jsdom/jsdom/commit/5f314a94ece44e94c6f662862bc12ba0ee6db30b incorrectly reset the web platform tests submodule to whatever it was on my local machine. (It turns out using VS code as a Git client isn't always a seamless abstraction.)

We should revert that change. The Travis CI build will fail until we do.

This doesn't affect our users of the newly-published v15.1.0 because it's just the tests, which aren't in the npm package anyway.

**Comment by Zirro** [comment]
Fixed by https://github.com/jsdom/jsdom/commit/33798c9d0ff7e5a84ca8c5fe8f73b0c552120d62.
