### ISSUE TITLE
Element.focus() does not set active element on document object

### ISSUE THREAD

**Issue by miggs125** [jsdom/jsdom#2586]
### Basic info:

- **Node.js version:** 10.15.3
- **jsdom version:** 13.2

jsdom does not set the activeElement of the document object when an elements focus() method is called.

Using similar code found in this [issue](https://github.com/jsdom/jsdom/issues/2472), the active element persists as the Body element even when focus is called.

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM;
const div = dom.window.document.createElement('div');
div.contentEditable = true;
div.focus();
console.log(dom.window.document.activeElement); // HTMLBodyElement {}
div.tabindex = 1;
div.focus();
console.log(dom.window.document.activeElement); // HTMLBodyElement {}


```

### How does similar code behave in browsers?
the element which has the focus() method called upon is set as the document's active element given that there is a contenteditable property set to true.

**Comment by Machiaweliczny** [comment]
There is regression for this case in `15.2.1`. Work fine in `15.1.1.`

**Comment by domenic** [comment]
Please open a new issue

**Comment by artyomtrityak** [comment]
i have similar problem using jsdom@15.1.1

**Comment by liamsc** [comment]
I also ran into this testing with enzyme and jsdom. I went to open an issue but noticed that the contributing doc has:
> Please create a minimal repro. Any reports involving third party libraries
will be closed, as we cannot debug third-party library interactions for you.

I don't have time to go about and try and reproduce this without enzyme so I'll put my code snippet here in case anyone can use it to repro or finds it helpful.

Background: when the isOpen prop changes, this triggers a componentDidUpdate call which uses a react ref to focus the input. The input element does not have a tabIndex property.

```
it('should autofocus if isOpen is true', () => {
        const props = { ...DEFAULT_PROPS, isOpen: false };
        const searchBar = mount(<SearchBar {...props} />);

        searchBar.setProps({ ...DEFAULT_PROPS, isOpen: true });
        const input = searchBar.find('input');

        expect(document.activeElement).to.equal(input.getDOMNode());
    });
```

per @Machiaweliczny's comment, with jsdom 15.2.1 && 15.2.0, document.activeElement is null.
However, in 15.1.1, the active element is present.

Please let me know if I can clarify anything further. Happy to help.

**Comment by artyomtrityak** [comment]
Solution i found is assigning tabIndex to all elements i want to focus (even `<a />`. It looks like jsdom does require tabIndex even for by default focusable elements.

**Comment by nktssh** [comment]
I also had this issue, fixing version to `15.1.1` helped.
Thanks @liamsc!

@artyomtrityak for some reason adding `tabIndex` doesn't work for me

**Comment by wojtekmaj** [comment]
This report is still valid as of 16.2.2.

**Comment by TimothyGu** [comment]
This appears to be the same bug as #2472, which has been fixed quite recently. The next release should have a fix fot this.

**Comment by quantuminformation** [comment]
when is the new release?

**Comment by marcosvega91** [comment]
Is someone experiencing issue with `getSelection` ?. After a `div` has focus I expect to call `getSelection` and get caret position, but `getSelection().rangeCount` is always 0.

**Comment by esamattis** [comment]
This is an old issue but I came here from the first google hit looking why `.focus()` does not seem work.

So for anyone else wondering: Make sure the element is added to the DOM tree:

```tsx
const input = document.createElement("input");
document.body.appendChild(input);

console.log(document.activeElement === input);
```

**Comment by hasghari** [comment]
> This is an old issue but I came here from the first google hit looking why `.focus()` does not seem work.
> 
> So for anyone else wondering: Make sure the element is added to the DOM tree:
> 
> ```tsx
> const input = document.createElement("input");
> document.body.appendChild(input);
> 
> input.focus();
> console.log(document.activeElement === input);
> ```

Worked like a charm, thanks!
