### ISSUE TITLE
Module not found: 'child_process' in '...\node_modules\jsdom\lib\jsdom\living'

### ISSUE THREAD

**Issue by bryansamuel1** [jsdom/jsdom#2590]
### Basic info:

- NODE.JS v8.12.0
- JSDOM v15.1.0

### Description
**jsdom\living\xmlhttprequest.js** requires a module **child_process** which is missing in jsdom\living.

Looking at the repo here on github I see the requirement and I also see that there is no module either. 

I am using jsdom in a Laravel/Vue project alongside mochapack to test my Vue components and this error appears whenever I run my package.json test script
```js
living\xmlhttprequest.js 

const HTTP_STATUS_CODES = require("http").STATUS_CODES;
const { spawnSync } = require("child_process");
const { URL } = require("whatwg-url");
```
In my test I require jsdom and set a URL as I use the package vuex-persistedstate.

```js
const jsdom = require('jsdom')
const { JSDOM } = jsdom
const dom = new JSDOM('', {
  url: 'http://localhost'
})
```

I am happy to provide further information but right now I don't know what else would be necessary.

**Comment by Sebmaster** [comment]
We specifically have only support (and test in) browserify. While it's definitely possible to run jsdom in the browser, we don't support other packers.

**Comment by Zirro** [comment]
> jsdom\living\xmlhttprequest.js requires a module child_process which is missing in jsdom\living.

To further clarify, [`child_process`](https://nodejs.org/api/child_process.html) is part of the Node.js API and not a module we are supposed to provide. The bundler you're using needs to include equivalents of these APIs, in the way that browserify does.

**Comment by x5engine** [comment]
module.exports = {
  webpack: config => {
    config.node = {
      fs: 'empty',
    }
    config.target = "node"

    return config
  }
}

**Comment by tlchatt** [comment]
> module.exports = {
> webpack: config => {
> config.node = {
> fs: 'empty',
> }
> config.target = "node"
> 
> ```
> return config
> ```
> 
> }
> }

Where do you put this?
