### ISSUE TITLE
getting page content and execute all inner scripts and detect page reload

### ISSUE THREAD

**Issue by se8820726** [jsdom/jsdom#2595]
I want to load the content of a URL and process its content, including HTML and JavaScript codes.

During the process, The script of the content sends a series of requests to other URLs, receives  information, and reloads the page automatically at the end.

I want to get notified when the page reloads and have access to its new content.

Is this possible through your library? 
If yes, send me a sample code please.

**Comment by domenic** [comment]
Sorry, this is an issue tracker, for reporting bugs, per the issue template. It is not a place to get help with coding. I suggest https://stackoverflow.com/.
