### ISSUE TITLE
querySelectorAll returned too many HTML elements

### ISSUE THREAD

**Issue by vincenthawke** [jsdom/jsdom#2597]
Node.js version:  10.15.3
jsdom version:  15.1.0

```js
const fs = require('fs');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const xmlFile = fs.readFileSync("question.xml", "utf8");
const dom = new JSDOM(xmlFile);
const all = dom.window.document.querySelectorAll("S");
console.log(all);
```

```xml
<?xml version="1.0" encoding="utf-8"?>
    <Foo>
        <FooBar>
            <S a="string1" b="string2" c="string3"/>
        </FooBar>
    </Foo>
    <Foo>
        <FooBar>
            <S a="string1" b="string2"/>
            <S a="string1"/>
        </FooBar>
    </Foo>
```

`querySelectorAll("S")` returns 7 HTML elements when there are clearly only 3. What makes it even stranger is if I rename the xml elements from `S` to `F`, it works correctly and finds only 3 elements. 

```xml
<?xml version="1.0" encoding="utf-8"?>
    <Foo>
        <FooBar>
            <F a="string1" b="string2" c="string3"/>
        </FooBar>
    </Foo>
    <Foo>
        <FooBar>
            <F a="string1" b="string2"/>
            <F a="string1"/>
        </FooBar>
    </Foo>
```
`querySelectorAll("F")`  returns 3 elements. I don't understand what is wrong. Looks inconsistent / buggy.

**Comment by Zirro** [comment]
The problem would appear to be that the input gets parsed as HTML, resulting in the following document:

```HTML
<!--?xml version="1.0" encoding="utf-8"?--><html><head></head><body><foo>
        <foobar>
            <s a="string1" b="string2" c="string3">
        </s></foobar><s a="string1" b="string2" c="string3">
    </s></foo><s a="string1" b="string2" c="string3">
    <foo>
        <foobar>
            <s a="string1" b="string2">
            <s a="string1">
        </s></s></foobar><s a="string1" b="string2"><s a="string1">
    </s></s></foo><s a="string1" b="string2"><s a="string1">
</s></s></s></body></html>
```

The reason behind the different results with `<F>` is that it isn't also the name of an HTML element. To parse the input as XML instead, you can either set the `contentType` option like so:

`new JSDOM(xmlFile, { contentType: "text/xml" });`

...or use the [`fromFile()`](https://github.com/jsdom/jsdom#fromfile) method which will automatically use the XML parser if the filename ends in `.xml`. Doing so with your current XML will result in an error ("documents may only contain one root") though, but wrapping the `<foo>`s in a parent node should take care of that.

**Comment by vincenthawke** [comment]
Thank you for fast reply. I was really confused because fromFile method worked but not others. `{ contentType: "text/xml" }` fixed it and works indeed as intended.
