### ISSUE TITLE
Missing ShadowRoot.activeElement descriptor

### ISSUE THREAD

**Issue by caridy** [jsdom/jsdom#2602]
### Basic info:

- **Node.js version:** v10.15.1
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {};
const dom = new JSDOM(`<body></body>`, options);

Object.getOwnPropertyDescriptor(dom.window.ShadowRoot.prototype, 'activeElement'); // yields undefined
```

### How does similar code behave in browsers?

```
Object.getOwnPropertyDescriptor(window.ShadowRoot.prototype, 'activeElement');
> {get: ƒ, set: undefined, enumerable: true, configurable: true}
```

https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement

**Comment by caridy** [comment]
cc @pmdartus

**Comment by pmdartus** [comment]
Fixed with 0f09068904bce4cd50aec3e170fa38ad03a5c29a.

**Comment by pwolaq** [comment]
@pmdartus I'm afraid this fix broke how `activeElement` works - see here: https://github.com/testing-library/jest-dom/issues/145

**Comment by domenic** [comment]
@pwolaq can you post a new issue, following the issue template? (Including, importantly, a minimal repro using only jsdom, not testing-library or jest or similar.)

**Comment by domenic** [comment]
Again, an issue following the issue template, instead of a comment in a closed issue, is the best way to get this prioritized and potentially fixed.
