### ISSUE TITLE
JSdom is passing CSS and JS even when they are turned OFF

### ISSUE THREAD

**Issue by termitek12** [jsdom/jsdom#2607]
node v8.10.0
jsdom v11.3.0

when a page load async JS and CSS via HTTP headers LINK field (preload), JSdom is passing this out - and edit you own CSS styles for example. If page you test has:
* {background:red;}
you rendered page has a red background too... (those setting are used):
```
	var document = window.document;
	var $ = window.jQuery;
```

No FetchExternalResources, ProcessExternalResources are used - SkipExternalResources is set to true (features: {} - object).

Any idea how to resolve that problem?

**Comment by domenic** [comment]
Not sure. jsdom v11 is no longer supported.

**Comment by termitek12** [comment]
On latest jsdom it's the same. I don't know why, but jsdom load requested page js and css - and it override some of my css and js. Do you have possible solution I can try?

**Comment by domenic** [comment]
Can you post an example following the issue template?

**Comment by termitek12** [comment]
Sure. For example - wp.pl, let me know if you too have a problem. Aaaa in you custom page...ble lets create something short:

```
<!DOCTYPE html>
<html>
<head><title></title></head>
<body>
<wrapper>This will be changed - cause HTTP headers link field preload css</wrapper>
</body>
</html>
```

And a css file:
`
wrapper{margin:10px;}`

it will be overrriden by - https://www.wp.pl/adVp-mAeB0tkXxtDcktSV3kUSB4qEQ4UeB1EA28GEhdpJGsbdwslCRFEHQwVK1I9NANILwMSUF0MP18rIyIOJhJGShoJFAQ8FEhaOwRVOwcPG0g0MxQ0UGQDWgo7CgUmYgB-WTUiUQASQEcvcycQAmQEbyULEwo1Jxd7CnFXJCwaNkgFcR8oDQxGezx5URQKAjNUJRsGKBZgAFtYFisLDzI5YQYkNRUIZDpVVAo2GCFmAENbByojCic6Z105Mxgeb0V3D3ERJS8bAGo0eTQXEzUXeR0CJzAcZRxpGhkfKgtjE38hKykwKW9AQSU0CSoqEgBlXS88VxQyG3wCAFYKIyJGYSJ4JBQeEhpPLzhTKiIYBH8vFAIQEG4fbgUjURsJByodJDIiAgIiAUEdMxwNJhMRHAMTAQYQPURVGXItEBI5QnQKFiwbLB0bbwUzViUoHDZJLhhVCz4ENmUoKDUsATsWTh94LwU1PyhoIDMsLRI8PXojEwcyNhAZRAYVFAYjJzUdAA4mBSJjEng-MiMLVyEhVVR1JC8LPhx_IyQwKz5vBHc7GTACIWAcWwU3FyVVZjh5ASYrVi0dNXwPLgg3KiRGWT8VKy8WFCFcOw8UJAYfNRwpEy4LMSI0Rz4wLTtdZzJMODgUKiEfPEkfKSYKAmInHCsyKikuEBlgN3MgDRwVN2gfCVUIKmBEfiEMNBZUGiR7JDNXJzMuRH0aeD8qKmNIeF47LgYVMUF9IRYfUw9mPGdVEFAUFz0HeQ4yCC0XZygeWhgiMjJmCVk1AlZUNiI0QSk1MC0VECReHhAhBi5uQEs7diMCEDIeVB0uCxI0bkJ7CyIXBC5nMhouBSYCCWU_RSZ3PysgMCBvBwoiUSA-O3gnOCgPPA5CdAYgBzc3EhkZWigBIBcxE2AscwYQXTA_fBoJNVY2LEFnFzQnUwIFCBscMDYCDCAAfVwmJgkVF0JgFRYQNisyFXQrMSM4IgU4Zg4iFBAcBwBcWiAVDSERQF5ZLAwCHBEneysnVVAnGBJoGjU3GQcBRVgscBAkJRVEQB0TF1MoIwdnCDI0FAY5BW8mEwEALCYRaSonKgcGMCYYHCAdLgFvCGIBAhMsLGcRQQ4sDCYoHDpiWjlVWQ8lO0cvIAY1DSc3ZigbMhsPIAZeHXBSVzc-In9adD9RMh4xGjkXCQsgLCBBPXIqLxUdE1k4ChQnVW8jbgI1UCI8HAp_NTEsB1ImIG44MhcWBiMaa14TDTUvLDlDKSsnNRcQG2UkBFIiNWdHZhgSAAQVBjt-PzVdGVRgPWoCED8KDxBAeiU3VRs9DgRFKzBVNw0PBX8XCx8AUAI4XTkIFhBXBQlpBQQEJB4yMx8rNQYYUDsdZSAvFBkJJRduFygEEi4ZM3UXNzNZBzVASws0NCM1OTh-XiUzUgswAVQgB1UEMiwjHA9xFDclAiFHJiY_KQVuGWYlG1cVMTESYBgXEgdXMj8dFSNWG1NkEmcvMzARUAVITC4FUisjHRVJWxEvWAUCJnhVBDNZBiRJYwQZHFddOURrHCVcDSUdJxkqDjRZITwbWhsRBxg8ASYbLzYCAAcwBWYFKAsZDTQlGyIRFDcXDjN7BgItAAkDO1wFGSBWMD46ZC8lEysXPAd4AzQhUR4aHWguJB0jCAUAXgUnNhkdByZODiYPDF1mH2cqczwzKxQHblQUClYnASJVDDgVIlJuSUA5ACcAVxIIfgEwUCssNSJ4IngqDRIhI0obEwRTIRoKZQwoKDQuI0FAIgtWOzUhHkwVChIqMWYCRB4yEjknJiRYHXkMB1A9M2YkdBYbET4IZj0TFBUGEikZCyQcDRYlRmgGICItLTAYZxgUBhkzFCpgOiUdJBY9AUElOwgMUTcheho4ERErMUZ_FQkyAFRhOFkJFQ4EKAcgHRgDUyoJAx5LWxJUJB01NxwCFhAtFmEZfFsAEi4xMxxGBgc=/

**Comment by Sebmaster** [comment]
That's not following the issue template.

**Comment by termitek12** [comment]
@sebmaster you mean by filling - https://github.com/jsdom/jsdom/issues/new ???

https://runkit.com/embed/bqdu9la7ezaw

**Comment by termitek12** [comment]
Topic can be closed, after debugging it seems that is not JSdom error/bug.
