### ISSUE TITLE
Undesirable encoding of `srcset` attr

### ISSUE THREAD

**Issue by harrysolovay** [jsdom/jsdom#2608]
### Basic info:

- **Node.js version:** 11.12.0

I'm trying to use `parse5` to turn all relative paths of an HTML file into absolute paths. I need to interact with ASTs for the sake of preventing content from being transformed (I only want to transform linked resources, aka. attributes). The HTML I'd like to transform contains many `srcset`s... which seem to be turned into `src`s by the parser. Additionally, the parser encodes the associated values. Swapping the value within the base64-encode is tough... I suppose I could use another library to transform it back... but hopefully there's a better way. I don't understand why the parser is behaving this way (probably to match browser specs?).

Below is the reproduction... any advice would be greatly appreciated. Thank you!

### Minimal reproduction case

```js
const {parse} = require('parse5');
const {includes, replace, startsWith} = require('ramda');

const parsed = parse(theHTML);

const target = '/somepath';
const replacement = 'https://pathprefix.com/somepath';

(() => {
  const traverse = node => {
    const {attrs, childNodes} = node;

    if (attrs && attrs.length) {
      for (let attributeI in attrs) {
        const {name, value} = attrs[attributeI];

        if (
          typeof value === 'string' &&
          (name === 'srcset' || startsWith(target, value))
        ) {
          node.attrs[attributeI].value = replace(target, replacement, value);
        }
      }
    }

    if (childNodes)
      for (let childNode of childNodes) {
        traverse(childNode);
      }
  };

  traverse(parsed);
})();
```

**Comment by domenic** [comment]
I guess you meant to open this on the parse5 repo.

**Comment by harrysolovay** [comment]
@domenic I'm sorry about that! Careless mistake of mine :/
