### ISSUE TITLE
setInterval returns undefined after the window closes

### ISSUE THREAD

**Issue by lacker** [jsdom/jsdom#2617]
### Basic info:

Node 8
jsdom 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM("");
let callback = () => {
  let value = dom.window.setInterval(() => {}, 1000);
  console.log("this should not be undefined:", value);
};
dom.window.close();
process.nextTick(callback);
```

The problem is that in jsdom, `setInterval` returns undefined after the window closes. However, normally setInterval will never return undefined, either in Node or in browsers. So it's reasonable for some code to be nested in a bunch of callbacks, and run after the jsdom window has been closed, but to expect a non-undefined return value for `setInterval`.

Specifically, some code in the `simple-peer` library does something like `let returnValue = setInterval(...); if (returnValue.unref) { ... }` to handle the case where timers should be unref'd to let Node exit. That code is correct according to either browsers or Node, but fails in a jsdom environment.

Instead, perhaps this could return `0` or some other number? That is normally a valid return value for `setInterval`.

### How does similar code behave in browsers?

Edit: Chrome just returns 0. It *is* possible to call `setInterval` on a window after it closes, by calling it from another window.

**Comment by domenic** [comment]
We should probably make it (and maybe everything in jsdom) throw after the window closes.

**Comment by Sebmaster** [comment]
@domenic I think this is actually a bug though.

```js
x = window.open("about:blank")
x.setTimeout("document.innerText += 'hi'", 1000) // 1
x.close();
x.setTimeout("document.innerText += 'hi'", 1000) // 2
```

**Comment by lacker** [comment]
Actually I was wrong about browser behavior - you *can* call `setInterval` after the window closes, if you're doing it from the script that opened the window. In Chrome, `setInterval` appears to return 0 in this situation. Specifically this code:

```
let w = window.open();
w.close();
let returnValue = w.setInterval(() => {}, 1000);
console.log(returnValue);
```

logs `0`. So I think `setInterval` and probably `setTimeout` as well should just return 0 rather than undefined in this situation.

**Comment by t-mullen** [comment]
Returning anything but a nonzero integer is against HTML spec. 

https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#dom-setinterval
https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timer-initialisation-steps

> The setInterval() method must return the value returned by the timer initialization steps ...a user-agent-defined integer that is greater than zero that will identify the timeout to be set by this call in the list of active timers.

**Comment by domenic** [comment]
Running code after a window closes isn't possible in a browser and there is no spec that applies in such a situation.

**Comment by lacker** [comment]
Chrome returns 0 after the window closes, though. So I guess Chrome is against HTML spec here? I would suggest just returning 0 for Chrome compatibility. I agree it should return some sort of integer.
