### ISSUE TITLE
How to serialize a DocumentFragment

### ISSUE THREAD

**Issue by reallyimeric** [jsdom/jsdom#2618]
The doc said

> If you need to serialize your DOM, you should probably use the JSDOM constructor more directly.

but I didn't find an example.

### Basic info:

- **Node.js version: `11.15.0`** 
- **jsdom version: `15.1.1`** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const frag = JSDOM.fragment(`<p>p1</p><p>p2</p>`);

JSDOM.prototype.serialize.call(frag);
```

### How does similar code behave in browsers?

N/A
`````

**Comment by bleonard252** [comment]
The docs mean to not use a fragment.

**Comment by domenic** [comment]
Sorry for missing this when it was first filed. @bleonard252 is correct!
