### ISSUE TITLE
How to pass a jQ script to a JSdom instance?

### ISSUE THREAD

**Issue by spamator12** [jsdom/jsdom#2619]
in old JSdom it was:
```

var jquery = fs.readFileSync('js/jquery.min.js', 'utf-8');

jsdom.env({
html:html,
src : [jquery], // here we are loading our jQ script
features: {
FetchExternalResources : ['script'],
ProcessExternalResources : ['script'],
SkipExternalResources: false
}, done: function (err, win) {
// code goes here 
});
```

And in new one I need to load it by editing html content?

**Comment by spamator12** [comment]
I guess it is the only way then...

I think I also need somebody to explain my how does JSdom scripts from external page affection the window. I have read that it is not good to use nodejs global window with external scripts. So when I pass to JSdom an HTML code of a page with `<script src=''>` tags and set the option to:
```
runScripts : 'dangerously',
resources : 'usable'
```
scripts will operate on JSdom special window and not the global nodejs one? Cause I get an errors like:
```
Error: Uncaught [TypeError: Cannot read property '_layerAdd' of null]
Error: Uncaught [TagError: adsbygoogle.push() error: No slot size for availableWidth=0]
Error: Could not load script: "script.js"
```

and this mean that there is something wrong with JSdom window, right?

**Comment by termitek12** [comment]
It seems that you JSdom got a wrong location (window.location.href) it could be a problem with window like you said. Can you show rest of the code?

**Comment by spamator12** [comment]
Sure:

```
	var url = 'https://jigsaw.w3.org/css-validator/validator?uri=luxik.pl&profile=css3&usermedium=all&warning=1&vextwarning=&lang=pl-PL';
	console.log('WE TRY TO GRAB: ' + url);
	var requestData = request({url : url, userAgent : 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'}, function(err, resp, HTMLdata) {
		if (!err && resp.statusCode === 200)
		{
			var JSdom1 = new JSDOM(HTMLdata, {runScripts : 'dangerously', resources : 'usable'});
			if (JSdom1.onload) {
					console.log('This will not load cause of: Error: Could not load script: "//www.w3.org/QA/Tools/w3c-include.js" (at process._tickCallback (internal/process/next_tick.js:180:9) Error: Tried to fetch invalid URL //www.w3.org/QA/Tools/w3c-include.js)');
			}
			else {
				console.log('There is an ERROR when parsing JSdom1 HTML content!\n');
				res.render('index');
			}
		}
	});
	requestData;
```

It seems right -  JSdom is not parsing address. I have tried to set:
var window = JSdom1.window;
var document = window.document;

When I try to pass HTML code as fragment() but it is not using window nor document.

**Comment by termitek12** [comment]
try to add additional properties to the object you pass to the JSDOM constructior - url and refeRRer.

**Comment by spamator12** [comment]
Yea this is better! Thanks, but I still catch error by request.

**Comment by spamator12** [comment]
I ended up using cherio.

**Comment by termitek12** [comment]
Yea cherio has a build in use of JQ.
