### ISSUE TITLE
focus() on focused element should not fire focus event

### ISSUE THREAD

**Issue by eps1lon** [jsdom/jsdom#2621]
### Basic info:

- **Node.js version:** 10.15.2
- **jsdom version:** 15.1.

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { window: { document } } = new JSDOM(`
<!DOCTYPE html>
<html>
  <head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
  </head>

  <body>
    <div id="app"><button>Hello, Dave</button></div>
  </body>
</html>
`);

function handleEvent(event) {
  console.log(`${event.type} event`, event.target);
}

const button = document.querySelector('button');
button.addEventListener('focus', handleEvent);

button.focus();
button.focus();

```

https://repl.it/@eps1lonExists/SimpleUnfoldedSequence

### How does similar code behave in browsers?

Repeated focus does not fire focus event. It seems like this is matching 

> If new focus target is the currently focused area of a top-level browsing context, then return.

-- https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps

which isn't implemented by jsdom.

https://codesandbox.io/s/repeated-imperative-focus-2gftr

### Misc

Would it be sufficient to check if `previous === this` and return if this is true after 

https://github.com/jsdom/jsdom/blob/529b9f31839d5c48d0352f239ccd9b53a229aee2/lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js#L34

? Couldn't find an existing test in https://github.com/web-platform-tests/wpt/tree/master/html/interaction/focus so I would need to add a new one to the upstream folder too, right?

**Comment by SeasonsNeedfulThings** [comment]
I dont understand any of this??

**Comment by SeasonsNeedfulThings** [comment]
be nice to have simple instructions
