### ISSUE TITLE
Fireevent on type=reset button not triggering

### ISSUE THREAD

**Issue by hanikishorpinisetty** [jsdom/jsdom#2622]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

```js
<form onSubmit={submitFn} onReset={resetFn}>
<input type="text" value="test" />
<button type="reset">Reset</button>
<button type="submit">Submit</button>
</form>
fireEvent.click on submit triggering form onSubmit function, but fireEvent.click on reset not triggering form onReset function.
```

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
This does not include important information in the issue template, so I will close it. Please fix that and then request a reoopen.
