### ISSUE TITLE
TypeError: Cannot read property '_cookieJar' of null

### ISSUE THREAD

**Issue by chillyond** [jsdom/jsdom#2623]
### Basic info:
Cause an error in `jest`
- **Node.js version:** v10.13.0
- **jsdom version:** 11.12.0

### Minimal reproduction case
test used in `jest`:
```js
test('connection', async () => {
  const port = await getPort({ port: getPort.makeRange(8080, 65535) })
  const io = socketIO(port)
  const connection = new Promise(resolve => {
    io.on('connection', resolve)
  })
  const client = socket('http://localhost:' + port)
  await connection
})

```

**Comment by domenic** [comment]
Sorry, this uses a lot of functions (getPort, test, socketIO, socket) which are not part of jsdom, and we cannot be responsible for debugging. Please produce a minimal example involving only jsdom, and we can debug.

**Comment by strazds** [comment]
Same problem:
(node:8200) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_cookieJar' of null
    at resolve (.\node_modules\jsdom\lib\jsdom\living\websockets\WebSocket-impl.js:124:39)
    at new Promise (<anonymous>)
    at WebSocketImpl.openingQueues.set.openingQueues.get.then (.\node_modules\jsdom\lib\jsdom\living\websockets\WebSocket-impl.js:112:94)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:8200) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
