### ISSUE TITLE
jest Spying on location assign

### ISSUE THREAD

**Issue by tommarien** [jsdom/jsdom#2625]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

According to blog [post](https://remarkablemark.org/blog/2018/11/17/mock-window-location/), we have to delete location first to put a jest.fn on the assign method.

delete window.location;
window.location = { assign: jest.fn() }

so we could use in a test, but why did the document.webidl specify it as unforgeable, because it seems like to break the entire testing aspect of jsdom.

on js-dom 11, we could just do

window.location.assign = jest.fn();

// act

expect(window.location.assign).toHaveBeenCalledWith('url');

Please advice

**Comment by domenic** [comment]
This is the same behavior as browsers. If you can figure out how to spy on location in browsers with Jest, you can do so in jsdom.
