### ISSUE TITLE
JSDOM is incompatible with Jest in its current state

### ISSUE THREAD

**Issue by reduxdj** [jsdom/jsdom#2629]
- **Node.js version: v8
- **jsdom version:15.1.1
```js
import 'jsdom-global/register';
import React from 'react';
import { expect } from 'chai';
import { configure, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
configure({ adapter: new Adapter() });
describe('Component Tes', () => {
  it('should have an id with accordion', () => {
    const wrapper = mount(
      <Component/>
    );
    expect(wrapper.find('#item')).to.exist; //eslint-disable-line
  });
```
The problem is setting up the the jest testrunner with babel-jest to load the components, the JS-DOM module throws an error. Although this is problematic for jest but works fine using mochawesome. Not sure what the error complaining about exactly?
```
TypeError: Cannot set property '_eventListeners' of undefined
      at Window.close (node_modules/jsdom/lib/jsdom/browser/Window.js:476:51)
          at Generator.throw (<anonymous>)
```

**Comment by domenic** [comment]
This code uses third party libraries and syntax that does not work in Node.js, so we cannot be responsible for debugging it. If you can produce a reproduction case that follows the issue template, we can reopen this issue.

**Comment by reduxdj** [comment]
What do you mean this code does not work in NodeJS, it does through babel. I would think you might have enough from the error to debug. It's unfortunate you keep closing this issue multiple times and other people are stuck at the same place.
