### ISSUE TITLE
Guidance using jsdom with no node.js or browser

### ISSUE THREAD

**Issue by alisomay** [jsdom/jsdom#2632]
Hello wonderful people who made this project happen, this is more like a question rather than an issue.
I need a simple DOM implementation which can have a window and a document object and the related methods. jsdom is more than enough and works great.
In my case I am running the JS in a custom environment interpreted by duktape engine. https://duktape.org/
Would you guide me to remove the node.js dependent parts of jsdom from the source code? 
Also would it be too cumbersome to do ? Or would the library work without them at all ? As I say I only need the replica of document and window objects.
Thank you very much.

**Comment by fabiosantoscode** [comment]
I'm working on a project where I run JSDOM inside a V8 isolate without access to nodeJS core modules or a module system at all, and I haven't done this yet, but what I plan to do is to use webpack (with `target: 'node'`) to remove the require calls, and also to replace node core requires with global variables which I'll inject into the isolate. This is probably something like what you want to do.

**Comment by alisomay** [comment]
That is true but in my case the requires are not a problem. The project I want to use jsdom is actually https://github.com/nick-thompson/blueprint which uses duktape engine. I thought the same and do what you did but I am in `Script evaluation failed: SyntaxError: parse error (line 1)
Duktape call error: TypeError: undefined not callable
    at [anon] (../../../../../blueprint/blueprint/duktape/src-noline/duktape.c:63374) internal` situation :) I couldn't find yet what is undefined in duktape environment which is defined in node.

**Comment by fabiosantoscode** [comment]
Interesting. Well, I don't know then :)
