### ISSUE TITLE
JSON api support on the window object

### ISSUE THREAD

**Issue by moshie** [jsdom/jsdom#2636]
### Basic info:

- **Node.js version:** v10.15.3
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const { window } = new JSDOM;

console.log(window.JSON); // undefined
```

https://codesandbox.io/embed/fervent-bird-z5dxm

**Comment by Sebmaster** [comment]
You need to initialise jsdom with `runScripts: 'outside-only'` to make it properly set up the sandbox for access to JS-native objects.
