### ISSUE TITLE
Use another symbol instead of angle brackets '<' '>'

### ISSUE THREAD

**Issue by yuis-ice** [jsdom/jsdom#2646]
I'm going to use jsdom as text data processing rather than as HTML. To distinguish between HTML and text data, I want to use custom HTML identifier tag, such as `{{tag}} {{/tag}}` instead of `<tag> </tag>`.

**Comment by Sebmaster** [comment]
Not possible (except if you write your own parser for your text tags), not gonna be implemented.

But you could always use custom HTML tags (x-tag) and strip them out instead of {{tag}}.

**Comment by yuis-ice** [comment]
I found jsdom/test/to-port-to-wpts/level3/core/files/orig/xhtml-symbol.ent file in this repository. 
In the file there's lines as follows.

```
<!ENTITY lang     "&#9001;"> <!-- left-pointing angle bracket = bra,
                                     U+2329 ISOtech -->
<!-- lang is NOT the same character as U+003C 'less than sign' 
     or U+2039 'single left-pointing angle quotation mark' -->
<!ENTITY rang     "&#9002;"> <!-- right-pointing angle bracket = ket,
                                     U+232A ISOtech -->
```

I guess I can modify and apply  the file to change the symbol. or the file is just a fake or something like reference?
