### ISSUE TITLE
onBlur event is being called incorrectly on a focused input field when focus is called several times

### ISSUE THREAD

**Issue by rohiniseetul** [jsdom/jsdom#2653]
### Basic info:

- **Node.js version:** 10.14.1
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const { document } = new JSDOM(`
<input 
    type="text" 
    id="foo" 
    onfocus="console.log('foo input field - onfocus event handler is fired')" 
    onblur="console.log('foo input field - onblur event handler is fired')"
/>`).window;

getFooInputElement = () => document.getElementById("foo");

// Attached event listeners
getFooInputElement().addEventListener(
  "focus",
  () => console.log("foo input field - heard browser focus event"),
  { capture: true }
);
getFooInputElement().addEventListener(
  "blur",
  () => console.log("foo input field - heard browser blur event"),
  { capture: true }
);

// Execute
console.log("Calling 'focus()' on foo input field");
getFooInputElement().focus();

console.log(
  "\nCalling on focus on the same foo input field which has focused already"
);
getFooInputElement().focus();

console.log(
  "Result/Issue: As we can see, `onBlur` event is fired when we call 'focus()' on the focused foo input field."
);
```
 Here's a link to [my repo](https://github.com/rohiniseetul/nodejs-app-using-jsdom) which I created and you can run the script and check out the above result.

### How does similar code behave in browsers?

I have tested the same code in normal browser and the result is different i.e. `onBlur` is event not being fired on a focused input when `focus()` is called multiple times on the same input. I have also created this [sandbox](https://codesandbox.io/embed/distracted-volhard-6j35e) example to prove that.

It would be much appreciated if you can take a look at the issue.

**Comment by mrjacobbloom** [comment]
Slightly more terse repro case:

```js
const { JSDOM }  = require('jsdom');
const { window } = new JSDOM('<!DOCTYPE html><html><body><input /></body></html>');
const input = window.document.querySelector('input');
input.addEventListener('focus', () => console.log('onfocus'));
input.addEventListener('blur', () => console.log('onblur'));

input.focus();
console.log('document.activeElement', window.document.activeElement);
input.focus();
```

prints:

```
onfocus
document.activeElement HTMLInputElement {}
onblur
onfocus
```

The following browsers do not call blur handler in this case (per [this fiddle](https://jsfiddle.net/mrjacobbloom/xk8gsov9/)):

- Chrome 79.0.3945.79
- Firefox 71.0
- Edge 44.18362.449.0

Relevant spec: either step 5 of https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps or step 1 of https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps

**Comment by jackgeek** [comment]
This issue appears to be resolved in 15.2.1.  It is mentioned in the [release notes](https://github.com/jsdom/jsdom/releases/tag/15.2.1)

**Comment by jackgeek** [comment]
> This issue appears to be resolved in 15.2.1. It is mentioned in the [release notes](https://github.com/jsdom/jsdom/releases/tag/15.2.1)

BTW - I have also verified it locally by being able to remove my work-around to this issue with 15.2.1 installed and my tests are still passing :)

**Comment by jackgeek** [comment]
@eps1lon Just figured out I could @ you to bring this issue to your attention 😂

**Comment by domenic** [comment]
Thanks, yeah, @eps1lon fixed this in https://github.com/jsdom/jsdom/commit/d8bede1fc532729b3951d53201a021648555140a.
