### ISSUE TITLE
How to set a value of an element node

### ISSUE THREAD

**Issue by brainwash1010** [jsdom/jsdom#2655]
Hi,
I am new just trying to test this api. currently I am unable to find the name of properties or methods. I did try to print the dom but it didnot help much. below is my problem.

I am getting an input type text element node from dom object. 

### fnamenode = dom.window.document.getElementById("fname")

the html code is
<input type="text" id="fname" value="test1" disabled/>

I am trying to set a new value in above value attribute or I am trying to update the value of "test1" 
I called setValue() on fnamenode, but it didnot work. 
when i tried to print the whole dom it says getter setter method but I am not sure what should i call in order to update the attribute value?

Thanks

**Comment by papandreou** [comment]
If you want to set the `value` attribute so it gets reflected in the reserialized output, you want the `setAttribute` method:

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <form>
      <input id="fname" type="text">
    </form>
  <body>
</html>
`);

dom.window.document.getElementById('fname').setAttribute('value', 'foo');

console.log(dom.serialize());
```

Output:

```html
<!DOCTYPE html><html><head></head>
  <body>
    <form>
      <input id="fname" type="text" value="foo">
    </form>
  

</body></html>
```

**Comment by papandreou** [comment]
... Just like in the browser, where there's also no `HTMLFormElement#setValue` and where updating the `value` property doesn't affect the reserialized HTML (eg. as observed in `document.body.innerHTML`).

Jsdom's mission statement is to behave like a browser, so the first thing to try is what you would do in a browser to achieve the same :)

**Comment by Addibro** [comment]
Hello! I run this code on my html docs:

```javascript
  const dom = JSDOM.fragment(JSON.stringify(html))
  dom.querySelectorAll('h2,h3').forEach((element, parent) => {
    const id = element.textContent.toLowerCase().replace(/\s+/g, '-')
    element.id = id
  })
```

The id's are not applied though, what am I missing? 

Thank you!
