### ISSUE TITLE
Setting input.valueAsDate or input.valueAsNumber doesn't affect input.value

### ISSUE THREAD

**Issue by Rich-Harris** [jsdom/jsdom#2658]
### Basic info:

- **Node.js version:** 11.6.0
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const { window } = new JSDOM();
const { document } = window;

document.body.innerHTML = `
  <input type="date">
  <input type="time">
  <input type="week">
  <input type="month">
`;

const today = new Date();

[...document.querySelectorAll('input')].forEach(input => {
  input.valueAsDate = today;
  console.log(`${input.type}: ${input.value}`);
});

document.body.innerHTML = `
  <input type="number">
  <input type="range">
`;

[...document.querySelectorAll('input')].forEach(input => {
  input.valueAsNumber = 42;
  console.log(`${input.type}: ${input.value}`);
});
```

This results in:

```
date: 
time: 
week: 
month:
number:
range:
```

### How does similar code behave in browsers?

```
date: 2019-09-07
time: 15:26:41.457
week: 2019-W36
month: 2019-09
number: 42
range: 42
```

https://jsbin.com/fujutaqimu/edit?html,output

**Comment by Rich-Harris** [comment]
(Should note that the same is true in reverse — setting `input.value` doesn't affect `input.valueAsDate` or `input.valueAsNumber`)

**Comment by domenic** [comment]
We currently don't implement valueAsDate or valueAsNumber at all, so you're just seeing the effect of what happens if you set a random property with any name on a HTML element. A pull request implementing them would be very welcome.
