### ISSUE TITLE
input.valueAsDate is not set to Jan 1 1970 for <input type="time">

### ISSUE THREAD

**Issue by Rich-Harris** [jsdom/jsdom#2659]
### Basic info:

- **Node.js version:** 11.6.0
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const { window } = new JSDOM();
const { document } = window;

document.body.innerHTML = `
  <input type="time">
`;

const input = document.querySelector('input');

input.valueAsDate = new Date();
console.log(`the year is ${input.valueAsDate.getFullYear()}`);
```

This outputs `the year is 2019`.

### How does similar code behave in browsers?

`the year is 1970`. The date is discarded, only the time should remain.

**Comment by domenic** [comment]
This is another consequence of the fact noted in https://github.com/jsdom/jsdom/issues/2658#issuecomment-529129461, which is that valueAsDate is not implemented at all in jsdom, so the code you're writing here is equivalent to

```js
input.anyPropertyName = new Date();
console.log(`the year is ${input.anyPropertyName.getFullYear()}`);
```
