### ISSUE TITLE
Could not load image

### ISSUE THREAD

**Issue by warhammercasey** [jsdom/jsdom#2662]
### Basic info:

- **Node.js version: 10.16.2
- **jsdom version: 15.1.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  { resources: "usable" }
};
const dom = new JSDOM(`
  <!DOCTYPE html>
<img id="myImg" src="image.png" />
`, options);

image = dom.window.document.getElementById('myImg');
console.log(image);
```

This just give me: Error: Could not load img: "image.png"
The image is in the node.js applications root directory and I have tried putting it in every directory related to JSDOM under /node_modules/jsdom/ in case the root was there.
Adding the option: documentRoot: __dirname doesn't change anything.

### How does similar code behave in browsers?

Should load the image properly

**Comment by papandreou** [comment]
It works if you specify the `url` option when instantiating `JSDOM` and point it at where your images live:

```js
const options = {
  resources: "usable",
  url: "file:///path/to/images/"
};
```

Where did you read about `documentRoot`? I don't see it in the docs or the source? It would be really handy with something like that, as jsdom will currently look at the root of the file system if an image has a root-relative url, eg. `<img src="/image.png">`.

**Comment by warhammercasey** [comment]
Thanks that works.
I read about `documentRoot` from [here.](https://github.com/jsdom/jsdom/issues/99)

**Comment by papandreou** [comment]
Ah, looks like it was removed more than 4 years ago in 69aca727670adcc43bd76a02af1660c15496d757
