### ISSUE TITLE
TypeError: Cannot redefine property: assign

### ISSUE THREAD

**Issue by mrchief** [jsdom/jsdom#2674]
### Basic info:

- **Node.js version:** 10.16
- **jsdom version:** 15.1.1

### Minimal reproduction case

```js
const jsdom = new JSDOM('<!doctype html><html><body></body></html>');
const { window } = jsdom;

global.window = window;
global.document = window.document;
global.navigator = {
  userAgent: 'node.js',
};
global.requestAnimationFrame = function (callback) {
  return setTimeout(callback, 0);
};
global.cancelAnimationFrame = function (id) {
  clearTimeout(id);
};

sinon.spy(window.location, 'assign');
// ...test
expect(window.location.assign.calledWith(uri)).to.equal(true);
```

I get `TypeError: Cannot redefine property: assign`. The immutability of objects in JSDOM 15 is the root cause here. I'm sure there are good reasons behind it but I'd like to know the recommended way to spy on `window.location.assign`.

**Comment by domenic** [comment]
You omitted a key part of the template, which is how similar code behaves in browsers.

**Comment by mrchief** [comment]
But this is a test utility, it should allow you to spy on methods. Isn't it?

**Comment by mrchief** [comment]
For now, this works with v14, and I think it'll fail in v15

```
    const { location } = window;

    before(() => {
      delete window.location;
      window.location = { assign: sinon.spy() };
    });

    afterEach(() => {
      window.location.assign.resetHistory();
    });

    after(() => {
      window.location = location;
    });
```

**Comment by domenic** [comment]
No; jsdom is a browser emulator. Sinon is a testing framework.


I'll close this as the template was improperly filled out and it appears there is no big with jsdom.
