### ISSUE TITLE
upgrading to saxes 4.0.0

### ISSUE THREAD

**Issue by lddubeau** [jsdom/jsdom#2677]
I've just released version 4.0.0-rc1 of saxes. I can submit a PR but there are a few things that require discussion due to breaking changes. Staying on the 3.x version is not really an option in the long term. There are bugs with end-of-line (EOL) handling in all versions prior to 4.0.0-rc1 that have been fixed in 4.0.0-rc1. It is likely that most people never saw those bugs because most folks have files that use ``\n`` as the EOL character.

The new release has a few breaking changes:

1. There's a remote possibility that someone came to rely on the old incorrect way saxes handled EOL characters other than ``\n``. Unfortunately, the upgrade will be a breaking change *for them*. Tough luck though because the old behavior was just flat out incorrect. It went against the XML specification and was inconsistent with how Firefox and Chrome behave.

2. In previous versions of saxes, when the configuration option ``fileName`` was left unset, then saxes would report errors like ``undefined:1:13: foo`` because the JavaScript value of the option would be ``undefined`` and JavaScript would convert it to a string. I knew this, and was fine with it, but someone filed a bug report and I agreed that it should be changed so that if there's no ``fileName`` specified, the error is reported without a file name ``1:13: foo``.

   I can easily modify jsdom to preserve the old behavior by setting ``fileName`` to the string ``"undefined"`` in those cases where there's no other available file name to pass. I don't know whether this is the desired solution.

3. saxes 4.0.0 adds support for XML 1.1, but last time I checked the whatwg specs there was no mention of XML 1.1, and in practice both Firefox and Chrome support only XML 1.0. However, Firefox and Chrome behave differently when passed a document with an XML declaration that specify version 1.1:

   * Chrome just ignores the version number in the XML declaration. So a document which declares itself to be XML 1.1 but is otherwise well-formed as an XML 1.0 document will parse without error.

   * Firefox generates a parsing error. So a document which declares itself to be XML 1.1 will not parse without error, even if it would otherwise be well-formed XML 1.0.

   There is a note in the XML specification 1.0 edition 5 under the [`XMLDecl` production](https://www.w3.org/TR/xml/#NT-XMLDecl) that says:

   > When an XML 1.0 processor encounters a document that specifies a 1.x version number other than '1.0', it will process it as a 1.0 document. This means that an XML 1.0 processor will accept 1.x documents provided they do not use any non-1.0 features.

   This is what Chrome does. Unfortunately, the authors of the specification did not use any of the consecrated words MUST, MUST NOT, etc. They say "will" and the word is unemphasized. (I find no equivalent note in the XML 1.1 specification.)

   At any rate, saxes can be used to follow either behavior. Following what Chrome does would be consistent with how jsdom has used saxes in the past. Still, if it turns out that's undesirable, now is the time to argue for a change.

**Comment by TimothyGu** [comment]
Thanks for your work! The progress is great to hear.

1. That's fine. It would really only be fixing a bug as far as jsdom is concerned, and we have made changes in the past that could theoretically be seen as breaking but are in fact bug-fixing, with only a patch bump.

2. The new behavior sounds fine without an extra `|| "undefined"`, though this might indeed warrant a major bump on jsdom's side.

3. Going with the Chrome behavior sounds good to me. The spec note sounds like it's meant to be informative rather than normative, but the fact that the XML 1.0 spec explicitly allows non-1.0 versions is indication enough that the informative note is correct.

   I think enabling XML 1.1 features by default is a bit risky for us considering no browser supports them, so as long as we can disable them it should be fine.

**Comment by lddubeau** [comment]
Thanks you for the reply. Yes, the plan is to force saxes to run in XML 1.0 mode *irrespective* of what the document declares. 4.0.0 adds two new flags: `defaultXMLVersion` and `forceXMLVersion`. Setting `defaultXMLVersion: "1.0", forceXMLVersion: true` gives the desired behavior.

I found some areas where performance could be improved, so I have an `rc.2` out now. I'm going to be unreachable for a few days so it may take another week before I can start testing jsdom with saxes 4.0.0-rc.X.
