### ISSUE TITLE
Read global var from the html

### ISSUE THREAD

**Issue by amihanya** [jsdom/jsdom#2679]
i have a html file that includ:
`<script>var createjs, AdobeAn;</script>`
after i run the jsdom i try to get the **AdobeAn** value but that return undefined

```
  const dom = new JSDOM(html);
  console.log("AdobeAn",dom.window.AdobeAn );
```

link to the files that i try to load:
main file:
http://rbes.co.il/banners/YeiZadik/zadik200919_970x250.html
is load that file:
http://rbes.co.il/banners/YeiZadik/zadik200919_970x250.js

and after the js file load **AdobeAn** created and dont equle undefined.

**Comment by Sebmaster** [comment]
See the [executing scripts](https://github.com/jsdom/jsdom#executing-scripts) section in the readme.
