### ISSUE TITLE
make it possible to get the full html from the window.document object?

### ISSUE THREAD

**Issue by Morriz** [jsdom/jsdom#268]
That is the last missing functionality I need to render full pages server side with jquery.

I can get this far (snippet):

```
    var templateHtml = templateHtml, // read from file
        doc = $(templateHtml);

    var html = doc[1].outerHTML;
```

But that only renders the 'html' node from the doc, leaving out all the other nodes. I especially need to have the script nodes rendered to html. But if possible, the entire structure.

I hope that this functionality is already in there. And if it isn't, I hope you have an idea as to get it in there.

Thanks for all the good work!

chek,

Maurice

**Comment by josephrocca** [comment]
Heads up to people arriving here via search engines, the API has changed to `dom.serialize()` as of writing: https://github.com/jsdom/jsdom#serializing-the-document-with-serialize
