### ISSUE TITLE
Update request-promise-native and request-promise-core to refer latest version of lodash

### ISSUE THREAD

**Issue by anushreemjoshi** [jsdom/jsdom#2684]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

jsdom package requires > request-promise-native >request-promise-core > lodash.

It has been seen that request-promise-core hasn't been updated for a while to require latest version of lodash. Versions of ldash less than 4.17.12 has security vulnerability for Prototype pollution. 

Please update request-promise-core to refer to latest version of lodash and update the same in request-promise-native.  

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by domenic** [comment]
We don't control request-promise-core and request-promise-native, so this appears to be filed on the wrong repository.
