### ISSUE TITLE
How to easily find what is supported?

### ISSUE THREAD

**Issue by goldingdamien** [jsdom/jsdom#2695]
I am testing jsdom-global to run a few window and document functions such as DOMRect and MediaStream but am getting a few errors. These errors may have nothing to do with jsdom, but I would like to be able to check if they are supported for debugging purposes. Is there some easy way(Wiki, table, grouped interface file, etc.) of checking functionality support?

**Comment by domenic** [comment]
You can use the same methods you'd use in a browser: test if window.X exists.

**Comment by goldingdamien** [comment]
I was more thinking of documentation.

**Comment by domenic** [comment]
Nope, like browsers, we just add features as we go.
