### ISSUE TITLE
how can I set special heasers by using jsdom.JSDOM.fromURL

### ISSUE THREAD

**Issue by einherjarcai** [jsdom/jsdom#2699]
### Basic info:

- **Node.js version:** v10.16.2
- **jsdom version:**  15.2.0

### Minimal reproduction case

```js
const resourceLoader = new jsdom.ResourceLoader({
    proxy: "http://XXXX:xxx",
    strictSSL: false,
  });
  let options = {
    runScripts: 'dangerously',
    cookieJar: cookieJar,
    resources: resourceLoader,
   //  I wanna set proxy headers in here,

  };
 let dom = await jsdom.JSDOM.fromURL(index_url, options);
  dom.window.close();
```
I wan to set my  proxy headers, such as {"proxy-authorization": ""},  I set it in "options" and "resourceLoader", but didn't work.

**Comment by Sebmaster** [comment]
You'll need to implement a custom ResourceLoader to set custom headers like that. See the [subclassing section](https://github.com/jsdom/jsdom#advanced-configuration) in the readme.

**Comment by walirt** [comment]
> You'll need to implement a custom ResourceLoader to set custom headers like that. See the [subclassing section](https://github.com/jsdom/jsdom#advanced-configuration) in the readme.

https://github.com/jsdom/jsdom/blob/4f5fbc6034857f9101b346173cc484ede4545245/lib/jsdom/browser/resources/resource-loader.js#L72-L126
I looked at the source code of ResourceLoader and found that it could not set headers
