### ISSUE TITLE
Support for focusin/focusout

### ISSUE THREAD

**Issue by Shadowlauch** [jsdom/jsdom#2708]
Currently when you focus an element in jsdom it dispatches 'blur' and 'focus' events but it does not dispatch 'focusin' & 'focusout' events. It would be great to have those events in jsdom.

https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event

**Comment by eps1lon** [comment]
@domenic Seems like we can close this issue after #2996 has been merged.
