### ISSUE TITLE
Event handler inside a .js file not firing when sending a click event

### ISSUE THREAD

**Issue by denikov** [jsdom/jsdom#2710]
### Basic info:

- **Node.js version:**  10.15.3
- **jsdom version:**  15.2.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const path = require("path");
const fs = require("fs");

const options = {
  url: 'file://' + path.join(process.cwd(), '/src/test/'),
  resources: 'usable',
  runScripts: 'dangerously'
};
const html = fs.readFileSync(path.join(process.cwd(), '/src/test/test.html'), 'utf-8');
const dom = new JSDOM(html, options);

dom.window.document.addEventListener('DOMContentLoaded', () => {
  const window = dom.window;
  const document = window.document;

  console.log(document.querySelector('#message').textContent); 
  //output -> 'hello world'
  console.log(document.querySelector('#test-button').textContent); 
  //output -> 'Click Me'
  document.querySelector('#test-button').click(); //does not work   
  
  /*var evt = document.createEvent("HTMLEvents");
  evt.initEvent("click", false, true);
  document.querySelector('#test-button').dispatchEvent(evt);*/ 
  //also does not work
  
setTimeout(() => {
    console.log(document.querySelector('#test-button').textContent; 
    //output -> 'foo' so the script loads and runs correctly
    console.log(document.querySelector('#message').textContent); 
    //output -> 'hello world';  expected output to be -> 'changed'
  }, 3000);
});
```

```html
<!DOCTYPE html>
  <head>
  </head>
  <body>
    <p id="message">hello world</p>
    <button id="test-button">Click Me</button>
    <script src="test.js"></script>
  </body>
</html>
```

```js
const App = {
  handleClick: (event) => {
    document.getElementById('message').textContent = 'changed';
  },
  init: function() {
    document.getElementById('test-button').textContent = 'foo';
    document.getElementById('test-button').addEventListener('click', this.handleClick);
  }
};

document.addEventListener('DOMContentLoaded', () => {
  App.init();
})
```

After 3 days of trying many different things I couldn't get it to work.  In a browser everything works correctly.  Adding an `onclick` inline on the button works but event handler does not work from an external script.  I read that jsdom can be used for scrapping so I imagine sending clicks should be possible.  I'm just trying to get familiar with it so I can use it in a testing environment.  Any suggestions please?  Each Google result related to jsdom is highlighted pink so I'm out of ideas...

**Comment by pmdartus** [comment]
I was able to reproduce your issue locally. There is a scheduling issue because the `DOMContentLoaded` event handler you attach in entry file is triggered before the `DOMContentLoaded` event handler you attach in `test.js`. Because of this, the `click` event is triggered before the `click` event handler is attached to the button.

I would recommend converting your `DOMContentLoaded` event handler to a `load` event handler.

```js
const { document } = dom.window; 
document.addEventListener('load', () => {
  document.querySelector('#test-button').click();
});
```

**Comment by denikov** [comment]
@pmdartus Besides some of the typos in my original question, your suggestion works now!  Thanks so much for clearing things up!
