### ISSUE TITLE
Click events blow up call stack in nested <label>s

### ISSUE THREAD

**Issue by babramczyk** [jsdom/jsdom#2717]
### Basic info:

- **Node.js version:** 8.16.0
- **jsdom version:** 15.1.1

### Description

When clicking an `<option>` in a `<select>`, there is a scenario where the click events are recursive, and never stop. It seems to stem from clicking the "associated" label element.

Here's the callstack frozen at a certain point:

![image](https://user-images.githubusercontent.com/16885191/69250048-94df5e80-0b74-11ea-93dd-8448656946a6.png)

Here is what the markup looks like:

```html
<div>
  <label for="gender-0">
    <span>Gender</span><span></span>
  </label>
  <div>
    <label>
      <select id="gender-0">
        <option value="">Select one</option>
        <option value="M">Male</option>
        <option value="F">Female</option>
        <option value="U">Unknown</option>
      </select>
    </label>
    </div>
</div>
```

**Edit:**

I realize the weird nature of having two `<label>` elements associated with the `<select>` (this is an effect of a component library I'm consuming). When I remove the second `<label>` from the example above, this problem goes away.

My question is at this point: Is this still a bug with `jsdom`, or is this invalid HTML? Even if it is the latter, maybe a better warning could be output in this scenario, and short-circuit to avoid the call stack problem.

**Comment by domenic** [comment]
Can you please follow the issue template, and include minimal reproduction code with no third party libraries?

**Comment by babramczyk** [comment]
Unfortunately, the way `jsdom` is being consumed to fire the event is through a third-party library `@testing-library/dom`, so I have no context on how they're firing that, and how I would reproduce it in a minimal way.

All I know is that when you have two `<label>`s associated with a `<select>` and you fire click events on the `<select>`, you get a max call stack error. Don't really have time to research a minimal use case beyond that 😞 Understand if maintainers don't either -- just wanted to call out this bug and you all can do what you want with it.

**Comment by TimothyGu** [comment]
The spec for `label` elements say:

> The activation behavior of a `label` element for events targeted at interactive content descendants of a `label` element, and any descendants of those interactive content descendants, must be to do nothing.

This seems to come into play here, but unfortunately it doesn’t seem to be implemented yet.

**Comment by babramczyk** [comment]
Here's a minimal reproduction case. Forgive my codesandbox shortcomings, you'll have to open the console and run `yarn jest --watchAll` to see the test fail.

https://codesandbox.io/s/wonderful-night-vjfpr?expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark

@domenic

**Comment by joeljeske** [comment]
I am having this same issue, but it happens to be with a <textarea> and the associated <label> instead of a <select>.

**Comment by domenic** [comment]
Sorry, a minimal reproduction case specifically involves no third party libraries like jest.

**Comment by babramczyk** [comment]
@domenic Updated the above codesandbox to remove Jest.

**Comment by bogem** [comment]
The same issue after upgrading jest to version from 24.9.0 to 25.2.0
