### ISSUE TITLE
document.activeElement not working in 15.2.1

### ISSUE THREAD

**Issue by Machiaweliczny** [jsdom/jsdom#2723]
### Basic info:

- **Node.js version: 10.15.3** 
- **jsdom version: 15.2.1** 

### Minimal reproduction case

    const { JSDOM } = require('jsdom');

    const dom = new JSDOM();
    const div = dom.window.document.createElement('div');
    div.tabIndex = 1;
    div.focus();
    console.log(
      'dom.window.document.activeElement',
      dom.window.document.activeElement
    );
    console.log(dom.window.document.activeElement === div); // should be true, is false in 15.2.1

This works fine in `15.1.1`

**Comment by Sebmaster** [comment]
We're behaving like browsers on this one now: https://jsbin.com/manuhox/edit?js,console

Therefore don't believe this is a bug in jsdom.

**Comment by milesj** [comment]
For people stumbling on this issue, there's a note on MDN about this.

> Behaviour of the focus in relation to different HTML features like tabindex or shadow dom, which previously remained under-specified, were recently updated (as October of 2019). Checkout WHATWG blog for more info.

https://blog.whatwg.org/focusing-on-focus

**Comment by sanchit-kialo** [comment]
> We're behaving like browsers on this one now: https://jsbin.com/manuhox/edit?js,console
> 
> Therefore don't believe this is a bug in jsdom.

I think there might be a bug in that jsbin, or a bug in jsbin itself.

Here is a JSFiddle: https://jsfiddle.net/8eLbwt24/

This JSFiddle demonstrates how calling `focus` on an element that is actually attached to the body *does* set `document.activeElement`.
This works in both Firefox and Chrome.

I also tested this code by running it directly in the Firefox console.

After noticing this behaviour, I think that JSDom should infact be setting `document.acticeElement` on programmatic focus, at least if the element is attached to the body of the document.

**Comment by jamime** [comment]
For anyone else that comes across this `15.1.1` would allow you to focus an element that was not attached to the body.

In the browser, the element must be attached to the body for  programatic focus to work.
```js
const div = document.createElement("div");
div.tabIndex = 1;

div.focus();

console.log(document.activeElement); // body

document.body.appendChild(div);

div.focus();

console.log(document.activeElement); // div
```

So for `15.2.0` and above the following works

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM();
const div = dom.window.document.createElement("div");
div.tabIndex = 1;

dom.window.document.body.appendChild(div);

div.focus();

console.log(
  "dom.window.document.activeElement",
  dom.window.document.activeElement
);
console.log(dom.window.document.activeElement === div);
```
