### ISSUE TITLE
Error `window` is not defined in a web worker context

### ISSUE THREAD

**Issue by willdurand** [jsdom/jsdom#2726]
Hi, we want to run `jsdom` in a "web worker context" as mentioned [here](https://github.com/jsdom/jsdom#running-jsdom-inside-a-web-browser) but there is an error because `window` is `undefined`.

### Basic info:

- **Node.js version:** `n/a`
- **jsdom version:** `master`

### Minimal reproduction case

Compile `jsdom` with `browserify`:

```
$ browserify lib/api.js -r -o jsdom.bundle.js
```

Then, using the [Spidermonkey JS shell](https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/) (which is an environment like a web worker), try to execute this generated bundle.

This leads to the following output:

```
$ js -f jsdom.bundle.js

jsdom.bundle.js:103903:18 ReferenceError: window is not defined
Stack:
  [560]<@jsdom.bundle.js:103903:18
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [698]</<@jsdom.bundle.js:148378:23
  [698]<@jsdom.bundle.js:149916:4
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [679]<@jsdom.bundle.js:145271:19
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [400]</<@jsdom.bundle.js:67365:24
  [400]<@jsdom.bundle.js:67786:4
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [405]</<@jsdom.bundle.js:68001:25
  [405]<@jsdom.bundle.js:69091:4
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [2]</<@jsdom.bundle.js:356:37
  [2]<@jsdom.bundle.js:1015:4
  o@jsdom.bundle.js:1:265
  o/<@jsdom.bundle.js:1:316
  [1]</<@jsdom.bundle.js:15:23
  [1]<@jsdom.bundle.js:338:4
  o@jsdom.bundle.js:1:265
  r@jsdom.bundle.js:1:432
  @jsdom.bundle.js:1:460
```

Our temporary "fix" is to replace `window.FormData` with `this.FormData` in the generated bundle.

Note: compiling with `webpack` produces the same error, hence potentially a problem in `jsdom` itself and not with the bundling process.

**Comment by domenic** [comment]
We don't support (or have the ability to test) the SpiderMonkey JS shell, so I'm not sure what we can do here. We support running in a web worker, which is tested in our continuous integration.

**Comment by Zirro** [comment]
The issue looks like it's related to the `form-data` dependency (see https://github.com/form-data/form-data/pull/267 - which was later modified and possibly regressed again in https://github.com/form-data/form-data/commit/c99e4ec32cd14d83776f2bdcc5a4e7384131c1b1) rather than something specific to the SpiderMonkey-environment. I see it while running the bundle in Node.js as well.

It's not clear to me if there is a combination of Browserify CLI flags (`--bare`/`--node` seem to reveal other issues) that can be used to work around it, or if `form-data` has to be fixed again. Let's reopen this until we have a trouble-free way of bundling jsdom for these environments.

**Comment by domenic** [comment]
Hmm, why was this not caught by our web worker CI, I wonder?

**Comment by Zirro** [comment]
Web Workers have the `self` global, while Node.js (and presumably also the SpiderMonkey JS shell) does not. That's problematic for this condition: https://github.com/form-data/form-data/blob/master/lib/browser.js

**Comment by domenic** [comment]
I see. In that case I think things are working as intended. Since Node.js/etc. are not supported configurations (e.g. not run on CI), then as you'd expect some dependencies might break in them.

**Comment by cagross** [comment]
I'm experiencing a similar issue, although I'm not using SpiderMonkey.  I'm using Git Bash for Windows.  Are you able to reproduce this on your end?

In my case, the steps to reproduce are:

### Compile jsdom with browserify

$ node_modules/.bin/browserify test.pageContent.js --o test-bundle.js

### In Git Bash for Windows, execute this generated bundle.

This leads to the following output:

```
$ node test-bundle.js

C:\Users\snarl\development\project\test-bundle.js:59075
module.exports = typeof self == 'object' ? self.FormData : window.FormData;
                                                        ^
ReferenceError: window is not defined
    at Object.263 (C:\Users\snarl\development\project\test-bundle.js:59075:60)
    at o (C:\Users\snarl\development\project\test-bundle.js:1:265)
    at C:\Users\snarl\development\project\test-bundle.js:1:316
    at Object.<anonymous> (C:\Users\snarl\development\project\test-bundle.js:207832:16)
    at Object.1074../lib/auth (C:\Users\snarl\development\project\test-bundle.js:209372:4)
    at o (C:\Users\snarl\development\project\test-bundle.js:1:265)
    at C:\Users\snarl\development\project\test-bundle.js:1:316
    at Object.1050../lib/cookies (C:\Users\snarl\development\project\test-bundle.js:205843:19)
    at o (C:\Users\snarl\development\project\test-bundle.js:1:265)
    at C:\Users\snarl\development\project\test-bundle.js:1:316
```
___
Installed Packages

* jsdom v16.5.3
* browserify v16.5.1

**Comment by domenic** [comment]
Yep, browserify is for producing browser bundles, not Node bundles, so that's as expected.

**Comment by cagross** [comment]
OK thanks for that--makes sense.

So how would you suggest I resolve my issue?  From OPs info, it seems like replacing Browserify with webpack will suffer from the same issue.  I might be able to convert all my ES6 module calls to CommonJS format--that might allow me to eschew Browserify during my unit tests.  But off the top of your head, do you know of any other options that might work?

**Comment by domenic** [comment]
I'd suggest using jsdom as it's intended to be used, as a CommonJS module. A CommonJS module in Node, or a browserify bundle in web browsers, are the two supported configurations. For anything else, you're on your own.

**Comment by hzmnet** [comment]
so how to boundle to  A CommonJS module in Node
