### ISSUE TITLE
Add Node 12 environment to TravisCI

### ISSUE THREAD

**Issue by pmdartus** [jsdom/jsdom#2730]
Currently the TravisCI tests against the [following versions](https://github.com/jsdom/jsdom/blob/master/.travis.yml#L2-L5) of Node: `8`, `10` and `latest` (currently `13.2.0`). We should also add `12` to the test matrix since it went LTS on Oct. 21 2019 ([release schedule](https://nodejs.org/en/about/releases/)).

We should also consider bumping the `node-canvas` test suite [version of Node](https://github.com/jsdom/jsdom/blob/master/.travis.yml#L23) at the same time. It currently runs on Node `8`, which will sunset at the end of 2019.

**Comment by domenic** [comment]
Agreed. I'm unsure how big we want the matrix to get considering canvas, but perhaps for canvas, oldest-support and latest would be good?
