### ISSUE TITLE
JSdom window (page) object accessibility

### ISSUE THREAD

**Issue by spamator12** [jsdom/jsdom#2738]
jsdom 11.3.0
node 10.16.0

I can acces the document object inside jsdom enviroment, but "outside" it is not working...
																		jsdom.env(
{
	features: {
	FetchExternalResources : ['script'],
	ProcessExternalResources : ['script'],
	SkipExternalResources: false
	html: googleBody,
																				done: function(err, window)
	{
		if (err) {console.log(err);}
		else
		{
			var doc = window.document;
			// for example lets... check if html got a specific selector:
			var selector = '.google';
			var test = doc.querySelector(selector);
			// I CAN access doc here, everything works fine <--
			f1(doc); // BUT
		}

	}
});

function f1(doc)
{
	var selector2 = '.google';
	var test2 = doc.querySelector(selector);
	// test is NOT accessible here <-- (!)
	// do I need to pass something more then document object??
}

**Comment by domenic** [comment]
jsdom v11 is not supported anymore; sorry!

**Comment by spamator12** [comment]
ok, thanks for input. I have installed new version - same problem.

**Comment by domenic** [comment]
Can you post the sample code using the latest version?

**Comment by spamator12** [comment]
It's the same as above but for newer version of jsdom. Ofcourse it's a big simplify - cause there is 20 thousands lines of code with many async operations. In my opinion it should work just like the above, DOC should be available when pass to functions - BUT maybe I do something wrong/or don't know about how jsdom is working - or my code is just messing something around I'm not notice, cause in a main flow of JSdom it's working fine, but when I pass it (doc variable with document DOMs) it's not...

On newer jsdom version there are some errors, but seems code is executing properly.

**Comment by domenic** [comment]
Sorry ,we can't debug issues without a sample file that we can run to reproduce them ourselves.

**Comment by spamator12** [comment]
Got it, gonna do more tests and I will get back here with some answers I hope.

**Comment by spamator12** [comment]
Got some time, and I think I got it - I had async task, and it seems it run AFTER the **window.close();** so the HTML code that was saved could not be mutated, by for example **.querySelector** - cause it has no DOM three. ONLY when JSDOM memory has HTML of the target page you can use DOM things on it, otherwise it just pure HTML without any functionality.
Domenic you can thrash this, or if you think that it will help some users, leave it or update the doc. Thanks.

**Comment by termitek12** [comment]
Hi you are right, here is the code that (I hope) explains that:

`    var url = "https://www.google.com";
    var requestData = request({url : url, headers : {'User-Agent' : 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0'}}, function(err, resp, HTMLdata) {
      if (!err && resp.statusCode === 200) {
        jsdom.env({
          html: HTMLdata,
          features: {
            FetchExternalResources : ['script'],
            ProcessExternalResources : ['script'],
            SkipExternalResources: false
          },
          done: function (err, targetWindow) {
            if (err)
            {
              console.log('ERR: ' + err);
            }
            else
            {
              var targetDoc = targetWindow.document;
              var pageText = targetDoc.documentElement.textContent;

              setTimeout(function() // for async behavior
              {
                var selector = '#main';
                selector = selector.trim();
                var test = targetDoc.querySelector(selector);
                console.log(test.innerHTML); // #main content does not exist - data expired (cleaned from memory)
              }, 4000);

                var selector = '#main';
                selector = selector.trim();
                var test = targetDoc.querySelector(selector);
                console.log(test.innerHTML); // #main content

              targetWindow.close(); // you empty all jsdom memory here so when setTimout is resolved it has no access to jsdom DOM data
            }
          }
        });// jddom.env
      }
    }); // request`

**Comment by spamator12** [comment]
Yes, this is exactly the problem, I have many async functions and it seems that I need to pass html data (with DOM) to be operable later on. @domenic is there something more I can do? Is this possible to .close() jsdom after the async functions are finished?
