### ISSUE TITLE
Cache fetch response of resource using CustomResourceLoader cause Memory leak

### ISSUE THREAD

**Issue by CJY0208** [jsdom/jsdom#2741]
Hi! 

I'm working on server-side rendering using jsdom, and I am trying to cache fetch response of static resource for speeding up rendering.  My approach may be wrong, which caused a memory leak. 

Using `resources: 'usable'` is OK

Any idea? Thanks!

### Basic info:

- **Node.js version:** 11.10.1
- **jsdom version:** 15.2.1

### Minimal reproduction case

```js
const resourceCache = {}
class CustomResourceLoader extends jsdom.ResourceLoader {
  fetch(url, options) {
    if (resourceCache[url]) {
      return resourceCache[url] // use cache of response
    }

    const promise = super.fetch(url, options)

    resourceCache[url] = promise // cache fetch response
    return promise
  }
}

const customResourceLoader = new CustomResourceLoader()

module.exports = function render(url) {
  return new Promise((resolve, reject) => {
    JSDOM.fromURL(url, {
      pretendToBeVisual: true,
      runScripts: 'dangerously',
      resources: customResourceLoader // using 'usable' without Memory Leak
    })
      .then(dom => dom.serialize())
      .then(resolve)
      .catch(reject)
  })
}
```

### How does similar code behave in browsers?

(Link to a jsbin or similar suggested.)

**Comment by Sebmaster** [comment]
If you don't clean your resourceCache of course you have a memory "leak". You're holding onto all of those responses.

**Comment by domenic** [comment]
I mean, this isn't a memory leak. Your program is using exactly as much memory as you told it too: it's keeping a cached copy of every response in the cache, and never releasing that memory.

Closing since this isn't jsdom related.

**Comment by CJY0208** [comment]
In My test code, only a controlled number of caches are holded with `resourceCache` and I also think this should not cause a memory leak

**Comment by Sebmaster** [comment]
> In My test code, only a controlled number of caches are holded with resourceCache and I also think this should not cause a memory leak

Then you need to provide us with a sample that actually shows the leak.

**Comment by CJY0208** [comment]
I found the reason in the process of making the example, indeed it was not caused by the resource loader, but because the `window.close` method was called prematurely

```js
const render = async url => {
  const dom = await JSDOM.fromURL(url, {
    pretendToBeVisual: true,
    runScripts: 'dangerously',
    resources: customResourceLoader
  })

  return new Promise(resolve => {
    const { window } = dom

    const html = dom.serialize()

    resolve(html)

    function shutdown() {
      window.close()
      if (typeof global.gc === 'function') {
        global.gc()
      }
    }

    // // shutdown after readyState turn to 'complete', no Memory leak
    // window.addEventListener('readystatechange', () => {
    //   if (document.readyState === 'complete') {
    //     shutdown()
    //   }
    // })

    // shutdown immediately cause Memory leak
    shutdown()
  })
}
```

**Comment by CJY0208** [comment]
Here is the gif while no memory leak

![no-leak](https://user-images.githubusercontent.com/18415774/70371520-ed518280-190e-11ea-850e-329f6080583c.gif)

And here is the problem gif

![leak](https://user-images.githubusercontent.com/18415774/70371536-1e31b780-190f-11ea-9d49-46243d41fcc0.gif)

**Comment by CJY0208** [comment]
Demo  is here

https://github.com/CJY0208/jsdom-memory-leak-demo

**Comment by CJY0208** [comment]
In this demo, `resourceCache` would only hold 3 resource and would never hold more

![no-more-resource](https://user-images.githubusercontent.com/18415774/70371724-d06a7e80-1911-11ea-8d0a-3536e1862db4.gif)

**Comment by Sebmaster** [comment]
Ah, that indeed sounds like there could be something there. Could you open a new issue with your new repro so can better keep track of this?

**Comment by CJY0208** [comment]
Sure, new issue here #2742
