### ISSUE TITLE
Overriding requestAnimationFrame FPS?

### ISSUE THREAD

**Issue by stephenash** [jsdom/jsdom#2748]
### Basic info:

- **Node.js version:** 12.13.1
- **jsdom version:** 15.2.1

### Minimal reproduction case
I'm working on a tool that uses an animation library (PixiJS) with JSDOM to animate the contents of a `canvas` element. Everything is working well on that front, but in profiling the node process, I'm seeing a lot of idle time between rendered frames.

![Screen Shot 2019-12-12 at 16 08 06](https://user-images.githubusercontent.com/573423/70758990-9c200500-1cf9-11ea-86e4-148e7b1f880d.png)

Each of those grey `(program)` boxes is idle time where `window.requestAnimationFrame` was called and the program waits for the `const fps = 1000 / 60;` timeout to be reached. Since JSDOM is not actually painting anything to the screen, the program is able to process frames much faster than 60 FPS.

Is there a way to override the hardcoded FPS limit for JSDOM? So far I've come up with this workaround, but there is enough other logic in the existing requestAnimationFrame implementation that this seems too heavy handed.

```js
const { JSDOM } = require("jsdom");

const options = {
  beforeParse: (window) => {
    window.requestAnimationFrame = (callback) => {
      return window.setTimeout(callback, 0);
    };
  },
  pretendToBeVisual: true,
  resources: 'usable',
};
const dom = new JSDOM(``, options);
```

### How does similar code behave in browsers?

Browser, OS, hardware use their own max FPS calculation.

**Comment by domenic** [comment]
Your code makes sense to me. It matches how you would override requestAnimationFrame in browsers, assuming you didn't care about the second argument to the callback. Is there something in particular that isn't working with it?

**Comment by stephenash** [comment]
I haven't noticed anything wrong with my workaround yet, but it does not integrate with the existing JSDOM code like `window.__stopAllTimers` (called from window.close()). Looking more to customize the FPS/timeout value, not override the entire function.

**Comment by domenic** [comment]
Well, jsdom is meant to behave like a browser, and in browsers the only way to change the behavior of the requestAnimationFrame is how you've done, so your approach makes sense to me.

**Comment by stephenash** [comment]
Sounds good. Thanks for the guidance.
