### ISSUE TITLE
EventTarget-impl.js doesn't handle case when 'wrapper' is 'undefined'

### ISSUE THREAD

**Issue by ChoroDev** [jsdom/jsdom#2749]
### Basic info:

- **Node.js version: v12.13.1** 
- **jsdom version: 15.2.1** 

### Minimal reproduction case
I'm trying to use document.getElementById('filter').onkeyup while 'filter' element doesn't exist. Getting an error outside tests:
![image](https://user-images.githubusercontent.com/29352750/70792725-e7462080-1daa-11ea-8566-db4a5dbc2f97.png)
Possible error: EventTarget-impl.js does not handle case when 'wrapper' is 'undefined':
![Untitled](https://user-images.githubusercontent.com/29352750/70792863-30967000-1dab-11ea-8b8b-2ecabc01e3de.png)
Tried to change code to:
![image](https://user-images.githubusercontent.com/29352750/70793362-304aa480-1dac-11ea-83ba-2c73dcf256d3.png)
Worked for me. Path to script:
jsdom/lib/jsdom/living/events/EventTarget-impl.js

### How to reproduce:
```js
const { JSDOM } = require('jsdom')
const jsdom = new JSDOM('<!DOCTYPE html><html><head></head><body>Test DOM</body></html>')
global.window = jsdom.window
global.document = jsdom.window.document
global.window.addEventListener('load', () => {
  global.document.getElementById('filter').onkeyup = console.log('Hello')
})
```

### How does similar code behave in browsers?
Didn't investigate

**Comment by domenic** [comment]
See https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by domenic** [comment]
> Didn't investigate

If you try similar code in browsers you'll find it says something like "TypeError cannot set property onkeyup of null". Do not omit important sections of the issue template.
