### ISSUE TITLE
Building jsdom SSR in AWS Lambda 

### ISSUE THREAD

**Issue by jamesw201** [jsdom/jsdom#2754]
There are two issues which try to work this out but no one has gotten very far yet ([1433](https://github.com/jsdom/jsdom/issues/1433), [1569](https://github.com/jsdom/jsdom/issues/1569)).

I appreciate that this may not be a primary concern for the support of this library but I think it would be useful to a lot of people if it can be understood, so I'm going to share my efforts in the hope that someone else can help me with what's left.

My intention is to use jsdom and d3 with react and next.js to create a server side rendered diagram in AWS Lambda.

I tried building jsdom using the AWS Lambda ami in docker using this:
```
FROM lambci/lambda:build-nodejs8.10

WORKDIR /home/app/

COPY /app/package.json /home/app

RUN npm install .

RUN zip -9yr /lambda.zip .
```
the package.json contains this dependency section:
```
"dependencies": {
    "jsdom": "^15.2.1"
}
```

and these commands to get the zip file out of the container: 
```
docker build -t docker-lambda .

docker create -ti --name my-container docker-lambda bash

docker cp my-container:/lambda.zip .
```
I then copied the node_modules contents over the node_modules contents of my Lambda so that they pushed in the next deploy. I'm using ```apex deploy``` although ```serverless deploy``` should be just the same.

Unfortunately when running the code which is just a simple example:
```
const jsdom = require('jsdom')
const { JSDOM } = jsdom

const dom = new JSDOM('<!DOCTYPE html><p>Hello world</p>')
const content = dom.window.document.querySelector('p').textContent
console.log(content)
```

I see the following error:
```
Unable to import module 'lib/index': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:4:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

If anyone could help identify what jsdom requires to run in the node8.10 or node10 environments it would be much appreciated.

**Comment by TimothyGu** [comment]
As shown in https://github.com/jsdom/jsdom/blob/97411a7fbeaac518355626b9a87b6e8964f3e92c/package.json#L116 we current support Node.js v8.x+. We can't really help with the specific issue with AWS Lambda that you described (which looks quite different from both #1569 and #1433), as jsdom works quite well on Node.js v8.x as far as I can tell.

Curiously, your stack trace seems to show that `lib/jsdom/living/helpers/selectors.js` is calling `require()` on line 4 with `lib/index`; which is not the case: https://github.com/jsdom/jsdom/blob/c3f0f2756bdbb20e235473728b562e04a67a6555/lib/jsdom/living/helpers/selectors.js#L4 I'd perhaps look into this a bit more.
