### ISSUE TITLE
document.documentElement.remove() behaviour in jsdom differs from browser behavior

### ISSUE THREAD

**Issue by Jakhotiya** [jsdom/jsdom#2755]
### Basic info:

- **Node.js v12.13:** 
- **jsdom 15.2.1** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

let dom = new JSDOM('',{contentType:'text/html'});
   document.documentElement.remove();
    document.documentElement = null;
    console.log(document.documentElement); //OUTPUT :HTMLHtmlElement {}
//same thing done in browser outputs : null
```

### How does similar code behave in browsers?
If you open browser console and do 
  document.documentElement.remove();
    document.documentElement = null;
    console.log(document.documentElement);
//OUTPUT : null

as a result of this following code triggers error while trying to add html node.
```
./node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js line 307
appendChild(/* Node */ arg) {
    if (this.documentElement && arg.nodeType === NODE_TYPE.ELEMENT_NODE) {
      throw new DOMException("The operation would yield an incorrect node tree.", "HierarchyRequestError");
    }
    return super.appendChild(arg);
  }
```

**Comment by TimothyGu** [comment]
I can't reproduce here:

```js
with (new JSDOM("").window) {
  document.documentElement.remove();
  document.documentElement = null;
  console.log(document.documentElement);
}
```

prints `null`.

**Comment by Jakhotiya** [comment]
@TimothyGu Ok. I see what's missing from the replicating instructions. 
This issue is only when you create a fresh project and add jsdom as dependency. 
SO I created a fresh project as 
```
mkdir jsdom-test
cd jsdom-test
npm init
npm install jsdom
```
Now the issue can be replicated

BUT if I run the code after cloning the repo and creating index.js and requiring JSDOM by
```
const {JSDOM} = require('./lib/api');
```
The issue can't be replicated.

DO you think, something is broken in the build?

**Comment by TimothyGu** [comment]
I did test with the Git master rather than the current branch, so maybe there is a bug in the last release that has since been fixed. You could wait until the next release, which will hopefully happen soon.

**Comment by Jakhotiya** [comment]
I did check. Yes it's a bug in 15.2.1 and is fixed in master. Thank you.
