### ISSUE TITLE
if there is a script tag in character string，will it parse incorrectly？

### ISSUE THREAD

**Issue by handsomeguy** [jsdom/jsdom#2758]
### Basic info:

- **Node.js version:** v10.16.3
- **jsdom version:** "^15.2.1"

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`<body>
  <script>document.body.appendChild(document.createElement("hr"));</script>
  <p>Hello world</p>
  <script>console.log("<script><\/script>")</script>
  </body>`);
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

```

### My question
i try my best to describe my question, i wanna figure out how jsdom parses HTML string, so i make some breakpoints to see how it works. But now I have an interesting question, when i put a script tag in character string ,which is wrapped in another script tag. it seems that it is wrong 

i mean it will parse like that:
start tag: <script>
characters: console.log("<script>
end tag: </script>
characters: ")
end tag: </script>

but my expectation is that:
start tag: <script>     
characters: console.log("<script><\/script>")     
end tag: </script>

hope i have described my question clearly.
so if a page which have reproduce the situation like what i say ,will it be wrong?
how to solve this problem?
thanks for reading ,hope to be answered~

**Comment by domenic** [comment]
This does not include a very important section of the issue template, which is how the corresponding code behaves in browsers.
