### ISSUE TITLE
Error: Cannot find module 'jsdom'

### ISSUE THREAD

**Issue by chinaambler1** [jsdom/jsdom#2760]
When I pass my node file to the console, I get this error. How do I fix this?

$ node node.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'jsdom'
Require stack:
- C:\Users\Admin\Documents\talktaxi\node.js
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797
:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:852:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:74:18)?[39m
    at Object.<anonymous> (C:\Users\Admin\Documents\talktaxi\node.js:1:15)
?[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10
)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:815:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:727:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)?[39
m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [ ?[32m'C:\\Users\\Admin\\Documents\\talktaxi\\node.js'?[39m ]
}

**Comment by domenic** [comment]
This issue doesn't follow the issue template, so we cannot help debug it.
