### ISSUE TITLE
Sometimes it doesn't return dom title in correct encoding format

### ISSUE THREAD

**Issue by luongvo** [jsdom/jsdom#2766]
### Basic info:

- **Node.js version:** 10.17.0
- **jsdom version:** 15.2.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const virtualConsole = new jsdom.VirtualConsole();

let url = "https://cafebiz.vn/ts-tu-ngu-qua-nuong-chieu-vi-giac-nguoi-viet-dang-tu-hai-ca-gia-dinh-vi-dung-mi-chinh-sai-20200101141108404.chn"
let dom = await JSDOM.fromURL(url, {virtualConsole});
let doc = dom.window.document;

let metaEls = doc.getElementsByTagName("meta");
let linkEls = doc.getElementsByTagName("link");
let titleTag = doc.getElementsByTagName("title");
let metaDescTag = doc.querySelector("meta[name='description']");

if (titleTag.length) {
    console.log(titleTag[0].textContent);
}
```

- The expected result is it should return a correct title: `TS. Từ Ngữ: Quá nuông chiều vị giác, người Việt đang tự hại cả gia đình vì dùng mì chính sai`
- Actual: sometimes it returns the title in a correct encoding, sometimes it doesn't: `TS. Tá»« Ngá»¯: QuÃ¡ nuÃ´ng chiá»�u vá»‹ giÃ¡c, ngÆ°á»�i Viá»‡t Ä‘ang tá»± háº¡i cáº£ gia Ä‘Ã¬nh vÃ¬ dÃ¹ng mÃ¬ chÃ­nh sai`

Here is the captured content of the link above:
![image](https://user-images.githubusercontent.com/16315358/71643292-606dcf00-2cea-11ea-9d05-f70349592858.png)

**Comment by domenic** [comment]
I can reproduce this. Very interesting. If you log `doc.characterSet` it is sometimes `UTF-8` and sometimes `windows-1252`. However, `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">` appears early in the document, so presumably we are doing something wrong in jsdom.

**Comment by domenic** [comment]
The intermittent nature is because sometimes the server sends `Content-Type: text/html` and sometimes it sends `Content-Type: text/html; charset=utf-8`. So we have some bug where the `<meta>` element is not properly overriding `Content-Type: text/html`.

**Comment by domenic** [comment]
It appears that html-encoding-sniffer is not finding the meta http-equiv attribute somehow; logging all return values of `getAttribute` in that file does not give anything for `http-equiv`.

So at this point either there is a bug in our implementation of the HTML encoding sniffer spec, or the HTML encoding sniffer spec itself has a bug that we copied over. Fun...

**Comment by luongvo** [comment]
@domenic I see that `html-encoding-sniffer` will return `defaultEncoding` in case it can't detect because there is no `transportLayerEncodingLabel` https://github.com/jsdom/html-encoding-sniffer/blob/8d69308c38af4b19170d2caeac6e16c6f52f5e01/lib/html-encoding-sniffer.js#L21. 

And JSDOM will pass the default encoding`windows-1252` https://github.com/jsdom/jsdom/blob/11be37a64315de57a02486010b725a49a69ac796/lib/api.js#L300. 

Should we add a default encoding to config like this? 🤔 
```
let dom = await JSDOM.fromURL(url, {virtualConsole, defaultEncoding: "utf-8"});
```

**Comment by domenic** [comment]
No. The default encoding is always windows-1252, like the spec and like browsers. We just need to fix a bug in our encoding sniffer so that it doesn't fall back to the default.

**Comment by domenic** [comment]
A fix is up at https://github.com/jsdom/html-encoding-sniffer/pull/5 and will hopefully roll into jsdom soon.
