### ISSUE TITLE
insertBefore(node, node) fails with Error: Not found

### ISSUE THREAD

**Issue by mbostock** [jsdom/jsdom#277]
Calling element.insertBefore(node, node) fails with the following error:

```
Error: Not found
at Object.<anonymous> (/Users/mbostock/node_modules/jsdom/lib/jsdom/level1/core.js:495:17)
at Object.insertBefore (/Users/mbostock/node_modules/jsdom/lib/jsdom/level2/events.js:325:20)
```

The problem is that the implementation removes the newChild (node), and then looks for the index of the refChild (also node). Since node was removed, this causes an error, when the correct behavior is a no-op.

**Comment by pmdartus** [comment]
This issue can be closed. [Node-insertBefore.html](https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/Node-insertBefore.html#L300-L311) wpt test covers this case.
