### ISSUE TITLE
`Intl.DateTimeFormat.prototype.formatToParts()` returns incorrectly cased type for the dayPeriod

### ISSUE THREAD

**Issue by cibernox** [jsdom/jsdom#2779]
### Basic info:

- **Node.js version:** All node versions I've tried
- **jsdom version:** All versions I've tried

### Minimal reproduction case

```js
new Intl.DateTimeFormat('en-US', { hour: "numeric", hour12: true }).formatToParts(new Date())
// [
//   { "type": "hour", "value": "11" }, 
//   { "type": "literal", "value": " " },
//   { "type": "dayperiod", "value": "PM" } <----- "type" should be "dayPeriod", with capital "P".
// ]
```
See documentation in MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts

### How does similar code behave in browsers?

In browsers it is correctly cased.

**Comment by Sebmaster** [comment]
Your repro doesn't include jsdom at all. Please provide a full one in your issue.

**Comment by domenic** [comment]
The reproduction code does not involve jsdom at all and as such should not be filed here.

**Comment by cibernox** [comment]
You're right, the Intl api is not part of JSDom, but part of node itself.
