### ISSUE TITLE
encoding not regonized 

### ISSUE THREAD

**Issue by pociej** [jsdom/jsdom#2782]
- **Node.js version:** 12.14.0 
- **jsdom version:** 15.2.1
### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
 /*anything */
};

JSDOM.fromURL("your_url", options).then(dom => {
  //do anything
});

```

Snippet above depending on the `your_url` throws `Error: Encoding not recognized: 'ISO-8859-2' (searched as: 'iso88592')` ( for example `https://gazeta.pl` ) or `Error: Encoding not recognized: 'UTF-8' (searched as: 'utf8')` ( for example `https://github.com`). There is no url i was able to make it working, always so one out of two errors described above. 
EDIT : I just noticed that above happen only if use JSDOM within the `jest` test file, when i created standalone file and run it, everything works as it should.  Here is reproduction repo : https://github.com/pociej/jsdom_problem_reproduction

**Comment by TimothyGu** [comment]
Unfortunately, we cannot support third-party libraries like Jest, especially when using jsdom stand-alone seems to work. I'll note however that your installation of Jest seems to be using a version of jsdom that's [quite old](https://github.com/pociej/jsdom_problem_reproduction/blob/2fca3da169c798a4f7179e87f89ea4ae34ea76c8/package-lock.json#L3451), but the [next version of Jest](https://github.com/facebook/jest/blob/8c20a8d8566ebcbb0cc9aadef3d5a230a2f97522/CHANGELOG.md#chore--maintenance) will have an upgraded jsdom. You may also find https://npm.im/jest-environment-jsdom-fifteen to be of interest, though I don't know if it works.
