### ISSUE TITLE
Document is not available in when run a function through window.setTimeout and window.setInterval

### ISSUE THREAD

**Issue by meetDeveloper** [jsdom/jsdom#2784]
### Basic info:

- **Node.js version: 10.16.2**
- **jsdom version: 15.2.1**

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  runScripts: "dangerously", 
  resources: "usable"
};
const dom = new JSDOM(`
<head>
<script async defer src="http://yourjavascript.com/125512480/a.js"></script>
</head>
<body>
<script>
setTimeout(() => { document.body.appendChild(document.createElement("p")); }, 10000);</script>
</body>`, options);

    try {
        await new Promise((resolve, reject) => {
            let timer = dom.window.setInterval(() => {
                console.log('Hello world');
                if (document.querySelectorAll('p').length === 1) {
                    console.log('Hello world');
                    clearInterval(timer);
                    resolve();
                }
            }, 500);
     });
    }
    catch (e) {
        console.log(e);
    }
```

It is mentioned in doc, that Timers in the jsdom (set by window.setTimeout() or window.setInterval()) will, by definition, execute code in the future in the context of the window.  But if they are running in context of windows why am I getting `Uncaught [ReferenceError: document is not defined]`

**Comment by Sebmaster** [comment]
They will execute with the context of the window (i.e. if you close the window they're not gonna get run), but variable scoping works as normal in JS, which means you'll have to access everything over `window.`. We don't do any magic with the functions you pass to timing functions.

May be possible to reword the docs there.

**Comment by meetDeveloper** [comment]
@Sebmaster Thanks that cleared it up, yeah docs need to reworded there, also I want to ask how did you know so much about js, that you made jsdom or are one of maintainer, I am quite new, and want to understand like how you do.

**Comment by Sebmaster** [comment]
> I want to ask how did you know so much about js, that you made jsdom or are one of maintainer, I am quite new, and want to understand like how you do.

I enjoy transcribing specifications into code. Started with node v0.4 with [mysql-cl](https://github.com/Sebmaster/mysqlcl) (production use not recommended), because the prevalent mysql client at the time didn't support proper prepared statements and went from there.

**Comment by meetDeveloper** [comment]
@Sebmaster So like where do you study javascript from, or where did you gained your foundation? Like when you started using node, did you tried understanding thread pools and all these things , or did you knew it

**Comment by Sebmaster** [comment]
Mostly just experimenting. Just go in with a plan, try and find what you need to make it happen. After a while you get an intuition on what should be available natively (in a language's stdlib) and how to find it.

**Comment by Sebmaster** [comment]
This has gotten quite off-topic though, so I'll close this issue so it doesn't distract as much.

**Comment by meetDeveloper** [comment]
@Sebmaster Thanks a lot.

**Comment by TimothyGu** [comment]
For me, I first learned JavaScript syntax and had no idea about what the event loop is and other low-level details, but I eventually picked those up from experience. I am of the opinion that programming is better learned through experience than textbooks. Knowing the implementation details are really not that important compared to actually using the language.

**Comment by meetDeveloper** [comment]
@TimothyGu Oh, so you had any experience with OS, or any such low level thing.?
