### ISSUE TITLE
Replace request with something better

### ISSUE THREAD

**Issue by TimothyGu** [jsdom/jsdom#2792]
We are currently using [both](https://github.com/jsdom/jsdom/blob/d240291edbe7d4180a5152993ced7950c834dc57/package.json#L35-L36) request and request-promise-native. We should replace them both with something better.

- **request** is in [maintenance mode](https://github.com/request/request/issues/3142).
- **request** is already quite [bloated](https://bundlephobia.com/result?p=request@2.88.0).
- **request-promise-native** uses [stealthy-require](https://www.npmjs.com/package/stealthy-require) which essentially results in two copies of request (see https://github.com/jsdom/jsdom/pull/2783#issuecomment-572415665)

Some alternatives are in https://github.com/request/request/issues/3143. Strongest candidate right now is probably **[node-fetch](https://www.npmjs.com/package/node-fetch)**.

**Comment by SimenB** [comment]
This is suddenly a bit more "needed"

```sh-session
$ yarn add jsdom
warning jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

https://twitter.com/mikeal/status/1227271424546459649

**Comment by mahnunchik** [comment]
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

**Comment by bnb** [comment]
Yep, this is propagating all the way up to jest now 😬

**Comment by SagnikPradhan** [comment]
Any updates? Will anything be replacing `request` any soon?

**Comment by domenic** [comment]
https://mobile.twitter.com/slicknet/status/782274190451671040

**Comment by demianalonso** [comment]
Is there a preferred package for replacing `request`?

**Comment by mahnunchik** [comment]
Not the [`axios`](https://github.com/axios/axios/issues/2190). It has [critical issue](https://github.com/axios/axios/issues/2190) for a while.

What about `fetch`?

**Comment by SagnikPradhan** [comment]
I would suggest `centra` but as @mahnunchik mentioned `fetch` (`node-fetch`) can be a thing too.

**Comment by roncli** [comment]
`@root/request` is a drop in replacement for both of these that I've been using.

**Comment by tobyhinloopen** [comment]
`node-fetch` since it uses an existing standard and will therefore not be deprecated anytime soon. Even if `node-fetch` gets deprecated, you can just replace it with another `fetch`-compatible library/polyfill.

**Comment by SagnikPradhan** [comment]
On Side Note, Has anyone ever thought of removing http client all together? And you know leaving it to the user to get the HTML?

**Comment by tobyhinloopen** [comment]
> On Side Note, Has anyone ever thought of removing http client all together? And you know leaving it to the user to get the HTML?

The http client is also used while running tests. For example, it fetches fixtures while running tests in the browser using XHR (using `request`). It also uses `request` to check whether the WPT servers are up.

I'm currently **attempting** to replace `request` and `request-promise-native` with `node-fetch` and I'll provide a PR when done.

**Comment by dungmv** [comment]
any update

**Comment by tobyhinloopen** [comment]
Still working on it. All my changes can be found [here](https://github.com/tobyhinloopen/jsdom/compare/master...2792-replace-request-with-node-fetch). I'll continue working on it at my earliest possibility, but I'm quite busy with clients.

**Comment by Hypnosphi** [comment]
@tobyhinloopen can you please open a draft PR, so that we all could track your progress?

**Comment by tobyhinloopen** [comment]
https://github.com/jsdom/jsdom/pull/3031

I'm sorry it's taking so long, I'm not sure when I'll be able to continue. If people are waiting for this, I suggest someone tries to continue working on it before I will be able to.

**Comment by MirrorBytes** [comment]
Would got be a better alternative to avoid practically rewriting the request library to support the xhr implementation? I mean, it's doable with node-fetch, but would require a rewrite of the entire xhr implementation from the looks of it. Got is nearly a drop in replacement.

**Comment by MirrorBytes** [comment]
I'll write up a draft PR tonight or tomorrow morning. I'll flag whatever open issues exist pertaining to this as well.

**Comment by SagnikPradhan** [comment]
If you did not realize @tobyhinloopen is already working this, you can help him if you want. 

Personally I'd have liked if JSDOM did not include any http client library and only came with mock clients for executing browser scripts. This way it would stay http client agnostic.

**Comment by backflip** [comment]
I might be mistaken, but it looks like the only issue left to do in https://github.com/jsdom/jsdom/pull/3054 is figuring out the failing `preflight-failure.htm` tests in https://travis-ci.com/github/jsdom/jsdom/jobs/389635257

**Comment by andrewaylett** [comment]
`request` is still used in `xhr-utils.js` -- I'm afraid I'd missed that caveat when claiming a fix.

**Comment by MirrorBytes** [comment]
@SagnikPradhan Fetch and node-fetch are used to avoid xhr entirely, that was the intent and still is... Why use something to implement the very thing they were made to avoid? If you read the readme of node-fetch, it explains as much in the first paragraph.

@backflip Because no one removed request prior to testing. You still need to implement xhr, or you'll have 300+ tests fail out the gate.

**Comment by MirrorBytes** [comment]
@SagnikPradhan Reflecting on what I said, I should clarify that it's not that I think it's not a likely solution, it's just that you would have to create an http client in the event you didn't use one (whether it's a separate library or not); and doing so around fetch/node-fetch would effectively be pointless considering other solutions exist without the need to manage them internally.

**Comment by jasonwilliams** [comment]
> Would `got` be a better alternative to avoid practically rewriting the `request` library to support the xhr implementation? I mean, it's doable with node-fetch, but would require a rewrite of the entire xhr implementation from the looks of it. Got is nearly a drop in replacement.

More users are likely to have node-fetch already deep  in their dependencies (as it seems to be the de-facto right now), so less downloads overall.  Also i think node are discussing having the same/or similar API built-in, so it would be the best one to go with for the long run, even if it does mean refactoring now.

**Comment by MirrorBytes** [comment]
It's virtually a tie as most projects that I've worked on had got deep in the dependencies alongside node-fetch. Less downloads though? You have to replace quite a bit... In fact, with what's already included in the PR is adding the same number of dependencies... not to mention you'll need ```form-data```, ```stream```, ```util```, etc. in order to refactor the xhr implementation.

Regardless there's going to be a slew downloads, and you're practically writing a new http client library specifically to handle xhr. Not to mention it would more than likely not be in spec either considering the workarounds that would be needed to support event emitters and such.

If a refactor were to happen, it would be to accommodate fetch.... which is exactly why ```request``` went into maintenance mode. I believe an spec-orientated, modern, and separately maintained library would be a better fit for the time being.

**Comment by SagnikPradhan** [comment]
Eh, I guess I agree with you. Less code the team has to maintain the better it is, and it seems like got is more popular? [got](https://github.com/sindresorhus/got/network/dependents) [node-fetch](https://github.com/node-fetch/node-fetch/network/dependents)

Personally I do not care about which client is running beneath, cause
1. I use `JSDOM` only as a html parser 
2. If it works it works.

**Comment by MirrorBytes** [comment]
@SagnikPradhan  I'm only stating for the interim. That is it. Breaking change can happen, but should not happen during an http client change for xhr in my opinion.

The more light weight, the better. However, that's not easy.

**Comment by Luxcium** [comment]
I was under the impression there was an easy fix for that ***request has been deprecated*** thing I am only a *normal human being* and I was expecting that *superheroes not wearing a cape* (i.e. Maintainers of the `50655` dependencies) would have found a solution by now... anyway keep doing a great job so *annoying little script kiddies* like me can continue resolving packages in our projects without *nasty error messages* (it's how us *annoying little script kiddies* call the *warning messages*):  
   
```yarn
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
```

**Comment by BeigeBox** [comment]
Has there been any movement on this?  It seems that “request” has security issues so it would be great to see even a less than optimal fix in place.

**Comment by MirrorBytes** [comment]
@BeigeBox Been attempting to re-implement XHR with `got`, but it's not an easy task; tons of hurdles with the way the implementation was written to accommodate `request`.

**Comment by MirrorBytes** [comment]
Not to mention that it spawns synchronous child processes that hang forever on any given error that are near impossible to figure out without hacking node itself. All relating to WPT of course.

**Comment by tobyhinloopen** [comment]
> Has there been any movement on this? It seems that “request” has security issues so it would be great to see even a less than optimal fix in place.

what security issues?

**Comment by MirrorBytes** [comment]
There aren't any "security" issues as far as I'm aware. The fact that a library is deprecated does not infer security issues, but does mean they may arise.

**Comment by tobyhinloopen** [comment]
There has been some progress, but still not finished.

I've been attempting to rewrite `xhr-utils` and `XMLHttpRequest-impl` using `fetch` and `node-fetch` but these files depend on so much details, I think I'm just going to use Node's `http` and `https` modules directly, since these files are only executed inside NodeJS environment anyway.

I'm still very busy so my available time can be tomorrow or next year.

**Comment by yong-jie** [comment]
> what security issues? and how are they relevant to jsdom?

Snyk lists a high severity [Prototype Pollution](https://snyk.io/vuln/npm:ajv) vulnerability for an old version of `ajv` (<6.12.3).

I believe people are receiving Snyk alerts for projects using jsdom because `ajv@6.10.1` is an indirect dependency. For the warning i received, it states `jsdom@16.4.0 › request@2.88.2 › har-validator@5.1.3 › ajv@6.10.1`.

**Comment by MirrorBytes** [comment]
@yong-jie The same would be true for eslint or table then. If you're getting those errors, upgrade your packages as they don't have hard version limitations. The latest version of har-validator requires ^6.12.3 according to my lock files.

**Comment by BorntraegerMarc** [comment]
> Not the axios. It has critical issue for a while.

Axios has solved the critical security issues...

**Comment by malfro** [comment]
axios would be the better replacement tool.

**Comment by bnb** [comment]
> axios would be the better replacement tool.

Axios is seemingly not actively maintained. Given that, it would increase the likelihood that we'll be having this _long standing_ discussion again at some point in the near future.

**Comment by soilSpoon** [comment]
How about [undici](https://www.npmjs.com/package/undici)

**Comment by jsg2021** [comment]
What's so bad about using http(s) libs directly from node?

**Comment by jsg2021** [comment]
> How about [undici](https://www.npmjs.com/package/undici)

I like how it has 0 deps :)

**Comment by alexp1917** [comment]
I've added a commit with some comments denoting where request is used. maybe I could get some feedback or this could help someone else tack the issue - https://github.com/alexp1917/jsdom/commit/44ee96437d6ee1b87bb7d468b508359281a05208

**Comment by jsg2021** [comment]
https://github.com/jsdom/jsdom/pull/3092

**Comment by alexp1917** [comment]
So this is almost done, I see

**Comment by vegardbb** [comment]
Correct, what remains to be done is a PR review and addressing feedback from the package maintainers.
