### ISSUE TITLE
Optional error binding in try/catch breaks module in most environments

### ISSUE THREAD

**Issue by AnandChowdhary** [jsdom/jsdom#2793]
Seems like [lib/jsdom/living/helpers/dates-and-times.js#L235](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/helpers/dates-and-times.js#L235) in v16.0.0, the most recent release, is using `try { } catch { }` without error binding, which isn't supported by most environments yet ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Browser_compatibility)).

```
/home/runner/work/ui/ui/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^
SyntaxError: Unexpected token {

  at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
  at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
  at Object.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)
```

Current method:

```js
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch {
    return false;
  }
}
```

Fixed method:

```js
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch (error) {
    return false;
  }
}
```

**Comment by domenic** [comment]
This is intentional. See

> The latest versions of jsdom require Node.js v10 or newer. (Versions of jsdom below v16 still work with previous Node.js versions, but are unsupported.)

from the readme.
