### ISSUE TITLE
Build production error

### ISSUE THREAD

**Issue by AmosXu** [jsdom/jsdom#2797]
jsdom: 16.0
node: 8.12.0

lib/jsdom/living/helpers/dates-and-times.js

LINE 235
```
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch {
    return false;
  }
}
```
please use replace
```
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch(e) {
    console.log(e)
    return false;
  }
}
```

**Comment by Sebmaster** [comment]
Node 8 is not supported anymore, from README:

> The latest versions of jsdom require Node.js v10 or newer. (Versions of jsdom below v16 still work with previous Node.js versions, but are unsupported.)
