### ISSUE TITLE
Unexpected Token : } catch {

### ISSUE THREAD

**Issue by Morgiver** [jsdom/jsdom#2801]
Hi i got an error when using JSDOM with Electron on Node 10.6.0 :
```
C:\Users\Morgiver\Documents\Developpement\GameSpider\node_modules\jsdom\lib\jsdom\living\helpers\dates-and-times.js:235
    } catch {
```
https://github.com/jsdom/jsdom/blob/e2dbad81835bab05256f68db05ace47eb3b6da71/lib/jsdom/living/helpers/dates-and-times.js#L235

To fix this you can edit the line 235 to : 
```
} catch(e) {
```

**Comment by domenic** [comment]
In my testing in Node.js 10.6.0 there is no such problem. So, this must be an Electron-specific issue. (E.g., I hear Electron bundles together both Chromium and Node.js, so maybe it has an old version of Chromium.)

If Electron does not properly have the Node 10.6.0 features, then it is not a supported configuration.

**Comment by himanshuagarwal456** [comment]
facing the same issue 
```/Users/himanshu.agarwal/projects/projs/clinical-trial-parse-server/node_modules/webidl-conversions/lib/index.js:357
    } catch {
            ^

SyntaxError: Unexpected token {
```
node version:v8.11.4
jsdom version:^16.2.2

const dom = new JSDOM(reportHtml); // simple initialization throwing error

**Comment by shiyongsway** [comment]
I have change the jsdom version to  10.1.0 has solved this problem.

**Comment by pssingh21** [comment]
I had the same problem using Jest v26. Using Jest@25 solved the issue for me. Jest@v25 has support for Node v8.

**Comment by mohrash92** [comment]
> have change the jsdom version to 10.1.0 has solved this problem.

Thank you this solution worked for me too 👍
