### ISSUE TITLE
How To? (Getting CSS for a particular end point by ViewPort)

### ISSUE THREAD

**Issue by davegermiquet** [jsdom/jsdom#2804]
### Basic info:

Node v10/v12
"jsdom": "^15.1.1",
### Minimal reproduction case

I have a use case where I have different CSS code, based on Media inputs or viewports. The element is defined the same, but consists of different css depending on viewport. It uses the Media functionality.

I tried to change the hard-coded values to a specific view port to see if it had that functionality but it returned the same css when I was expecting something different.

The function i'm using is the following:

document.getComputedStyle(element);

The part of code I changed was the following was in Window.js of JSDOM:

Starting at line 623:

 define(this, {
    name: "",
    status: "",
    devicePixelRatio: 1,
    innerWidth: 1900, // Originally was 1024
    innerHeight: 1200,// originally was 768
    outerWidth: 1900,
    outerHeight: 1200,
    pageXOffset: 0,
    pageYOffset: 0,
    screenX: 0,
    screenLeft: 0,
    screenY: 0,
    screenTop: 0,
    scrollX: 0,
    scrollY: 0,

    alert: notImplementedMethod("window.alert"),
    blur: notImplementedMethod("window.blur"),
    confirm: notImplementedMethod("window.confirm"),
    focus: notImplementedMethod("window.focus"),
    moveBy: notImplementedMethod("window.moveBy"),
    moveTo: notImplementedMethod("window.moveTo"),
    open: notImplementedMethod("window.open"),
    print: notImplementedMethod("window.print"),
    prompt: notImplementedMethod("window.prompt"),
    resizeBy: notImplementedMethod("window.resizeBy"),
    resizeTo: notImplementedMethod("window.resizeTo"),
    scroll: notImplementedMethod("window.scroll"),
    scrollBy: notImplementedMethod("window.scrollBy"),
    scrollTo: notImplementedMethod("window.scrollTo")
  });

Both resolutions show the same css with both view ports.

### How does similar code behave in browsers?

It comes up with different CSS on the viewport on the browser.

**Comment by domenic** [comment]
The minimal reproduction case here does not follow the format in the issue template; it is not code that we can run to reproduce the issue. So, we'll close this issue.
