### ISSUE TITLE
<input type="number"> produces binary floating point anomalies

### ISSUE THREAD

**Issue by dcwarwick** [jsdom/jsdom#2823]
### Basic info:

- **Node.js version:** 10.18.1
- **jsdom version:** 16.1.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const win = new JSDOM('', { url: 'https://localhost/' }).window;
const document = win.document;

// or paste from here onwards into a browser console
const input = document.createElement('input');
document.documentElement.appendChild(input);
input.setAttribute('type', 'number');
input.setAttribute('value', '1.2');
input.setAttribute('step', '0.3');
console.log('value (expect: 1.2) is:', input.value);

input.stepDown();
console.log('value (expect: 0.9) is:', input.value);
```

The following output is obtained:
```
value (expect: 1.2) is: 1.2
value (expect: 0.9) is: 0.8999999999999999
```

The floating point anomaly occurs because JSDOM is using ECMAScript numbers to implement the value/step/stepUp/stepDown features of `<input type="number">`, but these numbers are binary floating point and the HTML specification specifies *decimal* floating point (see https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number and https://html.spec.whatwg.org/multipage/input.html#number-state).

### How does similar code behave in browsers?

The following output is obtained using Google Chrome for example:
```
value (expect: 1.2) is: 1.2
value (expect: 0.9) is: 0.9
```

**Comment by dcwarwick** [comment]
I notice that 'decimal.js' is already required in, and is used to check whether the step is aligned. It would seem to make sense to extend the use of 'decimal.js' for all arithmetic to do with min, max, step, value. I haven't done this as a PR yet because I see there's already been some discussion, and the stepUp/Down methods are still quite recent, and I don't want to collide with someone :-) But if you'd like me to do a PR fixing this for your review just let me know and I'd be happy to do it.

**Comment by TimothyGu** [comment]
Aha, this looks like what I wanted to change in https://github.com/jsdom/jsdom/pull/2789#discussion_r365492244 (see collapsed comments) but couldn’t find the test case for.
