### ISSUE TITLE
Breaking change in isDate()

### ISSUE THREAD

**Issue by iaincollins** [jsdom/jsdom#2836]
Hi there,

Looks like a breaking change to an unhappy path snuck in version 16 last month.

https://github.com/jsdom/jsdom/blob/d2ae947c60297a8ec404b4adbd78267bedd439f4/lib/jsdom/living/helpers/dates-and-times.js#L235

Is currently:

```js
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch {
    return false;
  }
}
```

Should be something like:

```js
function isDate(obj) {
  try {
    Date.prototype.valueOf.call(obj);
    return true;
  } catch (e) {
    return false;
  }
}
```

**Comment by domenic** [comment]
No, this is working as intended. V16 is a major version and is allows to have breaking changes, such as requiring Node v10.
