### ISSUE TITLE
(How) Can I set height properties on window, documentElement or body?

### ISSUE THREAD

**Issue by DavidRicharz** [jsdom/jsdom#2843]
How can I alter height/width element properties in jsdom?  I don't see any setters and simply applying a value to a selected property won't work.

I realize this is not what we would do within a regular browser environment, but jsdom doesn't seem to implement any kind of height/width properties by itself. Simply adding elements to the jsdom constructor should increase height/width properties of the document.

I also found [this](https://github.com/jsdom/jsdom/issues/2342#issuecomment-415086243) "solution", but it only extends to document.documentElement and does not update any other nodes (body, p#content).

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM('<!DOCTYPE html><p id="content">Some Elem with height </p>');

//without alteration
console.log(dom.window.document.body.querySelector('#content').clientHeight); // 0 There is no real height property

//simply trying to assign a value
dom.window.document.documentElement.clientHeight = 1234;
console.log(dom.window.document.documentElement.clientHeight); // 0

//using defineProperty
Object.defineProperty(dom.window.HTMLHtmlElement.prototype, 'clientWidth', {value: 1234});
console.log(dom.window.document.documentElement.clientWidth) // 1234
console.log(dom.window.document.body.clientWidth) // 0 
console.log(dom.window.document.documentElement.querySelector('#content').clientWidth) // 0
```

**Comment by domenic** [comment]
> Simply adding elements to the jsdom constructor should increase height/width properties of the document.

Doing this would require implementing a layout system, which [is not currently in our plans](https://github.com/jsdom/jsdom#unimplemented-parts-of-the-web-platform). The best you can do is use defineProperty to supply fake values. But, if you really want to get layed-out coordinates, you may be best off with a true headless browser, not with jsdom.

**Comment by domenic** [comment]
I'll dupe this into #135.
