### ISSUE TITLE
QuerySelector throws error if given ID is not present

### ISSUE THREAD

**Issue by PrernaK1603** [jsdom/jsdom#2857]
**Code**
```
let isIdPresent = dom.window.document.querySelector(
          "#head"
        );
        if(isIdPresent!=null){
          console.log("isIdPresent",isIdPresent);
        }else{
          console.log("not present");
        }
```
Here querySelector throws error if it is not able to find the given id and exits the program.
**Error**

(node:9576) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
(node:9576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

Expected:

- if id is not present it should not exits the program and continue with else block.

**Comment by domenic** [comment]
This issue does not follow the issue template.
