### ISSUE TITLE
Input number validation error for decimal steps due to floating-point arithmetic

### ISSUE THREAD

**Issue by lordoffreaks** [jsdom/jsdom#2862]
### Basic info:

- **Node.js version:** 12.6.1
- **jsdom version:** 16.2.0

### Minimal reproduction case

Continuing https://github.com/jsdom/jsdom/issues/2288 I'm finding the same error ocurring for me using jsdom 16.2.0 see https://codesandbox.io/s/dark-bird-bf18s

```js
import React from "react";
import { render } from "@testing-library/react";
import "@testing-library/jest-dom";

function Input() {
  return (
    <input
      aria-label="price"
      type="number"
      value="100"
      min="0"
      max="500"
      step="0.001"
    />
  );
}

test("Input is valid with a number with the min/max", () => {
  const { queryByLabelText } = render(<Input />);
  const input = queryByLabelText("price");

  expect(input.value).toBe("100");
  expect(input.validity.stepMismatch).toBe(false);
});

```

### How does similar code behave in browsers?

https://codesandbox.io/s/dark-bird-bf18s

Thanks

**Comment by domenic** [comment]
Sorry, this is not a minimal reproduction case. A minimal reproduction case does not involve other libraries, and does not involve syntax that fails to work in Node.js.

I will close this, but can reopen it if it you comment saying that you've updated the original post with an actual minimal reproduction case.
