### ISSUE TITLE
document.addEventListener lacks support for registering CustomElements as eventListener

### ISSUE THREAD

**Issue by Saegrov** [jsdom/jsdom#2869]
### Basic info:

- **Node.js version: 10.15.2** 
- **jsdom version: 16.2** 

### Minimal reproduction case

```js
const jsdom = require('jsdom');

const { JSDOM } = jsdom;

const dom = new JSDOM(
    `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>No</title>
      </head>

      <body>
        <my-custom-click id="click">Click me!</my-custom-click>
        <script>
          class MyCustomClick extends HTMLElement {
            connectedCallback() {
              document.addEventListener('click', this);
              
              // Replace the line above with the line below and it works
              //document.addEventListener('click', (e) => this.handleEvent(e));
            }

            handleEvent(event) {
              if (event.target == this) {
                this.innerHTML = 'It worked!';
              }
            }
          }

          window.customElements.define('my-custom-click', MyCustomClick);
        </script>
      </body>
    </html>
  `,
    { runScripts: 'dangerously' }
);

const {
    window: { document },
} = dom;

const customElement = document.getElementById('click');
customElement.click();
if(customElement.innerHTML === 'It worked!') {
    console.log('Success!');
} else {
    throw Error('This did not work!')
}

```

### How does similar code behave in browsers?

This works in the browser. See example:
https://codesandbox.io/s/eloquent-flower-t5w08?fontsize=14&hidenavigation=1&theme=dark

**Comment by Saegrov** [comment]
I've done some digging and in `jsdom/living/events/EventTarget.js` there is the following code:
```
      {
        let curArg = arguments[1];
        if (curArg === null || curArg === undefined) {
          curArg = null;
        } else {
          curArg = utils.tryImplForWrapper(curArg);
        }
        args.push(curArg);
      }
```

If I comment out `utils.tryImplForWrapper(curArg);` the example runs fine.
It seems that when adding `MyCustomClick` as an event listener, the code above replaces `MyCustomClick` with an `HTMLElementImpl`.


In `jsdom/living/EventTarget-impl` there is the following code for handling object as an eventListener if they have an `handleEvent` property:
```
      if (typeof listener.callback === "object") {
        if (typeof listener.callback.handleEvent === "function") {
          listener.callback.handleEvent(idlUtils.wrapperForImpl(eventImpl));
        }
      }
```

Since `MyCustomClick` is replaced with an `HTMLElementImpl` `handleEvent` no longer exists on the registered eventListener doesn't fire.

I'm happy to provide a PR but I have no idea where to even start even if I think I've identified the problem.

**Comment by domenic** [comment]
Very interesting archeology; thank you. With the first report I had suspected this was a general problem not specific to custom elements. With your investigation I now see that it's likely custom element specific.

This is going to be a bit tricky to fix properly, and I wouldn't necessarily advise working on a PR, since it will involve some deep jsdom internals. It seems like what we need to do is make sure callback interfaces (like EventHandler) are not always unwrapped in webidl2js... i.e. we probably need to implement at least some of the callback interface stuff.

@TimothyGu started work on callback _functions_ in https://github.com/jsdom/webidl2js/pull/123, but those are a simpler version of what's going on here...

**Comment by TimothyGu** [comment]
Interesting indeed. https://github.com/jsdom/webidl2js/pull/123 is a bit more ambitious, but this could be fixed more easily.

**Comment by TimothyGu** [comment]
This will get fixed in the next jsdom release, which will incorporate jsdom/webidl2js#182.
