### ISSUE TITLE
QuerySelector Not working with Node v12.16.1

### ISSUE THREAD

**Issue by dvreed77** [jsdom/jsdom#2870]
### Basic info:

- **Node.js version:** v12.16.1
- **jsdom version:** 16.2.0

### Minimal reproduction case

```js
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
console.log(dom.window.document.querySelectorAll("p"));
```

When running this with Node version 12.16.1, the output of this is `NodeList {}`. When running with Node version <= 11, the output is `NodeList { '0': HTMLParagraphElement {} }`

**Comment by TimothyGu** [comment]
This is an artifact of recent changes to Node.js' `util.format` function, that is used in `console.log`. If you explicitly print out the `length` of the `NodeList` (or if you convert the `NodeList` to an array through `Array.from` or `[...obj]`), you see that the object is in fact not empty. See https://runkit.com/timothygu/5e588813857db1001441093f.
