### ISSUE TITLE
requestAnimationFrame prevents process from terminating

### ISSUE THREAD

**Issue by fasttime** [jsdom/jsdom#2886]
Since version 16.1.0, as soon as `requestAnimationFrame` is used, the Node process no longer terminates normally unless `window.close` is explicitly called.

In my understanding this is owed to a `setInterval` callback that keeps ghosting around even when there are no more pending asynchronous animation requests.

### Basic info:

- **Node.js version:** 13.10.0
- **jsdom version:** 16.1.0 and 16.2.0 are affected

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const { window } = new JSDOM('', { pretendToBeVisual: true });
window.requestAnimationFrame(() => console.log('animation frame'));
// process keeps running - press ctrl + C to break
```

### How does similar code behave in browsers?

Normally, the is issue is peculiar to Node. https://jsbin.com/mogunaposi/edit?js,console

**Comment by domenic** [comment]
Thanks, that wasn't intended, although it's pretty obvious in retrospect. I wonder how our tests didn't catch it...

**Comment by arturparkhisenko** [comment]
The v16.0.1 works for me on Node 10.

**Comment by domenic** [comment]
Yeah, this bug was introduced in https://github.com/jsdom/jsdom/commit/1ebb1fcd3823882e2cee36afcd1b78217b629ee4

**Comment by AviVahl** [comment]
The tests didn't catch it because of https://github.com/jsdom/jsdom/blob/16.2.1/.mocharc.json#L2
