### ISSUE TITLE
BUG with `select.selectedOptions`. Probably caching.

### ISSUE THREAD

**Issue by catalin-luntraru** [jsdom/jsdom#2908]
### Basic info:

- **Node.js version:** 13.11.0
- **jsdom version:** 16.2.1

### Minimal reproduction case

```js
const jsdom = require('jsdom')
const dom = new jsdom.JSDOM(`<select>
  <option value="x" data-foo="a">1st opt</option>
  <option value="y" data-foo="b">2nd opt</option>
</select>`)
const select = dom.window.document.querySelector('select')
select.value = 'x'
console.log(select.value, select.selectedOptions[0].dataset.foo) // comment this out and it works
select.value = 'y'
console.log(select.value, select.selectedOptions[0].dataset.foo)
```

If you set a value on a `select` field and then you mention `select.selectedOptions` and then you change the `select` field value again, the value does change, but the `selectedOptions` object stays the same.

Once you comment out the `select.selectedOptions` code between the 2 value setters, then it works correctly, showing the correct `selectedOptions` dataset value.

### How does similar code behave in browsers?

https://jsbin.com/dufivogoxe/edit?html,js,console,output
As you can see on jsbin, the browser does show the correct `selectedOptions` object even if you mention the `selectedOptions` in between the setters

**Comment by catalin-luntraru** [comment]
As a temporary fix I'm using this method

```javascript
getSelectedOption (select) {
  // return select.selectedOptions[0] // @todo when jsdom fixes this bug re-enable it https://github.com/jsdom/jsdom/issues/2908
  return select.querySelector(`option[value="${select.value}"]`)
}
```

**Comment by ExE-Boss** [comment]
It’s because changing the `select.value` is not correctly updating the internal `_version` field, which is used to optimise `HTMLCollection`, `HTMLOptionCollection`, `NodeList` and several other things.

I’m fixing that in <https://github.com/jsdom/jsdom/pull/2909>.
