### ISSUE TITLE
BUG: can't install with npm github because of dependency link issue

### ISSUE THREAD

**Issue by catalin-luntraru** [jsdom/jsdom#2914]
I want to use the master branch of jsdom through github instead of the npm 16.2.1 version.

I tried `npm i -D git+ssh://git@github.com/jsdom/jsdom.git` and also `npm i -D git+https://git@github.com/jsdom/jsdom.git` and it takes a long time and then it fails with 

```
npm ERR! prepareGitDep npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! prepareGitDep npm ERR! Unsupported URL Type "link:": link:./scripts/eslint-plugin
```

I looked at the `package.json` of jsdom and you have this in your devDependencies list `"eslint-plugin-jsdom-internal": "link:./scripts/eslint-plugin"` which causes the issue. 

Can we do something about this `link` to `eslint`, so npm doesn't crash?
Thank you.

**Comment by domenic** [comment]
We use yarn, not npm. See https://github.com/jsdom/jsdom/blob/master/Contributing.md.
