### ISSUE TITLE
@types/jsdom，/node_modules/parse5/lib"' has no exported member 'ElementLocation'.causes program compilation to fail

### ISSUE THREAD

**Issue by laishiwen** [jsdom/jsdom#2915]
// fail info
![image](https://user-images.githubusercontent.com/17078631/77386282-693fdf80-6dc5-11ea-90e9-d026ee5bb74d.png)

// bad
![image](https://user-images.githubusercontent.com/17078631/77386351-92f90680-6dc5-11ea-9e97-87f0cae27ffb.png)

// great
step 1:
![image](https://user-images.githubusercontent.com/17078631/77386476-d9e6fc00-6dc5-11ea-834b-0b62a3b2f12a.png)

step 2:
![image](https://user-images.githubusercontent.com/17078631/77386637-3d712980-6dc6-11ea-9daf-50d09c645086.png)

step 3:
![image](https://user-images.githubusercontent.com/17078631/77386542-06027d00-6dc6-11ea-80c1-965256f5447a.png)

**Comment by domenic** [comment]
This does not follow the issue template.

**Comment by TimothyGu** [comment]
In particular, we don’t maintain the types of jsdom. You should direct your query to the maintainers of `@types/jsdom`.
