### ISSUE TITLE
Why can't I silence the 'Could not parse CSS stylesheet' error?

### ISSUE THREAD

**Issue by geopic** [jsdom/jsdom#2922]
I'm writing a web scraping project for a machine with limited storage and every now and again, `jsdom` throws an error when it cannot parse the stylesheet, where the message contains stack trace and all. I'm not too interested in the error being fixed, I assume it happens due to the website I'm scraping from. But I need to handle the error myself, since the size of the error message is making it difficult to operate under the tight storage size restrictions. It just isn't happening though, I always get the native JSDOM error. Please allow me to handle it myself.

### Basic info:

- **Node.js version:** 13.11.0
- **jsdom version:** 16.2.0

### Minimal reproduction case

```ts
const { JSDOM } = require('jsdom');

try {
  window = new JSDOM(html).window;
} catch {
  // this never appears, even when JSDOM throws
  console.error('JSDOM stylesheet parsing error, operation aborted.');
}
```

### How does similar code behave in browsers?

N/A, error is logged in console server-side.

**Comment by Sebmaster** [comment]
jsdom connects the virtual console to the real console by default: https://github.com/jsdom/jsdom#virtual-consoles

**Comment by geopic** [comment]
Thank you @Sebmaster.
