### ISSUE TITLE
Disabling or removing focused element doesn't trigger blur event

### ISSUE THREAD

**Issue by diegohaz** [jsdom/jsdom#2931]
### Basic info:

- **Node.js version:** 12.13.0
- **jsdom version:** 16.2.1

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { document } = new JSDOM(`<button id="button">Button</button>`).window;

const button = document.getElementById("button");

button.addEventListener("blur", () => {
  console.log("blur");
});

button.addEventListener("focus", event => {
  console.log("focus");
  setTimeout(() => {
    console.log("disable");
    button.disabled = true;
    // remove() should also blur the element
    // console.log("remove");
    // button.remove();
  }, 1000);
});

button.focus();
```

This is the console output
```
focus
disable
```

### How does similar code behave in browsers?

This is the console output:
```
focus
disable
blur
```

https://jsbin.com/daceneg/edit?html,js,console,output

**Comment by domenic** [comment]
This actually is behaving per spec, and matches Firefox.

I thought there was a spec issue open on figuring out whether the spec/Firefox should change, or Chrome should change, but the closest I can find right now is https://github.com/whatwg/html/issues/1195. But in any case, it's not a jsdom bug.

**Comment by diegohaz** [comment]
You're right! Just tested on Firefox and Safari, and the behavior is the same as jsdom. Thanks for the quick reply!
