### ISSUE TITLE
Roll WPT and remove dom/ tests from to-upstream

### ISSUE THREAD

**Issue by domenic** [jsdom/jsdom#2935]
Once https://github.com/web-platform-tests/wpt/pull/22727 is merged, we should roll WPTs and then we should remove everything in the dom/ folder except the dont-upstream variants.

I'm filing this as a tracking issue because in the past we've upstreamed things but failed to remove them from to-upstream/, which is counterproductive.

**Comment by TimothyGu** [comment]
Also remove the duplicated `<label>` tests added here: https://github.com/web-platform-tests/wpt/pull/22749
