### ISSUE TITLE
fs.promises API is experimental on node v10

### ISSUE THREAD

**Issue by clshortfuse** [jsdom/jsdom#2939]
### Basic info:

- **Node.js version:** `v10.16.0`
- **jsdom version:** `16.2.2`

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
```
### Issue

On Node v10 `fs.promises` is Experimental and node emits a warning:

```
> (node:6749) ExperimentalWarning: The fs.promises API is experimental
    at Object.get (fs.js:1846:17)
    at Object.<anonymous> (/home/user/projects/project/node_modules/jsdom/lib/api.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at repl:1:19
```

**Comment by clshortfuse** [comment]
Seems like it's no longer experimental past v10.17 according to https://github.com/nodejs/node/pull/29875

Perhaps the `package.json` should bump the `node` version to `>=10.17`?

**Comment by TimothyGu** [comment]
If you upgrade to the latest v10 version (10.20.0) at the time of speaking, you should see the warning disappear. This was changed in [10.17.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#2019-10-22-version-10170-dubnium-lts-bethgriggs).

**Comment by TimothyGu** [comment]
> Perhaps the `package.json` should bump the `node` version to `>=10.17`?

We can't really do that without a major bump as it'll technically be a breaking change, and it seems too small of a thing to bump major for.

**Comment by clshortfuse** [comment]
@TimothyGu Thanks. It does appear that anything `<10.1` will fail because `fs.promises` doesn't exist until then. Before `10.1` it was `fs/promises`. I'll have to check if any of my deployments are running something versions. So an engine change might be proper. For `>10.1 && <10.16` it's just a warning.

https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.1.0

**Comment by TimothyGu** [comment]
Ah, that's unfortunate. FWIW, one of jsdom's dependencies [webidl-conversions](https://github.com/jsdom/webidl-conversions/blob/master/package.json) already requires v10.4 (which is pre-LTS and introduces BigInt), so if you use any version lower than 10.1 you should already see a warning at installation. It's good practice in general to always stay at the latest branch release for crucial security updates.

**Comment by domenic** [comment]
Node v10 is no longer supported by jsdom, so closing.
