### ISSUE TITLE
How to change the default URL passed on the constructor JSDOM afterwards?

### ISSUE THREAD

**Issue by evandrocoan** [jsdom/jsdom#2946]
This is the default constructor:
```js
const dom = new JSDOM(``, {
  url: "https://example.org/",
  referrer: "https://example.com/",
  contentType: "text/html",
  includeNodeLocations: true,
  storageQuota: 10000000
});
```

It has the `url` parameter which defines these things:
> - `url` sets the value returned by `window.location`, `document.URL`, and `document.documentURI`, and affects things like resolution of relative URLs within the document and the same-origin restrictions and referrer used while fetching subresources. It defaults to `"about:blank"`.

How can I change the value of `url` after calling the constructor?

Does `jsdom.changeURL(window, 'https://localhost:9001')` changes all the values returned by `window.location`, `document.URL`, and `document.documentURI`, and affects things like the resolution of relative URLs within the document?

The constructor `const dom = new JSDOM()` does not take a `window` object as required by `jsdom.changeURL`. Why it does `jsdom.changeURL()` requires a `window` object while the constructor `new JSDOM()` does not?

**Comment by domenic** [comment]
I don't know what `jsdom.changeURL` is, but you're probably looking for https://github.com/jsdom/jsdom#reconfiguring-the-jsdom-with-reconfiguresettings

**Comment by evandrocoan** [comment]
Thanks! In that example, what are the `windowTop` and `myFakeTopForTesting`?

Look at this test, it seems I do not have to pass `windowTop` and I can only use `url`.
https://github.com/jsdom/jsdom/blob/11be37a64315de57a02486010b725a49a69ac796/test/api/methods.js#L198-L204
