### ISSUE TITLE
document.hasFocus() should be true after .activeElement removal

### ISSUE THREAD

**Issue by eps1lon** [jsdom/jsdom#2953]
### Basic info:

- **Node.js version:** 10.20.1
- **jsdom version:** 16.2.2

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const { window: { document } } = new JSDOM(`
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
<body>
  <button>to be removed</button>
</body>
</html>
`);

const logFocusState = () =>
  console.log(`hasFocus(): ${String(document.hasFocus())}`);
const button = document.querySelector("button");

logFocusState();

button.focus();

logFocusState();

button.parentElement.removeChild(button);

logFocusState();
```

logs
```
"hasFocus(): false"
"hasFocus(): true"
"hasFocus(): false"
```

-- https://runkit.com/eps1lon/5ea04de6ae4fb3001afacf54

### How does similar code behave in browsers?

```
"hasFocus(): false"
"hasFocus(): true"
"hasFocus(): true"
```

-- https://jsbin.com/jirefovida/edit?html,js,console

Tested in: Chrome 81

In the jsbin you won't be able to observe the same sequence in firefox since it never allows the element to be focused since the iframe isn't focused. However, if you focus the iframe you'll see the hasFocus() remains true after the element removal.

**Comment by domenic** [comment]
Nice catch. The relevant part of the spec is https://html.spec.whatwg.org/#focus-fixup-rule. A fix would be much appreciated.
