### ISSUE TITLE
Custom Elements Registry seems to be shared across JSDOM instances

### ISSUE THREAD

**Issue by carlosmaniero** [jsdom/jsdom#2960]
### Basic info:

- **Node.js version:** v12.8.1
- **jsdom version:** 6.2.2

### Minimal reproduction case

```js
const {JSDOM} = require('jsdom');
const window1 = new JSDOM().window;
const window2 = new JSDOM().window;
const window3 = new JSDOM().window;

window1.customElements.define('my-element', class extends window1.HTMLElement {})
window2.customElements.define('my-element', class extends window2.HTMLElement {})
window3.customElements.define('my-element', class extends window3.HTMLElement {})
```

#### Produces
```DOMException [NotSupportedError]: This name has already been registered in the registry```

### How does similar code behave in browsers?

I'm using JSDOM to render my Custom Elements on Server Side. Sometimes, if two requests are made at the same time, a `DOMException [NotSupportedError]: This name has already been registered in the registry` is raised. My guess is that Custom Elements Registry has been shared across multiple JSDOM instances.

This **is not** a major issue and I was able to make this workaround:

```js
if (window.customElements.get(selector)) {
    return;
}
if (window.customElements.register(selector, myCustomElement)) 
```

**Comment by TimothyGu** [comment]
You are defining `my-element` on both `window2.customElements` twice… is that intended?

**Comment by carlosmaniero** [comment]
This is just a single plain code to be easy to reproduce. 

### A scenario a little bit more realistic:

I have an express endpoint that does something like this:
```js
app.get('/', function (req, res) {
    const dom = new JSDOM('<my-element></my-element>');

    dom.window.customElements.define('my-element', class extends window1.HTMLElement {
        // ...
    });

    res.send(dom.serialize());
});
```

When I ran this few times I get the issue:

```sh
curl http://localhost/
curl http://localhost/
```

To make the server side rendering work I need to have an instance of JSDOM per request. As it seems to be sharing the `Custom Element Registry` across instances the issue happens.
