### ISSUE TITLE
globalThis is not defined on Node 10

### ISSUE THREAD

**Issue by ianschmitz** [jsdom/jsdom#2961]
We're currently running into issues [upgrading Create React App](https://github.com/facebook/create-react-app/pull/8955) to use the latest versions of Jest and jsdom (26 and 16 respectively). When running our test suite on Node 10.20.1, we receive this error: 

```
    ReferenceError: globalThis is not defined

      at evalmachine.<anonymous>:1:1
      at setupWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:51:55)
      at new Window (node_modules/jsdom/lib/jsdom/browser/Window.js:107:3)
      at exports.createWindow (node_modules/jsdom/lib/jsdom/browser/Window.js:38:10)
      at new JSDOM (node_modules/jsdom/lib/api.js:36:20)
```

After digging in with @SimenB, we discovered that it appears to potentially be caused by a core-js polyfill of `globalThis` (we're still investigating if we can work around in some way).

Here is a repro as copied from @SimenB's comment here: https://github.com/jsdom/jsdom/issues/2795#issuecomment-624460723 (thanks for digging into the issue with me Simen!)

> 
> FWIW, this reproduces the issue:
> 
> // polyfill globalThis for older nodes
> globalThis = global;
> const { JSDOM } = require('jsdom');
> new JSDOM('', {runScripts: 'dangerously'});
> Setting globalThis to anything at all will reproduce, I just picked global to be somewhat realistic. An even more realistic polyfill might be require('core-js'); which will also break, and might (I haven't verified) be inserted by @babel/preset-env and/or @babel/runtime.
> 
> Not sure it's necessarily something that needs to be fixed/changed in JSDOM, but it might be made more robust*? Anyways, hopes this helps folks hitting this issue to track it down. It's not Jest itself that does this.
> 
> *) e.g. filtering on vm.runInContext('this', windowInstance) rather than global in the outer context. This might not be feasible, I haven't played with it.

**Comment by ianschmitz** [comment]
Update: I've found what is polyfilling `global.globalThis` in our case: https://github.com/microsoft/TypeScript/blob/27616dd523279a5d699d2154edb4de6abc8234ad/src/services/globalThisShim.ts#L21

**Comment by s0l0c0ding** [comment]
got the same issue on my angular blog was using "jsdom": "^16.2.2" and node 10, all  went smoothly after updating node to 12

**Comment by bidoubiwa** [comment]
The solution to this is to use this library https://www.npmjs.com/package/jest-environment-jsdom which uses the previous version of jest (jest-environment-jsdom@25). 
Jest 25 uses the jsdom version that still support node 10. 

```
// package.jsom
    "jest-environment-jsdom": "25.5",
```

```javascript
// jest config
      displayName: 'dom',
      testEnvironment: 'jest-environment-jsdom',
```

**Comment by bidoubiwa** [comment]
The solution to this is to use this library https://www.npmjs.com/package/jest-environment-jsdom which creates a jest jsdom environment with the version jsdom from any jest version.

For example, by using jest-environment-jsdom version 25, you will use the jsdom from this version. And in jest 25, the jsdom version was still compatible with node 10

```
// package.jsom
    "jest-environment-jsdom": "25.5",
```

```javascript
// jest config
      displayName: 'dom',
      testEnvironment: 'jest-environment-jsdom',
```

**Comment by domenic** [comment]
Node v10 is no longer supported by jsdom, so closing.
