### ISSUE TITLE
which version is the max version and base on node8/9,not node 10?

### ISSUE THREAD

**Issue by yhuaqiang** [jsdom/jsdom#2964]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by TimothyGu** [comment]
You can use jsdom v15 with Node.js v8.x. See https://github.com/jsdom/jsdom/blob/master/Changelog.md#1600.

You should never use Node.js v9.x.
