### ISSUE TITLE
Reporting `nodeLocation`s for nodes which were dynamically created is surprising

### ISSUE THREAD

**Issue by bakkot** [jsdom/jsdom#2968]
### Basic info:

- **Node.js version:** v12.16.2
 **jsdom version:** v16.2.2

### Minimal reproduction case

```js
let jsdom = require('jsdom');

let dom = new jsdom.JSDOM('<a><b></a></b>', { includeNodeLocations: true });

let b = dom.window.document.querySelector('b');
console.log(dom.nodeLocation(b).startOffset);

dom.window.document.querySelector('a').innerHTML = '<b></b>';
b = dom.window.document.querySelector('b');
console.log(dom.nodeLocation(b) && dom.nodeLocation(b).startOffset);
```

The first `console.log` prints `3`, which is good. The second prints `0`, which is surprising to me - at that point `b` does not exist in the actual source. Also, offset `0` in the original source has nothing to do with `b`.

This changed in 49353e224b6c59e48c3cc7da3700dbe93a2286ac (first released in 14.1.0); prior to that commit, the above would have printed `3` and `undefined`.

This breaks consumers which assume they can safely map location information, if it exists, back to the original source. E.g. this breaks ecmarkup, which is doing [exactly that](https://github.com/tc39/ecmarkup/blob/6aa114edb04c1e590f6d52760e7c9abd3e2545ce/src/Grammar.ts#L19).

### How does similar code behave in browsers?

N/A

**Comment by TimothyGu** [comment]
I think a better option would probably be to include the URL path in the object returned by `nodeLocation`, if possible. Would that work for ecmarkup?

**Comment by bakkot** [comment]
I'm not sure what "the URL path" means in the context of nodes dynamically inserted with `innerHTML`.

**Comment by TimothyGu** [comment]
I was thinking the URL of the script that set the innerHTML, but I guess that wouldn't work too well if the script is part of the HTML file itself hmm.

**Comment by bakkot** [comment]
Would you accept a patch which disabled node locations when parsing with `innerHTML` and `outerHTML`? If yes, would you also want it disabled during

- `createContextualFragment`
- DOMParser `parseFromString`
- frame creation
- XHR `responseXML`

which are the other places it looks like node locations are being tracked?
