### ISSUE TITLE
setAttribute does not allow to set empty value

### ISSUE THREAD

**Issue by panec** [jsdom/jsdom#2977]
### Basic info:

- **Node.js version:** 10.20.1
- **jsdom version:** 16.2.2

According to specification it is possible to set attribute with no value. This attribute becomes a boolean attribute and its value is treated as `true`.

> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; as a rule, you should specify the empty string ("") in value

https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

So when calling `.setAttribute('disabled', '')` the expected result is attribute of `disabled` and not `disabled=""`.

### Minimal reproduction case
```js
const { JSDOM } = require('jsdom');
const dom = new JSDOM(`<!DOCTYPE html><input type="checkbox" checked>`);
dom.window.document.querySelector('input').setAttribute('disabled', '');
const serializedDom = dom.serialize();
```

Value of `serializedDom` is 
```html
<!DOCTYPE html><html><head></head>
<body><input type="checkbox" checked="" disabled=""></body>
</html>
```

### How does similar code behave in browsers?
Value of `serializedDom` in browser is
```html
<!DOCTYPE html><html><head></head>
<body><input type="checkbox" checked disabled></body>
</html>
```

**Comment by TimothyGu** [comment]
If you put
```html
<!DOCTYPE html><html><head></head>
<body><input id="test" type="checkbox" checked></body>
</html>
```
in a file and run the following in the browser console
```js
test.setAttribute('disabled', '')
document.documentElement.outerHTML
```
You will see that the output is 
```html
<html><head></head><body><input type="checkbox" checked="" disabled=""></body></html>
```
So our behavior is spec-compliant.

In general, the serialization algorithm for HTML elements doesn't take into account information about the specific attribute. The fact that `disabled` has the same effect as `disabled=""` is roughly analogous to `{ prop: 3 }` having the same effect as `{ "prop": 3 }` in JavaScript – but only the latter is used in JSON, a serialization format, just like how only `disabled=""` is used in the canonical HTML serialization.
