### ISSUE TITLE
Don't update the _lastFocusedElement when calling focus on a detached node.

### ISSUE THREAD

**Issue by kentcdodds** [jsdom/jsdom#2978]
### Basic info:

- **Node.js version:** Any (tried on 12)
- **jsdom version:** Any (tried on 16)

### Minimal reproduction case

https://repl.it/repls/ImmaculateHumongousCompilers

```js
const { JSDOM } = require("jsdom")

const options = {}
const {window} = new JSDOM(`
  <html><body></body></html>
`, options)

const {document} = window

function test() {
  const div = document.createElement('div')
  const button = document.createElement('button')
  div.append(button)
  document.body.append(div)
  button.focus()

  if (document.activeElement !== button) {
    throw new Error('button not focused')
  }

  div.remove()

  if (document.activeElement !== document.body) {
    throw new Error('div removed, but body not focused')
  }

  button.focus()

  if (document.activeElement !== document.body) {
    throw new Error('focus called on a detached node, but focus not preserved on body')
  }
}

test()
```

### How does similar code behave in browsers?

Note that if you copy/paste/invoke `test` into the browser console or a regular JavaScript file then there are no errors: https://jsbin.com/wuqukirazo/edit?js,console

From my observations, I think that when `focus` is called on a detached node, it should not update the `_lastFocusedElement` here:

https://github.com/jsdom/jsdom/blob/5e39a4c60377c95ac09ea938ecbf5f1f91cb0360/lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js#L46

At least, that's what makes sense to me.

**Comment by eps1lon** [comment]
Alternative jsbin+runkit that reproduces the same issue as far as I can tell but requires less setup:

JSDOM 16.3:
```js
const { JSDOM } = require("jsdom");

const { window: { document } } = new JSDOM(`
<!DOCTYPE html>
<html>
  <head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
  </head>

  <body></body>
</html>
`);

const button = document.createElement('button');
button.addEventListener('focus', () => console.log('focus'));

console.log(document.activeElement.tagName)
button.focus();
console.log(document.activeElement.tagName)
```
-- https://runkit.com/eps1lon/5f08c75bb6983b001a2c0fbb

logs:
```
"BODY"
"focus"
TypeErrorStack Trace Viewer
TypeError: Cannot read property 'tagName' of null
```

Chrome Version 83.0.4103.116 (Official Build) (64-bit), Firefox 78.01:
```js
const button = document.createElement('button');
button.addEventListener('focus', () => console.log('focus'));

console.log(document.activeElement.tagName)
button.focus();
console.log(document.activeElement.tagName)
```
-- https://jsbin.com/cuwugowovu/1/edit?js,console

logs:
```
"BODY"
"BODY"
```

I'm working on a test+(hopefully) fix.
