### ISSUE TITLE
Appending declarative shadow root to template tag

### ISSUE THREAD

**Issue by Wildhoney** [jsdom/jsdom#2983]
### Basic info:

- **Node.js version:** `v14.3.0`
- **jsdom version:** `v16.2.2`

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');
const document = new JSDOM().window.document;

const template = document.createElement('template');
template.setAttribute('shadowroot', 'open');

const text = document.createTextNode('Imogen!');
template.appendChild(text);

console.log(template.outerHTML);
```

**Result:**
```javascript
<template shadowroot="open"></template>
```

**Expected:**

```javascript
<template shadowroot="open">Imogen!</template>
```

### How does similar code behave in browsers?

Chrome implementation of the proposal with working example: https://www.chromestatus.com/feature/5191745052606464

**Comment by domenic** [comment]
Thanks, but we have no intention of implementing based on a proposal. If this becomes a standard, we can consider devoting our spare time to working on it.

**Comment by Wildhoney** [comment]
👍

**Comment by TechQuery** [comment]
@Wildhoney @domenic I have published [a polyfill for the final version of this proposal][1], which has been used for **VDOM/JSX to HTML** generation: EasyWebApp/DOM-Renderer#5

[1]: https://github.com/EasyWebApp/declarative-shadow-dom-polyfill

**Comment by SparK-Cruz** [comment]
Any updates on this one?
