### ISSUE TITLE
Serialization with formatting?

### ISSUE THREAD

**Issue by opcodewriter** [jsdom/jsdom#2985]
I'm using JSDOM to create XML on the fly. 
Is there a way to serialize with formatting? `serialize()` doesn't seem to have any options. I also looked at the options in the JSDOM constructor, no luck with that either.

**Comment by domenic** [comment]
No. I suggest you look into dedicated packages for formatting XML; jsdom acts as a DOM, not a beautifier.

**Comment by papandreou** [comment]
I needed some pretty-printing abilities in assetgraph (which also uses jsdom), and came up with this solution: https://github.com/papandreou/domspace

**Comment by opcodewriter** [comment]
> 
> 
> No. I suggest you look into dedicated packages for formatting XML; jsdom acts as a DOM, not a beautifier.

Do you have any suggestions for a package or packages? Thanks!
