### ISSUE TITLE
querySelectorAll cannot be chained

### ISSUE THREAD

**Issue by Kadrian** [jsdom/jsdom#2987]
### Basic info:

- **Node.js version: 14
- **jsdom version: 16.2.2

### Minimal reproduction case

```js
  const dom = new JSDOM(
    '<div class="xyz"><table><tbody><tr><td>Hello</td></tr></tbody></table><table></table></div>'
  );

  const x = dom.window.document
    .querySelector(".xyz table")
    .querySelectorAll("tr");

  console.log(x); // Expected a TR Element, got NodeList {}
```

### How does similar code behave in browsers?

In a browser I'm getting the TR element.

**Comment by domenic** [comment]
Can you post a link to a jsbin? querySelectorAll does not return a TR element; it returns a NodeList.
