### ISSUE TITLE
JSDom returns integer instead of timer

### ISSUE THREAD

**Issue by retrohacker** [jsdom/jsdom#2989]
### Basic info

```js
const timer = setInterval(console.log("hai"), 1000);
timer.unref()
```

### Expected Result

```
$ node index.js
bai
```

### Actual Result

```
$ node index.js
TypeError: id.unref is not a function
```

**Comment by domenic** [comment]
This issue does not follow the issue template, so we'll close it.

**Comment by retrohacker** [comment]
Sorry. Re-opened with less template mangling here: https://github.com/jsdom/jsdom/issues/2990
