### ISSUE TITLE
Not implemented: HTMLMediaElement.prototype.pause

### ISSUE THREAD

**Issue by Solomon-m** [jsdom/jsdom#2992]
_Hello everyone, 
Someone point me in the right direction. I am getting following error while running test cases. I am using React testing library. I am trying to test my component which has audioTag in it. Thanks in Advance._ 

console.error node_modules/@testing-library/react/dist/act-compat.js:52
    `Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. `

 PASS   MyApp src/__tests__/audioTag.test.js
  <==== AudioTag ====>
    ✓  AudioTag (466ms)

  `console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29`
    `Error: Not implemented: HTMLMediaElement.prototype.pause`
        `at module.exports (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)`
        `at HTMLAudioElementImpl.pause (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/nodes/HTMLMediaElement-impl.js:119:5)`
        `at HTMLAudioElement.pause (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/generated/HTMLMediaElement.js:125:34)`
        `at AudioPlayer.componentWillUnmount (/Users/solomon/Documents/Myapp/server/src/components/commons/components/audioplayer/index.js:302:16)`
        `at callComponentWillUnmountWithTimer (/Users/solomon/Documents/Myapp/node_modules/react-dom/cjs/react-dom.development.js:19580:12)`
        `at HTMLUnknownElement.callCallback (/Users/solomon/Documents/Myapp/node_modules/react-dom/cjs/react-dom.development.js:188:14)`
        `at innerInvokeEventListeners (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)`
        `at invokeEventListeners (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)`
        `at HTMLUnknownElementImpl._dispatch (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)`
        `at HTMLUnknownElementImpl.dispatchEvent (/Users/solomon/Documents/Myapp/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:101:17) undefined`

**Comment by domenic** [comment]
This issue does not follow the issue template, and as such isn't something we can help with.
