### ISSUE TITLE
`Node` interface doesnt expose constants for node types like Node.TEST_NODE

### ISSUE THREAD

**Issue by mozfreddyb** [jsdom/jsdom#2993]
### Basic info:

- **Node.js version:** N/A
- **jsdom version:** latets

### Minimal reproduction case

jsdom's `Node` interface does not expose numerical constants for node types, e.g. `Node.TEXT_NODE,` `Node.ELEMENT_NODE` etc.

Note that those are already widely used and available in the source. It's just not hanging off of the `Node` interface you provide.

### How does similar code behave in browsers?

Works as specified

**Comment by domenic** [comment]
This issue does not follow the issue template, including a minimal reproduction case we can run to confirm, or a Node.js version we can test against. As such, I'll close it.

**Comment by bmaupin** [comment]
Apparently the types are accessible through the DOM's `.window.Node` (https://github.com/jsdom/jsdom/issues/2220#issuecomment-917436488).

This might be a terrible hack, but instead I just added this to the top of my file:

```javascript
const Node = new JSDOM('').window.Node;
```
