### ISSUE TITLE
How to serialize a cloned document, to avoid re-parsing

### ISSUE THREAD

**Issue by Lcfvs** [jsdom/jsdom#2994]
### Basic info:

- **Node.js version:** 14.0.0
- **jsdom version:** 16.2.2

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {};
const dom = new JSDOM(`<!DOCTYPE html>`, options);
const { window: { document } } = dom
const clone = document.cloneNode(true)

clone.documentElement.id = 'an-id'
console.log(dom.serialize()) // serializes the original document
```

### How does similar code behave in browsers?
N/A

**Comment by Lcfvs** [comment]
Actually, I do that:

```js
function serialize (node) {
  const rendered = node[render]()
  const { documentElement } = rendered

  if (!documentElement) {
    return serializer.serializeToString(rendered)
  }

  const dom = new JSDOM('<!DOCTYPE html>')
  const { window: { document } } = dom

  document.replaceChild(documentElement, document.documentElement)

  return dom.serialize()
}
```

But, why not an optional parameter, to `dom.serialize()`?

```js
 serialize(document = this[window]._document) {
    return fragmentSerialization(idlUtils.implForWrapper(document), { requireWellFormed: false });
  }
```

**Comment by domenic** [comment]
`dom.serialize()` serializes `dom`; it's not meant as a general serializer of any `JSDOM` instance. (I.e., it's an instance method, not a static.)

In general if you have a `Document`, and not a `JSDOM` instance, which you want to serialize, you're going to need to use the normal mechanisms for serializing `Document` objects, i.e. whatever you would normally do in a browser.
