### ISSUE TITLE
JSDOM - BigInt usage crashing on Safari

### ISSUE THREAD

**Issue by kvnam** [jsdom/jsdom#3010]
### Basic info:

- **Node.js version:** 12.13.0
- **jsdom version:** 16.3.0

### Minimal reproduction case

```
import JSDOM   from 'jsdom';

const { window } = new JSDOM();

```
The use of BigInt is causing my React application to crash in Safari. I had to bump the version down to 16.2.0 to fix this. It seems the recent update to `webidl-conversions` library is the cause, as BigInt was added there. Thanks!

### How does similar code behave in browsers?
Opening the code sandbox in Safari and Firefox is throwing errors linked to the BigInt, SharedArrayBuffer etc. from the  `webidl-conversions`files

https://codesandbox.io/s/condescending-wood-y38n1?file=/src/App.js:128-139 
![JSDOM_Safari_BigInt](https://user-images.githubusercontent.com/3608742/87772628-a2520300-c83f-11ea-8282-0ee19ba7078b.jpg)

**Comment by domenic** [comment]
This issue does not follow the issue template, as it used syntax that does not work in the specified Node.js version. As such, we'll close it. If you can supply a minimal reproduction case which I can put in a file named `test.js` and then get an error when running `node test.js` we can reopen.

**Comment by atlsykes** [comment]
So I was getting this same error in Chrome with a new React app. and it just popped up over this past weekend (7/24 - 7/25). I had to downgrade to 15.0.0 to fix it (too far?). Sticking with this version for now... Node version 14.7.1.

**Comment by dattm97** [comment]
I downgrade jsdom to 16.2.0 and use with DOMPurify version 2.3.10 but i got error message like that

<img width="934" alt="image" src="https://user-images.githubusercontent.com/76091352/183393578-41dfeee2-a49e-474f-8eb2-277934390dd5.png">
