### ISSUE TITLE
How to stringify jsdom?

### ISSUE THREAD

**Issue by cata-code** [jsdom/jsdom#3014]
I would like to pass the entire JSDOM object from node.js to the client (electron chrome), and then navigate the jsdom object from there.

I tried `dom.serialize()` but it just dumps an html string.
I tried `JSON.stringify(dom)` but it's just an empty object.

For reference my code is

```js
async parseHtmlCssFile (file) {
    const dom = await JSDOM.fromFile(file, { resources: 'usable' })
    return new Promise((resolve, reject) => {
      dom.window.document.addEventListener('DOMContentLoaded', () => {
        // how do I stringify the dom object?
        return resolve(dom)
      })
    })
  }
```

**Comment by domenic** [comment]
This isn't really possible. A DOM contains a complex myriad of information at every level of the tree. You're not going to be able to serialize it easily, and certainly not with any built-in functionality of JSDOM.

**Comment by cata-code** [comment]
@domenic Thank you. Then I shall do all the logic in node.js and just pass to the client the end result.
