### ISSUE TITLE
Bug: ResourceLoader needs decodeURI(file)

### ISSUE THREAD

**Issue by cata-code** [jsdom/jsdom#3016]
I have an html file that links to this css file `<link rel="stylesheet" href="css/page/hey 진 シーン/i 🥰 you 😘😘😘😘/yolo.css">` and when jsdom needs to load the css file with the `resources: 'usable'` option, it fails with this error:

```
Error: Could not load link: "file:///home/user/dev/test-folder/css/page/hey%20%EC%A7%84%20%E3%82%B7%E3%83%BC%E3%83%B3/i%20%F0%9F%A5%B0%20you%20%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98/yolo.css"
    at onErrorWrapped (/home/user/dev/code/app/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:38:19)
    at Object.check (/home/user/dev/code/app/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:72:23)
    at /home/user/dev/code/app/node_modules/jsdom/lib/jsdom/browser/resources/resource-queue.js:83:27
    at processTicksAndRejections (internal/process/task_queues.js:94:5) [Error: ENOENT: no such file or directory, open '/home/user/dev/test-folder/css/page/hey %EC%A7%84 %E3%82%B7%E3%83%BC%E3%83%B3/i %F0%9F%A5%B0 you %F0%9F%98%98%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98/yolo.css'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/user/dev/test-folder/css/page/hey %EC%A7%84 %E3%82%B7%E3%83%BC%E3%83%B3/i %F0%9F%A5%B0 you %F0%9F%98%98%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98/yolo.css'
```
I think we need to add an `decodeURI(file)` when fetching the resource file

### Basic info:

- **Node.js version:** 14.4.0
- **jsdom version:** 16.3.0

**Comment by domenic** [comment]
What URL does your browser try to load when you load that file into it? Can you provide the full example so that we can run it, per the issue template?

**Comment by cata-code** [comment]
Probably here we need to add `encodeUri()`
https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/resources/resource-loader.js#L46

**Comment by cata-code** [comment]
The URL is `css/page/hey 진 シーン/i 🥰 you 😘😘😘😘/yolo.css`
and in the address bar it becomes `file:///home/user/dev/test-folder/hey%20%EC%A7%84%20%E3%82%B7%E3%83%BC%E3%83%B3/i%20%F0%9F%A5%B0%20you%20%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98%F0%9F%98%98/yolo.html`

**Comment by cata-code** [comment]
@domenic  Adding `filePath = decodeURI(filePath)` in https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/resources/resource-loader.js#L46 fixes the issue

**Comment by cata-code** [comment]
@domenic Any updates on this? Applying the change above fixes the issue.

**Comment by domenic** [comment]
Your diagnosis seems reasonable. A pull request, including tests, would be accepted.

**Comment by cata-code** [comment]
I tried to make a test but my system uses python 3 not 2 and I didn't want to mess that up again just for a small test

https://web-platform-tests.org/running-tests/from-local-system.html#system-setup
At least that's what this document says.
