### ISSUE TITLE
document property only contains a "location" property

### ISSUE THREAD

**Issue by octalpixel** [jsdom/jsdom#3017]
### Basic info:
Hi,
Started using JSDOM today and ran into a small problem. When using axios and  passing data it on JSDOM, I get only document location and nothing else in the HTMLELEMENT
Any possible reason why ? 

- **Node.js version:** 12.16.1
- **jsdom version:** 16.3.0

**Comment by domenic** [comment]
This issue does not follow the issue template, with code that we can use to reproduce the problem. As such, we will close it. Feel free to leave a comment if you have edited the OP to follow the template.

**Comment by Blummer92** [comment]
I have the same question. I was trying to use axios to pull data and then JSDOM to read that data as I do with cheerio. here is a snipit of what I'm looking at:
`
const axios = require("axios");
const read = require("jsdom");
const url = "https://.com";

axios(url).then(response => {
  const html = response.data;
  const $ = read.load(html);
  const summeryTable = $(
    read.window.document.querySelector(".video-action-tab about-tab active")
      .textContent
  );
  console.log(summeryTable.length);
});
`
