### ISSUE TITLE
document property only contains a "location" property 

### ISSUE THREAD

**Issue by octalpixel** [jsdom/jsdom#3018]
### Basic info:

- **Node.js version:** 12.16.1
- **jsdom version:** 16.3.0

### Minimal reproduction case

```js
const jsdom = require("jsdom")
const { JSDOM } = jsdom

const dom = new JSDOM(`<!DOCTYPE html><body><p id="main">My First JSDOM!</p></body>`)

console.log(dom.window.document)
console.log(dom.window.document.querySelector("body"));
console.log(dom.window.document.children);
console.log(dom.window.document.contentType);
```
This is the output that I get for the console.log
```js
Document { location: [Getter/Setter] }
HTMLBodyElement {}
HTMLCollection {}
text/html
```

### How does similar code behave in browsers?
N/A

**Comment by domenic** [comment]
This is due to how Node.js's console outputs values. All the properties are still there. As you can see from the fact that e.g. `.children` and `.contentType` work.

**Comment by octalpixel** [comment]
Wow! Thanks. My bad it works!
