### ISSUE TITLE
TypeError: Cannot read property 'innerHTML' of null [Query - no issue]

### ISSUE THREAD

**Issue by juanamm** [jsdom/jsdom#3020]
Could you help me get the inner element?
`var currentSong = document.getElementById('currentSong').innerHTML;`
                                                                                                ^
TypeError: Cannot read property 'innerHTML' of null

I am a novice and I do not understand the syntax that I must put before to be able to obtain the internal element.

I try with:

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
global.document = new JSDOM('http://127.0.0.1/').window.document;
var currentSong = document.getElementById('currentSong').innerHTML;

```

Also try:

```
global.document = new JSDOM('http://127.0.0.1/').window.document;
var currentSong = global.document.getElementById('currentSong').innerHTML;
```

Obviously I am making a mistake in the syntax. :/

**Comment by domenic** [comment]
Read the README in more detail. You're passing the HTML string `http://127.0.0.1/` to JSDOM. There is no element with ID `currentSong` inside that string; it's just some text.

If you want to pass a URL, you'll want to use something like `JSDOM.fromURL()`.

**Comment by juanamm** [comment]
@domenic, forget that about the URL I put it out of ignorance.

I want to get this:
var currentSong = **document.getElementById('currentSong').innerHTML;**

I don't know what to put before that.
