### ISSUE TITLE
Despite Reading And Trying Solutions From Past Issues I Cannot Get JSDOM To Load My Script

### ISSUE THREAD

**Issue by EricRicketts** [jsdom/jsdom#3023]
### Basic info:

- **Node.js version:** 14.7.0
- **jsdom version:** 16.3.0
- **jest version:** 26.2.1

### Minimal reproduction case

**HTML**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>A Simple Example Load The Script</title>
  <script type="text/javascript" src="./simple_example_launch_school.js"></script>
</head>
<body>
  <p>
    <span id="output">0</span>
    <button id="add">Add One</button>
    <button id="reset">Reset</button>
  </p>
</body>
</html>
```

**Javascript code => simple_example_launch_school.js**
```js
document.addEventListener('DOMContentLoaded', () => {
  let count = 0;
  let output = document.getElementById('output');
  let addButton = document.getElementById('add');
  let resetButton = document.getElementById('reset');

  addButton.addEventListener('click', () => {
    count += 1;
    output.textContent = String(count);
  });

  resetButton.addEventListener('click', () => {
    count = 0;
    output.textContent = String(count);
  });
});
```

**Jest Test Code**
```js
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

describe('Launch School A Simple Example', function () {
  let results, html, expected, window, document, output, addButton, resetButton;
  describe('Load Script In JSDOM Vice External Loading', function () {
    beforeEach(() => {
      let codeDirectory = path.join(__dirname, '..', 'code');
      html = fs.readFileSync(codeDirectory + '/main.html', 'utf8');
        let options = {
          resources: 'usable',
          runScripts: 'dangerously',
        };
        const dom = new JSDOM(html, options)
        dom.window.document.addEventListener('DOMContentLoaded', () => {
          // We need to delay one extra turn because we are the first DOMContentLoaded listener,
          // but we want to execute this code only after the second DOMContentLoaded listener
          // (added by external.js) fires.
          setImmediate(() => {
            console.log(dom.window.document.body.children.length);
            console.log(dom.window.document.body.innerHTML);
          });
        });
      window = dom.window;
      document = window.document;
      output = document.getElementById('output');
      addButton = document.getElementById('add');
      resetButton = document.getElementById('reset');
    });

    it('should allow output to increment via the add button',  ()  => {
      expected = ["0", "1", "2"];
      results = [output.textContent];
      addButton.click();
      results.push(output.textContent);
      addButton.click();
      results.push(output.textContent);
      expect(results).toEqual(expected);
    });
  });
});
```

**Warnings/Test Results**
```
Cannot log after tests are done. Did you forget to wait for something async in your test?

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Array [
        "0",
    -   "1",
    -   "2",
    +   "0",
    +   "0",
      ]
```

### How does similar code behave in browsers?

My first step regarding debugging was to run the code in the browser (Brave) it worked fine, both the increment event and the reset event.

### Further Debugging Steps

Before I go into my debugging process, just a little background.  I am dong a very thorough online Programming/Web Development course called Launch School.  I am currently near the end of the program and we are learning how to setup
event listeners in the DOM.  I love to test, so I always take any given problem and try to write a test for it.

In a separate test I was able to get everything working by not loading any javascript files via the script tag and setting up
all the event listeners in the ```beforeEach``` function.  Obviously, it is far more convenient to have all of the necessary event listeners setup before I makes assertions in my test file.  This is what I was trying to accomplish.

We have covered the traditional callback mechanisms and I have tested with callbacks in Jest, however, the course has not covered Promises yet, I will get to that shortly.

**Debugging Steps:**
1.  Checked that the html file as being read properly.  OK.
2.  Reviewed and studied to the best of my ability #1914 and #1924.  As a matter of fact my last attempted solution was to use the code from **Domenic Denicola** arising from issue #1914.
3.  I tried using ```done``` and ```done()``` in my ```beforeEach``` function.  I was not really hopeful in this case because I do not see how Jest can monitor ```DOMContentLoaded```.
4.  I tried Jest's ```async/await``` options in both my test assertion code (the ```it```) and in ```beforeEach```.
5.  Obviously, the script is not loading before I make my assertions and Jest is giving me a warning telling me so.  So how in the world do I robustly ensure the script has been loaded?

**Comment by domenic** [comment]
Thank you for the detailed issue. However, we cannot help debug issues with third-party frameworks and libraries like Jest. Would you be able to create a minimal example that does not use third-party libraries, but instead only jsdom?

**Comment by EricRicketts** [comment]
Sorry about that, it never crossed my mind that the JSDOM team would also have to look into Jest.  I have a lot to learn!!  Regardless, here is my new **minimal example** making use of the current code base.

**HTML Remains The Same**
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>A Simple Example Load The Script</title>
  <script type="text/javascript" src="./simple_example_launch_school.js"></script>
</head>
<body>
  <p>
    <span id="output">0</span>
    <button id="add">Add One</button>
    <button id="reset">Reset</button>
  </p>
</body>
</html>
```

**Javascript Code Remains The Same, What main.html loads => simple_example_launch_school.js**
```js
document.addEventListener('DOMContentLoaded', () => {
  let count = 0;
  let output = document.getElementById('output');
  let addButton = document.getElementById('add');
  let resetButton = document.getElementById('reset');

  addButton.addEventListener('click', () => {
    count += 1;
    output.textContent = String(count);
  });

  resetButton.addEventListener('click', () => {
    count = 0;
    output.textContent = String(count);
  });
});
```
**New Test Code Just Run From Command Line => jsdom_only.js**
```node jsdom_only.js```
```js
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');
let codeDirectory = path.join(__dirname, '..', 'code');
html = fs.readFileSync(codeDirectory + '/main.html', 'utf8');
let options = {
  resources: 'usable',
  runScripts: 'dangerously',
};
const dom = new JSDOM(html, options);
dom.window.document.addEventListener('DOMContentLoaded', () => {
  // We need to delay one extra turn because we are the first DOMContentLoaded listener,
  // but we want to execute this code only after the second DOMContentLoaded listener
  // (added by external.js) fires.
  setImmediate(() => {
    console.log(dom.window.document.body.children.length)
    console.log(dom.window.document.body.innerHTML)
    console.log(output.textContent);
    addButton.click();
    console.log(output.textContent);
  });
});
let window = dom.window;
let document = window.document;

let addButton = document.getElementById('add');
let output = document.getElementById('output');

console.log(output.textContent);
addButton.click();
console.log(output.textContent);
```

**Output**
```
0
0
1

  <p>
    <span id="output">0</span>
    <button id="add">Add One</button>
    <button id="reset">Reset</button>
  </p>


0
0
```

**Comments**
We can see what the code did, it output the lower 2 console.logs first, outside of the ```addEventListener``` function, then
in the callback for ```addEventListener``` it output the number of children in ```document.body``` then the ```innerHTML``` for ```document.body``` and finally the two console.logs, which remained at 0.  If the code was working correctly, the second console.log from each pair of console.logs would have output 1.  I was hoping the script would load in the callback for ```addEventListener``` but it looks like it did not.

So do I need to code up some kind of Promise in my **simple_example_launch_school.js** file?  If so, what do I need to check on to make sure the script has loaded?

**Comment by domenic** [comment]
Thanks for the smaller test case!

One big issue I see with the code provided is that you're not setting a URL for your HTML supplied to the `JSDOM` constructor. So, it's not going to be able to resolve relative URLs like `./simple_example_launch_school.js`.

**Comment by EricRicketts** [comment]
You can close the issue, I found a workaround as per #1867, I created a ```script``` tag, read the script itself using ```fs.readFileSync```, set the ```textContent``` of the ```script``` tag to the results of reading the file and then used ```document.head.appendChild``` to append the ```script``` tag to the html.  The test worked fine.  Just for any future reference here is my code:

## Minimal Reproduction Use

### main.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>A Simple Example Load The Script</title>
</head>
<body>
  <p>
    <span id="output">0</span>
    <button id="add">Add One</button>
    <button id="reset">Reset</button>
  </p>
</body>
</html>
```

### simple_example_launch_school.js
```js
document.addEventListener('DOMContentLoaded', () => {
  let count = 0;
  let output = document.getElementById('output');
  let addButton = document.getElementById('add');
  let resetButton = document.getElementById('reset');

  addButton.addEventListener('click', () => {
    count += 1;
    output.textContent = String(count);
  });

  resetButton.addEventListener('click', () => {
    count = 0;
    output.textContent = String(count);
  });
});
```

### another_simple_example.test.js
```js
const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

describe('Launch School A Simple Example', function () {
  let results, dom, html, expected, window, document, output, addButton, resetButton;
  describe('Load Script In JSDOM Vice External Loading', function () {
    beforeEach(() => {
      let codeDirectory = path.join(__dirname, '..', 'code');
      html = fs.readFileSync(codeDirectory + '/main.html');
      let options = {
        resources: 'usable',
        runScripts: 'dangerously',
      };
      let scriptContent = fs.readFileSync(codeDirectory + '/simple_example_launch_school.js', 'utf8');
      dom = new JSDOM(html, options);
      window = dom.window;
      document = window.document;
      let scriptElement = document.createElement('script');
      scriptElement.textContent = scriptContent;
      document.head.appendChild(scriptElement);
      output = document.getElementById('output');
      addButton = document.getElementById('add');
      resetButton = document.getElementById('reset');
    });

    it('should allow output to increment via the add button',  ()  => {
      expected = ["0", "1", "2"];
      results = [output.textContent];
      addButton.click();
      results.push(output.textContent);
      addButton.click();
      results.push(output.textContent);
      expect(results).toEqual(expected);
    });
  });
});
```

A few more comments:
1.  I ran an experiment, I ran the tests with no ```options``` object in the ```JSDOM``` constructor, and the tests failed, this is what I was expecting based on the documentation.
2.  I tried using the ```JSDOM.fromFile``` with the appropriate options and used an external variable ```promiseDOM``` to capture the ```JSDOM``` object from the return promise.  This also failed, more than likely because I am new to Promises and I did not know how to use Jest's ```async/await``` options in my ```beforeEach```.  Right now it is not worth the effort to debug.
3.  More than likely I do not have enough Javascript and browser knowledge to help the jsdom team at this point, since I have found a workaround, it might be best to close the issue.
```

**Comment by domenic** [comment]
Alright, glad you found something that works! I still encourage you to supply a `url` option.

**Comment by hugolpz** [comment]
Hi @Domenic . Like @EricRicketts I really tried to figure out how the `url` option was working by myself but couldn't figure it out from online documentation and examples. It could indeed be a weak point of your documentation to clarify. Ideally, a minimal working demo would be best. Allow me to point out to you [this alternative minimal demo on stackoverflow](https://stackoverflow.com/a/63695076/1974961). It provides most of the initial settings and can be turned into a `url` options loading external js demo easily. :sunflower:

**Comment by cpiber** [comment]
Hi @domenic @hugolpz Bit late to the party, but I found how to be able to load scripts relative to the working directory. You can set the `url` option to `\`file://${__dirname}/index.html\``, then all scripts are resolved relative to the path of the current file.

**Comment by zhex900** [comment]
@cpiber How did you do that?

```  
const html = fs.readFileSync(path.resolve(__dirname, "./index.html"), "utf8"); 
 dom = new JSDOM(html, {
      url: `file://${__dirname}/index.html`,
      runScripts: "dangerously",
    });
````

index.html
````
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="./index.js" ></script>
</head>
````
This does not run index.js.

**Comment by cpiber** [comment]
@zhex900 My particular setup:
```js
const dom = new JSDOM('', { url: `file://${__dirname}/index.html`, runScripts: 'dangerously', resources: 'usable' });
injectScript('../fixtures/log.js', dom);
```
where `injectScript` creates a script tag with the given parameter as `src`.

From the link supplied by @hugolpz:
> If you want to execute external scripts, included via <script src="">, you'll also need to ensure that they load them. To do this, add the option resources: "usable" as [described below](https://github.com/jsdom/jsdom#loading-subresources).
