### ISSUE TITLE
how to get the document variable with a different name

### ISSUE THREAD

**Issue by alexbfree** [jsdom/jsdom#3039]
Hi, just a question.

How do I do this example:
```
const { document } = (new JSDOM(`...`)).window;
```
if I already have a variable called `document` in scope, and I don't want to override it?

**Comment by chkpnt** [comment]
You are looking for the keyword "Object destructuring". A good description of this technique can be found in the [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment): 

<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment"><img width="1048" alt="grafik" src="https://user-images.githubusercontent.com/1956979/93604587-da073380-f9c5-11ea-98e0-3fd411fee88a.png"></a>

**Comment by alexbfree** [comment]
Fantastic - thank you!
