### ISSUE TITLE
Error: Can't resolve 'canvas' 

### ISSUE THREAD

**Issue by amandaytq** [jsdom/jsdom#3042]
### Basic info:

- **Node.js version:** 11.5.0
- **jsdom version:** 16.4.0
- **@angular/core** 10.0.5

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);

$ = require('jquery')(dom.window);
```

### Issue faced: 
I am trying to use jsdom to create window and document objects for my SSR angular project. however, I am experiencing this error. I am using the window to attempt to initialize the jQuery library as previously I kept getting a `jQuery requires window` error. 

```
ERROR in ./node_modules/jsdom/lib/jsdom/utils.js
Module not found: Error: Can't resolve 'canvas' in '/Users/amanda/Documents/project/node_modules/jsdom/lib/jsdom'
```

**Comment by cwagner22** [comment]
Same issue, any fix?

**Comment by amandaytq** [comment]
try to install `https://www.npmjs.com/package/canvas` to your project.

**Comment by cwagner22** [comment]
Thanks, came to the same conclusion after wasting many hours... (just to satisfy gatsby)

**Comment by crazyair** [comment]
install canval
```

 ERROR  Failed to compile with 1 errors                                                                                                                                              10:08:39 AM

 error  in ./node_modules/canvas/build/Release/canvas.node

Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

**Comment by crazyair** [comment]
> try to install `https://www.npmjs.com/package/canvas` to your project.

no fix it

**Comment by zhoukq** [comment]
```
plugins: [
new webpack.IgnorePlugin(/canvas/, /jsdom$/)
]
```
can solve this issue
see https://github.com/konvajs/react-konva/issues/102

**Comment by leobenkel** [comment]
> ```
> plugins: [
> new webpack.IgnorePlugin(/canvas/, /jsdom$/)
> ]
> ```
> 
> can solve this issue
> see [konvajs/react-konva#102](https://github.com/konvajs/react-konva/issues/102)

Where do you add this code ?

**Comment by kkomelin** [comment]
@leobenkel I guess it should be added to your webpack config.

**Comment by gRoussac** [comment]
Hi,

It seems to be now

```
plugins: [
      new webpack.IgnorePlugin({
        resourceRegExp: /canvas/,
        contextRegExp: /jsdom$/,
      }),
    ],
```

Which in Angular Universal server config with ``` "@angular-builders/custom-webpack:server"``` leads to 

```
Compiled successfully.
/srv/www/evaluator/dist/evaluator/server/main.js:168664
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf( /*#__PURE__*/_wrapAsyncGenerator(function* () {})).prototype);
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at 63611 (/srv/www/.../server/main.js:168664:39)
    at __webpack_require__ (/srv/www/.../server/main.js:393617:42)
    at 58986 (/srv/www/.../server/main.js:89808:18)
    at __webpack_require__ (/srv/www/.../server/main.js:393617:42)
    at /srv/www/.../main.js:393821:64
    at /srv/www/.../main.js:393915:3
    at Object.<anonymous> (/srv/www/.../main.js:393920:12)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)

Node.js v18.7.0

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:4000
```
And I really don't know what to do with that now...

Moreover that jsdom can be loaded in Nest.js backend without trouble but not Angular Universal backend.

**Comment by zm3d3ni** [comment]
@gRoussac did you manage to solve the issue?
