### ISSUE TITLE
Classes can't be instantiated from class declaration

### ISSUE THREAD

**Issue by chkpnt** [jsdom/jsdom#3051]
Classes can only be instantiated from class expressions but not from class declarations. But actually, I'm unsure if this is really a bug or just a misunderstood concept.

### Basic info:

- **Node.js version:** 14.4.0
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');
const { window } = new JSDOM('', { runScripts: 'dangerously' });
const scriptElement = window.document.createElement('script');
scriptElement.textContent = `
    class A {
        constructor() {
            console.log("class A initialized")
        }
    }

    var B = class B {
        constructor() {
            console.log("class B initialized")
        }
    }
`;
window.document.body.appendChild(scriptElement);

new window.A();    // prints: TypeError: window.A is not a constructor
new window.B();    // prints: class B initialized
```

### How does similar code behave in browsers?

https://jsbin.com/xufofoyego/3/edit?html,console

**Comment by domenic** [comment]
This is as expected. The `class` declaration does not create global variables, so they are not exposed on `window`.
