### ISSUE TITLE
CSS background-position and background-image do not apply on DOM element

### ISSUE THREAD

**Issue by jonnycraze** [jsdom/jsdom#3056]
### Basic info:
Getting errors when applying background styles to an html element. W

- Node version 10.x
- jsdom version 24.8.x

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {};
const dom = new JSDOM(`
  <div style="background-position: top 5px right; background-image: linear-gradient(to right, #333, #ccc), url('https://nas-national-prod.s3.amazonaws.com/styles/hero_mobile/s3/h_a1_7443_5_painted-bunting_julie_torkomian_adult-male.jpg')"></div>`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?
These styles work as expected in all modern browsers.
(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
I can't tell what the actual code is that behaves differently; this just creates a JSDOM instance, and doesn't do anything with it.
