### ISSUE TITLE
How to define window.navigator.getBattery by myself?

### ISSUE THREAD

**Issue by pyAppman** [jsdom/jsdom#3061]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by TimothyGu** [comment]
See https://github.com/jsdom/jsdom#intervening-before-parsing.
