### ISSUE TITLE
TypeError: Cannot read property '_customElementDefinitions' of undefined

### ISSUE THREAD

**Issue by adityashukla74** [jsdom/jsdom#3063]
### Basic info:

- **Node.js version:** node 14.0.0
- **jsdom version:** ~16.4.0

Getting this error "TypeError: Cannot read property '_customElementDefinitions' of undefined" after upgrading AngularJS app from Webpack1 to Webpack4 and subsequently other packages.

When I run npm run test, it throws the error.

**Comment by shivarajloni** [comment]
hey! can i contribute

**Comment by 40x** [comment]
How did you end up resolving this? facing with with latest jest
