### ISSUE TITLE
newly created video element with mute attribute shouldn't trigger _dispatchVolumeChange

### ISSUE THREAD

**Issue by antoniopacheco** [jsdom/jsdom#3065]
### Basic info:

Newly created video with mute tag should not fire `_dispatchVolumeChange
this event is causing an issue on react / react-testing-library:
https://github.com/testing-library/react-testing-library/issues/470

I noticed that in the code:
https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLMediaElement-impl.js#L23
there is no way to give a default value to mute (and it should be possible via attributes)

- **Node.js version:** 12.18.3
- **jsdom version:**

**Comment by domenic** [comment]
This issue does not follow the issue template, so we'll close it since it's not helpful to us as library authors in debugging.
