### ISSUE TITLE
Lib is not working for a specific HTML file.

### ISSUE THREAD

**Issue by efcjunior** [jsdom/jsdom#3077]
I don´t know why this lib is not working when I run the following code with an HTML file of size > 5 MB

Environment: 
OS: Windows 10
Nodejs : v12.16.1
jsdom : "^16.4.0"
IDE: webstorm
File: [Hinario](https://raw.githubusercontent.com/efcjunior/hinario-novo-cantico-api/main/hinario.html)

`const jsdom = require("jsdom");
const { JSDOM } = jsdom;

JSDOM.fromFile("hinario.html").then(dom => {
    console.log(dom.window.document.getElementById('pf1'));
}).catch(e => console.log(e));`
[](url)

**Comment by atomicwelding** [comment]
Please reupload the file. What behavior were you waiting for?
