### ISSUE TITLE
Unix only?

### ISSUE THREAD

**Issue by DoctorDerek** [jsdom/jsdom#3079]
### Basic info:

- **Node.js version:** 14.15.1
- **jsdom version:** latest

### Minimal reproduction case

This is how it crashes for me:
```
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\acorn
npm ERR! dest C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\.acorn.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\acorn' -> 'C:\dev\React-TDD-Gift-Giver\node_modules\acorn-globals\node_modules\.acorn.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\derek\AppData\Roaming\npm-cache\_logs\2020-11-30T22_48_51_788Z-debug.log
```

This was with
```
npm install --save-dev --save-exact jsdom
```

on Windows 10 x64

### How does similar code behave in browsers?

n/a

**Comment by domenic** [comment]
Nope, I develop this on Windows, and ran that same command locally with no problems. This seems like a system-specific issue, or perhaps a transient error with a virus checker or similar.

**Comment by DoctorDerek** [comment]
Weird! Thanks for the update, then. It worked after restarting the terminal 😂😅

**Comment by DoctorDerek** [comment]
The issue was --save-exact instead of just not using it.

When I removed it and ran it in a new terminal:
```
npm install --save-dev jsdom jsdom-global
```

It worked because my package.json file got updated:
```
-        "acorn": "^4.0.4"
+        "acorn": "^7.1.1",
```

Cheers!
