### ISSUE TITLE
JSDOM from file has null origin

### ISSUE THREAD

**Issue by Hodaya27392** [jsdom/jsdom#3081]
I use JSDOM to load an HTML file into a NODEJS server.

I actually do not have a client, nor do I need one. I only need the DOM to use its scripts (they do not currently appear in the code I present because it does not matter to the question).

DOM load code:

```
JSDOM.fromFile('./index.html', options).then((dom) => {
   //Doing a few things
}).catch(err => {
    console.log(err);
});
```

HTML page:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<script>
    var oReq = new XMLHttpRequest();
    oReq.addEventListener("load", ()=>{
        console.log('OK');
    });
    oReq.open('GET', 'https://www.google.com/');
    oReq.send();
</script>
</html>
```
In trying to execute xhr I get the following error: `Error: Cross origin null forbidden`

I guess since I loaded the DOM from file it's origin is null.

I checked the matter and indeed when I load the DOM from a URL I have a correct origin, and when I load it from file I have no origin at all.

Number of code restrictions:

> I can not load from URL - I have to load from file so it does not help me to have origin when loading from URL.

> I can not set: oReq.setRequestHeader ('Access-Control-Allow-Origin', '*'); because in my original code I use SDK within which the XHR code is executed

So actually what I need is a way to define the ORIGIN

How can I configure the ORIGIN to be the server where the DOM is loading?

**Comment by Sebmaster** [comment]
I think setting [`url`](https://github.com/jsdom/jsdom#simple-options) is probably what you're looking for here. fromFile gives it a file:/// default, which isn't compatible with origins.

**Comment by Hodaya27392** [comment]
It helped thanks!
