### ISSUE TITLE
`instanceof Error` check returns unexpected result

### ISSUE THREAD

**Issue by akphi** [jsdom/jsdom#3082]
### Basic info:

- **Node.js version:** 14.13.0
- **Yarn version:** 1.22.5
- **jsdom version:** 16.4.0
- **jest version:** 26.6.3

### Minimal reproduction case
I'm using JSDom via Jest, this is my repo repro
https://github.com/akphi/jest-jsdom-test/blob/main/src/basic.test.js for Jest
https://github.com/akphi/jest-jsdom-test/blob/main/index.js for native JSDOM example

```js
try {
  // invalid URL to be thrown
  const url = new URL("something");
} catch (e) {
  console.log(e instanceof Error); // expect `true` but returns `false`
}
```

### How does similar code behave in browsers?
It behaves as expected in the browser: i.e. `instanceof Error` returns `true`

Link: https://codesandbox.io/s/xenodochial-gauss-2cqjx?file=/src/App.tsx

### Points to consider
The gist of the problem is by providing an invalid base URL, the package `whatwg-url` used by `jsdom` throws a `TypeError` which gets picked up by my test, but fails my `instanceof Error` check.

I did a little bit of digging, there are many issues raised regarding sandboxing or `instanceof` check, though I don't understand fully, I see 2 categories:
1. Misconfigured JSDom, such as in https://github.com/jsdom/jsdom/issues/2555. But as mentioned, I use `Jest` with default settings so I hope I did not misconfigured anything here
2. Something related to sandboxing and the fact that jsdom `Error` is somehow different than the `Error` in my `instanceof` check.

**Comment by domenic** [comment]
Can you provide a reproduction that doesn't use Jest? We cannot help debug Jest usage.

**Comment by akphi** [comment]
@domenic Sure! I just updated my repo. The code is this
```javascript
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const dom = new JSDOM(`<body>
  <script>
    try {
      // invalid URL to be thrown
      const url = new URL("something");
    } catch (e) {
      console.log(e instanceof Error); // expect true
    }
  </script>
</body>`, { runScripts: "dangerously" });

// `node index.js` prints `false` 
```

**Comment by domenic** [comment]
Thanks. I guess then this is "Errors and other globals from the outer Node.js environment are still used" from https://github.com/jsdom/jsdom/issues/2727, which is pretty hard to fix.

**Comment by akphi** [comment]
@domenic gotcha, just want to confirm that! Will close this to track #2727
Thanks!
