### ISSUE TITLE
<span> tags and <strong> tags are not working in JSDOM

### ISSUE THREAD

**Issue by ankeshdamahe** [jsdom/jsdom#3089]
### Basic info:

- **Node.js version:** v10.20.1
- **jsdom version:** v16.4.0

### Minimal reproduction case

```js
function serverDOMBuilder (html) {
  const jsdom = require('jsdom')
  const { JSDOM } = jsdom

  const {
        document,
        HTMLElement,
        HTMLAnchorElement
    } = (new JSDOM(html, { includeNodeLocations: true })).window;
    
    global.HTMLElement = HTMLElement;
    global.HTMLAnchorElement = HTMLAnchorElement;

    const doc = document.implementation.createHTMLDocument('foo');
    doc.documentElement.innerHTML = html;
    const root = doc.getElementsByTagName('body')[0];
    return root;
} 


const rawFromHTML =(content)=>{
    
    const djs = require('draft-js');
    const html = '<!DOCTYPE html><body><p id="main"><span>My First JSDOM!<span></p><p>Hey this <strong>editor</strong> rocks 😀</p></body>';
    const blocks = djs.convertFromHTML(html, serverDOMBuilder);
    const json=djs.convertToRaw(djs.ContentState.createFromBlockArray(blocks));
    return json;
    
}
```

### How does similar code behave in browsers?
I am new to jsdom so I am not getting how to solve  this issue.
Error I am getting 
(node:4685) UnhandledPromiseRejectionWarning: ReferenceError: Node is not defined
```

```

**Comment by Sebmaster** [comment]
This is not a jsdom issue, your issue is that you're loading draft-js wrong. It needs to be loaded _inside_ the jsdom env, but you're loading it in the node env.

You'll need to do some external bundling of draft-js and then run the resulting script in the jsdom sandbox either by including a script tag or via eval.
