### ISSUE TITLE
Empty data attributes have a `=""` automatically added to them. How do I avoid it?

### ISSUE THREAD

**Issue by dpw1** [jsdom/jsdom#3098]
### Basic info:

- **Node.js version:** 14.3
- **jsdom version:** 16.4

### Overview
Empty data attributes have a `=""` added after them, I'd like to remove it. How do I do so?

### Minimal reproduction case

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const test = `<div data-llama></div>`;

let dom = new JSDOM(test);
const result = dom.window.document.documentElement.innerHTML;

console.log(result); //<head></head><body><div data-llama=""></div></body>
```

### Output received from example above:
```
<head></head><body><div data-llama=""></div></body>
```

### Intended Output:
```
<head></head><body><div data-llama></div></body>
```

Thanks!

**Comment by domenic** [comment]
Yep, this is how browsers behave, per spec. You forgot the part of the issue template that links to a similar example in jsbin.
