### ISSUE TITLE
[Question]: Is it possible to get the value of a variable defined in a script tag?

### ISSUE THREAD

**Issue by MichaelDeBoey** [jsdom/jsdom#3100]
I was wondering if it's somehow possible to get the value of the `graphData` variable from the HTML below?

```html
<html lang="en">
<head>
    <title>Title</title>
</head>

<body>
<div id="graph"></div>

<script>
    // Do some scripting here ...
</script>

<script type="application/javascript" src="path/to/highcharts.js"></script>
<script>
    const graphData = [
        JSON.parse('[[12345, 10.0], [12346, 10.1], [12347, 10.2], [12348, 10.3]]'),
        JSON.parse('[[67890, 100.0], [67891, 101.0], [67892, 102.0], [67893, 103.0]]'),
        JSON.parse('[[1234567890, 1000.0], [1234567891, 1010.0], [1234567892, 1020.0], [1234567893, 1030.0]]'),
    ]

    // show graphData in #graph ...
    Highcharts.Chart({
        // ...
    })
</script>

<script>
    // Do some more scripting here ...
</script>
</body>
</html>
```

Since `graphData` is a `const`, it's  not  available on `window`, so I tried to get it from the context of the script like below, but that also isn't working unfortunately 😕

```js
const { scripts } = new JSDOM(data, { runScripts: 'dangerously' }).window.document;
const [{ graphData }] = [...scripts].filter(({ innerHTML }) => innerHTML.includes('graphData'));

console.log({ graphData });
```

I'm probably overlooking something here I guess.
Thanks for helping me out! 👊

**Comment by nth2say** [comment]
It depends on the varible's scope & lifetime. 
For this case, you can access it by window.graphData, since the graphData is defined in global scope.

**Comment by MichaelDeBoey** [comment]
@nth2say Doing the following (like you suggested), returns `undefined`:

```js
const { graphData } = new JSDOM(data).window;

console.log({ graphData });
```

Passing the `runScript: 'dangerously'` option like

```js
const { graphData } = new JSDOM(data,  { runScript: 'dangerously' }).window;

console.log({ graphData });
```

Will throw the following error:

```shell
Error: Uncaught [ReferenceError: Highcharts is not defined]
```

**Comment by nth2say** [comment]
@MichaelDeBoey 
Constants are block-scoped. try to define it with var in the html.
`
var graphData = [...]
`

**Comment by MichaelDeBoey** [comment]
> try to define it with var in the html

I'm not in control of making the HTML, that's from a third party

**Comment by MichaelDeBoey** [comment]
> try to define it with var in the html

@nth2say I'm not in control of making the HTML, that's from a third party

**Comment by nth2say** [comment]
> > try to define it with var in the html
> 
> @nth2say I'm not in control of making the HTML, that's from a third party

Consider to hook the Highcharts.Chart function to get the input parameters. 
one possible solution is that use a customerResourceLoader to replcace the path/to/highcharts.js with your own version, and dump out the data.

**Comment by minamme** [comment]
Hi
How did you solve it?

**Comment by niteshsh4rma** [comment]
Hi, you can solve it with

`
const { window } = new JSDOM(data,  { runScript: 'dangerously' })
`
`
const yourVariable = window.eval("graphData")
`

**Comment by MichaelDeBoey** [comment]
@niteshsh4rma As mentioned above, that will throw the following error:

```shell
Error: Uncaught [ReferenceError: Highcharts is not defined]
```
