### ISSUE TITLE
JSDOM Can Take up to 20x the time to parse HTML using the Apple M1 Chip compared to an Intel Core i7

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jsdom/jsdom#3104]
### Basic info:

- **Node.js version:** 12.18.4
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const prevTime = process.hrtime();
// index.html is attached
new JSDOM(require('fs').readFileSync(__dirname + '/index.html', { encoding: 'UTF-8' }));
const nanoSecondsDiff = process.hrtime(prevTime).reduce((sec, nano) => sec * 1e9 + nano);
process.stdout.write(`JSDOM: ${nanoSecondsDiff / 1000000}ms\n`);
```

**Apple M1 (multiple runs)**

```
JSDOM: 719.308166ms
JSDOM: 726.734083ms
JSDOM: 708.450083ms
```

**Windows Intel i7 (multiple runs)**

```
JSDOM: 151.1591ms
JSDOM: 156.0055ms
JSDOM: 152.7689ms
```

I've attached the `index.html` file so you can reproduce yourself (if you have an Apple M1 at hand). In other tests, it took `~150ms` in an Intel and `~2200ms` when running with M1.

I can reproduce with any HTML with more than 5k chars in the source, regardless if it's mostly JS, HTML, or CSS.

[index.html.zip](https://github.com/jsdom/jsdom/files/5892319/index.html.zip)

Is somebody aware of this? I tried to just but couldn't find any similar reports... the difference in performance is mindblowing.

**Comment by eaaliprantis** [comment]
Windows > Apple?

**Comment by FagnerMartinsBrack** [comment]
@eaaliprantis This is not about the platform, but about the chip. HTML parsing for previous Mac using Intel was performing normally.

After I reinstalled my packages, the issue was gone. Not sure if it was an Apple update or a patch version update of JSDOM. I guess the source of this issue will remain a mystery. If I manage to reproduce again, then I can reopen this.
