### ISSUE TITLE
Blank line in `<head>` makes the serialize() method return an output without any child nodes inside `<head>`.

### ISSUE THREAD

**Issue by homanp** [jsdom/jsdom#3109]
### Basic info:

If the `<head>` tag in the input HTML contains a blank line JSDOM will remove all tags inside of the `<head>` tag.

Example HTML: view-source:https://campusbokhandeln.se/

- **Node.js version:** 15.8.0
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(html);
const doc = dom.window.document;

const script = doc.createElement('script');
script.setAttribute('type', 'text/javascript');
script.setAttribute('src', 'https://myscript.com/script.js'); 

doc.head.append(script);

console.log(dom.serialize());

```

### How does similar code behave in browsers?

The browser can handle blank lines without any issues.

**Comment by homanp** [comment]
An approach would be to add some kind of cleanup functionality after the normalizing of html:

https://github.com/jsdom/jsdom/blob/69f6bf689ba240c29c56f04b6e5d855f86e54a30/lib/api.js#L290

I could make a PR with an example.

**Comment by domenic** [comment]
Can you create a _minimal_ reproduction case, that does not rely on a live website? For example, https://runkit.com/domenicdenicola/6022ac24863057001a9648a7 does not exhibit the problem.

**Comment by homanp** [comment]
@domenic ok I'll do that

**Comment by homanp** [comment]
@domenic https://runkit.com/homanp/60239aea69a31000196cb3f7

Here you have the example.

**Comment by domenic** [comment]
This seems to be working the same way as it does in browsers. The RunKit output (it's a little hard to tell because it's hidden in a tooltip) is

```html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head></head><body><br>



    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css">


    Test

</body></html>
```

which is correct and matches how browsers work: see e.g. http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=8908

So, this appears to not be a bug in jsdom, since it matches browsers. Does that seem right to you?

**Comment by homanp** [comment]
Yep, I think you are correct here. Closing this issue for now. Thanks @domenic
