### ISSUE TITLE
Injected scripts onload event not fired

### ISSUE THREAD

**Issue by alexpozzi** [jsdom/jsdom#3118]
First of all, thanks for the great work!

My application needs to lazy load some scripts depending on some conditions.
For example, before loading a component that needs an external SDK, I wrap that component with a script loader component which injects the needed SDK script in the DOM and, once the script is loaded (via an onload callback), mounts the wrapped component.

Trying to run the same code on JSDOM the wrapped component never mounts because the script onload event is never fired.

I didn't find any information on that in the documentation and in other issues neither.
Is this supported?

### Basic info:

- **Node.js version:** v12
- **jsdom version:** v16.4.0

I didn't add a minimal reproduction case but, in case it's needed, I can provide one.

**Comment by domenic** [comment]
Yes, we need a minimal reproduction case so that we can debug.

**Comment by alexpozzi** [comment]
Just figured out that it's not a JSDOM issue but something related to my code.
Script's onload callbacks are correctly fired :slightly_smiling_face:
