### ISSUE TITLE
KeyboardEvent.getModifierState does not appropriately trigger in jsdom

### ISSUE THREAD

**Issue by nfpiche** [jsdom/jsdom#3126]
### Basic info:

- **Node.js version:** 12.13.0
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');
const dom = new JSDOM(`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>JS Bin</title>
  </head>
  <body>
    <div id="text" />
  </body>
</html>
`);

dom.window.addEventListener('keydown', e => {
  if (e.getModifierState('Control')) {
    dom.window.document.getElementById('text').innerHTML = 'you pressed control too';
  } else {
    dom.window.document.getElementById('text').innerHTML = 'you did not press with control';
  }
});

const e = new dom.window.KeyboardEvent('keydown', { key: 'a', ctrlKey: true });
dom.window.dispatchEvent(e);
console.log(dom.window.document.getElementById('text').textContent);

const e2 = new dom.window.KeyboardEvent('keydown', { key: 'a', ctrlKey: true, modifierControl: true });
dom.window.dispatchEvent(e2);
console.log(dom.window.document.getElementById('text').textContent);
```

You can see in the output it is following the `else` clause because it does not think that ctrl key was also sent.

### How does similar code behave in browsers?

You can try the buttons as they manually fire the event similar to what happens in JSDOM, but also see it working as expected with actual keyboard events.
https://jsbin.com/ziqeyapuxo/edit?html,js

I also tried something similar to the test you have [here](https://github.com/jsdom/jsdom/blob/master/test/web-platform-tests/to-upstream/uievents/getModifierState.html) but that did not work for getting `getModifierState` to work, I'm unclear if I need to setup some options maybe to enable this?

**Comment by Maxim-Zabunkov** [comment]
I've faced the same issue, Prod code uses `KeyboardEvent.getModifierState('Control')`.
But I am unable to simulate it in JsDOM. It falls down to `EventModifierMixinImpl.getModifierState` which does not have `this.modifierControl`
