### ISSUE TITLE
jsdom 16.5.0 break support for customElements.get

### ISSUE THREAD

**Issue by fdesforges** [jsdom/jsdom#3133]
### Basic info:

- Node.js version: v14.13.0 
- jsdom version: 16.5.0 

Issue has been reproduce using last version of jest.

### Minimal reproduction case

(minimal setup using `npm init -y` in an empty directory and just adding jsdom as dependency in the project)

```js
const {JSDOM} = require('jdsom')

const dom = new JSDOM(`<body>
<script>
class CustomElement extends HTMLElement {}
customElements.define('my-ce', CustomElement )
console.log(customElements.get('my-ce'))
</script>
</body>`, {runScripts: 'dangerously'})
```

with 16.4.0 ==> works as expected
```
$ node index.js
[class CustomElement extends HTMLElement]
```

with 16.5.0 ==>  Does not work as expected
```
$ node index.js
undefined
```

---

The origin come from this refactoring : https://github.com/jsdom/jsdom/commit/ff69a75706eac5ef90d9eb46aedd90a14e29984c

In the file [CustomElementRegistry.html line 184](https://github.com/jsdom/jsdom/blame/2d82763248296c5f118d6fd890317f5db5de1635/lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js#184) the property `ctor` is removed :

```js
    const definition = {
      name,
      localName,
      // removed line  ctor,
      constructor,
      objectReference: ctor,
      observedAttributes,
      lifecycleCallbacks,
      disableShadow,
```
So the method get is not working anymore because it check the `ctor` property existence : (https://github.com/jsdom/jsdom/blame/2d82763248296c5f118d6fd890317f5db5de1635/lib/jsdom/living/custom-elements/CustomElementRegistry-impl.js#L217)

```js
  get(name) {
    const definition = this._customElementDefinitions.find(entry => entry.name === name);
    return definition && definition.ctor;
  }
```

**Comment by domenic** [comment]
Fascinating... It's quite sad that our test suite didn't catch this.

**Comment by ExE-Boss** [comment]
@domenic I’m updating the test suite to be able to catch this in <https://github.com/jsdom/jsdom/pull/2956>.
