### ISSUE TITLE
Implementing getBBox for SVG

### ISSUE THREAD

**Issue by kewp** [jsdom/jsdom#3159]
### Basic info:

- **Node.js version: 12.13.0** 
- **jsdom version: 16.5.1**

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

global.SVGSVGElement = (new JSDOM()).window.SVGSVGElement;

Object.defineProperty(global.SVGSVGElement.prototype, 'getBBox', {
  writable: true,
  value: () => ({
    x: 0,
    y: 0,
    width: 0,
    height: 0
  })
});

const options = {
  resources: 'usable',
  runScripts: 'dangerously'
};

JSDOM.fromFile('index.html', options).then( (dom) => {

       console.log(html.prettyPrint(dom.serialize()));
       
});
```

I'm getting `TypeError: element.getBBox is not a function`. What am I doing wrong?

**Comment by TimothyGu** [comment]
Different windows don't share the same `SVGSVGElement` class. To polyfill the method, see https://github.com/jsdom/jsdom#intervening-before-parsing.

Also you probably want to polyfill `SVGGraphicsElement.prototype.getBBox`, rather than just SVGSVGElement. See https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement/getBBox.

**Comment by kewp** [comment]
Thanks for the reply.

This is what I have now:

```js
const options = {
  resources: 'usable',
  runScripts: 'dangerously',
  beforeParse: (window) => {
    Object.defineProperty(window.SVGGraphicsElement.prototype, 'getBBox', {
      writable: true,
      value: () => ({
        x: 0,
        y: 0,
        width: 0,
        height: 0
      })
    });
  }
};
```

but I'm still getting the same error.

Does my code look right?

**Comment by kewp** [comment]
Hmm weird. I got it to work by prototyping `SVGElement` (why all the weird names?)

```js
Object.defineProperty(window.SVGElement.prototype, 'getBBox', {
      writable: true,
      value: () => ({
        x: 0,
        y: 0,
        width: 0,
        height: 0
      })
    });
```

**Comment by kewp** [comment]
And for anyone in future: I got the write name by going to the stack trace
and printing out the element with `console.log(element);` which gave me `SVGElement`
(i.e. not `SVGSVGElement` or `SVGGraphicElement`...)

**Comment by TimothyGu** [comment]
> why all the weird names?

That's just how web APIs work. We don't get to change it. SVGElement is a base class for all SVG elements. SVGSVGElement represents `<svg>` elements specifically.

**Comment by kewp** [comment]
Hmmm I see. I suppose that makes sense.
