### ISSUE TITLE
Clicking on a checkbox does not remove the `indetermiante` flag

### ISSUE THREAD

**Issue by enjoythelive1** [jsdom/jsdom#3167]
### Basic info:

- **Node.js version:** v15.12.0
- **jsdom version:** v16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {};
const dom = new JSDOM(`
  <input type="checkbox" checked />
`, options);

const checkbox = dom.querySelector('input');
checkbox.indeterminate = true;

checkbox.click();

assert(checkbox.checked === false);
assert(checkbox.indeterminate === false); // This one fails
```

### How does similar code behave in browsers?

https://jsbin.com/tanacomugi/edit?html,js,output

**Comment by domenic** [comment]
This was fixed in https://github.com/jsdom/jsdom/blob/master/Changelog.md#1652 I am pretty sure!
