### ISSUE TITLE
Implement Ranges and Traversal

### ISSUE THREAD

**Issue by tmpvar** [jsdom/jsdom#317]
<del>http://www.w3.org/TR/DOM-Level-2-Traversal-Range/</del>

- <ins>https://dom.spec.whatwg.org/#ranges</ins>
- <ins>https://dom.spec.whatwg.org/#traversal</ins>

We will need to find/write a test suite.

**Comment by jeffdolle-sge** [comment]
+1 for this

**Comment by domenic** [comment]
Spam +1 comments cause features to get moved to the back of the backlog. Please use the voting buttons instead. Deleting the recent +1s.

**Comment by adrianheine** [comment]
I'm still there, btw, as is my half-finished code. I hope to get this done eventually.

**Comment by acusti** [comment]
@adrianheine Does the TreeWalker implementation which landed help you get any closer to finishing your implementation?

**Comment by philipp-spiess** [comment]
Any updates on this?

**Comment by domenic** [comment]
https://twitter.com/slicknet/status/782274190451671040

**Comment by caub** [comment]
I use sometimes `Range#createContextualFragment`, I don't really know why this useful method is there though

so I ended up doing this for tests
```js
global.document.createRange = () => ({
  createContextualFragment: str => JSDOM.fragment(str)
});
```

**Comment by megamindbrian** [comment]
@domenic I think what @acusti was asking is what are the next steps to get this verified?

I am trying to use this:
https://github.com/PrismJS/prism/issues/896

Can someone recommend an alternative path?  I like the idea of having a highlighted diff and syntax highlighting with Prism.  Might even come out better than Github's highlighter.

**Comment by tilgovi** [comment]
@adrianheine I might be interested in helping out if you share your WIP.

**Comment by megamindbrian** [comment]
@adrianheine Is this relevant? http://tonsky.me/blog/chrome-intervention/

**Comment by Fi1osof** [comment]
Got errors in jest tests.
```
TypeError: document.createRange is not a function

      at createRange (node_modules/popper.js/src/utils/findCommonOffsetParent.js:27:26)
      at findCommonOffsetParent (node_modules/popper.js/src/utils/getReferenceOffsets.js:16:85)
      at Popper.getReferenceOffsets (node_modules/popper.js/src/methods/update.js:29:28)
      at Popper.call (node_modules/popper.js/src/index.js:94:19)
      at node_modules/popper.js/dist/umd/popper.js:51:7
```

Find link [here](https://github.com/mui-org/material-ui/blob/57e8a88faeebba4d67aaaf6c5b178ebfe97264a6/test/utils/createDOM.js#L13)

**Comment by domenic** [comment]
https://mobile.twitter.com/slicknet/status/782274190451671040

**Comment by ivan-zakharchuk** [comment]
When will it be released? So jest could upgrade to the newest version.
