### ISSUE TITLE
[Help] Preserve attributes original case when parsing HTML documents

### ISSUE THREAD

**Issue by AmineOzil** [jsdom/jsdom#3177]
### Basic info:

- **Node.js version:**  14.15.5
- **jsdom version:**  16.5.2

### The Problem : 
I'm working on an Angular project while I need to manipulate the template file and do some modifications (adding ids and so on), in order to do these modifications I've used JSDOM to parse the HTML files and manipulate their HTML Elements, the problem encountred with JSDOM is that it lowercases all attributes and tag names found on the HTML files and since Angular parser is case-sensitive (unlike HTML parser which is case-insensitive) so it makes sense that I want to preserve all the HTML files original case, is there any option to configure JSDOM so it preserves original case for the parsed HTML documents ?

### Minimal reproduction case

```ts
        files.forEach(file => {

        let html = fs.readFileSync(file,"utf-8");
        html=html.replace(/%/g,'--pct--'); //Replacing the '%' sign to avoid errors when decoding html file
        html = decodeURIComponent(html); 
        html=html.replace(/--pct--/g,'%');
        console.log(html);
        /*Html original file :
        <ckeditor #ckEditor
        [(ngModel)]="contentWithTags.content"
        [readonly]="false"
        (change)="changes($event)"
        debounce="500"
        *ngIf="items_research && items_research.length>0"
        [config]="ckeConfig">
        </ckeditor>
        */
        console.log("---------------------------------------");
        var dom = new JSDOM(html);
        doc = dom.window.document;
        /* Some manipulation code on document 
        .
        .
        */
        var finalResult = doc.documentElement.outerHTML;
        console.log(finalResult);
        /* Final result:
        <ckeditor #ckeditor="" 
        [(ngmodel)]="contentWithTags.content" 
        *ngif="items_research &amp;&amp;   
        items_research.length>0" 
        [readonly]="false" 
        (change)="changes($event)" 
        debounce="500" 
        [config]="ckeConfig">
        </ckeditor>
        */
        fs.writeFile(file, finalResult, err => { //Saving the result file after manipulation
        console.log('done');
        });
    })
```

**Comment by domenic** [comment]
This is not possible, because browsers do not preserve attribute casing, and jsdom is intended to emulate a browser.

**Comment by damodharanj** [comment]
Can a mode for angular be added to this ? I too have the same issue
