### ISSUE TITLE
getComputedStyle does not return the right visibility sometimes

### ISSUE THREAD

**Issue by romain-trotard** [jsdom/jsdom#3182]
Hello guys

### Basic info:

- **Node.js version:** 14.16.0
- **jsdom version:** 16.4.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM(`
  <html lang="en">
    <head>
      <title>Document</title>
      <style>
        #hiddenDiv {
            visibility: hidden;
        }
        
        /* This rule is important because add rule on the div */
        * {
            margin-bottom: 10px;
        }
      </style>
    </head>
    <body>
      You should not see anything below me
      <div id="hiddenDiv">You do not see me</div>
    </body>
  </html>`);

const { document } = dom.window;

const hiddenDiv = document.getElementById('hiddenDiv');

// Visibility is visible instead of hidden
console.log(dom.window.getComputedStyle(hiddenDiv)._values.visibility);
```

I also made a repository but not sure if it will be useful (because using react + styled-components + testing-library): https://github.com/romain-trotard/jsdom-visibility-styled-components-problem

### How does similar code behave in browsers?

I just made a screenshot in a browser:

![image](https://user-images.githubusercontent.com/17161484/116559546-dabf5b00-a900-11eb-85a2-2755d1dcdeb8.png)

### Reason of the problem

I have debugged jsdom and have found where the problem is.
Actually the problem is here: https://github.com/jsdom/jsdom/blob/04f6c13f4a4d387c7fc979b8f62c6f68d8a0c639/lib/jsdom/living/helpers/style-rules.js#L63

The reason is that next rules override the value of previous rule.
I have made a fix here https://github.com/romain-trotard/jsdom/tree/getCascadedPropertyValue-change

![image](https://user-images.githubusercontent.com/17161484/116560688-e7907e80-a901-11eb-8874-9fa6ec5b9326.png)

`getPropertyValue` returns an empty string "" if the property is not found in the rule (https://github.com/NV/CSSOM/blob/97bee0949153ecb3295eccf98da2be79b7269e2f/lib/CSSStyleDeclaration.js#L31)

If it's ok with you I can make a PR :)

Thanks

**Comment by el-ethan** [comment]
Any updates on this? I am having an issue that I think is related to this same thing. I have a component that sets `visibility` to `hidden` in some conditions. The component is working fine in the browser, but after updating `jest` (which brought along an update to `jsdom`), my unit tests for visibility have started to fail. It appears that when a component has its styles modified by a styles defined in a parent component, visibility is overridden, even when the parent component doesn't define any visibility styles. I set up a minimal example [here](https://github.com/el-ethan/to-be-visible-test/tree/master).

**Comment by domenic** [comment]
https://mobile.twitter.com/slicknet/status/782274190451671040

**Comment by el-ethan** [comment]
@domenic my intention was not to simply add "+1" noise, perhaps you didn't finish reading my comment? While my description of my issue may have been less than coherent, I also included a link to [a repo with an easily reproducible example](https://github.com/el-ethan/to-be-visible-test/tree/master) of the same issue in a different context with the hope of adding more clues to the issue. I have removed the sentence "Any updates on this?" from my comment. Please let me know if there is anything else in my comment that you find to be unhelpful or noisy, and I will update.

**Comment by romain-trotard** [comment]
I will make a PR soon, for this issue if it's ok for you @domenic

**Comment by romain-trotard** [comment]
@el-ethan I have try my fix with your reproduction repo and it seems to work for your problem too ;)
