### ISSUE TITLE
Form submit via input tag or form tag will only send content-type "application/json" instead of multipart/form-data

### ISSUE THREAD

**Issue by champagnetony** [jsdom/jsdom#3186]
### Basic info:

- **Node.js version:** 12.16.0
- **jsdom version:** ^16.5.2

### Minimal reproduction case

```
const dom = new JSDOM(
<!DOCTYPE html>
<html>
  <body>
    <input type="file" />
  </body>
</html>
);
const {document, File, FileList} = dom.window;

        const filePaths = [path.resolve('tests/helpers/attachment.txt')];
        const inputElement = document.querySelector('input[type=file]');
        addFileList(inputElement, filePaths);

        let res = null;
        const handleUpload = () => {
            const doUpload = async () => {
                const file = inputElement.files[0];
                if (file.size > 10485760) {
                    console.log('file is too big to upload. please pick one smaller than 10MB');
                } else if (file) {
                    const input = {
                        mappingId: {
                            pmid: propertyManagerId,
                            ecid: '1234567',
                            rn: 'RES-12345',
                            vcid: '1c323485-e1de-463a-be80-8bd35423464b'
                        },
                        contentLength: file.size,
                        ttl: 'FOREVER',
                        bytes: file
                    };
                    const result = await toPromise(
                        graphql({
                            query: ADD_ATTACHMENT_MUTATION,
                            variables: {input}
                        })
                    );
                    res = result;
                }
            };
            doUpload();
        };

        Object.defineProperty(inputElement, 'onchange', {
            value: handleUpload,
            writable: false,
        });
        inputElement.onchange();
```

I have tried with just the single input tag and with a form tag and with an input submit tag as well

```
<form onsubmit="return false" encrypt="multipart/form-data">
      <input type="file">
      <input type="submit">
    </form>
```
I have tried with and without the encrpyt attribute. 
I have tried using FormData within the handleUpload

```
const data = new FormData();
data.append('file', file);
```

Nothing works. jsdom always sets the content-type to 'application/json'

The request is a graphql request getting sent to an apollo-server-hapi instance on an ephemeral port set up in the test env and it's the same config as the actual server setup. 

Here's what is posted from jsdom debugged in node-fetch - {"operationName":"getAttachmentStatus","variables":{},"query":"query getAttachmentStatus($attachmentId: ID!) {\n  getAttachmentStatus(attachmentId: $attachmentId) {\n    success\n    status\n  }\n}\n"} 

Obviously it is in fact JSON but the browser is able to detect the file upload in the variables and so sets the content-type as multipart/form-data which allows for different handling in the apollo-server. 

### How does similar code behave in browsers?

The same code in a browser sets the content-type to multipart/form-data correctly

Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryi5K7dTUit5cESaZH

------WebKitFormBoundaryi5K7dTUit5cESaZH
Content-Disposition: form-data; name="operations"

{"operationName":"addAttachment","variables":{"input":{"mappingId":{"pmid":1512,"ecid":15574132,"rn":"RES-14152","vcid":"27727d30-fde5-4f92-84a9-584adc4a119c"},"mappingType":"attachment_json","source":"esc","contentLength":22,"ttl":"FOREVER","bytes":null}},"query":"mutation addAttachment($input: AddAttachmentInput!) {\n  communications {\n    addAttachment(input: $input) {\n      success\n      errorMessage\n      status\n      url\n      __typename\n    }\n    __typename\n  }\n}\n"}
------WebKitFormBoundaryi5K7dTUit5cESaZH
Content-Disposition: form-data; name="map"

{"1":["variables.input.bytes"]}
------WebKitFormBoundaryi5K7dTUit5cESaZH
Content-Disposition: form-data; name="1"; filename="attachment.txt"
Content-Type: text/plain

this is an attachment

------WebKitFormBoundaryi5K7dTUit5cESaZH--

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
jsdom actually doesn't support form submission at allz so this is a pretty surprising bug.

**Comment by domenic** [comment]
Oh, I see, you aren't submitting the form, you are calling a third-party library named graphql. So this is unrelated to jsdom.
