### ISSUE TITLE
access the DOM inside the worker

### ISSUE THREAD

**Issue by axionos** [jsdom/jsdom#3189]
### Basic info:

- **Node.js version:** v15.8.0
- **jsdom version:** 16.5.3

### Minimal reproduction case

```js
// app.js
const myWorker = new Worker('/worker-bundle.js');
const message = {
	msg: JSON.stringify(result)
};

myWorker.postMessage(message);



```
```js
// worker
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

onmessage = function(e) {
    const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
    console.log(dom.window.document.querySelector("p").textContent);
    console.log(document); // Uncaught ReferenceError: document is not defined
}

```

I'm curious if there is a way I can access the real DOM from inside the worker. 
so far I've been able to create a virtual DOM using browserify within the worker, but no luck in accessing the document.

I'm trying to grab a DOM element that's already rendered on the screen from the worker, manipulate it somehow within the worker and update it using jsDom.

Please let me know if this is possible. Thank you.
 

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
No, it's not possible. JSDOM is a re-implementation of the DOM; it doesn't give you any access to the original DOM of a page.
