### ISSUE TITLE
Bump ws to patch out security vulnerability.

### ISSUE THREAD

**Issue by krystan** [jsdom/jsdom#3196]
### Basic info:

- Node.js version -> any
- jsdom version -> any

### Minimal reproduction case

N/A

### How does similar code behave in browsers?

N/A

Currently ws 7.4.5 suffers from a ReDoS security vulnerability, should bump to latest fixed version to patch out vulnerability.

**Comment by TimothyGu** [comment]
It may be a security vulnerability for the `ws` project, but it's not a vulnerability for us. jsdom does not guarantee any security properties for visited websites.

**Comment by krystan** [comment]
> jsdom does not guarantee any security properties for visited websites.

Appreciated but you realise anything that relies on your project and is scanned by security scanners will open up a transient dependency violation.

**Comment by lilbitner** [comment]
Hello! Curious if this is going to be merged soon? If not, any suggestions for how to update this transient dependency myself (if that is possible)?

**Comment by Sebmaster** [comment]
jsdom does not pin dependencies to exact versions, so as long as you can convince your package manager to upgrade `ws` jsdom will happily accept it. If regular upgrades don't do anything, just remove jsdom and re-add it to your project, that'll force it to pick latest deps.

**Comment by krystan** [comment]
you want me to abandon the pull request or just let it sit there ?
