### ISSUE TITLE
Append element in the head is not working

### ISSUE THREAD

**Issue by victormaestri** [jsdom/jsdom#3199]
### Basic info:

When trying to add the script element in the head of document, it is not working.
This functionality is already expected in the browser.
In **jsdom version 11.12.0** it was working.

- **Node.js version:** ^10
- **jsdom version:** 16.6.0

### Minimal reproduction case

```js
describe('DOM', () => {
  it('should append script in head', () => {
    const s = document.createElement('script')
    const div = document.createElement('div')
    document.head.appendChild(s)
    document.body.appendChild(div)
    console.log(document.documentElement.innerHTML)
  })
})
```
Return:
```shell
console.log
    <head></head><body><div></div></body>
```

**Comment by domenic** [comment]
Unfortunately this issue does not follow the issue template, as it seems to use some third-party library (involving `describe` and `it`) and isn't using JSDOM at all from what I can tell (since it's not using `new JSDOM()`). Please update the post to include an example in the style of the issue template, which we can run with no third party libraries. Then reply to this thread, and we can reopen the issue.

**Comment by TimothyGu** [comment]
Indeed, this doesn't look like a jsdom issue. With the following script:

```js
const { JSDOM } = require('jsdom');

const { window } = new JSDOM('');
const { document } = window;

const s = document.createElement('script')
const div = document.createElement('div')
document.head.appendChild(s)
document.body.appendChild(div)
console.log(document.documentElement.innerHTML)
```

The printed output is

```html
<head><script></script></head><body><div></div></body>
```

as expected.

**Comment by victormaestri** [comment]
I created a codesandbox with same dependencies I use in my project and it worked:
https://codesandbox.io/s/boring-voice-4osdx?file=/src/App.js

I'll work on to know why in my project it doesn't works. If I find some relevante to the community, I'll post about it.

For now, thanks!
