### ISSUE TITLE
Vulnerable package

### ISSUE THREAD

**Issue by PabloJomer** [jsdom/jsdom#3202]
https://github.com/jsdom/jsdom/blob/0024630fc62d1abb567cd531f9396b9a811424aa/package.json#L48

Hi there is a vulnerability in ws that has been patched. Would you upgrade to the latest version 7.4.6 ?

Kind regards,
Pablo

**Comment by PabloJomer** [comment]
Sure, just thinking to alert you.

**Comment by TimothyGu** [comment]
Duplicate of #3196. Fixed in #3197.
