### ISSUE TITLE
Did someone meet this error: "Error: Uncaught 6463000" 

### ISSUE THREAD

**Issue by yuanhongboo** [jsdom/jsdom#3204]
### Basic info:

- **Node.js version:**  12.22.1
- **jsdom version:**  16.4.0

![image](https://user-images.githubusercontent.com/68771569/121768069-b2c54780-cb8e-11eb-9795-b511904b5760.png)

By the way, I'm running jsdom with jest:

![image](https://user-images.githubusercontent.com/68771569/121768126-fddf5a80-cb8e-11eb-8704-b7ff2546978f.png)

**Comment by TimothyGu** [comment]
Sorry, we cannot look into issues involving a third-party dependency (Jest in this case). Please follow the issue template exactly to get support from us.
