### ISSUE TITLE
File instance does not have an arrayBuffer method

### ISSUE THREAD

**Issue by ehab-cl** [jsdom/jsdom#3206]
### Basic info:

- **Node.js version:**  v15
- **jsdom version:**  v16

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const { window } = new JSDOM("<!DOCTYPE html>");

const jsDomfile = new window.File(["sd"], "sa.txt");

console.log(jsDomfile.arrayBuffer()); // throws jsDomfile.arrayBuffer is not a function

```

### How does similar code behave in browsers?

Same issue here https://codesandbox.io/s/jsdom-testing-forked-894vb?file=/src/index.js:0-253 we can see in comparison that the native File has the arrayBuffer method.

**Comment by TimothyGu** [comment]
Duplicate of #2555.

**Comment by jimmywarting** [comment]
should pull the source from https://github.com/node-fetch/fetch-blob/blob/main/index.js
(more up to spec)
