### ISSUE TITLE
TypeError: Cannot convert undefined or null to object after npm run build in React

### ISSUE THREAD

**Issue by S7012MY** [jsdom/jsdom#3212]
### Basic info:

- **Node.js version:** v14.17.2
- **jsdom version:** 16.6.0

### Minimal reproduction case

```js
const jsdom = require("jsdom");
```
Trying to use jsdom in a react application. It works fine when running it using npm start, but when building, I get `Cannot convert undefined or null to object` in the console and the webpage is white. 

### Code
Here's the component where I'm using it. I removed everything except `require` and the problem was still present.
```js
import { createCodeElement } from '../Helpers/Code.js';

const jsdom = require("jsdom");
const { JSDOM } = jsdom;

// Receives
//   - html - string containing the HTML code
//   - js - string containing the JS code
//   - uuid - we need this so that users will be able to run the same code
//            multiple times
function CodeRunner(props) {
  const dom = new JSDOM(props.html);
  let document = dom.window.document;
  document.body.appendChild(createCodeElement(document, props.js, props.uuid));

  return (
    <iframe name="result"
      allow="midi; geolocation; microphone; camera; display-capture; encrypted-media;"
      sandbox="allow-modals allow-forms allow-scripts allow-same-origin allow-popups allow-top-navigation-by-user-activation allow-downloads"
      allowFullScreen=""
      allowpaymentrequest=""
      title="codeRunner"
      id={props.uuid}
      frameBorder="0"
      src=""
      srcDoc={dom.serialize()}
    >
    </iframe>
  );
}

export default CodeRunner;
```

**Comment by TimothyGu** [comment]
This issue does not follow the issue template. We require issue reports to be independent of other packages, ideally a single self-contained Node.js script that we can run ourselves. Your code appears to rely on React and other packages, as well as (I'm assuming) a code bundler. See also https://github.com/jsdom/jsdom#running-jsdom-inside-a-web-browser.
