### ISSUE TITLE
parse6 Integration

### ISSUE THREAD

**Issue by frank-dspeed** [jsdom/jsdom#3216]
### Basic info:
I am really far in the progress of rewriting parse5 and call it parse6 as the api changed a lot to support more usecases
It would be nice if you could help me to identify all your needs. Mean while i my self will track issues that i find in cheerio and jsdom.

## List of Already Corrected Errors and cases
- Parser/open-stackelements now got a eventEmitter on() pop, remove, push
  -https://github.com/jsdom/jsdom/blob/e4c4004c122797cd897f35475bb6ab42688ba452/lib/jsdom/browser/parser/html.js#L21-L34
- Fixed BOM Handling when the input is marked at the begining with a BOM.
- Corrected Inconsistent Named Variables.
- deprecating the 

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
We're happy with parse5 at the moment.
