### ISSUE TITLE
The result of querySelector() has too many Escape character

### ISSUE THREAD

**Issue by weijialiu-hiretual** [jsdom/jsdom#3230]
If I get element on web page, I can get Correct results.
![image](https://user-images.githubusercontent.com/82020360/130407803-2675d5eb-5de5-4fe9-96d8-76d38c69dcd4.png)

But in JSDOM, the result has too many Escape character.
![image](https://user-images.githubusercontent.com/82020360/130407740-dac813a5-7818-44d5-a62b-80cbc4b2e4fb.png)

What should I do? 

Thank you so much !

**Comment by domenic** [comment]
This issue does not follow the issue template, so we cannot help.
