### ISSUE TITLE
getComputedStyle performance

### ISSUE THREAD

**Issue by just-boris** [jsdom/jsdom#3234]
### Basic info:

- **Node.js version:** n/a
- **jsdom version:** any version is affected

### Minimal reproduction case

```js
const div = document.createElement('div');
document.body.appendChild(div);

console.time('getComputedStyle');
getComputedStyle(div);
console.timeEnd('getComputedStyle');
```

### How does similar code behave in browsers?

This code take a fraction of millisecond in real browsers, but 100 times slower in JSDOM. There are some libraries in the ecosystem heavily relying on this API and the tests become slow because of that.

Related issues: 

https://github.com/testing-library/dom-testing-library/issues/820 
https://github.com/theKashey/react-focus-lock/issues/151

**Comment by just-boris** [comment]
As a possible solution, I think, it could cache the result of this call

https://github.com/jsdom/jsdom/blob/9dae17bf0ad09042cfccd82e6a9d06d3a615d9f4/lib/jsdom/browser/Window.js#L799-L807

External stylesheets usually do not change dynamically and this could give a significant improvement

**Comment by donaldpipowitch** [comment]
I recently ran CPU profiling on our Jest tests (using testing-library) and indeed it looks like getComputedValue/getSpecifiedValue/getComputedStyle really eats up a lot of time.

**Comment by nickroth** [comment]
We recently updated to use jsdom 16 in our jest tests and noticed a big slow down that I believe is related to this. Some components in React use react-focus-lock and the tests use RTL. 

Running `node --prof` with jest seems to indicate some native function called "__ZN2v88internal17Builtin_JsonParseEiPmPNS0_7IsolateE" as where it spends a lot of time and calls to that stem heavily from the functions that @donaldpipowitch listed. Node version is 14.18.3 but also tried on latest v16 and saw no improvement. Local OS is macOS 12.0.1 but similar slowdowns are seen across across the team and CI environment that all use varying OS's.

**Comment by jsnajdr** [comment]
Some analysis about why `getComputedStyle` is so slow. JSDOM has a [default stylesheet](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/default-stylesheet.js) with 120 rules. Your app can add additional rules, for example, one of our unit tests I've been debugging adds 90 additional rules from Emotion, the total becoming 210, but 120 rules is the baseline everyone starts with.

`getComputedStyle(element)` takes your element, matches it against all these 120 rules (using the `matches()` function, implemented with [nwsapi](https://github.com/dperini/nwsapi)), collecting the matching rules' properties into one `CSSStyleDeclaration` and returns that. So, there are 120 `matches` for every element.

But that's not all. There are auto-inherited properties like [`visibility`](https://drafts.csswg.org/css2/#visibility): 

<img width="841" alt="Screenshot 2022-12-20 at 18 46 16" src="https://user-images.githubusercontent.com/664258/208732789-c7e49afc-efcd-49ae-829f-020cf4f47718.png">

To compute their value, we need to look at the parent element to see what its `visibility` is and then copy that value into the current element's computed style. Computing `visibility` for the parent element means matching the parent element against all the 120 CSS rules, too. And if the parent doesn't have a specified `visibility` property, we need to traverse all the way to the root.

We need to do _O(number_of_css_rules * element_tree_depth )_ calls of `matches`. Just one `getComputedStyle(element)` call for an element that's 10 elements deep in the tree, it calls `matches` 1200 times.

It gets worse when the user-space code itself does parent traversal. In the popular `@testing-library/user-event` library, when you perform an `userEvent.click(el)` operation, it checks if the element has a `pointer-event` CSS rule that would disable mouse events. There's a [`closestPointerEventsDeclaration` function](https://github.com/testing-library/user-event/blob/1aa2027e5ec445ab413808556efa7763b65053d3/src/utils/pointer/cssPointerEvents.ts#L22-L32) to traverse the element tree and find a declaration in one of the parents. It does a loop like:
```js
for (let el = element; el; el = el.parentElement) {
  const pointerEvents = window.getComputedStyle(el).pointerEvents;
  if (pointerEvents) {
    return { pointerEvents };
  }
}
```
Here we're matching the 120 CSS rules _n * ( n + 1 ) / 2_ times, where _n_ is the _element_tree_depth_. Clicking on an element that's 10 elements deep involves _120 * 10 * 11 / 2 = 6600_ `matches` calls. The number grows with the square of element tree depth, and can quickly be in tens of thousands. In profiler, you can see a single `userEvent.click` call takes around 100ms:

<img width="771" alt="Screenshot 2022-12-20 at 19 03 36" src="https://user-images.githubusercontent.com/664258/208737420-dedbe5e5-ea3d-464b-a387-f5572bb060cd.png">

Another library that does this quadratic parent traversal is `@floating-ui/dom`, a library for positioning floating popover elements, which has a [`getNearestOverflowAncestor`](https://github.com/floating-ui/floating-ui/blob/6644439ca4cb0781e4695e89ae3d6cf7c2587e9f/packages/dom/src/utils/getNearestOverflowAncestor.ts) helper that looks at the `overflow` and `display` computed styles.

A solution for this performance issue would be caching the computed styles for each element. Of course the biggest problem is when to invalidate the cache. But maybe even the most naive invalidation, which invalidates styles for the entire document on any DOM change, would help a lot.

The `pointer-events` issue in particular has a standalone solution: the `pointer-events` property is auto-inheritable, just like `visibility`, so `jsdom` could support that natively, in the [`propertiesWithResolvedValueImplemented`](https://github.com/jsdom/jsdom/blob/22f7c3c51829a6f14387f7a99e5cdf087f72e685/lib/jsdom/living/helpers/style-rules.js#L13-L22) object. Then `userEvent` wouldn't have to traverse the DOM itself and could look at computed styles of just one element.
