### ISSUE TITLE
Minimal script raises error about SharedBufferArray

### ISSUE THREAD

**Issue by chrillek** [jsdom/jsdom#3237]
### Basic info:

- **Node.js version:** 15.3
- **jsdom version:** 17.0.0
### Minimal reproduction case
Content of file.js:
```js
const { jsdom } = require("jsdom");
```
Command line on macOS 11.5.2:
`browserify file.js | osascript -l JavaScript`
Error message:
`execution error: Error: ReferenceError: Can't find variable: SharedArrayBuffer (-2700)`

Safari's JavaScript (which is the same one that the `osascript` tool uses) does not provide SharedArrayBuffer, according to caniuse.com. Could that be the cause of the error?
### How does similar code behave in browsers?

`browserify file.js > expanded.js` and then including the script in a simple HTML file raises an error in Firefox, too.

**Comment by chrillek** [comment]
This problem does not arise with jsdom version 14, but with 16 and 17. Didn't bother to check with version 15.

**Comment by domenic** [comment]
Duping into https://github.com/jsdom/webidl-conversions/issues/38
