### ISSUE TITLE
new Text() does not work with textContent, innerHTML, etc

### ISSUE THREAD

**Issue by SephReed** [jsdom/jsdom#3241]
### Basic info:

- **Node.js version:** 16.6.2
- **jsdom version:** 17.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const domNode = document.createElement("div");
domNode.appendChild(new Text("Some Text"));

console.log(domNode.textContent); // err: 'Cannot read property \'replace\' of undefined',
```

> Function.Serializer.escapeString (node_modules/window/node_modules/parse5/lib/serializer/index.js:165:15)
  Serializer._serializeTextNode (node_modules/window/node_modules/parse5/lib/serializer/index.js:148:37)
  Serializer._serializeChildNodes (node_modules/window/node_modules/parse5/lib/serializer/index.js:52:26)
  Serializer.serialize (node_modules/window/node_modules/parse5/lib/serializer/index.js:36:14)
  Object.exports.serialize (node_modules/window/node_modules/parse5/lib/index.js:28:23)

### How does similar code behave in browsers?

it would log "Some Text"

**Comment by SephReed** [comment]
I forgot to include my setup:

```
const browserEnv = require("browser-env");

browserEnv([
  "window",
  "document",
  "Event",
  "setTimeout",
  "location",
  "Node",
  "HTMLDivElement",
  "HTMLElement",
  "Text"
]);

global.requestAnimationFrame = (cb) => setTimeout(cb, 24);
```

**Comment by domenic** [comment]
OK. That is using a third-party package, which we cannot provide support for. Please provide a minimal repro case that uses only jsdom, and not third-party packages.
