### ISSUE TITLE
CORS error if `access-control-allow-origin` from the 3rd party service is `*`

### ISSUE THREAD

**Issue by SUNLINGLING98** [jsdom/jsdom#3245]
### Basic info:

- **Node.js version:** v12.16.1
- **jsdom version:** jsdom@11.12.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const dom = new JSDOM(`
    url: 'https://service.com',
    referrer: 'https://service.com',
    contentType: 'text/html',
    includeNodeLocations: true,
    storageQuota: 10000000,
`);
```
This lib is used for our IT live tests involving calls to the 3rd party services. 

### Issue
When the 3rd party service got called, it failed with the error message: `Error: Cross origin https://service.com forbidden.`

### Findings:
It looked like the CORS check failed on this line [L75 in `validCORSHeaders`](https://github.com/jsdom/jsdom/blob/11.12.0/lib/jsdom/living/xhr-utils.js#L75). This seemed to be related to the [`mergeHeaders` result](https://github.com/jsdom/jsdom/blob/11.12.0/lib/jsdom/living/xhr-utils.js#L54-L58). Please note that the `access-control-allow-origin` from the service response headers was `*`, while it was `https://service.com` in the preflight response headers. 

### How does similar code behave in browsers?
The same situation, i.e.  `access-control-allow-origin` from the service response headers was `*`, while `https://service.com` in the preflight response headers worked fine in browsers.

Is this a known issue with this specific jsdom version? Has it been fixed in any version?

**Comment by domenic** [comment]
Unfortunately this does not provide a minimal reproduction case that we can run to reproduce the issue ourselves. (The code is not even valid; it's passing a string.) So we will not be able to help you with this, and thus cannot keep this issue open.

Please leave a comment if you are able to provide a repro, runnable using https://npm.runkit.com/jsdom, that displays the error. Then we can reopen and investigate.

**Comment by SUNLINGLING98** [comment]
I cannot think of an easy way for your team to reproduce yet. The includes a 3rd party service with `access-control-allow-origin` set as `*`. Please let me know if you have any recommendations on providing such an environment.

In the meantime, can you help and clarify your comment:
>  (The code is not even valid; it's passing a string.)

Which code did you refer to?

**Comment by domenic** [comment]
The code in the original post. It's trying to pass options but is just passing a string. It appears like it took the code in the issue template and mistakenly edited it, instead of actually trying to create a reproduction code snippet like the template asks for.

**Comment by SUNLINGLING98** [comment]
@domenic 
> It's trying to pass options but is just passing a string

Got it. The original posted code was corrected. Hope it works in a way that it should now.

In the meantime, I still have a question on the [mergeHeaders](https://github.com/jsdom/jsdom/blob/11.12.0/lib/jsdom/living/xhr-utils.js#L54-L58). 

Yes, in my case, the `access-control-allow-origin` in the response headers for `preflight` and the real request were mis-matched. It was `'https://service.com'` for preflight and `'*'` for the real request. Then the merged value `'https://service.com,*'` caused the CORS validation failed in JSDOM [here](https://github.com/jsdom/jsdom/blob/11.12.0/lib/jsdom/living/xhr-utils.js#L75) (Also described above in the issue description). However, the browsers chromium, FF, and Safari treat it as valid, and the same situation works fine there.

Could you share the reasons or specification on [this merge process](https://github.com/jsdom/jsdom/blob/11.12.0/lib/jsdom/living/xhr-utils.js#L54-L58)? I checked this [spec](https://fetch.spec.whatwg.org/#cors-protocol) and could find any guidance on a mismatched cross-origin from preflight vs real request. 

Thanks!

**Comment by domenic** [comment]
Sorry, I'm not really able to spend time on debugging this without a reproduction case.
