### ISSUE TITLE
Unordered list inside list element not found or ignored

### ISSUE THREAD

**Issue by alexmro** [jsdom/jsdom#3254]
### Basic info:

- **Node.js version:** 12.20.1
- **jsdom version:** 17.0.0

### Minimal reproduction case

```html
<div id="example">
<ul class="big-list">
  <li class="big-list-item">
    <div>Some div element</div>
    <ul class="sub-list">
      <li>Item</li>
    </ul>
  </li>
</ul>
</div>
```

```js
const jsodm = require('jsdom').JSDOM;

var dom = new jsdom(body);
var exampleDiv = dom.window.document.querySelector('#example');

var bigListItems = exampleDiv.querySelectorAll('.big-list .big-list-item');
for (var i = 0; i < bigListItems.length; i++) {
    var sublistItems = bigListItems[i].querySelectorAll('ul li');
    var sublistDiv = bigListItems[i].querySelectorAll('div');
}

```

The problem I have is that `ul` elements inside a `li` are not found. In the example above the `div` element is found (strange, I don't know if `div` is supported inside `li`) but the `ul` element is not.
When I try to get the count of children for the `li` element it says 1, as if the `ul` did not exist and only the `div`

**Comment by domenic** [comment]
When I try to run this example using `node test.js`, I get issues where `jsdom` and `body` are not declared. Please edit the OP to include an actual minimal reproduction that we can test successfully, then leave a comment, and we can reopen this to try to help.
