### ISSUE TITLE
Can't remove the attribute 'is'

### ISSUE THREAD

**Issue by domark0721** [jsdom/jsdom#3265]
### Basic info:

- **Node.js version:** 14
- **jsdom version:** 16~18

### Minimal reproduction case
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body class="theme-settings">
    <section>
      <article id="step-container">
        <section id="personal-info" is="personal-info" test="personal-info" class="screen">vvv</section>
      </article>
    </section>
  </body>
</html>
```

```js
const jsdom = require('jsdom');
const fs = require('fs');

const { JSDOM } = jsdom;

const content = fs.readFileSync('./index.html', { encoding: 'utf8' });
const dom = new JSDOM(content);
const doc = dom.window.document;
const replaceableElementsA = doc.querySelectorAll('*[is]');
Array.prototype.forEach.call(replaceableElementsA, function eachEl(el) {
  el.removeAttribute('is');
});

const replaceableElementsB = doc.querySelectorAll('*[test]');
Array.prototype.forEach.call(replaceableElementsB, function eachEl(el) {
  el.removeAttribute('test');
});


console.log(doc.documentElement.innerHTML)
```

The same code works on the jsdom@15.*
It can't remove it after I upgraded jsdom@16~18.

I can remove other attributes normally but 'is' can't only.
Does it exist bugs?

**Comment by domark0721** [comment]
> Please provide a complete reproduction case we can run with `node test.js`. Yours fails with undefined variable `html`. We can reopen after you have done so.

I have provided the sample code.

**Comment by domenic** [comment]
Did you test the same code in browsers? A link to a jsbin or similar is strongly suggested.

**Comment by domark0721** [comment]
> Did you test the same code in browsers? A link to a jsbin or similar is strongly suggested.

I create a new project on the Codesandbox.
You can change the jsdom version on the left panel.
https://codesandbox.io/s/jsdom-ticket-skg40

**Comment by domenic** [comment]
I can't get that page to open (it's just blank forever for me).

Anyway, I was referring to something like this: https://jsbin.com/tehaqanuca/1/edit?html,console,output

As you can see, jsdom is behaving like browsers, so there is no bug here.

**Comment by domark0721** [comment]
> I can't get that page to open (it's just blank forever for me).
> 
> Anyway, I was referring to something like this: https://jsbin.com/tehaqanuca/1/edit?html,console,output
> 
> As you can see, jsdom is behaving like browsers, so there is no bug here.

```js
const replaceableElementsA = doc.querySelectorAll('*[is]');
Array.prototype.forEach.call(replaceableElementsA, function eachEl(el) {
  el.removeAttribute('is');
});
```

the result on jsdom@15.x.x
```html
<section id="personal-info" class="screen">vvv</section>
```

the reulst on jsdom@16~18
```html
<section id="personal-info" is="personal-info" class="screen">vvv</section>
```

I don't know why **"is"** attribute can't be removed on jsdom@16~18, but jsdom@15 can.

Do you see the differences?
Does the keyword 'is' as an attribute have something special?
I use this attribute for the custom component.

**Comment by TimothyGu** [comment]
jsdom 16.2.0 added (proper) support for custom elements, and according to latest web standards the `is` attribute cannot be removed after element creation.

**Comment by domark0721** [comment]
> jsdom 16.2.0 added (proper) support for custom elements, and according to latest web standards the `is` attribute cannot be removed after element creation.

Thanks for your information.
It seems I need to refactor my legacy code.
