### ISSUE TITLE
 My getElements ByClassName returns nothing

### ISSUE THREAD

**Issue by Ellathet** [jsdom/jsdom#3270]
Taking the className from my gift, but the return I have is below

```
console.log(dom.window.document.body.getElementsByClassName('documents'));
```

HTMLCollection {}
HTMLCollection {}
HTMLCollection {}
HTMLCollection {}
HTMLCollection {}

This console be inside in forEach. How can I take a elements inside a HTMLCollection...

**Comment by TimothyGu** [comment]
Please use the [issue template](https://github.com/jsdom/jsdom/blob/master/.github/ISSUE_TEMPLATE.md) when filing issues. We cannot help debug issues that don't follow that template.
