### ISSUE TITLE
Query on using jsdom to scrape a fully loaded webpage.

### ISSUE THREAD

**Issue by tathastu871** [jsdom/jsdom#3277]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

How can i scrape a url using jsdom and execute all script tags so that fully loaded offline copy of webpage can be made.

I am new to node and jsdom documemtation is very confusing.

Can anyone help me regarding loading external url into jsdom and executing all scripts tags so that i can make offline copy/snapshot of that website

I have searched google for tutorials but no results.
### Minimal reproduction case

What is have tried is to download webpage using wget so that i get index.html and now when i tend to load it in throws several errors
 Code:
```
'use strict';

const { JSDOM } = require('jsdom');

const options = {
  resources: 'usable',
  runScripts: 'dangerously',
};

JSDOM.fromFile('test.html', options)
});
```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)
 I am using jsdom in termux on android

**Comment by TimothyGu** [comment]
The code you have is exactly how to do it. You should look through the errors you got to figure out a solution.
