### ISSUE TITLE
jsdom@18.0.1  500

### ISSUE THREAD

**Issue by 1095huang** [jsdom/jsdom#3281]
jsdom@18.0.1  500
[img](https://img14.360buyimg.com/imagetools/jfs/t1/126917/24/22366/89286/618a0d0dE83e039c2/0f224133f4ad4e04.png)
[image](https://img10.360buyimg.com/imagetools/jfs/t1/203161/37/14829/37561/618a0eaaE6b67b542/ec8ef06dc2ce1cd5.png)

**Comment by TimothyGu** [comment]
https://registry.npmjs.org/jsdom/-/jsdom-18.0.1.tgz works fine here. You're using a non-npm registry (I assume it's a Chinese mirror), so maybe you should take it up with them.

For what it's worth, https://registry.npmmirror.com/jsdom/download/jsdom-18.0.1.tgz, https://registry.npmmirror.com/jsdom/-/jsdom-18.0.1.tgz, and https://oss.npmmirror.com/jsdom/-/jsdom-18.0.1.tgz all seem to work. I can't find a homepage to jd.com's mirror.
