### ISSUE TITLE
Problem on page executing external javascript where class Request is used

### ISSUE THREAD

**Issue by Summersummer3** [jsdom/jsdom#3288]
### Basic info:

- **Node.js version:** v14.17.3
- **jsdom version:** 18.1.0

### Minimal reproduction case

The html page:
`<script>external.js</script>`

external.js:
`const supportRequest = Request && Request instanceof Object`

Error:
Error: Uncaught [ReferenceError: Request is not defined]

And I have tried to import some fetch packages but it doesn't work:
```js
const got = require('got');
require('isomorphic-fetch');
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

const sdkURL= 'http://example.com';

(async () => {
  const response = await got(sdkURL);
  const dom = new JSDOM(response.body, { url: sdkURL, runScripts: "dangerously", resources: "usable" });

  console.log(response.body)
  // This log is normal, but then error comes when external.js executed
  console.log(Request)

  async function getPage() {
    setImmediate(() => {
      const nodeList = [...dom.window.document.body.querySelectorAll('input')];
      console.log(nodeList)
      });
      }
    )
  }

  dom.window.addEventListener('load', getPage)

})()
````

### How does similar code behave in browsers?
Works well

**Comment by domenic** [comment]
Yep, we have not implemented `Request` or `fetch()` yet. Duping into https://github.com/jsdom/jsdom/issues/1724
