### ISSUE TITLE
Clear defined customElements?

### ISSUE THREAD

**Issue by elado** [jsdom/jsdom#3303]
### Basic info:

- **Node.js version:** v14
- **jsdom version:** v19

### Minimal reproduction case

I use `customElements.define`, e.g.

```js
window.customElements.define('foo-bar', class extends HTMLElement {});
```

Is there a way to clear the registry? Specifically for jest tests, otherwise the defined elements leak between tests. I understand there's no such DOM API, but this seems like an important functionality.

**Comment by domenic** [comment]
The best way is to create a new document; jsdom documents behave like DOM documents.
