### ISSUE TITLE
isConnected API does not work

### ISSUE THREAD

**Issue by coder-lcn** [jsdom/jsdom#3312]
### Basic info:

- **Node.js version:*v16.13.1*  
- **jsdom version:*16.4.0* 

### Minimal reproduction case

```js
// It only works on the browser side
if (!div.current.isConnected) {
    console.log("render");
    document.body.append(div.current);
}
```

minimal repro: https://codesandbox.io/s/clever-rhodes-eoe5l?file=/src/index.test.js

### How does similar code behave in browsers?
It behaves normally in the browser.

**Comment by domenic** [comment]
This minimal repro seems to use libraries besides jsdom (and in fact never includes jsdom at all), so we cannot help you. Please produce a minimal repro following the issue template that we can run with `node test.js` and that uses no libraries besides jsdom, and we can reopen this issue.
