### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by kokoloko13** [jsdom/jsdom#3316]
### Basic info:
- **Node.js version: 16.13.1** 
- **jsdom version: 19.0.0** 

### Minimal reproduction case

```js
const jsdom = require('jsdom');
const { JSDOM } = jsdom;

const dom = new JSDOM(`<!DOCTYPE html><body><p id="main">My First JSDOM!</p></body>`);
console.log(dom.window.document.getElementById("main").textContent);

```

### How does similar code behave in browsers?
All usage codes in the internet shows that simple example how to use JSDOM to log paragraph content.

Long story short: 
Node is logging that the document is not defined:

![image](https://user-images.githubusercontent.com/15813784/148846162-66932336-4966-4e10-a1e2-8cd6d6a864a0.png)

Did anyone have situation like this? I don't know what to do...

(Link to a jsbin or similar strongly suggested.)

**Comment by Sebmaster** [comment]
Your minimum repro works perfectly fine and doesn't log that error: https://runkit.com/sebmaster/61dcaee8721f0a0008fd5c37
