### ISSUE TITLE
Specifiying `userAgent` option doesn't change `window.navigator.userAgent`

### ISSUE THREAD

**Issue by dzcpy** [jsdom/jsdom#3325]
### Basic info:

- **Node.js version:** any
- **jsdom version:** 19.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  userAgent: "Mellblomenator/9000"
};
const dom = new JSDOM(``, options);
console.log(dom.window.navigator.userAgent) // Mozilla/5.0 (win32) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/19.0.0

```

Example:
https://codesandbox.io/s/elegant-pike-c0t48

### How does similar code behave in browsers?

Not related to browser

**Comment by domenic** [comment]
Wow, this is a pretty bad documentation bug!

Back in https://github.com/jsdom/jsdom/commit/f865e45fdbdf12d6a6874f69ea5cc80b39f9d575 we moved the `userAgent` option to the `ResourceLoader` constructor. So the following is the new way to do this:

```js
const { JSDOM, ResourceLoader } = require("jsdom");

const loader = new ResourceLoader({
  userAgent: "Mellblomenator/9000"
});
const dom = new JSDOM(``, { resources: loader });
console.log(dom.window.navigator.userAgent);
```

**Comment by domenic** [comment]
Wait a minute. The docs are totally correct here already. I'm not sure where you got the idea of there being a `userAgent` option to the `JSDOM()` function, but here it's documented for the `ResourceLoader`: https://github.com/jsdom/jsdom#advanced-configuration

**Comment by dzcpy** [comment]
Well, I guess I got it from TypeScript type hinting in VSCode. However ResourceLoader only works when there's a resource loaded while executing the script. It doesn't change window.navigator.userAgent if there's no extra resources loaded. I ended up using Object.defineProperties:
```html
<script>Object.defineProperties(navigator, { userAgent: { value: '${userAgent}', writable: true } })</script>
```

**Comment by domenic** [comment]
A few months late on a response, but I've had the above email on my "to-investigate" list for months. I just investigated, and found out that the claim

> However ResourceLoader only works when there's a resource loaded while executing the script. It doesn't change window.navigator.userAgent if there's no extra resources loaded.

is false. The code example I gave above, where no extra resources are loaded, works fine and shows that `window.navigator.userAgent` is indeed changed: https://runkit.com/domenicdenicola/62d2ae5518c55b00084a5902

I imagine this is a bit too late to be helpful to you, but maybe for anyone else...
