### ISSUE TITLE
Feature request: add AbortController support to addEventListener

### ISSUE THREAD

**Issue by alexreardon** [jsdom/jsdom#3327]
It is possible to provide in a `signal` (`AbortSignal`) as a part of the `AddEventListenerOptions` object. When this `signal` is aborted, any event listeners that were provided with that `signal` will be unbound.

- [`AbortSignal`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal)
- [spec](https://dom.spec.whatwg.org/#ref-for-dom-eventtarget-addeventlistener%E2%91%A2)
- [Browser support](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#browser_compatibility) - most noteably using `signal` is currently not supported in Safari

Given there is not universal support yet, should this be added to jsdom?

I was thinking of having a crack at adding `AbortSignal` support to `EventTarget-impl.js`

**Comment by BurntCaramel** [comment]
It appears it is in Safari: https://bugs.webkit.org/show_bug.cgi?id=218753
