### ISSUE TITLE
HTML structure got changed after serializing it from a dom tree

### ISSUE THREAD

**Issue by RichardHoOoOo** [jsdom/jsdom#3328]
### Basic info:

- **Node.js version:**  v16.13.2
- **jsdom version:**  19.0.0

### Minimal reproduction case

I just use jsdom to load an html file into a dom tree and serialize the dom tree.

The html file (simplified)
```
<html>
    <head>
        ::script::
        <script src="jquery.min.js"> </script>
    </head>
    <body> 
    </body>
</html>
```

The transformation code 
```js
const { JSDOM } = require("jsdom");
// No options are set
const dom = new JSDOM(html); // html is the about html code
var result = dom.serialize();
console.log(result);
```

The output is
```
<html>
     <head>
     </head>
     <body>
        ::script::
        <script src="file:///android_asset/jquery.min.js"> </script>
     </body>
</html>
```

You can see the `<script>` element is moved from `<head>` to `<body>`. I found if I remove `::script::`, the `<script>` element is not moved. But I use `::script::` for a specific purpose, so I don't want to remove it. 

Is there any way to preserve the structure of an html file after serializing it from a dom tree?

**Comment by domenic** [comment]
Yep. This is how browsers, and thus how jsdom, works. http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=10008
