### ISSUE TITLE
Node.js 16 -  Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'

### ISSUE THREAD

**Issue by cut2run** [jsdom/jsdom#3331]
### Basic info:

- **Node.js version:** v16.13.2
- **jsdom version:** v.19.0.0

### Minimal reproduction case

```ts
/**
 * Trigger event on the HTML Element
 * @param element HTML element
 * @param event event name to trigger
 */
function triggerEvent(element: Element, event: string): void {
    element?.dispatchEvent(new Event(event));
}

//mocha unit test
describe("utils.UI", () => {
    it("trigger Event on Element emmits this event", () => {
        const customEvent = "click";
        const elem = document.createElement("input");
        let result = "none";
        elem.addEventListener(customEvent, (e) => {
            e.stopPropagation();
            e.preventDefault();
            result = e.type;
        });
        triggerEvent(elem, customEvent);
        expect(result).to.equal(customEvent);
        elem.remove();
    });
});

```
The code above works fine under all Node.js 14.x.x versions, including the latest 14.18.3 release. When Node.js 16.x.x is installed, the same unit test fails in "Event.js" "convert" function on "is" check with the following call stack ...

> Exception has occurred: TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
  at Object.exports.convert (C:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\jsdom\lib\jsdom\living\generated\Event.js:22:9)
    at HTMLInputElement.dispatchEvent (C:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:236:24)
    at Function.Ui.triggerEvent (C:\Users\ivanov\workspace\EmailEncryptionO365AddOn\src\lib\UiUtils.ts:32:18)
    at Context.<anonymous> (C:\Users\ivanov\workspace\EmailEncryptionO365AddOn\test\UiUtils.spec.ts:59:27)
    at callFn (c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runnable.js:366:21)
    at Test.Runnable.run (c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runnable.js:354:5)
    at Runner.runTest (c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runner.js:678:10)
    at c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runner.js:801:12
    at next (c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runner.js:593:14)
    at c:\Users\ivanov\workspace\EmailEncryptionO365AddOn\node_modules\mocha\lib\runner.js:603:7

The issue can be resolved by using a specific object of the "Event" interface, for example, this changed line will work ...

```ts
    element?.dispatchEvent(new CustomEvent(event));
```
The point is that we have a lot of dependencies on other packages and they use "Event" object as well, for example Bootstrap5 use the same "dispatchEvent" with "new Event('transitionend')". The following is Bootstrap function which failed as well ...

```js
  const triggerTransitionEnd = element => {
    element.dispatchEvent(new Event(TRANSITION_END));
  };
```

**Comment by domenic** [comment]
Unfortunately this example "minimal reproduction case"uses a lot of undefined functions like "describe", which are not implemented with jsdom. Please create a file we can run with `node test.js` that exhibits the problem, at which point we can reopen this and debug it for you further.

**Comment by cut2run** [comment]
I thought it would be quite simple for you guys to copy one line of code, which I repeated several times, with the call to `dispatchEvent`, but let me add the example per your request ...
### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
    url: 'http://localhost:3000'
};
const {window} = new JSDOM(`
<!doctype html><html><head><meta charset="utf-8"></head><body></body></html>
`, options);

global.window = window;
global.document = window.document;
//global.Event = window.Event;

const elem = document.createElement("input");
document.body.appendChild(elem);

elem.dispatchEvent(new Event("click"));

elem.remove();
```
With the example above (please note, Event registration commented out) the Node.js 14 produces the following error:
> ReferenceError: Event is not defined
at Object.<anonymous> (C:\Users\louniakova\VSProjects\demo\index.js:17:24)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
at internal/main/run_main_module.js:17:47

At the same time Node.js 16 produces the following error:
> C:\Users\ivanov\workspace\jsdom\node_modules\jsdom\lib\jsdom\living\generated\Event.js:22
  throw new globalObject.TypeError(`${context} is not of type 'Event'.`);
  ^
TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at Object.exports.convert (C:\Users\ivanov\workspace\jsdom\node_modules\jsdom\lib\jsdom\living\generated\Event.js:22:9)
    at HTMLInputElement.dispatchEvent (C:\Users\ivanov\workspace\jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:236:24)
    at Object.<anonymous> (C:\Users\ivanov\workspace\jsdom\src\index.js:17:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47


We are using "[global-jsdom](https://github.com/modosc/global-jsdom/blob/main/esm/index.mjs)" to registered default `jsDom` globally. This handy package doesn't do separate registration of global `Event` as I have commented in the code example. Basically, at this point, I just would like to confirm from you guys, that in order to use `Event` object I must register it in global space, and this will do. Am I correct or I am missing something?

From the errors above I assume that Node.js 16 most likely has `Event` object, but it is not the part of DOM of `jsdom` and Node.js 14 doesn't have the `Event` object at all. Do you understand clearly what is going on here?

**Comment by Sebmaster** [comment]
Yes, this is exactly the case, you cannot mix and match globals. This is explicitly documented here: https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by cut2run** [comment]
Thanks @Sebmaster ! This is the document I have to read before going with "global-jsdom". I will review the way we use `jsdom` in our unit tests and will try to follow the suggestions from the document.

**Comment by thuey** [comment]
@cut2run I am running into a similar issue. A dependency of my source code is creating a `new Event()`, which gets dispatched to a jsdom `EventTarget`. I then get the error "Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'".

I can "fix" it by setting `global.Event = window.Event`, but realize from this thread that this is discouraged.

What was your resolution on this issue?

**Comment by cut2run** [comment]
@thuey Basically this "discouraged" fix I end up using, but in a limited way, while I need to run my unit tests. I have created my own browser mock class where I am storing all the globals I need to override inside the private variables on initialization. After, I set the globals with JSDOM objects. And the last I have the method to restore the globals from the private variables. On "before" of the unit tests I initialize my browser mock and on "after" I would restore the globals back. One of these globals is `global.Event`.

**Comment by thuey** [comment]
Thanks @cut2run! Caching and then restoring the globals makes sense.

@Sebmaster  The problem appears to be that the global `Event` constructor from NodeJS is stamping over the global `Event` constructor available from jsdom. In the wiki article you referenced, I don't see a pattern that would provide a reasonable workaround for this. Do you have any suggestions?
