### ISSUE TITLE
getComputedStyle() does not update styles pseudo class "placeholder-shown"

### ISSUE THREAD

**Issue by vaidotasp** [jsdom/jsdom#3334]
### Basic info:

- "@testing-library/jest-dom": 5.16.1,

### Minimal reproduction case
Cross posting this from https://github.com/testing-library/react-testing-library/issues/1007, as good folks from `testing-library` directed me to post the issue here. I am very unfamiliar with jsdom implementation of `getComputedStyle()` but it seems like it does not work correctly with applying `:placeholder-shown` pseudo class. More information is in the issue that has been linked. Let me know how can I improve this and especially if you need me to work on issue reproduction. Thank you.

**Comment by domenic** [comment]
Unfortunately this issue does not follow our issue template, and thus is not something we can help with. Please let us know if you have edited it to follow the issue template, including a minimal example that does not rely on any external libraries such as "@testing-library/jest-dom". Then we can reopen it.
