### ISSUE TITLE
resourceLoader proxy: https://192.168.0.1:9080 (Tor HTTPTunnelPort 9080) error

### ISSUE THREAD

**Issue by garycnew** [jsdom/jsdom#3338]
### Basic info:

- **Node.js version:** v12.22.5
- **jsdom version:** 16.4.0

### Minimal reproduction case

```
  const resourceLoader = new jsdom.ResourceLoader({
    proxy: "https://192.168.0.1:9080", // Tor HTTPTunnelPort 9080
    strictSSL: true,
    userAgent: "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" // Tor Default User-Agent
  });

  const dom = await JSDOM.fromURL(url, {
    runScripts: "dangerously",
    resources: resourceLoader,
    //resources: "usable",
    virtualConsole
  });
```

### UnhandledPromiseRejectionWarning: RequestError: Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established

```
$ node check.js
(node:60210) UnhandledPromiseRejectionWarning: RequestError: Error: tunneling socket could not be established, cause=Client network socket disconnected before secure TLS connection was established
    at new RequestError (/usr/local/lib/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/share/nodejs/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (/usr/share/nodejs/request/request.js:881:8)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.onError (/usr/share/nodejs/tunnel-agent/index.js:179:21)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
(node:60210) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60210) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### How does similar code behave in browsers? The Tor HTTPTunnelPort 9080 is working as expected from the same machine.

```
$ wget --tries=1 -e use_proxy=on -e https_proxy=192.168.0.1:9080 -O - --no-check-certificate -U "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" https://check.torproject.org/
--2022-02-09 23:34:40--  https://check.torproject.org/
Connecting to 192.168.0.1:9080... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’
...
  <img src="/torcheck/img/tor-on.png" class="onion" />
  
  <h1 class="on">
    
      Congratulations. This browser is configured to use Tor.
    
  </h1>
  <p>Your IP address appears to be:  <strong>193.32.127.156</strong></p>
```

### Does jsdom proxy using GET or CONNECT? Tor HTTPTunnelPort only permits CONNECT.  Is there any way to better understand what's causing the "Client network socket disconnected before secure TLS connection was established" error?  I have jsdom making an async call and waiting for 9000ms.

**Comment by domenic** [comment]
Our proxy support is based on https://www.npmjs.com/package/http-proxy-agent / https://www.npmjs.com/package/https-proxy-agent . I don't actually know much about how it works, but maybe reading the documentation for those packages would help...

**Comment by garycnew** [comment]
@domenic

Thank you for pointing me in the right direction with https-proxy-agent, which affirms that it uses the CONNECT method.

That being said, the https-proxy-agent should work with Tor HTTPTunnelPort.  Does resourceLoader require that https-proxy-agent be constructed separately within the same script?  Does resourceLoader require that https-proxy-agent be installed as a dependency under node_modules/jsdom/node_modules/https-proxy-agent or can it be installed in the parent node_modules directory? I have https-proxy-agent installed in the parent node_modules directory as a deb package.

I'm starting to wonder about the resourceLoader example provided within the jsdom documentation:
```
const resourceLoader = new jsdom.ResourceLoader({
  proxy: "http://127.0.0.1:9001",
  strictSSL: false,
  userAgent: "Mellblomenator/9000",
});
const dom = new JSDOM(``, { resources: resourceLoader });
```
It appears as if the resourceLoader example is suggesting that a Tor SOCKS Proxy (127.0.0.1:9001) be used as a default proxy, which won't work unless resourceLoader supports socks-proxy-agent.

I appreciate your assistance.

Respectfully,


Gary

**Comment by domenic** [comment]
> That being said, the https-proxy-agent should work with Tor HTTPTunnelPort. Does resourceLoader require that https-proxy-agent be constructed separately within the same script? 

No. It is done under the hood, in [agent-factory.js](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/helpers/agent-factory.js). The callers are [resource-loader.js](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/browser/resources/resource-loader.js) and some stuff in our XHR implementation.

>  Does resourceLoader require that https-proxy-agent be installed as a dependency under node_modules/jsdom/node_modules/https-proxy-agent or can it be installed in the parent node_modules directory? I have https-proxy-agent installed in the parent node_modules directory as a deb package.

Just `npm install jsdom` and it will be installed automatically. It is a dependency. I don't know anything about deb packages; that doesn't sound like the normal way to consume Node.js modules so I can't answer any questions about that setup.

> It appears as if the resourceLoader example is suggesting that a Tor SOCKS Proxy (127.0.0.1:9001) be used as a default proxy, which won't work unless resourceLoader supports socks-proxy-agent.

I guess you are assuming that the port 9001 means a specific thing? That was not our intent when writing it. It's just a random port that some people might use when configuring their proxy server. I guess Tor SOCKS proxies are one such proxy, but I did not know that.

**Comment by garycnew** [comment]
@domenic

I took the liberty of removing the nodejs deb dependencies, installed as recommended `npm install jsdom`, and verified that node_modules/jsdom/node_modules/https-proxy-agent was successfully installed.

Now, I'm receiving the following 'Timed out' error:
```
$ node check.js
node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Timed out".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```
To further troubleshoot the issue, I created a script using the https-proxy-agent example code and configured it with my Tor HTTPTunnelPort Proxy and the desired EndPoint:
```
$ cat proxy.js 
var url = require('url');
var https = require('https');
var HttpsProxyAgent = require('jsdom/node_modules/https-proxy-agent');

// HTTP/HTTPS proxy to connect to
var proxy = process.env.http_proxy || 'http://192.168.0.1:9080';
console.log('using proxy server %j', proxy);

// HTTPS endpoint for the proxy to connect to
var endpoint = process.argv[2] || 'https://check.torproject.org';
console.log('attempting to GET %j', endpoint);
var options = url.parse(endpoint);

// create an instance of the `HttpsProxyAgent` class with the proxy server information
var agent = new HttpsProxyAgent(proxy);
options.agent = agent;

https.get(options, function (res) {
  console.log('"response" event!', res.headers);
  res.pipe(process.stdout);
});
```
The proxy.js script using the https-proxy-agent example code connected successfully, but did not execute the javascript on the page as expected (without jsdom):
```
$ node proxy.js 
using proxy server "http://192.168.0.1:9080"
attempting to GET "https://check.torproject.org"
"response" event! {
  date: 'Fri, 11 Feb 2022 00:27:15 GMT',
  server: 'Apache',
  'x-content-type-options': 'nosniff',
  'x-frame-options': 'sameorigin',
  'x-xss-protection': '1',
  'referrer-policy': 'no-referrer',
  'strict-transport-security': 'max-age=15768000; preload',
  'content-type': 'text/html; charset=utf-8',
  vary: 'Accept-Encoding',
  connection: 'close',
  'transfer-encoding': 'chunked'
}
...
<img src="/torcheck/img/tor-not.png" class="onion" />
  
  <h1 class="not">
    
      Congratulations. This browser is configured to use Tor.
    
  </h1>
  <p>Your IP address appears to be:  <strong>109.70.100.24</strong></p>
```
If https-proxy-agent is called within jsdom under-the-hood, I'm starting to think there might be a bug with this hook.

Are there known bugs or successful implementations of https-proxy-agent with jsdom?

Thank you for your assistance.

Respectfully,


Gary

P.S. The real-world default Tor ORPort is 127.0.0.1:9001, which is a SOCKS Proxy.  You might consider changing the resourceLoader sample to use 127.0.0.1:9080, which is the default Tor HTTPTunnelPort as to provide a more accurate empirical example.

**Comment by garycnew** [comment]
@domenic 

https-proxy-agent does work fine via jsdom.  It turns out the issue was related to my malformed jquery selector.  To verify, I opened the jquery selector up to html > body and low and behold I received the expected page output.

For posterity's sake, the following is what I ended up using with Tor HTTPTunnelPort 9080:
```
  function getRandomInt(max) { return Math.floor(Math.random()*1E16); }
  const random = getRandomInt();
  //console.log(random);

  const resourceLoader = new jsdom.ResourceLoader({
    proxy: `http://${random}@192.168.0.1:9080`, // Tor HTTPTunnelPort 9080
    strictSSL: false, // No Check Certificate
    userAgent: "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0" // Tor Default User-Agent
  });

  const dom = await JSDOM.fromURL(url, {
    runScripts: "dangerously",
    resources: resourceLoader,
    //resources: "usable",
    virtualConsole
  });
```

I appreciate your assistance and patience.  Closing.

Respectfully,


Gary
