### ISSUE TITLE
__webpack_require__(...).map is not a function

### ISSUE THREAD

**Issue by yinguangyao** [jsdom/jsdom#3345]
### Basic info:

- **Node.js version:** v12.14.0
- **jsdom version:** 16.6.0

### Minimal reproduction case

https://github.com/yinguangyao/jsdom-webpack

```js
npm i
npm run build
node dist/main.js
```
### problem performance
The error message is as follows:

```js
internals.rules = __webpack_require__(344).map(function (rule) {
                                           
TypeError: __webpack_require__(...).map is not a function
```
The problem looks to be with psl here.

**Comment by domenic** [comment]
Webpack is not a supported tool for using with jsdom, or rather, if webpack cannot handle this particular Node.js-targeted package, then that is an issue that needs to be fixed with webpack; we will not change our code.
