### ISSUE TITLE
jsdom non operational inside service worker, mv3, chrome extension

### ISSUE THREAD

**Issue by kostia-lev** [jsdom/jsdom#3348]
### Basic info:

- jsdom version: 19

### Minimal reproduction case

I am trying to use jsdom inside manifest 3 service worker in chrome extension, like this:
[](https://stackoverflow.com/questions/70541843/using-jsdom-in-chrome-extension-manifest-v3
)

And I get EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
I just need querySelector.

**Comment by domenic** [comment]
Dupe of https://github.com/jsdom/jsdom/issues/3315.

**Comment by guest271314** [comment]
Here you go https://github.com/guest271314/jsdom-extension/blob/main/background.js
