### ISSUE TITLE
Export `DOMParser` class

### ISSUE THREAD

**Issue by AlttiRi** [jsdom/jsdom#3364]
I would like if it will export `DOMParser` class.

```js
import {DOMParser} from "jsdom";
```

I need only `DOMParser` class with browsers-like behavior since I want have the code that will work in Node.js and browsers.

In particular in this case I no need more to write _(in additional to marking of `jsdom` as external dependency in the bundler config)_:
```js
globalThis.DOMParser = globalThis.DOMParser || new JSDOM().window.DOMParser;
```

---

Also I assume that in this case it would possible to decrease the count of imports that will decrease Node.js bundle's size. It's strange if `DOMParser` would be depended from different things are listed here https://github.com/jsdom/jsdom#customizing-jsdom.

**Ideally, it would be great if it was published as a separate package.**

For example, [xmldom](https://github.com/xmldom/xmldom) is only 126 kB, however, it has not compatible with the modern browsers API. It has no `body`, `head`, `innerHTML` props, `querySelector` method.

On the other hand using of [jsdom](https://github.com/jsdom/jsdom) seems to be overkill for only `DOMParser` class. 
It's 2.7 MB (and 6.36 MB of node_modules additionally).

**Comment by domenic** [comment]
Sorry, this isn't a direction we're interested in taking the jsdom project. You may want to find a separate project that only provides parser functionality.
