### ISSUE TITLE
Cannot set certain element style properties to empty

### ISSUE THREAD

**Issue by yyx990803** [jsdom/jsdom#3372]
### Basic info:

- **Node.js version:** 16.13.2
- **jsdom version:** 19.0.0

### Minimal reproduction case

This works as expected:

```js
const el = document.createElement('div')
el.style.margin = '10px'
console.log(el.style.margin) // '10px'

el.style.margin = ''
console.log(el.style.margin) // ''
```

This does **NOT**:

```js
const el = document.createElement('div')
el.style.marginLeft = '10px'
console.log(el.style.marginLeft) // '10px'

el.style.marginLeft = '20px'
console.log(el.style.marginLeft) // '20px'

el.style.marginLeft = ''
console.log(el.style.marginLeft) // '20px'
```

Note after setting `marginLeft` to empty, the value on `style` is still `'20px'`.

### How does similar code behave in browsers?

You can just paste the code in the browser console to witness the expected behavior: `el.style.marginLeft` should return empty string.

**Comment by sombriks** [comment]
yep it works on browser
![Captura de tela de 2022-05-20 02-22-15](https://user-images.githubusercontent.com/556695/169456219-94fd1f6e-f563-4c13-917b-b2528ffa2515.png)
but not on jsdom
![Captura de tela de 2022-05-20 02-23-02](https://user-images.githubusercontent.com/556695/169456301-631a0d57-3925-4013-85d9-c96cb2bbea00.png)
