### ISSUE TITLE
Not able to capture delayed render element in JSDOM.fromURL

### ISSUE THREAD

**Issue by ankur46** [jsdom/jsdom#3376]
Hello, 
Thank you so much for implementing JSDOM, it really makes my life easy, 
But unfortunately, I am facing the below issue while executing in my code-base

So I called JSDOM.fromURL() method to capture DOM content from the passed URL, but there are some 'Div' elements in the webpage that are rendering with some delay and I am not able to capture them, I tried so many ways but got no luck, below is my code, any help will be highly appreciated 

`      
        const resourceLoader = new jsdom.ResourceLoader({
            userAgent: body.userAgent
        });
          
        JSDOM.fromURL(body.url, {
            resources: resourceLoader,
        }).then(dom => {
                dom.window.addEventListener('load', () => {
                    dom.window.document.querySelectorAll('div').forEach(key => {
                        if (key.id) console.log(key.id);
                    });
       });
`
Please help me !!!

**Comment by domenic** [comment]
This issue does not follow the issue template, and so we cannot help.

**Comment by ankur46** [comment]
I have created the new issue using issue template. Please check 
[https://github.com/jsdom/jsdom/issues/3377](url)
