### ISSUE TITLE
Not able to capture delayed render element in JSDOM.fromURL

### ISSUE THREAD

**Issue by ankur46** [jsdom/jsdom#3377]
## Basic info:
- Node.js version: v12.21
- jsdom version: v19.0.0
##  Minimal reproduction case

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const body = {
        url:'https://sports.yahoo.com/the-daily-sweat-will-giannis-take-over-in-game-2-122807772.html?feature=enableMonalixaBodySlot&at_preview_token=E-TjFHZkpoHEfw5Er2ptjg&at_preview_index=1_1&at_preview_listed_activities_only=true',
        userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36'
     }
     const resourceLoader = new jsdom.ResourceLoader({
          userAgent: body.userAgent
      });
             
      JSDOM.fromURL(body.url, {
          resources: resourceLoader,
      }).then(dom => {
            dom.window.addEventListener('load', () => {
                dom.window.document.querySelectorAll('div').forEach(key => {
                if(key.id) console.log(key.id);
                });
        });
});
```
Actual output:
```
It is not retuning some delayed ( 3-4 seconds ) render div element in dom
```
Expected output:
```
div's which are delayed with few seconds should also be included in response from fromURL promise
```
## How does similar code behave in browsers?
When I hit above URL directly in browser that expected div's are getting render but with some small delay

**Comment by domenic** [comment]
I am unable to debug this issue. When I try this I get a different error: https://runkit.com/domenicdenicola/6299125ea1d2d6000705e719

> Unterminated string constant (3:15)

I'll close this issue until you can provide a proper reproduction case that we can run to help debug. You can edit the original post to fix that, and then leave a comment and we will reopen.

I strongly suggest double-checking your code before asking open-source maintainers to debug it a third time.

**Comment by ankur46** [comment]
Hello @domenic  sorry for that **I have updated the code and its working fine now in runKit**

Please Re-open the issue and help me in achieving the desired output

**Comment by ankur46** [comment]
I have added below screenshot in which I have highlighted the div that I want to capture in the promise response of JSDOM.fromURL() method

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/17536592/171800841-46dadf5d-502a-454f-9ebb-9a56485b00f0.png">

**Comment by domenic** [comment]
Great.

It sounds like you want to log divs that are not present when the `load` event is fired. Have you tried waiting until those divs are present in the DOM, e.g. using a polling loop?

**Comment by ankur46** [comment]
Hello Actually i tried timeout , will it be possible if you can help in what code we should add to above mentioned code to achieve polling 
it will be great help

**Comment by domenic** [comment]
Sorry, no, this is an issue tracker for finding bugs in jsdom, not a general programming help forum.

**Comment by ankur46** [comment]
ok np , but thanks for above comments will check on polling

**Comment by ankur46** [comment]
hello, @domenic  just wanted to check inside the polling function I need to call JSDOM.fromURL method recursively right till the desired div is not captured?

**Comment by ankur46** [comment]
Can we use **MutationObserver** to achieve desired output ?
