### ISSUE TITLE
Writing to HTMLSelectElement.value throws TypeError

### ISSUE THREAD

**Issue by rvugt85** [jsdom/jsdom#3380]
### Basic info:

- **Node.js version:** 14.19.0
- **jsdom version:** 

### Minimal reproduction case

https://github.com/testing-library/user-event/issues/961

**Comment by domenic** [comment]
Unfortunately this issue does not follow the issue template, e.g. it appears to use a third party library "user-event" instead of providing a minimal snippet of code using only jsdom which we could use to debug any potential issue. As such, I'll close it.
