### ISSUE TITLE
Could not load script when use dynamic import

### ISSUE THREAD

**Issue by yinguangyao** [jsdom/jsdom#3381]
### Basic info:

- **Node.js version:** 12.22.0
- **jsdom version:** 18.1.1

### problem

When I use dynamic import, webpack dynamically creates the script element and then sets the src attribute.
But if the URL is set, jsdom will add origin when requesting the dynamic import script, but I want to load the local JS file.

```js
const jsdomInstance = new jsdom.JSDOM(
      `<!DOCTYPE html>
        <style>
          html, body { width: 2000px; height: 1000px; }
          * { margin: 0; padding: 0}
        </style>
        <body></body>
      </html>`,
      {
        url: 'https://example.com/',
        runScripts: 'dangerously',
        resources: 'usable',
     }
  );

// sourcePath is the entry file packaged by webpack, and there are JS files in it that use dynamic import
const sourceContent = fs.readFileSync(sourcePath, 'utf-8');
const script = new vm.Script(sourceContent);

 script.runInNewContext(jsdomInstance.getInternalVMContext(), { timeout: 3000 });
```

If I set the URL to the file:// protocol, it will prompt the following error:
localStorage is not available for opaque origins

**Comment by domenic** [comment]
Let's dupe this into #2475.
