### ISSUE TITLE
canvas.toBlob() generates empty image

### ISSUE THREAD

**Issue by tentone** [jsdom/jsdom#3384]
### Basic info:

- **Node.js version:** 16
- **jsdom version:** 20

 - I have been using jest for our testing suite alongside a electron based runner to run the tests in a real browser environment.
 - Eventually we decided to move to JSDOM since it is lightweigth and seems to work correctly for almost everything.
 - We were using canvas to draw random image test data and using the toBlob() method to retrieve the canvas image.
 - On JSDOM we observed that the canvas returns a empty image with a 100x100 size.
 - We have included the "canvas": "~2.9.1" library into our project.

### Minimal reproduction case

```js
	public static imageGenerator(width: number = 400, height: number = 400, format: string = 'png'): Promise<Blob> {
		const canvas: any = document.createElement('canvas');
		canvas.width = width;
		canvas.height = height;

		const ctx = canvas.getContext('2d');
		ctx.clearRect(0, 0, width, height);
		
		for (let i = 0; i < 600; i++) {
			const x = Math.floor(Math.random() * 300);
			const y = Math.floor(Math.random() * 300);
			const radius = Math.floor(Math.random() * 20);
			
			const r = Math.floor(Math.random() * 255);
			const g = Math.floor(Math.random() * 255);
			const b = Math.floor(Math.random() * 255);
			
			ctx.beginPath();
			ctx.arc(x, y, radius, Math.PI * 2, 0, false);
			ctx.fillStyle = 'rgba(' + r + ',' + g + ',' + b + ',1)';
			ctx.fill();
			ctx.closePath();
		}

		return new Promise(function(resolve, reject) {
			canvas.toBlob(function(blob) {
				resolve(blob);
			}, 'image/' + format);
		});
	}
```
![output](https://user-images.githubusercontent.com/9158354/174644868-58aa2125-7260-488b-a8e1-2abb49e8313d.png)

### How does similar code behave in browsers?
 - In the browser the code generates a random image with some circles of random color.

**Comment by 1001Josias** [comment]
Did you manage to solve this problem?

**Comment by tentone** [comment]
So far no. Might take some time later to put togheter a branch to try and fix it and open PR after.

A walkaround is to use other available method to get the canvas content as image.
