### ISSUE TITLE
HTMLStyleElement has a null "sheet" property when created with DOMParser

### ISSUE THREAD

**Issue by mat-sz** [jsdom/jsdom#3386]
### Basic info:

- **Node.js version:** 18.3.0
- **jsdom version:** 20.0.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

const dom = new JSDOM();
const parsed = new dom.window.DOMParser().parseFromString(
  '<style>b { color: red; }</style>',
  'text/html'
);
const style = parsed.querySelector('style');
console.log(style.sheet); // will be null
```

### How does similar code behave in browsers?

```js
const parsed = new DOMParser().parseFromString(
  '<style>b { color: red; }</style>',
  'text/html'
);
const style = parsed.querySelector('style');
console.log(style.sheet); // will be CSSStyleSheet
```

https://jsbin.com/xatefupada/edit?html,console

Tested in Chromium 102.0.5005.61 and Firefox 101.0.

I believe that the check for defaultView is unnecessary: https://github.com/jsdom/jsdom/blob/6d7ccf2517259fe97b082b363134ea9612800747/lib/jsdom/living/nodes/HTMLStyleElement-impl.js#L55

In browsers, DOMParser root has no defaultView.

**Comment by domenic** [comment]
Same root cause as #3179; let's merge it into that.
