### ISSUE TITLE
Issue with the xhtml or xml loading into JSDOM

### ISSUE THREAD

**Issue by hadawalepravin13390** [jsdom/jsdom#3390]
### Before loading into JSDOM

`<p style="text-align:right;margin-bottom:0pt;margin-top:0pt;margin-left:0pt;;text-indent:0pt;;color:#000000;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;text-transform:none;font-variant: normal;"><ix:nonFraction unitRef="U_iso4217USD" id="F_000180" name="us-gaap:ComprehensiveIncomeNetOfTax" contextRef="C_0001364742_20220101_20220331" decimals="-6" format="ixt:numdotdecimal" scale="6">1,311</ix:nonFraction></p>`

### Content gets modified to

`<p style="text-align:right;margin-bottom:0pt;margin-top:0pt;margin-left:0pt;;text-indent:0pt;;color:#000000;font-size:10pt;font-family:Arial;font-weight:normal;font-style:normal;text-transform:none;font-variant: normal;"><ix:nonfraction unitref="U_iso4217USD" id="F_000180" name="us-gaap:ComprehensiveIncomeNetOfTax" contextref="C_0001364742_20220101_20220331" decimals="-6" format="ixt:numdotdecimal" scale="6">1,311</ix:nonfraction></p>`

### All the xml / xhtml tags and properties like ix:nonFraction, unitRef, contextRef are getting converted into lower cases. Would it be possible to restrict this conversion?

**Comment by domenic** [comment]
This issue does not follow the issue template, and so is not something we can help with.
