### ISSUE TITLE
Quick Question on Proxies

### ISSUE THREAD

**Issue by inf3rnus** [jsdom/jsdom#3391]
Hey all!

Hope you don't mind me posting here, I didn't see anything in the wiki on this...

I'm curious what the use of the proxies is for?

I get that a proxy allows you to listen to operations performed on one reference so that you can intercept those operations and perform side-effects on whatever else you have in memory as you see fit.

Just curious as to what the advantage/use case is for jsdom, it fascinates me and probably others?

**Comment by domenic** [comment]
Not sure what proxies exactly you're discussing, but maybe it's the `Proxy` JavaScript feature. In jsdom, those are necessary to implement this part of the web spec ecosystem: https://webidl.spec.whatwg.org/#es-legacy-platform-objects
