### ISSUE TITLE
is it an invalid source code from 'lib/jsdom/vm-shim.js/line 6' ?

### ISSUE THREAD

**Issue by liting-yes** [jsdom/jsdom#3399]
![屏幕截图 2022-07-10 205502](https://user-images.githubusercontent.com/69500429/178145807-3997dd48-2041-46ac-9696-c31478ae288e.jpg)

I am a beginner. When I looked at the source code, I found that the reference of this file here is invalid. Maybe it made sense before, but I don't quite understand the meaning now.

**Comment by domenic** [comment]
No, the code is valid.
