### ISSUE TITLE
Please upgrade nwsapi to 2.2.1 on next release to get fix on `toBeVisible` matcher 🙏 

### ISSUE THREAD

**Issue by vripoche** [jsdom/jsdom#3401]
Hello 😃,

nwsapi `2.2.0` have errors with visible matchers (`toBeVisible` from `jest-dom`) with last versions of JS-to-CSS libraries as xstyled. This was fixed on last hot fix of `nwsapi` (`2.2.1`), it works well with `patch-package` patch in my project but such patches are not really clean.

Regards.

**Comment by domenic** [comment]
jsdom already uses the ^2.2.0 specifier so any install of it will install nwsapi 2.2.1 since that is the latest version compatible with that specifier.

**Comment by vripoche** [comment]
It is still `2.2.0` version in `yarn.lock`, if I install latest version of `jsdom`: `20.0.0`, I have always `nwsapi` `2.2.0` in `node_modules`

**Comment by pomfrida** [comment]
@domenic 
Our Snyk security tests fails on your dependency nwsapi@2.2.0, as it has a DoS vulnerability.
Please upgrade this package to the latest version.
