### ISSUE TITLE
Request for clarification in the README 

### ISSUE THREAD

**Issue by 3rdManRun** [jsdom/jsdom#3410]
Noticed in the README it says:

> Event handler attributes, like `<div onclick="">`, are also governed by this setting; they will not function unless runScripts is set to "dangerously". (However, event handler properties, like `div.onclick = ...`, will function regardless of runScripts.)

So my confusion is how does anyone run `div.onclick` without runScripts? My understanding is that you need <script> to run scripts which would be noop without "dangerously"?

**Comment by domenic** [comment]
Example:

```js
const dom = new JSDOM();
dom.window.document.body.onclick = () => console.log("hello");
dom.window.document.body.dispatchEvent(new dom.window.Event("click"));
```

**Comment by 3rdManRun** [comment]
Thanks
