### ISSUE TITLE
'[:srcset]' is not a valid selector

### ISSUE THREAD

**Issue by Waynezhi** [jsdom/jsdom#3414]
- node v14.17.3
- jsdom v20.0.0

`this.dom.window.document.querySelectorAll('img[\\:src]:not([\\:srcset])')`

this selector works in chrome

_it does not work for me , but works for other people (even with jsdom v15), can not figure out why._

**Comment by domenic** [comment]
This issue does not follow the issue template, in particular including a full reproduction case (i.e. something I can copy paste into a file and run with `node test.js`). So we will have to close it.
