### ISSUE TITLE
[XML] querySelector with two elements, one capitalized

### ISSUE THREAD

**Issue by regseb** [jsdom/jsdom#3416]
### Basic info:

- **Node.js version:** v18.7.0
- **jsdom version:** 20.0.0

### Description

I found a difference between jsdom and browsers (Firefox and Chromium). For an XML document with a capitalized element, the `querySelector()` method doesn't work when searching by putting two elements in the selector.

- :heavy_check_mark: `querySelector("qux")`
- :heavy_check_mark: `querySelector("Qux")`
- :heavy_check_mark: `querySelector("qux corge")`
- :x: `querySelector("Qux corge")`

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const DOMParser = new JSDOM().window.DOMParser;

const xml = `<Foo><bar>baz</bar></Foo>`;
const root = "Foo";
const child = "bar";

const doc = new DOMParser().parseFromString(xml, "application/xml");
console.log("root: " + doc.querySelector(root).textContent);
console.log("child: " + doc.querySelector(child).textContent);
console.log("root child: " + doc.querySelector(`${root} ${child}`).textContent);
```

```
root: baz
child: baz
file:///home/regseb/testcase/index.js:11
console.log("root child: " + doc.querySelector(`${root} ${child}`).textContent);
                                                                  ^

TypeError: Cannot read properties of null (reading 'textContent')
    at file:///home/regseb/testcase/index.js:11:67
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.7.0
```

### How does similar code behave in browsers?

https://jsbin.com/xotuzuzage/edit?js,console

**Comment by regseb** [comment]
I opened an issue on https://github.com/dperini/nwsapi/issues/62.

**Comment by tinco** [comment]
We ran into this issue as well, temporary workaround that fixed it for us was adding:

```
    "resolutions": {
        "nwsapi": "2.2.0"
    },
```

To the top of our `package.json`. A fix seems to already been in the repo, but nwsapi is on a slow release schedule.

**Comment by regseb** [comment]
The bug in _nwsapi_ has been fixed. I created a PR to update the dependency.

- https://github.com/dperini/nwsapi/issues/62
- https://github.com/dperini/nwsapi/pull/79
- https://github.com/jsdom/jsdom/pull/3528
