### ISSUE TITLE
Having difficulty following advice in README

### ISSUE THREAD

**Issue by Korijn** [jsdom/jsdom#3417]
I'm using the latest version of jsdom with vue.js and am running tests in node.js. In the readme you give the following advice:

> We strongly advise against trying to "execute scripts" by mashing together the jsdom and Node global environments (e.g. by doing global.window = dom.window), and then executing scripts or test code inside the Node global environment. Instead, you should treat jsdom like you would a browser, and run all scripts and tests that need access to a DOM inside the jsdom environment, using window.eval or runScripts: "dangerously". This might require, for example, creating a browserify bundle to execute as a <script> element—just like you would in a browser.

However, vue acquires a handle on `document` at import time (see [here](https://github.com/vuejs/core/blob/9c304bfe7942a20264235865b4bb5f6e53fdee0d/packages/runtime-dom/src/nodeOps.ts#L5)). I don't really see how I can make that work with the advice given. I would prefer to instantiate the dom before every test and tear it down after every test, but the `document` global needs to exist already at import time... any advice on how I can wrangle this code into submission? :)

**Comment by domenic** [comment]
How would you run your tests in a browser? Presumably, using a `<script>` tag.

First, get them running in a browser using a `<script>` tag. Then, implement that solution in jsdom, by loading that same `<script>` tag into jsdom.

See also https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global.

Hope this helps!

**Comment by Korijn** [comment]
I see, thanks.

(I don't see how I can implement that in combination with things like [@vue/test-utils](https://github.com/vuejs/test-utils) since I would need to also run the test code in the browser, not just the library/application. In practice the boundary between application and test code is not as black and white as it is in your example.

**Comment by domenic** [comment]
Right, tests need to be runnable in a browser, to be runnable in jsdom. Because jsdom emulates a browser. If you can't run your tests in a browser, then they won't run in jsdom.

**Comment by DanKaplanSES** [comment]
> Right, tests need to be runnable in a browser, to be runnable in jsdom. Because jsdom emulates a browser. If you can't run your tests in a browser, then they won't run in jsdom.

@domenic In this context, do you consider selenium, Cypress.io, Puppeteer, TestCafe, etc. to run tests inside or outside the browser? In other words, is jsdom only intended to run _javascript unit_ test frameworks like Jasmine, Jest, Mocha, etc.?

**Comment by domenic** [comment]
I'm not familiar with those products, so I couldn't say.

**Comment by DanKaplanSES** [comment]
@domenic I see. In that case, I created #3608 to get more eyes on my question. Thanks!
