### ISSUE TITLE
CookieJar - Tough-Cookie breaking change 

### ISSUE THREAD

**Issue by arpowers** [jsdom/jsdom#3419]
ToughCookie just released a breaking change in a minor release and it's breaking all related tests using JSDom (when in localhost context)

Cause https://github.com/salesforce/tough-cookie/issues/246

Blown up tests look like this: 
<img width="1147" alt="Screen Shot 2022-08-22 at 3 44 12 PM" src="https://user-images.githubusercontent.com/308134/186032320-45e08f37-2d41-46fa-ac25-64ffcb424061.png">

Is it possible to provide the options required to the dependency? 

Otherwise, recommend pinning this particular dependency to version 4.0 until you have a chance to update

**Comment by CSchulz** [comment]
You can configure the cookie jar via the jsdom options, it is called cookieJar.

Here the example we are using for our jsdom jest environment:

    testEnvironmentOptions: {
      url: 'http://localhost/',
      cookieJar: new toughCookie.CookieJar(undefined, {
        // first option copied from https://github.com/jsdom/jsdom/blob/master/lib/api.js
        // // jsdom cookie jars must be loose by default
        looseMode: true,
        allowSpecialUseDomain: true,
      }),
    },

**Comment by arpowers** [comment]
Only problem for us is that we are using Vitest which doesn't provide an interface (that I've seen)

**Comment by redbugz** [comment]
If tough-cookie is going to be picky about this now, it would seem that jsdom should configure their internal cookieJar to be loose and allow special domains by default, as that seems a common use case for testing is to use special use domains

**Comment by andreschort** [comment]
Hi, this had me spinning a few hours today.
If you are using npm v8 you can use the overrides in package.json (https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)
Like this:
`"overrides": {
    "tough-cookie": "4.0.0"
  },`

**Comment by domenic** [comment]
I'm confident tough-cookie will revert their breaking change. I have no plans to address this on the jsdom side; please direct your attention to their repository instead, to urge them to fix their breaking change sooner.

**Comment by CSchulz** [comment]
If anyone still has trouble with the new 4.1.1 release, check your used url for your testing environment. It needs to be a full qualified domain name in case of localhost you can use localhost.local

**Comment by nagakiran** [comment]
> You can configure the cookie jar via the jsdom options, it is called cookieJar.
> 
> Here the example we are using for our jsdom jest environment:
> 
> ```
> testEnvironmentOptions: {
>   url: 'http://localhost.local/',
>   cookieJar: new jsdom.CookieJar(undefined, {
>     allowSpecialUseDomain: true,
>   }),
> },
> ```
> 
> You have to use a FQDN even for localhost otherwise you will run into [salesforce/tough-cookie#248](https://github.com/salesforce/tough-cookie/issues/248) bug.

Have tried this config in "jsest.config.js" but getting the error "jsdom is not defined". 
Do we need to import "jsdom" in some way to make it available in "jest.config.js" or this code snippet need to be placed in some other file?

**Comment by CSchulz** [comment]
> > You can configure the cookie jar via the jsdom options, it is called cookieJar.
> > Here the example we are using for our jsdom jest environment:
> > ```
> > testEnvironmentOptions: {
> >   url: 'http://localhost.local/',
> >   cookieJar: new jsdom.CookieJar(undefined, {
> >     allowSpecialUseDomain: true,
> >   }),
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You have to use a FQDN even for localhost otherwise you will run into [salesforce/tough-cookie#248](https://github.com/salesforce/tough-cookie/issues/248) bug.
> 
> Have tried this config in "jsest.config.js" but getting the error "jsdom is not defined". Do we need to import "jsdom" in some way to make it available in "jest.config.js" or this code snippet need to be placed in some other file?

Yes you have to require jsdom, but this is not required any more. With 4.1.2 there is another patch release which handles this case as well.
