### ISSUE TITLE
Add changelog to npmignore?

### ISSUE THREAD

**Issue by Pomax** [jsdom/jsdom#3424]
While important to have on the repo, the changelog file does not actually do anything other than take up a tremendous amount of space on disk. Especially for small projects, it would be super useful to not include it as part of the install package and instead simply have it exist on the repo for reference (the same argument could be made for the README.md, as people are far more likely to check the docs online than they are to dig through the node_modules dir for readme information)

**Comment by domenic** [comment]
I'd suggest that people who wish to strip their downloaded Node packages down to nothing, do so with post-install tools of their choice, instead of performing outreach to every package in their dependency tree.

**Comment by Pomax** [comment]
fair enough, but if the data is egragious and doesn't contribute to the dependency itself, filing issues on 20 repos seems entirely justified.
