### ISSUE TITLE
Query selector fails when parent tag contains an upper case letter

### ISSUE THREAD

**Issue by sasensi** [jsdom/jsdom#3428]
### Basic info:

- **Node.js version:** v16.13.0
- **jsdom version:** 20.0.0

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const xml = `
<root>
  <aB>
    <c></c>
  </aB>
  <cd>
    <e></e>
  </cd>
</root>
`;

const dom = new JSDOM(xml, { contentType: 'application/xml' });
const document = dom.window.document;
const ko = document.querySelectorAll('aB *').length; // 0 (should be 1)
const ok = document.querySelectorAll('cd *').length; // 1
```

### How does similar code behave in browsers?

This works as expected in browser, as demonstrated [here](https://jsfiddle.net/9txn1u54/1/).

```js
const xml = `
<root>
  <aB>
    <c></c>
  </aB>
  <cd>
    <e></e>
  </cd>
</root>
`;

const parser = new DOMParser();
const doc = parser.parseFromString(xml, "application/xml");

const ko = doc.querySelectorAll('aB *').length; // 1
const ok = doc.querySelectorAll('cd *').length; // 1

console.log({ko,ok});
```

**Comment by iMrDJAi** [comment]
I have the same issue! I thought the problem caused by my code, I was freaking out that I couldn't find what went wrong. 😅

**Comment by regseb** [comment]
I think this is the same problem as the issue: [_[XML] querySelector with two elements, one capitalized_ #3416](https://github.com/jsdom/jsdom/issues/3416)
