### ISSUE TITLE
FATAL ERROR when calling the constructor on a 31MB HTML file

### ISSUE THREAD

**Issue by omeriko** [jsdom/jsdom#3450]
### Basic info:

- **Node.js version: 17.0.1 
- **jsdom version: 16.2.2 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
```
Hi Guys,

We have to store and manipulate relatively heavy HTML files: about 30-40 Megabytes each file. 
When we try to read the file content from the hard disk into JSDOM by calling the JSDOM constructor:

const dom = new JSDOM(`
  a_large_string_ with_length_of_31_MB
`, {});

We get the following FATAL ERROR: 

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7252CAFFF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+113567
 2: 00007FF72525AA76 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+67382
 3: 00007FF72525B92D node::OnFatalError+301
 4: 00007FF725C4DB4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF725C3829D v8::Isolate::Exit+653
 6: 00007FF725ADBD3C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF725AD9231 v8::internal::Heap::CollectGarbage+4257
 8: 00007FF725AE008B v8::internal::Heap::GlobalSizeOfObjects+331
 9: 00007FF725B25DCB v8::internal::StackGuard::HandleInterrupts+891
10: 00007FF7258348D6 v8::internal::DateCache::Weekday+8342
11: 00007FF725CE0141 v8::internal::SetupIsolateDelegate::SetupHeap+513585
12: 0000021287B9B1C2
Worker 1  has exitted.

What can we do to fix that? 

(Link to a jsbin or similar strongly suggested.)

**Comment by omeriko** [comment]
Issue solved :-)

It appears that our server has only 2GB of RAM, and with JSDOM's memory consumption when manipulating a 31 MB html file - it was not possible :-(

We did 2 things:
=============== 

1. We replaced JSDOM with a different library that does not consume so much memory, and we succeeded to process our 31 MB HTML file even on 2 GB RAM.

2. We also upgraded our RAM memory from 2 GB to 8 GB in order to make sure our server can handle the load of concurrent requests of that kind.

**Comment by stas-dolgachov** [comment]
@omeriko Glad to hear. What library did you use?

**Comment by omeriko** [comment]
> @omeriko Glad to hear. What library did you use?
We are using cheerio library: https://cheerio.js.org/

**Comment by TimothyGu** [comment]
If Cheerio is sufficient for your purposes, there's no need to use jsdom :) We support a lot more things than Cheerio, and thus require a lot more memory.
