### ISSUE TITLE
 Cannot set window.crypto.subtle in jsdom 20.0.2

### ISSUE THREAD

**Issue by nmattia** [jsdom/jsdom#3455]
It looks like I can't add my own `crypto` implementation for NodeJS anymore, although it used to work. May be due to jsdom now providing _some_ implementation (https://github.com/jsdom/jsdom/pull/3352). See original ticket here: https://github.com/facebook/jest/issues/13542

### Basic info:

- **Node.js version:** v16
- **jsdom version:** 20.0.2

### Minimal reproduction case

Set `global.crypto` in `test-setup.ts` and then use e.g. `window.crypto.subtle.importKey`:

``` ts
// test-setup.ts
import crypto from "@trust/webcrypto";
global.crypto = crypto;
```

``` ts
// my-test.ts
    ...
    const key = await window.crypto.subtle.importKey( ... )
```

```
    TypeError: Cannot read properties of undefined (reading 'importKey')

      52 | ): Promise<[Uint8Array, Uint8Array]> {
      53 |   const data = new TextEncoder().encode("ed25519 seed");
    > 54 |   const key = await window.crypto.subtle.importKey(
         |                                          ^
      55 |     "raw",
      56 |     data,
      57 |     {
```

**Comment by domenic** [comment]
Unfortunately, this is not a miniaml reproduction case, as it appears to use third party modules and does not consist of a single set of lines we can paste into a file called `test.js` and run using `node test.js`.

If you are able to provide such a repro, please comment here and we can reopen the issue.

**Comment by SimenB** [comment]
fwiw, a minimal example is in the issue reported to jest: https://github.com/facebook/jest/issues/13542#issuecomment-1297158255

**Comment by domenic** [comment]
Ah, OK! That looks like it's working as expected. Browsers have the same behavior:

![Screenshot illustrating the same behavior in Firefox's developer console](https://user-images.githubusercontent.com/617481/205000436-956650ab-055c-4b34-b100-52b32700da8f.png)

**Comment by SimenB** [comment]
Fair enough - I didn't test out that part! 👍 I see adding more things to `crypto` work, rather than replacing the entire thing (at least in Chrome, e.g. `window.crypto.thing = 'wooo'`), so OP can probably just do

```js
import crypto from "@trust/webcrypto";
global.crypto.subtle = crypto.subtle;
```

**Comment by nmattia** [comment]
Thanks, I'll give it a try!

**Comment by nmattia** [comment]
That worked, thanks 👍 Had to tell ts not to worry though:

```ts
import crypto from "@trust/webcrypto";
// @ts-ignore
global.crypto.subtle = crypto.subtle;
```
