### ISSUE TITLE
Incomplete implementation of HTMLFormControlsCollection

### ISSUE THREAD

**Issue by csaunier** [jsdom/jsdom#3458]
Hello :wave: 

### Basic info:

- **Node.js version:** v16.10.0
- **jsdom version:** 20.0.1

### Minimal reproduction case

During my development, i encounter a case where i want to test that an input is well required, and thus not valid if i don't add any value.
For context, i'm inside a `jest` environment.

```js
  it("should fail because of being required ", () => {
    form = `
      <form id="form">
        <input type="text" required="true" name="name" />
      </form>
    `

    document.body.innerHTML = form
    expect(checkValidation(document.getElementById("form"))).rejects.toEqual({})
  })
```

```js

export const checkValidation = form => {
  const { elements } = form

  console.log(elements.namedItem("name").checkValidity())

  return new Promise((resolve, reject) => {
    // various validation using elements...
  })
}

 ```

But, (yes, there is a but), i have difficulties to understand how the newly implemented `HTMLFormControlsCollection` works, and his `namedItem`.

By looking at the file [HTMLFormControlsCollection-impl.js](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/nodes/HTMLFormControlsCollection-impl.js), it seems that only the `RadioNodeList` case is managed, so if there is radio button, but not all other form fields, under `Elements`.

It's also what i understand looking at the [spec](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#the-htmlformcontrolscollection-interface) or [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection).

This is linked to this PR : https://github.com/jsdom/jsdom/pull/3337

Can you confirm that the implementation of `HTMLFormControlsCollection` is not complete ?

**Comment by domenic** [comment]
Sorry, this issue does not contain a minimal reproduction case, following the issue template and using no third party libraries like Jest. Can you create an example that we can run by putting it into a file called `test.js`, and then running `node test.js`?

**Comment by csaunier** [comment]
Hello :) 

Indeed, i made a test.mjs file and all worked well!
```js
import { JSDOM } from 'jsdom'

const dom = new JSDOM(`
  <!DOCTYPE html>
  <body>
    <form id="form">
      <input type="text" required="true" name="name" value="shj" />
    </form>
  </body>
`)

const elements = dom.window.document.getElementById('form').elements
console.log(elements.namedItem('name'))
```

It make also dig a bit more inside `RadioNodeListImpl` and `NodeListImpl` to better understand what is happening.

Error was well in my context.

Sorry for opening this issue a bit too fast...
