### ISSUE TITLE
MouseEvent: x and y support

### ISSUE THREAD

**Issue by SimonSiefke** [jsdom/jsdom#3470]
### Basic info:

- **Node.js version:** 18.12.1
- **jsdom version:** 20.0.3

### Minimal reproduction case

![jsdom](https://user-images.githubusercontent.com/23744935/206845288-b00ea037-5e20-4d8c-8a0e-587b02721e02.png)

```js
import { JSDOM } from "jsdom";

const dom = new JSDOM(`<div></div>`, {});

// @ts-ignore
const { document } = dom.window;

const div = document.querySelector("div");

const handleClick = (event) => {
  const { x, y, clientX, clientY } = event;
  console.log(`x: ${x}`);
  console.log(`y: ${y}`);
  console.log(`clientX: ${clientX}`);
  console.log(`clientY: ${clientY}`);
};
div.addEventListener("click", handleClick);

const event = new MouseEvent("click", {
  clientX: 10,
  clientY: 20,
});
div.dispatchEvent(event);
```

### How does similar code behave in browsers?

`x` and `y` properties are printed to the console

![chrome](https://user-images.githubusercontent.com/23744935/206845406-28051b4d-d6cc-44f2-a455-c8d34dc932a4.png)

### Specification

Link: https://www.w3.org/TR/cssom-view-1/#extensions-to-the-mouseevent-interface

```
The x attribute must return the value of [clientX](https://www.w3.org/TR/cssom-view-1/#dom-mouseevent-clientx).

The y attribute must return the value of [clientY](https://www.w3.org/TR/cssom-view-1/#dom-mouseevent-clienty).
```

**Comment by domenic** [comment]
Fixed by #3484.
