### ISSUE TITLE
Document shows only "Location" attribute

### ISSUE THREAD

**Issue by TramontaG** [jsdom/jsdom#3473]
### Basic info:

I'm trying to use JSDOM for a webscraper and for some reason the window.document is loaded only with the Location attribute.  Nothing more

- **Node.js version:** v16.14.0
- **jsdom version:** 20.0.1

### Minimal reproduction case

```js
import axios from 'axios';
import { JSDOM } from 'jsdom';

axios
	.get('https://gadget.horoscopovirtual.com.br/horoscopo/')
	.then((resp) => new JSDOM(resp.data))
	.then((website) => {
		console.log(website.window.document); // Document { location: [Getter/Setter] }
	});

```

I've checked the result of the axios request and it contains the html in string form. It should be ok, I've already done that before with the exact same code and it worked fine.

**Comment by domenic** [comment]
Please add code that behaves differently (e.g., `x !== y`) in browsers and Node. What shows up in the console is up to Node.js and browsers's UI teams.

**Comment by TramontaG** [comment]
What you mean by code that behaves differently? The console output is not the problem, the JSDOM object itself is missing everything but `Location`, logging to the console was just the way to verify that. All the other properties like `querySelector`, `addEventListener`, `body` and everything else are undefined when I try to access via code.

**Comment by domenic** [comment]
Please give me an example that shows `website.window.document.body === undefined` or similar. I think you'll find that prints false.
