### ISSUE TITLE
'Unsuported type :hover' and 'Unknown pseudo-class selector :visible'

### ISSUE THREAD

**Issue by Ninita1** [jsdom/jsdom#3477]
### Basic info:

- **Node.js version:** 16.10.0
- **jsdom version:** 20.0.3

### Minimal reproduction case

I'm not able to use **selectors with pseudo classes**. Is there any trick to do this or some mandatory configuration?

For example, if I do `$("button:hover")` I get the error: 
> **Syntax error, unrecognized expression: unsupported pseudo: hover**

And if I do `document.querySelectorAll("div.testingDivs:not(:visible)")` I get the error:
> **unknown pseudo-class selector ':visible'**

Here is some code with examples: [demo project](https://codesandbox.io/s/cocky-butterfly-r1tutt?file=/src/App.test.js)

I already notice this problem is related to **nwsapi** plugin. Seems **jsdom** is not registering the pseudo-classes selectors and I think this should be doing in the file `jsdom\lib\jsdom\living\helpers\selectors.js`. 
In this file the **nwsapi** plugin is only initialized and in the `nwsapi.js` file the selectors are saved in the property `Selectors`. As the **nwsapi** is only initialized without any selector registered, then the `Selectors` are empty all the time and I get the "`unknown pseudo-class selector ':visible'`" error message.

I already tried to do this before the **Jest** test setup:
```
const _nwsapi = require("nwsapi"),
  NW = _nwsapi({
    document: window.document,
    DOMException: global.DOMException
  });

window.NW = {Dom: NW};

require("nwsapi/src/modules/nwsapi-jquery");
```

And almost worked, the `Selectors` were filled with the cases in that file. However, when I use a selector, the **jsdom** initialize the **nwsapi** and the `Selectors` are set to an empty object again.

Anyone have a solution for this?

Follow here too: https://stackoverflow.com/questions/74991267/unsuported-type-hover-and-unknown-pseudo-class-selector-visible

**Comment by domenic** [comment]
This issue does not follow the issue template, in particular the part that reads

```
TO BE CLEAR: your example needs to be self-contained enough that we can
copy-paste it into a file named `test.js`, and then run it using
`node test.js`. *No* Jest or similar.

IF YOU DO NOT FOLLOW THESE INSTRUCTIONS WE WILL CLOSE THE ISSUE.
```
