### ISSUE TITLE
`getComputedStyle` cache issue with v21.1.0

### ISSUE THREAD

**Issue by cexbrayat** [jsdom/jsdom#3502]
### Basic info:

- **Node.js version:** v16.14.2
- **jsdom version:** 21.1.0

### Minimal reproduction case

IIUC jsdom v21.1 introduced caching for getComputedStyle, triggering test failures when we upgraded to it.

Please take a look at the following test.

It accesses the computed style of an element created with `document.createElement` but never inserts it in the DOM, then updates it, then accesses the computed style again.

Then the test fails because the computed style is cached and we get the same one as the first access.
Removing the first access makes the test succeed (or downgrading to v21.0).

See the repro online on the following stackblitz if you prefer
https://stackblitz.com/edit/vitest-dev-vitest-whharw?file=test/basic.test.ts

```ts
const { JSDOM } = require('jsdom');

const { window } = new JSDOM(`<!DOCTYPE html><body></body>`);
const element = window.document.createElement('span');
// document.querySelector('body').appendChild(element);

console.log('before', element.style.display); // ''
// commenting out this line makes the test succeed
console.log(window.getComputedStyle(element).display); // ''

element.style.display = 'none';

console.log('after', element.style.display); // 'none'
console.log(window.getComputedStyle(element).display); // '' instead of 'none'

```

The test succeeds if:
- we comment the first check
- we use jsdom v21.0
- we insert the element in the DOM

**Comment by cexbrayat** [comment]
EDIT: I updated the original repro with Vue Code (as the one without was not reproducing the issue)

**Comment by domenic** [comment]
Closing per this comment in the issue template:

> Please create a minimal repro. Any reports involving third party libraries
> will be closed, as we cannot debug third-party library interactions for you.
> 
> Please do not use syntax that is not supported in Node.js, such as JSX. If
> we cannot run the code in Node.js, we will close the issue, as we cannot
> debug whatever toolchain you are using.
> 
> TO BE CLEAR: your example needs to be self-contained enough that we can
> copy-paste it into a file named `test.js`, and then run it using
> `node test.js`. *No* Jest or similar.
> 
> IF YOU DO NOT FOLLOW THESE INSTRUCTIONS WE WILL CLOSE THE ISSUE.

Let us know if you can follow these instructions, and then we can reopen and investigate the issue.

**Comment by cexbrayat** [comment]
@domenic Sorry about that, I updated the repro 👍

**Comment by domenic** [comment]
Thanks for updating the repro, and sorry for the delay as I was on vacation.

It looks to me like jsdom's behavior now correctly matches browsers: https://jsbin.com/covuqujaru/edit?html,console . Do you agree? If so, then I think this is working as intended, and you got a bugfix when you upgraded jsdom.

**Comment by cexbrayat** [comment]
Thanks for taking a look @domenic If that now matches the browser's behavior then I can't argue

For a bit of context: this triggers regressions in the Vue ecosystem as the official testing lib does not attach tested components to the DOM by default. We'll probably have to change that.

Thanks for your time
