### ISSUE TITLE
focusout relatedTarget should be an element or null

### ISSUE THREAD

**Issue by matttdawson** [jsdom/jsdom#3509]
### Basic info:

- **Node.js version:** 16.15.1
- **jsdom version:** 21.1

### Minimal reproduction case

This causes a problems in jest/jsdom tests with aggrid ^28.

The relatedTarget of a focusout event is set to document, which causes our aggrid tests to fail as related target should be an Element or null.

In the code at: https://github.com/jsdom/jsdom/blob/04f6c13f4a4d387c7fc979b8f62c6f68d8a0c639/lib/jsdom/living/nodes/HTMLOrSVGElement-impl.js#L79

The third parameter is setting the relatedTarget to this._ownerDocument.
In the w3c docs https://w3c.github.io/uievents/#focusout it says related target should be the 'event target receiving focus'.
Documents can't receive activeElement focus as they aren't elements.
At worst it should be null, at best it should be the element receiving focus.

### How does similar code behave in browsers?

Chrome browser returns null for relatedTarget when focusout is caused by not focusing another element, otherwise it returns the element that is being focused.

**Comment by elentok-salto** [comment]
Hi, Is there any workaround for this?

**Comment by swbartholomew** [comment]
Responding here as well since the root issue seems to be from here, but I am also experiencing this while using ag-grid and would appreciate any workarounds :)

**Comment by matttdawson** [comment]
No, sorry I haven't found workaround.  It's a real pain.

**Comment by matttdawson** [comment]
Wow, just after posting there's no work around I found one.
Add this to your jest test.
```
// @ts-ignore
document.classList = { contains: () => false };
```

**Comment by swbartholomew** [comment]
Haha that's awesome, glad you were able to find something, thanks for updating me! I'll let you know if we too can find success with this.
