### ISSUE TITLE
pushState/replaceState with empty URL removes hash fragment

### ISSUE THREAD

**Issue by joliss** [jsdom/jsdom#3513]
I'm not sure if this falls under #1565, but `pushState` and `replaceState` differ from browser behavior when the URL argument is `""`, in that they remove hash fragments from the URL.

### Basic info:

- **Node.js version:** 18.7.0
- **jsdom version:** master (65ef06)

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");
const dom = new JSDOM("", { url: "http://localhost/foo/bar#baz" });
dom.window.history.pushState(null, null, "");
console.log(dom.window.document.URL);
// prints: http://localhost/foo/bar
// should be: http://localhost/foo/bar#baz
```

### How does similar code behave in browsers?

In Chrome and Firefox:

```js
window.history.pushState(null, null, "/foo/bar#baz");
window.history.pushState(null, null, "");
console.log(window.document.URL);
// prints: http://localhost:3000/foo/bar#baz
```

**Comment by domenic** [comment]
This is actually a spec issue, and is blocked on resolving that: https://github.com/whatwg/html/issues/9343
