### ISSUE TITLE
`AbortSignal.timeout` not implemented

### ISSUE THREAD

**Issue by silverwind** [jsdom/jsdom#3516]
### Basic info:

- **Node.js version:** v19.7.0
- **jsdom version:** v21.1.0

### Minimal reproduction case

```js
console.log(AbortSignal.timeout(1000));
```

Raises `TypeError: AbortSignal.timeout is not a function`.

### How does similar code behave in browsers?

Logs `AbortSignal {aborted: false, reason: undefined, onabort: null}`

[MDN reference](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout)

**Comment by ajw015** [comment]
➕
