### ISSUE TITLE
Regular Expression Denial of Service (ReDoS) vulnerability

### ISSUE THREAD

**Issue by MateuszKikmunter** [jsdom/jsdom#3527]
### Basic info:

- **Node.js version:** 16.15.1
- **jsdom version:** 21.1.0

Snyk reports that jsdom is vulnerable to Regular Expression Denial of Service (ReDoS)
![Screenshot 2023-04-06 at 10 59 05](https://user-images.githubusercontent.com/38324997/230343994-e796c646-af64-4f61-82d8-a258a9645643.png)

### Minimal reproduction case

Run snyk scan against the package.

**Comment by MateuszKikmunter** [comment]
Closing as there's a [PR](https://github.com/jonschlinkert/word-wrap/pull/33) with a fix pending in the word-wrap repo.

**Comment by jacobleesinger** [comment]
It doesn't look like that PR's ever going to get merged 😞

**Comment by nchevsky** [comment]
For anyone else depending on `jsdom` <= 21, it's possible to upgrade `escodegen` to v2.1.0 which [moves `optionator` from `dependencies` to `devDependencies`](https://github.com/estools/escodegen/compare/v2.0.0...v2.1.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), removing `word-wrap` from the equation altogether.

### Before
```
└─┬ jest-environment-jsdom@29.6.0
  └─┬ jsdom@20.0.1
    └─┬ escodegen@2.0.0
      └─┬ optionator@0.8.3
        └── word-wrap@1.2.3
```

### After
```
└─┬ jest-environment-jsdom@29.6.0
  └─┬ jsdom@20.0.1
    └── escodegen@2.1.0
```
