### ISSUE TITLE
How to select event of "onload" in tag of "body"

### ISSUE THREAD

**Issue by Christynorl** [jsdom/jsdom#3530]
👋Hello everyone. I want to select the 'onload' event through jsdom. The code I use is `var dom=jsdom.JSDOM.fragment(html);
node=dom.querySelector("[onload]");` .When the html element includes an element like `<img src=x onload=alert("welcome")>` .It will be successfully selected, but the onload event in the body tag of the following tag cannot be successfully selected. Select, how should I solve it, thank you for your help.When my html is `<body onload=alert(1)>` .It failed to select the element.What should I do if I want to select the onload event in the body tag.

**Comment by domenic** [comment]
This does not follow the issue template, and as such is being closed.
