### ISSUE TITLE
How to select event 'onload' in tag 'body'?

### ISSUE THREAD

**Issue by Christynorl** [jsdom/jsdom#3531]
### Basic info:

- **Node.js version:** v18.12.1
- **jsdom version:** the latest version
function    "querySelector"

### Minimal reproduction case
Hello everyone. I want to select the 'onload' event through jsdom. The code I use is `var dom=jsdom.JSDOM.fragment(html); node=dom.querySelector("[onload]"); `.When the html element includes an element like `< img src=x onload=alert("welcome")>` .It will be successfully selected, but the onload event in the body tag of the following tag cannot be successfully selected. Select, how should I solve it, thank you for your help.When my html is `<body onload=alert(1)>` .It failed to select the element.What should I do if I want to select the onload event in the body tag.

### How does similar code behave in browsers?
`<body onload=alert("welcome")>`
the window is alerted successfully.So how can I select the event onload in tag body?Do you have some good ideas?Thanks so much.

**Comment by domenic** [comment]
This issue does not follow the issue template, in particular it does not give a specific version for jsdom, and this part of the issue template is not followed:

````

<!--
Please create a minimal repro. Any reports involving third party libraries
will be closed, as we cannot debug third-party library interactions for you.

Please do not use syntax that is not supported in Node.js, such as JSX. If
we cannot run the code in Node.js, we will close the issue, as we cannot
debug whatever toolchain you are using.

TO BE CLEAR: your example needs to be self-contained enough that we can
copy-paste it into a file named `test.js`, and then run it using
`node test.js`. *No* Jest or similar.

IF YOU DO NOT FOLLOW THESE INSTRUCTIONS WE WILL CLOSE THE ISSUE.
-->

```js
const { JSDOM } = require("jsdom");

const options = {
  ... your options here ...
};
const dom = new JSDOM(`
  ... your HTML here ...
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

````
