### ISSUE TITLE
jsdom在vue项目中引入报错

### ISSUE THREAD

**Issue by mxjgit** [jsdom/jsdom#3534]
Failed to compile.

./node_modules/jsdom/lib/api.js 140:46
Module parse failed: Unexpected token (140:46)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|           url: req.href + originalHash,
|           contentType: res.headers["content-type"],
>           referrer: req.getHeader("referer") ?? undefined
|         });
|

**Comment by beydeng** [comment]
这里报错的原因，最后找到了没？

**Comment by c1h2e6n** [comment]
解决了么？我现在也遇到这个
