### ISSUE TITLE
Having a error in a script stops all scripts from running

### ISSUE THREAD

**Issue by JijaProGamer** [jsdom/jsdom#3539]
### Basic info:

- **Node.js version:** v18.14.2
- **jsdom version:** v21.1.1

### Minimal reproduction case

JSDom stops execution for all scripts if any script included in the page has a error. This stops web scraping, since this will stop Javascript from running on websites like reddit, youtube and StackOverflow.

This is the error I get: "Error: Uncaught [ReferenceError: StackExchange is not defined]"

### How does similar code behave in browsers?

Puppeteer and chromium run javascript just fine

**Comment by domenic** [comment]
This issue does not follow the issue template, in particular this part:

```
TO BE CLEAR: your example needs to be self-contained enough that we can
copy-paste it into a file named `test.js`, and then run it using
`node test.js`.
```

As such, we'll close it.
