### ISSUE TITLE
`href` attribute doesn't prefix by `location`

### ISSUE THREAD

**Issue by regseb** [jsdom/jsdom#3545]
### Basic info:

- **Node.js version:** v18.16.0
- **jsdom version:** 22.0.0

The [`href`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/href) attribute doesn't prefix the URL returned by `location`.

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const jsdom = new JSDOM();
jsdom.reconfigure({ url: "https://jsbin.com/foo" });
const DOMParser = jsdom.window.DOMParser;

// Workaround
// Object.defineProperty(jsdom.window.HTMLAnchorElement.prototype, "href", {
//     get: function () {
//         return new URL(this.getAttribute("href"), jsdom.window.location).href;
//     },
// });

const doc = new DOMParser().parseFromString('<a href="bar"></a>', "text/html");
console.log(doc.querySelector("a").href); // Expected "https://jsbin.com/bar"
```

```shell
bar
```

### How does similar code behave in browsers?

https://jsbin.com/nidizegote/edit?js,console

```shell
https://null.jsbin.com/bar
```

**Comment by domenic** [comment]
This was fixed in https://github.com/jsdom/jsdom/commit/35259cc11e1fe52a1fd7ad8eece8b0f715d57686.
