### ISSUE TITLE
RequestError: Error: unable to verify the first certificate #1897

### ISSUE THREAD

**Issue by Ukhupacha** [jsdom/jsdom#3548]
### Basic info:

- **Node.js version:** 
- Node v18.14.0
- **jsdom version:** 
22.0.0
### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');

JSDOM.fromURL('https://www.senamhi.gob.pe/?p=pronostico-detalle&dp=08&localidad=0019').then(dom => {
  console.log(dom.serialize());
});
```

### How does similar code behave in browsers?
It works normally on browsers. 
[https://www.senamhi.gob.pe/?p=pronostico-detalle&dp=08&localidad=0019](url)

This issue is related to this ticket [https://github.com/jsdom/jsdom/issues/1897#issue-238726661](url)
I have a webpage from which I want to scrape content (weather related) but the webpage doesn't have a certificate chain complete [https://www.ssllabs.com/ssltest/analyze.html?d=www.senamhi.gob.pe](url), because of that I get **Unable to veriff the first certificate**, is there a way that I can still get the DOM content?

Kindly

**Comment by domenic** [comment]
We inherit this behavior from Node.js's `https` module, and so it is outside of our control. Please file the issue on https://github.com/nodejs/node instead. Ideally with a minimal reproduction case that does not use jsdom.
