### ISSUE TITLE
how can globalThis.xxx = 'xxx' set to globalThis in node instead of set to jsdom.window.xxx in script tag

### ISSUE THREAD

**Issue by nyqykk** [jsdom/jsdom#3550]
### Basic info:

- **Node.js version:*latest* 
- **jsdom version:*latest* 

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const options = {
  runScripts: "dangerously",
  resources: "usable",
};
const dom = new JSDOM(`
  <script>globalThis.xxx = 'xxx'</script>
`, options);

... your code that reproduces the problem here, probably using dom.window ...
```

because i use globalThis to get the variable,but i use loadScript(create a script tag to load resource) so that the variable was set to jsdom.window, this will cause i can nerver get the variable,can this variable escape to globalThis or other method? thanks

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
This kind of question is better suited for StackOverflow, as it's not a bug in jsdom.
