### ISSUE TITLE
Update tough-cookie package to version 4.1.3 - critical vulnerability

### ISSUE THREAD

**Issue by sveem** [jsdom/jsdom#3572]
Update **tough-cookie** dependency to the latest version 4.1.3 due to a critical vulnerability.

**Reason:** Versions of the package tough-cookie before 4.1.3 are vulnerable to Prototype Pollution due to improper handling of Cookies when using CookieJar in rejectPublicSuffixes=false mode. This issue arises from the manner in which the objects are initialized.

https://github.com/salesforce/tough-cookie/releases/tag/v4.1.3

**Comment by amonnphillip** [comment]
When do you think the PR for this will be merged?

**Comment by sl-arnaudmathieu** [comment]
Hi, a new release will be released to include this fix in the last version ? Cheers

**Comment by domenic** [comment]
jsdom does not set the `rejectPublicSuffixes` flag, so this issue does not affect us.

**Comment by carledren** [comment]
My opinion on the matter. If a vulnerability doesn't pose a direct threat in a specific context, it can still be good practice to update dependencies to their latest secure versions where feasible. This proactive approach can help prevent future vulnerabilities that might be introduced if the usage of the dependency changes, and can also alleviate concerns from users or contributors who might be alarmed to see a known vulnerability in the dependency tree.

As for people looking for a fix to this vulnerability, one can add the latest tough-cookie in an:
`override: {}` field in your package.json. See [overrides field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)

**Comment by domenic** [comment]
jsom already uses the `^4.1.2` semver specifier so anyone who installs it will get the latest version of tough-cookie in the 4.x range.

**Comment by bovas85** [comment]
4.1.2 is vulnerable, the semver won't fix that
