### ISSUE TITLE
Reset VM Context for each test

### ISSUE THREAD

**Issue by suityou01** [jsdom/jsdom#3573]
### Basic info:

I want to create a custom environment that can reset the VM context between tests.

- **Node.js version:** 16
- **jsdom version:** 22

### Minimal reproduction case

```js
const JSDOMEnvironment = require('jest-environment-jsdom').TestEnvironment;
class NunjucksTestEnvironment extends JSDOMEnvironment {
    
    constructor(config, context) {
      super(config, context);
    }
    setupScriptHelpers = () => {
      this.global.reloadScript = (scriptId, document) => {
      const script = document.getElementById(scriptId);
      const scriptContent = script.textContent;
      script.parentNode.removeChild(script);
      const loadBackScript = document.createElement('script');
      loadBackScript.setAttribute('id', scriptId);
      loadBackScript.textContent = scriptContent;
      document.body.appendChild(loadBackScript);
    };

    async setup() {
      await super.setup();
      setupScriptHelpers();
    }

    async teardown() {}

    getVmContext() {
      return super.getVmContext();
    }

    async handleTestEvent(event, state) {
      if (event.name === 'test_start') { 
      
      }
    }
}
```	

The in my test suite

```js
/**
 * @jest-environment ./__tests__/environments/nunjucks-test-environment.js
 */
/* eslint-env browser */
describe('template.njk', () => {
	it('should return true from the script function call', () => {
		document.body.innerHTML = nunjucksTestRenderer.render(
			`template.njk`
		);
		global.reloadScript('myscript', document); <-- Here it breaks
		
	});
```

So in my template you would have something like ...

```jinja2
{% block content %}
    <script id='clientside-validation'>
      const val = 1; /* This gets created on the global context of the VM so cannot reload this script without reseting the whole of JSDOM
    </script>
{% endblock %}
```

So hopefully you can see my reload function when it reloads the script element in the subsequent tests withint the same suite this will fail with the error

"Identifier is already declared"

and the error is thrown from processJavaScript (node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:242:10)

Which looks like this

```js
vm.runInContext(code, window, { filename, lineOffset, displayErrors: false });
```

The second argument to vm.runInContext is the window object which is set up when the environment is first set up, and "Contextified" into a vm context because "runscripts: 'dangerously'" is set.

My question specifically is how can I provide a new context to the VM for every test?

I can lift the createWindow function from '/jsdom/lib/jsdom/browser/Window' and create a new Window without much hassle, and this is not adding much to the testing time. When I try and reset the this.dom.window in the test environment is where I run into trouble.

It seems the window property of the JSDOM object is declared unique by a symbol. How can I reset this property with the new window value?

**Comment by domenic** [comment]
This is not the repository for jest-jsdom-environment, so we cannot help with this.

**Comment by suityou01** [comment]
My question was specifically about JSDOM. The error line was from a JSDOM class. This is not a jest-jsdom-environment question but a JSDOM only question. Please re-read. For clarity, the vmConsole and Window objects are JSDOM constructs not jest.

**Comment by domenic** [comment]
If you would like help you'll need to follow the issue template and give self-contained example code showing the bug using no third party packages.
