### ISSUE TITLE
NodeLists from different documents have unequal constructors

### ISSUE THREAD

**Issue by papandreou** [jsdom/jsdom#3575]
### Basic info:

- **Node.js version:** 20.4.0
- **jsdom version:** 22.1.0

### Minimal reproduction case

```js
const parseHtmlDocument =
  typeof DOMParser !== 'undefined'
    ? (str) => new DOMParser().parseFromString(str, 'text/html')
    : (str) => new (require('jsdom').JSDOM)(str).window.document;

const htmlSrc = '<!DOCTYPE html><html><head></head><body>foo</body></html>';

// Parse the document twice and fetch the child nodes of the HTMLHtmlElement:
const aNodeList = parseHtmlDocument(htmlSrc).childNodes[1].childNodes;
const bNodeList = parseHtmlDocument(htmlSrc).childNodes[1].childNodes;

console.log(aNodeList.constructor === bNodeList.constructor); // false
```

### How does similar code behave in browsers?

It returns `true`, see [jsfiddle](https://jsfiddle.net/0kLy8arh/)

### Discussion

Interestingly, `NodeList`s belonging to the same document have the same constructor.

The constructors used to be equal across documents, I've bisected the change in behavior down to [this commit](https://github.com/jsdom/jsdom/commit/5e39a4c60377c95ac09ea938ecbf5f1f91cb0360), which landed in 16.0.0.

I ran into this while trying to [update `jsdom`](https://github.com/unexpectedjs/unexpected-dom/pull/473) in the `unexpected-dom` DOM assertion library. The internals of the assertion library checks that the constructors match when comparing array-like objects, which causes identical documents and nodelists to be considered unequal.

I'm not sure if this is by design, and I can obviously work around it on my side, but I still wanted to bring it up because it differs from what `DOMParser` does in browsers. I'm not 100% sure whether it's considered analogous to `new JSDOM`, though :innocent:

**Comment by domenic** [comment]
This is by design. A new JSDOM instance is a new Window, which comes with a new copy of every property of Window, including window.NodeList.

If you want behavior like you get in browsers by using DOMParser multiple times, then use a single jsdom Window's dom.window.DOMParser, like you do in browsers.

**Comment by papandreou** [comment]
Thanks for clarifying! I'll figure something out.
