### ISSUE TITLE
I can't use instanceof because the element classes are from a different JSDOM instance and therefore not the same class

### ISSUE THREAD

**Issue by coolCucumber-cat** [jsdom/jsdom#3576]
### Basic info:

- **Node.js version:** 18.16.0 
- **jsdom version:** 21.1.1 

### Minimal reproduction case

```js
import { JSDOM } from 'jsdom'
const { HTMLElement } = new JSDOM().window

const html = new JSDOM('<div></div>').window.document
console.log(html.querySelector('div') instanceof HTMLElement) //false, because they are both the HTMLElement class, but not the same one, just like how `[] != []` but `let a = []; a == a`
```

This is a very simple example, but when you have multiple DOMs for webscraping (fetching all the links and then scraping the links), along with a global function to check that something is a HTMLElement and throwing errors if it isn't, this is a nightmare. The classes should not be from each instance, because otherwise you can't compare them, it will always be false.

Anyone know any other packages that already have this implemented?

**Comment by domenic** [comment]
Each JSDOM instance has its own Window. This is by design. If you want to reuse a Window (and all its classes), then you need to structure your code this way.

**Comment by coolCucumber-cat** [comment]
> Each JSDOM instance has its own Window. This is by design. If you want to reuse a Window (and all its classes), then you need to structure your code this way.

You are misunderstanding. Obviously each instance has its own window, how the hell would it work if it didn't? Each instance has its own HTMLElement, HTMLDivElement etc, which is the problem. It means I can't reuse the class across multiple instances and I have to get them for each instance, along with any function that uses them.

**Comment by domenic** [comment]
Of course. That's how windows work. window1 is entirely different from window2, including its properties like window1.HTMLElement vs. window2.HTMLElement.

**Comment by coolCucumber-cat** [comment]
> Of course. That's how windows work. window1 is entirely different from window2, including its properties like window1.HTMLElement vs. window2.HTMLElement.

How else am I supposed to do it?

**Comment by coolCucumber-cat** [comment]
You can import DOMWindow, why not Document, HTMLElement etc
