### ISSUE TITLE
The entire lib/jsdom/living/generated directory is missing while in use by lib/jsdom/living/aborting

### ISSUE THREAD

**Issue by abbaseya** [jsdom/jsdom#3581]
I believe this is a mistake at the latest release, similar to #1449 
With a missing `lib/jsdom/living/aborting/AbortSignal-impl.js` I get the following error whenever using `signal` as a third parameter for `addEventListener`:

```javascript
const dom = new JSDOM(`<body>
  <script>
    const controller = new AbortController();
    window.addEventListener('scroll', () => {}, { signal: controller.signal }
  </script>
</body>`, { runScripts: "dangerously" });
```

Result:
```
TypeError: Failed to execute 'addEventListener' on 'EventTarget': parameter 3 dictionary has member 'signal' that is not of type 'AbortSignal'.
```

**Comment by abbaseya** [comment]
Scratch that, turns out that `AbortController` needs to get exposed in testing environment!

```javascript
global.AbortController = dom.window.AbortController;
```

**Comment by domenic** [comment]
https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

**Comment by abbaseya** [comment]
> https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

Thanks for the hint @domenic but isn't that suggesting to change the source code before testing?
I mean `const controller = new AbortController();` to `const controller = new window.AbortController();` ?
