### ISSUE TITLE
An error has occurred related to the 'safer-buffer' dependency.

### ISSUE THREAD

**Issue by rkdmf0000** [jsdom/jsdom#3582]
### Basic info:

- **Node.js version:v18.15.0 
- **jsdom version:22.1.0 
-  @types/jsdom : 21.1.1

### Minimal reproduction case
There is no example of code writing. This happens after the installation is done

### How does similar code behave in browsers?
1.
![image](https://github.com/jsdom/jsdom/assets/24689260/0f086b8e-f30b-488f-9c18-5514633ed896)

2.
![image](https://github.com/jsdom/jsdom/assets/24689260/5f4a93de-9428-4d9a-a5d4-8c30d461ff83)
I tried changing the version of 'safer-buffer', but the issue has not been resolved.

**Comment by domenic** [comment]
This issue does not follow the issue template, including example code we can use to reproduce the problem, so we cannot help.

**Comment by rkdmf0000** [comment]
Since the error occurs just by installing it, there is no appropriate example to provide. 

Here's the installation command:
`npm install jsdom`

**Comment by domenic** [comment]
Ah. That does not occur on my system, or on the system of the other thousands of jsdom users, so this is an issue with your computer, not with jsdom.

**Comment by rkdmf0000** [comment]
Oh, I see, thank you for the answer. I will let you know if there are any good results or solutions.

The development environment is a Node-based Docker container on Ubuntu OS, running on AWS EC2. I am using the Nuxt framework in Vue3.

**Comment by OfficialCRUGG** [comment]
I can reproduce this on SvelteKit with Svelte when on the client-side.

**Comment by broken-arun** [comment]
@domenic It is happening in a contained environment also. Here is the code sample: https://stackblitz.com/edit/vitejs-vite-mub4s9?file=src%2FApp.tsx

Please look into it
