### ISSUE TITLE
Update tough-cookie-4.1.2.tgz version to 4.1.3 

### ISSUE THREAD

**Issue by bchandel77** [jsdom/jsdom#3590]
### Basic info:

- **Node.js version:** 
- **jsdom version:** 

### Minimal reproduction case
Hi Team, Versions of the package tough-cookie before 4.1.3 are vulnerable to Prototype Pollution due to improper handling of Cookies when using CookieJar in rejectPublicSuffixes=false mode. This issue arises from the manner in which the objects are initialized. Could you please upgrade the version to 4.1.3.

**Comment by domenic** [comment]
Dupe of closed issues and PRs.
