### ISSUE TITLE
[bug] unclosed tag, with special character present

### ISSUE THREAD

**Issue by joaocruz-dev** [jsdom/jsdom#3595]
I believe I found a bug in the JSDOM parser.

Given a UTF-8 string in the XML standard (found below), when removing the **&** character, jsdom correctly returns the data, with the presence of the **&** character, it throws an error: **about:blank:10: 0: unclosed tag: MEMO**

### Basic info:

- **NPM version:** 9.5.1
- **Node.js version:** 18.16.0
- **jsdom version:** 22.1.0

### Minimal reproduction case

```ts
import { JSDOM } from 'jsdom'

const xml = `
<OFX>
<STMTTRN>
<TRNTYPE>DEBIT</TRNTYPE>
<TRNAMT>-127</TRNAMT>
<FITID>c1c9d884-ae76-4140-9e9c-83d7c3dfbeeb</FITID>
<MEMO>PG *BANK & LABEL</MEMO>
<NAME>PG *BANK & LABEL</NAME>
</STMTTRN>
</OFX>
`
const dom = new JSDOM(xml, { contentType: 'text/xml' })
```

**Obs:** I carried out tests with other special characters and the exception was not thrown. I believe it is something related to special HTML codes, which start with **&**

**Comment by domenic** [comment]
This is because this is invalid XML. Use `&amp;` to escape.
