### ISSUE TITLE
document.appendChild should throw if there is already a child

### ISSUE THREAD

**Issue by aredridel** [jsdom/jsdom#36]
Should raise a heirarchy error

**Comment by snuggs** [comment]
Also processing instructions are included as well @aredridel @tmpvar @domenic is this fixed or should we add test? Going through some old issues for some low hanging fruit cleanup.

**Comment by pmdartus** [comment]
The proper `HierarchyRequestError` is thrown when attempting to insert a new child on a Document with a child. This case is covered by the [append-on-Document.html](https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/append-on-Document.html#L25-L32) test.
The issue can be closed.
