### ISSUE TITLE
new URL(…).searchParams.size is not implemented

### ISSUE THREAD

**Issue by Ayc0** [jsdom/jsdom#3604]
### Basic info:

- **Node.js version:** v18.15.0
- **jsdom version:** v22.1.0

### Minimal reproduction case

```js
const { JSDOM } = require('jsdom');
const jsdom = new JSDOM();
console.log(new jsdom.window.URL('https://github.com/jsdom/jsdom').searchParams.size);
// undefined & should be 0

console.log(new jsdom.window.URL('https://github.com/jsdom/jsdom?hello').searchParams.size);
// undefined & should be 1
```

### How does similar code behave in browsers?

In the chrome devtools:

```js
new URL('https://github.com/jsdom/jsdom').searchParams.size
new URL('https://github.com/jsdom/jsdom?hello').searchParams.size
```

<img width="493" alt="image" src="https://github.com/jsdom/jsdom/assets/22725671/fb1a2292-7681-475f-b0fb-95b020681cf9">

**Comment by Ayc0** [comment]
To fix it locally in my codebase, I added this in the `setupFilesAfterEnv` file for my Jest conf:

```js
Object.defineProperty(URLSearchParams.prototype, 'size', {
    get() {
        let size = 0;
        for (const entry of this) {
            size++;
        }
        return size;
    },
});
```

**Comment by Ayc0** [comment]
I can see that `whatwg-url` added this in their last version, so we could just upgrade `whatwg-url` to the v13:

https://github.com/jsdom/whatwg-url/releases/tag/v13.0.0

> Added `URLSearchParams`'s `size` getter, per https://github.com/whatwg/url/commit/12b6f0c456c6df049e2704c92bb3a6d4d1364ec8.

**Comment by Ayc0** [comment]
I opened https://github.com/jsdom/jsdom/pull/3606 to fix this issue

**Comment by jimmywarting** [comment]
Erm... if we would use global built in URL / SearchParams this wouldn't be an issue. 
Maybe we could use built in instead?
