### ISSUE TITLE
Deprecated Punycode module generating deprecation warnings

### ISSUE THREAD

**Issue by danascheider** [jsdom/jsdom#3613]
### Basic info:

- **Node.js version:** 21.0.0
- **jsdom version:** 22.1.0

### Minimal reproduction case

After updating to Node 21.0.0 from 19.8.1, I am seeing deprecation warnings when I run my headless Vitest tests:

```
The `punycode` module is deprecated. Please use a userland alternative instead.
```

You can see examples of this warning in the test step of [this GitHub Actions build](https://github.com/danascheider/skyrim_inventory_management_frontend/actions/runs/6660333198/job/18101256615?pr=165).

Running `yarn why punycode` on my project reveals that punycode is a transitive dependency of JSDOM that I cannot directly update or remove as a dependency. Looking through the issues and PRs on this repo, it seems no one has raised this before. I'm not sure of the scope of required changes to remove this module from JSDOM, but this is something I might be able to help out with if it isn't too onerous. In either case I thought the maintainers might like to know about this since it could be a compatibility issue with future Node versions.

### Additional Information

Punycode is a transitive JSDOM dependency, through the [tough-cookie](https://www.npmjs.com/package/tough-cookie) package. Discussion on [this issue report](https://github.com/salesforce/tough-cookie/issues/315) indicates that Punycode is removed as a dependency in v. 4.1.0.

**Comment by danascheider** [comment]
Update: This seems to be an issue with `tough-cookie` - they said updating `tough-cookie` to 4.1.3 should fix the warnings but it is already at 4.1.3 in my project. I'm following up with the maintainers to see what they say and will circle back here when I know more or an update is released.

**Comment by ddolcimascolo** [comment]
It's `psl`, actually. See https://github.com/lupomontero/psl/issues/296

**Comment by oidualc** [comment]
So, from tough-cookie they say they don't intend to support Node 21, so the issue is not even considered. Would it mean that jsdom will print the warning for all the lifetime of Node 21, or is it possible to evaluate an alternative solution (e.g. use dependencies that do support non LTS Node versions)?
https://github.com/salesforce/tough-cookie/issues/324

**Comment by danascheider** [comment]
Thanks for the added info, folks. I'd also be interested in JSDOM's intended path forward on Node 21 support since, as the thread @oidualc linked notes, Node 22 won't be out for a while. The offer to help out with this stands.

**Comment by wirdehall** [comment]
> Thanks for the added info, folks. I'd also be interested in JSDOM's intended path forward on Node 21 support since, as the thread @oidualc linked notes, Node 22 won't be out for a while. The offer to help out with this stands.

Me too. Any update on this? Will JSOM not support Node 21?

**Comment by domenic** [comment]
jsdom works fine on Node 21.

**Comment by oidualc** [comment]
> jsdom works fine on Node 21.

We know, the question is if jsdom supports Node 21, not if it just works on it. Those are two different things.

**Comment by domenic** [comment]
jsdom supports Node 21.

**Comment by luckydonald** [comment]
`psl` has been updated to use the userland one (https://github.com/lupomontero/psl/commit/3ddec00372501a4657d28fbd87e6fd59db12a897).

Alternatively, `tough-cookie` has swiched to `tldts`: https://github.com/salesforce/tough-cookie/pull/346,
as there's no movement in https://github.com/lupomontero/psl/issues/296 (they finally fixed it almost two months ago, but still no release)

**Comment by skagedal** [comment]
Hello and thank you for maintaining this package! It appears that a new release of [tough-cookie](https://github.com/salesforce/tough-cookie) was released a few days ago that includes the updated dependencies. Would it be possible for you to upgrade the dependency of tough-cookie to 4.1.4?

**Comment by domenic** [comment]
jsdom already uses `^` in its dependency specifier so there is no action necessary from our side as long as tough-cookie incorporates the improvement in a minor or patch version.

**Comment by eyelidlessness** [comment]
Would it be reasonable to load `tough-cookie` on demand (e.g. on access to cookie-specific DOM APIs)? I'd be happy to look into contributing this if it's welcome.

**Comment by TimJohns** [comment]
First, as always, big thank you to the contributors and maintainers here. 

Heads-up that `tough-cookie` 4.1.4 still uses `psl`, and per [this comment in tough-cookie issue 338,](https://github.com/salesforce/tough-cookie/issues/338), it sounds like it will need an explicit update (i.e. the ^ in the dependency specifier for jsdom won't get it automatically):

> @skagedal this won't be backported to 4.1.4. It's only available in our v5 release candidate for now ([5.0.0-rc.1](https://www.npmjs.com/package/tough-cookie/v/5.0.0-rc.1)).
>
> The upcoming v5 release is primarily an internal uplift that includes TypeScript support and improved documentation so it should be a seamless upgrade but feel free to try out the release candidate ahead of time and report any issues 😄

**Comment by dolie** [comment]
Deprecation warnings have been visible for too long 👎 JSdom has too many dependencies.
I switched to `happy-dom` 🌈🚀.

**Comment by Mukul1127** [comment]
Just wanna relay this but @aparajita shared a nice .pnpmfile.cjs to fix it:

https://github.com/absolute-version/commit-and-tag-version/issues/166#issuecomment-2232070913

It just upgrades the tough-cookie dependency to 5.0.0-rc

**Comment by JanMosigItemis** [comment]
Hm not sure about this.. the deprecation warnings are gone, but still:

$ npm ls punycode
└─┬ jsdom@25.0.0
  └─┬ whatwg-url@14.0.0
    └─┬ tr46@5.0.0
      └── punycode@2.3.1

**Comment by JanMosigItemis** [comment]
Hm.. on a second thought, I guess these use the userland version of punycode?

**Comment by avegancafe** [comment]
Has this been fixed at all? This issue sounds like it's been addressed but I'm still seeing this issue and just installed jest and jest-environment-jsdom

**Comment by HummingMind** [comment]
jsdom 25.0.1 is using a newer version of touch-cookie, which no longer generates this warning.

So you would need to make sure any pakcages you are using that rely on jsdom, are set to use jsdom ^25.
Or you can use overrides to do that yourself (at your own risk of any potential incompatibilities).

**Comment by luskin** [comment]
Am I missing something or is this still a problem with jsdom 25.0.1?

<img width="327" alt="Image" src="https://github.com/user-attachments/assets/8a6af1c7-b09c-4b63-a230-c5fda2902131" />

**Comment by xfournet** [comment]
@luskin no problem, see https://github.com/jsdom/tr46/blob/v5.0.0/index.js#L3
