### ISSUE TITLE
SyntaxError: Unexpected `||=` Operator on Web Service Hosting

### ISSUE THREAD

**Issue by JAYAKANTHARUN** [jsdom/jsdom#3635]
### Basic info:

- **Node.js version:** v18.16.1
- **jsdom version:** ^23.0.1

### Minimal reproduction case

```js
const express = require('express')
const app = express()
const { JSDOM } = require("jsdom");

app.post('/submit2',(req,res)=>{
    let currentTextarea2 = req.body.textarea3 || '';
    currentTextarea2 = currentTextarea2.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
    const dom = new JSDOM(currentTextarea2);
    const liElements = dom.window.document.querySelectorAll('li');
    let liArray = [];
    liElements.forEach(li => {
        liArray.push(li.outerHTML);
    });
    console.log(liArray)           //The array of `<li>` elements will be displayed in the terminal 
});

```

### How does similar code behave in browsers?

When running the code on localhost, no errors occur. However, when attempting to host it on render.com, an error arises.

```js
/opt/render/project/src/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
      this[filesSymbol] ||= FileList.createImpl(this._globalObject);
                        ^^^
SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/render/project/src/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by asamuzaK** [comment]
Set nodejs version and try again.
See https://render.com/docs/node-version

I don't think it's an issue of jsdom.

**Comment by JAYAKANTHARUN** [comment]
The problem persists even with setting the Node.js version using environmental variables.

It's interesting to note that jsdom works smoothly with version 18.16.1 but encounters issues with version 20.9.0. It appears that jsdom support may vary across different Node.js versions, and setting the version via environmental variables doesn't entirely resolve the issue in version 20.9.0. 

I may not have the complete picture, so if there are any corrections or suggestions, please feel free to convey them.

**Comment by asamuzaK** [comment]
> It's interesting to note that jsdom works smoothly with version 18.16.1 but encounters issues with version 20.9.0.

Please show the error log on 20.9.0 or tell us the steps to reproduce it.

Thanks.

**Comment by domenic** [comment]
This is not an issue with jsdom, but instead with whatever environment you are running it in (apparently something called "render.com"). In Node.js v18, jsdom works fine.
