### ISSUE TITLE
Question about DOMException

### ISSUE THREAD

**Issue by asamuzaK** [jsdom/jsdom#3638]
Not an issue but a question related to #3628.
Node.js implemented global DOMException in v17.
Why does jsdom need there own DOMException?
This can be a problem if third-party modules that jsdom depends on use globalThis.DOMException.

### Basic info:

- **Node.js version:** v20.10.0 
- **jsdom version:** v23.0.1 

### Minimal reproduction case

```js
import { strict as assert } from 'node:assert';
import { JSDOM } from 'jsdom';
const { window } = new JSDOM();
const err = new window.DOMException();
assert.equal(err instanceof window.DOMException, err instanceof globalThis.DOMException);
// AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
// true !== false
```

### How does similar code behave in browsers?

Expected `globalThis.DOMException === window.DOMException`.

**Comment by domenic** [comment]
jsdom needs its own implementation of all classes, since they each need to be window specific. In browsers, `window1.DOMException !== window2.DOMException`, and we need to uphold that invariant in jsdom.
