### ISSUE TITLE
JSDOM Includes Head Elements in Body when an unknown html element is present in head

### ISSUE THREAD

**Issue by marcbuils** [jsdom/jsdom#3642]
### Basic info:

- **Node.js version: 20** 
- **jsdom version: 23** 

### Minimal reproduction case

```js
import { JSDOM } from 'jsdom';

const bodyHTML = `
<!DOCTYPE html>
<html lang="fr">
  <head>
    <ui5-shared-resources></ui5-shared-resources>
    <title>My title</title>
  </head>
  <body>
    <h1>My body</h1>
  </body>
</html>`;

const dom = new JSDOM(bodyHTML);
console.log(dom.window.document.body.innerHTML);
```

Display :
```
<ui5-shared-resources></ui5-shared-resources>
    <title>My title</title>
  
  
    <h1>My body</h1>
```

### How does similar code behave in browsers?

Display :
```
<h1>My body</h1>
```

**Comment by daavko** [comment]
Firefox 120, Chrome 120, and Safari 17.1.2 all output identically to JSDOM here, from what I checked. Moreover, custom elements are not valid in `<head>`, according to the HTML standard (see https://html.spec.whatwg.org/multipage/semantics.html#the-head-element , specifically the "Content model" bit). This seems like intended and correct behavior to me.

**Comment by domenic** [comment]
Indeed, this is why we often ask for a jsbin showing the results.
