### ISSUE TITLE
Load JSDOM in GJS

### ISSUE THREAD

**Issue by Zipdox2** [jsdom/jsdom#3677]
I would like to be able to use JSDOM in [GJS](https://gjs-docs.gnome.org/gjs/). AFAIK JSDOM is imported using CommonJS. GJS [only supports ES modules](https://gjs-docs.gnome.org/gjs/esmodules.md). How would I go about loading JSDOM?

**Comment by domenic** [comment]
I don't know; I suggest asking the GJS people. This is a Node.js project.
