### ISSUE TITLE
Raw parsing and serialization (HTML entities etc)

### ISSUE THREAD

**Issue by Eccenux** [jsdom/jsdom#3690]
### Basic info:

- **Node.js version:** 18.18.0 
- **jsdom version:** 24.0.0 

### Minimal reproduction case

JSDOM replaces some entities which makes it unsafe as an XML parser (at least when you want your changes to be as small as possible). I think there should be some mode where it doesn't touch anything.
```js
let header = `<?xml version='1.0' encoding='UTF-8'?>\n`;
// notice &quot; there
let xml = `
<root>
  <buildSteps>
    <hudson.plugins.groovy.SystemGroovy>
	  <command>
def scriptDir = &quot;/var/www/jenkins-groovy-helpers/JenkinsBuildHelper&quot;;
</command>
    </hudson.plugins.groovy.SystemGroovy>
  </buildSteps>
</root>
`;

const dom = new JSDOM(header + xml, { contentType: 'application/xml' });
const document = dom.window.document;
let srcSteps = document.querySelector('buildSteps');
for (let index = 0; index < srcSteps.children.length; index++) {
	const element = srcSteps.children[index];
	// BUG: outerHTML doesn't have entities
	console.log(index, element.outerHTML);
}
```

This comes from a small-ish repo and an issue I noticed when parsing Jenkins XML:
https://github.com/Eccenux/jenkins-postbuild-converter/issues/1

Seems like default parsing / serialization mode is doing some unsafe operations. Specifically changing HTML entities. This is bad because Jenkins expects almost all special characters to be saved as entities (even new lines in some cases).

### How does similar code behave in browsers?

N/A I think (serialization is a JSDOM thing AFAIK).

**Comment by domenic** [comment]
Serialization is a browser thing, and jsdom follows the spec at https://w3c.github.io/DOM-Parsing/#xml-serialization

Replacing entities is not unsafe; it's required by the parsing specification. See https://github.com/inikulin/parse5/issues/261#issuecomment-401389295 for a previous discussion.

**Comment by Eccenux** [comment]
OK, but this is not true:
> Replacing entities is not unsafe; it's required by the parsing specification. See https://github.com/inikulin/parse5/issues/261#issuecomment-401389295 for a previous discussion.

JSDOM is unsafe for parsing XML. Entities are not always exchangeable. Would be nice to state it in the docs so that people don't waste time on using JSDOM when in a specific use case it will not work.
