### ISSUE TITLE
Any way to disable implied tags/auto closing tags?

### ISSUE THREAD

**Issue by Vallek** [jsdom/jsdom#3698]
Hi! Is there a way to disable automatically putting head, body and auto closing tags? I know that's how browsers behave. But i use jsdom with html includes and don't need it.

**Comment by domenic** [comment]
Nope!

**Comment by Vallek** [comment]
Ok, thanks for quick answer)

**Comment by Vallek** [comment]
For those who will look for answer. You can remove strings with fs.readFile and fs.writeFile like this:
```
fs.readFile("path/file.html", 'utf8', function(err, data) {
		let removeOpen = data.replace('<html><head></head><body>', '');
		let removeEnd = removeOpen.replace('</aside></body></html>', '');
	
		fs.writeFile("path/file.html", removeEnd, 'utf8', function(err) {
			if (err) return console.log(err);
		});
	});
```
Put it inside `stream`

Or with gulp:

```
gulp.task('remove', function() {
	return src(['path/file.html'])
	.pipe(replace('<html><head></head><body>', ''))
	.pipe(replace('</aside></body></html>', ''))
	.pipe(dest('path/'));
});
```
Change tags to whatever you need for specific file. Not very scalable, although you can try with regex.
