### ISSUE TITLE
The script module will not retrieve the script from src and execute it

### ISSUE THREAD

**Issue by tocha688** [jsdom/jsdom#3704]
He doesn't know how to execute
`<script type="module" crossorigin="" src="/assets/index-d623a739.js"></script>`

Normal execution
` <script defer="" src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon="{&quot;rayId&quot;:&quot;8742246f29987b24&quot;,&quot;r&quot;:1,&quot;version&quot;:&quot;2024.3.0&quot;,&quot;token&quot;:&quot;f5a3b1e1fc5e473aa41dbeac542eaea4&quot;}" crossorigin="anonymous"></script>`

**Comment by domenic** [comment]
This issue does not follow the issue template.
