### ISSUE TITLE
Weird `Uint8Array` behaviour. Different classes?

### ISSUE THREAD

**Issue by raulfdm** [jsdom/jsdom#3711]
### Basic info

- **Node.js version:** v20.10.0
- **jsdom version:** 24

### Bug description

I have a setup that uses Vitest + JSDOM. There, we test Node code alongside with React components.

I wrote a tiny node function to generate JWT using an recommended library (jose) and just because we're using JSDOM, it fails its execution only in the test environment. If I remove `jsdom` from the environment, it works just fine.

But the weird part is that it isn't related to any Browser or anything because if I replace with `happy-dom`, it works without a problem.

I've recorded a video that shows in depth what's going on:

https://github.com/jsdom/jsdom/assets/12464600/8f533e68-59fd-498b-ba91-d1fa31f8f71b

### Minimal reproduction case

https://github.com/raulfdm/jsdom-jose-crypto-bug

### How does similar code behave in browsers?

Not applicable

**Comment by domenic** [comment]
Unfortunately, we can't debug interaction issues with third-party packages like vitest. If you are able to create a minimum reproduction case that follows the issue template, we can reopen this.

**Comment by raulfdm** [comment]
At first I got annoyed about the issue being closed like this @domenic , but this forced me to try this in full isolation and I finally found where the problem is: https://github.com/vitest-dev/vitest/issues/5685

Cheers 😄
