### ISSUE TITLE
JSDOM/whatwg-url is slow to parse URLs with long query string

### ISSUE THREAD

**Issue by tkrotoff** [jsdom/jsdom#3712]
### Basic info

- **Node.js version: 20.12.1** 
- **jsdom version: 24.0.0** 

### Minimal reproduction case

JSDOM/whatwg-url is slow to parse URLs with long query string.

This repo is an example with 500 [MSW](https://github.com/mswjs/msw) handlers: https://github.com/tkrotoff/jsdom-slow-URL-parsing

Results (MacBook Pro 16" M1, macOS 14.4.1, Node.js v20.12.1):

- Vitest `environment: 'node'`
  - JSDOM + MSW short URL: 23.951ms
  - JSDOM + MSW long URL: 27.046ms

- Vitest `environment: 'happy-dom'`
  - JSDOM + MSW short URL: 20.962ms
  - JSDOM + MSW long URL: 29.937ms

- Vitest `environment: 'jsdom'`
  - JSDOM + MSW short URL: 66.226ms
  - JSDOM + MSW long URL: **3.740s**

- Vitest `environment: 'jsdom'` + whatwg-url patched
  - JSDOM + MSW short URL: 34.554ms
  - JSDOM + MSW long URL: **126.326ms**

### Solution

Deprecate [JSDOM/whatwg-url](https://github.com/jsdom/whatwg-url) and remove this dependency in JSDOM.

URL and URLSearchParams have been implemented natively everywhere for quite some time:
- https://developer.mozilla.org/en-US/docs/Web/API/URL#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#browser_compatibility

Meanwhile here is a dirty patch:

```DIFF
diff --git a/node_modules/whatwg-url/lib/URL-impl.js b/node_modules/whatwg-url/lib/URL-impl.js
index eb66cae..1042729 100644
--- a/node_modules/whatwg-url/lib/URL-impl.js
+++ b/node_modules/whatwg-url/lib/URL-impl.js
@@ -244,3 +244,13 @@ exports.implementation = class URLImpl {
     this._url.path = this._url.path.replace(/\u0020+$/u, "");
   }
 };
+
+class URLImpl extends URL {
+  constructor(globalObject, constructorArgs) {
+    const url = constructorArgs[0];
+    const base = constructorArgs[1];
+    super(url, base);
+  }
+}
+
+exports.implementation = URLImpl;
diff --git a/node_modules/whatwg-url/lib/URLSearchParams-impl.js b/node_modules/whatwg-url/lib/URLSearchParams-impl.js
index 934c4ff..f4c3305 100644
--- a/node_modules/whatwg-url/lib/URLSearchParams-impl.js
+++ b/node_modules/whatwg-url/lib/URLSearchParams-impl.js
@@ -137,3 +137,12 @@ exports.implementation = class URLSearchParamsImpl {
     return urlencoded.serializeUrlencoded(this._list);
   }
 };
+
+class URLSearchParamsImpl extends URLSearchParams {
+  constructor(globalObject, constructorArgs) {
+    const init = constructorArgs[0];
+    super(init);
+  }
+}
+
+exports.implementation = URLSearchParamsImpl;
```

<br><br>

On our internal application (react-testing-library, jsdom, Vitest, MSW), we have seen tremendous performance increase on our CI thanks to this dirty patch.

**Comment by domenic** [comment]
We're happy with jsdom/whatwg-url as-is. jsdom is a projec meant to implement specifications from scratch for fun. Performance is a secondary objective for us.

**Comment by tkrotoff** [comment]
🤯 Wow

I've been spent hours to understand on our large code base why our react-testing-library tests were very slow and then a few more to create a repo with a clean reproduction of the issue.

Would be nice to clearly state at the top of the README that _jsdom is a project meant to implement specifications from scratch for fun. Performance is a secondary objective for us_
