### ISSUE TITLE
TypeError: resources must be an instance of ResourceLoader

### ISSUE THREAD

**Issue by Shramkoweb** [jsdom/jsdom#3717]
### Basic info:

- **Node.js version:** v20.12.2
- **jsdom version:** ^24.0.0

I am trying to update jsdom from `20` to `24`, and get an error:
  TypeError: `resources` must be an instance of `ResourceLoader`
### Minimal reproduction case

I used config same like in [your documentation ](https://github.com/jsdom/jsdom?tab=readme-ov-file#advanced-configuration), and this is worked before .

```js
import { TestEnvironment } from 'jest-environment-jsdom';
import { ResourceLoader } from 'jsdom';

class CustomResourceLoader extends ResourceLoader {
  fetch(url, options) {
    if (url === 'https://mock.local/success.js') {
      return Promise.resolve(Buffer.from(''));
    }

    if (url === 'https://mock.local/fail.js') {
      return Promise.reject();
    }

    return super.fetch(url, options);
  }
}

class CustomJSDOMEnvironment extends TestEnvironment {
  constructor(config, options) {
    super(
      {
        ...config,
        projectConfig: {
          ...config.projectConfig,
          testEnvironmentOptions: {
            ...config.projectConfig.testEnvironmentOptions,
            resources: new CustomResourceLoader(),
          },
        },
      },
      options
    );
  }
}

export default CustomJSDOMEnvironment;

```

It reproduces in 21, 22, 23, and 24 versions.

**Comment by domenic** [comment]
Unfortunately we cannot help debug issues with third party packages like jest-environment-jsdom. If you can rewrite this to follow the issue template and produce a file using only jsdom which we can run using `node test.js`, we can reopen.

**Comment by SimenB** [comment]
You'll need to match up jsdom version with `jest-environment-jsdom`. See https://github.com/jestjs/jest/issues/14954#issuecomment-1988729969 for an example of how to use your own version (e.g. 24)

**Comment by DanKaplanSES** [comment]
I think [my draft PR](https://github.com/jsdom/jsdom/pull/3883) may fix this, but I'm trying to find a way to reproduce it for an issue. I think there is a lot of useful information in there that should help someone learn what's going on.
