### ISSUE TITLE
jsdom querySelector is not working as normal when happened to "<section />" tag

### ISSUE THREAD

**Issue by AJLoveChina** [jsdom/jsdom#3725]
### Basic info:

- **Node.js version:** 
v20.13.1
- **jsdom version:** 
"jsdom": "^24.0.0",

### Minimal reproduction case

```js
const { JSDOM } = require("jsdom");

const xml = `
<div>
<spans>
  <span>1</span>
  <span>
    2
    <section2 />
  </span>
  <span>
    3
    <section />
  </span>
  <span>4</span>
</spans>
</div>`;

console.log(
  Array.from(
    new JSDOM(xml, {
      contentType: "text/html",
    }).window.document.querySelectorAll("div > spans > span"),
  ).map((item) => {
    return {
      innerHTML: item.innerHTML,
    };
  }),
);

```

The result is 
![image](https://github.com/jsdom/jsdom/assets/11222746/b8975197-cbb1-4f32-a328-7d0924b4b955)

It's wrong, it should be 4 items, not 3. The section tag is parsed in wrong way.

### How does similar code behave in browsers?

https://jsbin.com/wikama/edit?html,js,console

![image](https://github.com/jsdom/jsdom/assets/11222746/965c8caf-6210-48da-8aba-67c4fa3b1b55)

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
Your example in the jsbin uses the XML DOMParser. Your code in the reproduction case uses jsdom in HTML mode.
