### ISSUE TITLE
beforeParse can't remove script tags linking to files

### ISSUE THREAD

**Issue by OZZlE** [jsdom/jsdom#3726]
### Basic info:

- **Node.js version:** v20.14.0
- **jsdom version:** 24.1.0

### Minimal reproduction case

```js
  let dom = new JSDOM('<html><head></head><body><script src="/static/scripts/DTMFunctions.js?133471098090994052"></script></body></html>', {
    beforeParse(window) {
      window.document
        .querySelectorAll("script[src]")
        .forEach((el) => el.remove());
      window.document
        .querySelectorAll('[rel="preload"]')
        .forEach((el) => el.remove());
    },
  });
```

still keeps all the script tags but they should be removed, those that links to files at least

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by OZZlE** [comment]
tried also:

    let dom = new JSDOM(pageHtml, {
      beforeParse(win: any) {
        win.document.querySelectorAll("script").forEach((el) => {
          if (el.getAttribute("src")) {
            el.remove();
          }
        });
        win.document
          .querySelectorAll('[rel="preload"]')
          .forEach((el) => el.remove());
      },
    });

**Comment by domenic** [comment]
It's called `beforeParse` because it runs *before* the HTML you provide is parsed...
