### ISSUE TITLE
global object behaving differently

### ISSUE THREAD

**Issue by rahulmr123** [jsdom/jsdom#3727]
### Basic info:

- **Node.js version:** 20.0
- **jsdom version:** 24.1.0

When i run the below code in Node 16, Im getting correct out put.
But when I run the same code in Node 20, Getting reference error
```
   evalmachine.<anonymous>:5
    }; console.log(document)
                   ^
    
    ReferenceError: document is not defined
```

Im working on a legacy project, and we were injecting the window, documents etc to the global context created. 
In node 20, once you inject the code, its still not working.

### Minimal reproduction case

```js
const vm = require('node:vm');
const fs = require( "fs" );



const ctx = vm.createContext(global);
// ctx.window = window;
ctx.document = window.document;

try {
  const result = vm.runInContext(` console.log(document)`, ctx);
} catch(e) {
  console.log(e.stack, 'err1');
  console.log('x is', ctx.x)
}

```

### How does similar code behave in browsers?

(Link to a jsbin or similar strongly suggested.)

**Comment by domenic** [comment]
When I run your code in a file named `test.js` with `node test.js`, I get `window` being not defined. You need to define window.
