### ISSUE TITLE
Load local copy of jquery?

### ISSUE THREAD

**Issue by megablue** [jsdom/jsdom#379]
How do I load a local script file? I tried the code below, however i got nothing beside a null for errors.

jsdom.env("http://www.google.com", [
  __dirname + '/scripts/jquery-1.7.1.js'
],
function(errors, window) {
  $ = window.$;
  console.log(errors);
  console.log($().jquery);
});

however the code below worked as long as i am not fetching from a remote site.

jsdom.env("<p>testing</p>", [
  __dirname + '/scripts/jquery-1.7.1.js'
],
function(errors, window) {
  $ = window.$;
  console.log(errors);
  console.log($().jquery);
});

I found someone faced an exact same problem as mine on http://stackoverflow.com/questions/8480854/jsdom-env-local-jquery-script-doesnt-work

**Comment by rileybwesley** [comment]
Worked great! Nice tip :)
