### ISSUE TITLE
document is not defined in jest runtime

### ISSUE THREAD

**Issue by AnaniZhu** [jsdom/jsdom#3796]
### Basic info:

- **Node.js version:*20* 
- **jsdom version:*20.0.3* 

### Minimal reproduction case

There is a bug in the dependency of this repository on nwsap 2.2.14 version, which uses the document.xxx method internally, causing errors in the nodejs environment。

This is the problem identified when executing test cases with Jest:
![image](https://github.com/user-attachments/assets/cb720059-9ffe-48b7-b194-3c8ce53d3bad)

Temporarily resolve this issue by locking version nwsap@2.2.13

(Link to a jsbin or similar strongly suggested.)

**Comment by codev911** [comment]
i try solve by install as Dev Dependencies on my side too, by install this lib : [nwsapi@2.2.13](https://www.npmjs.com/package/nwsapi/v/2.2.13)
here screenshot after install it : 
![image](https://github.com/user-attachments/assets/672db0e0-f6e8-4416-b8cf-b09aac194b1a)
![image](https://github.com/user-attachments/assets/9c4acf82-937a-4137-8477-5d080f53fff7)

**Comment by AnaniZhu** [comment]
> i try solve by install as Dev Dependencies on my side too, by install this lib : [nwsapi@2.2.13](https://www.npmjs.com/package/nwsapi/v/2.2.13) here screenshot after install it : ![image](https://private-user-images.githubusercontent.com/53482087/391102469-672db0e0-f6e8-4416-b8cf-b09aac194b1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODgyNjIsIm5iZiI6MTczMjg4Nzk2MiwicGF0aCI6Ii81MzQ4MjA4Ny8zOTExMDI0NjktNjcyZGIwZTAtZjZlOC00NDE2LWI4Y2YtYjA5YWFjMTk0YjFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzNDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0ZTRlNWQ3YTM5YTY5M2M2ZTJmZjRiNWJkMDE4MmJhNTg2YzVkYzNmOTFlMzJiMTYzNDlkMTRkOTk0YjMxYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TSRHFs-N3AbIGNB6ioCSk4LViSOa2AXP-IVzzSJFoWc) ![image](https://private-user-images.githubusercontent.com/53482087/391102536-9c4acf82-937a-4137-8477-5d080f53fff7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4ODgyNjIsIm5iZiI6MTczMjg4Nzk2MiwicGF0aCI6Ii81MzQ4MjA4Ny8zOTExMDI1MzYtOWM0YWNmODItOTM3YS00MTM3LTg0NzctNWQwODBmNTNmZmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDEzNDYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTNjMTI3Y2MxODA0YzM0Mzc0MTQwMGFjMDAwMWM5ZTEzMDJjYTAzMjRmYWQwNzczYzFjOTIwNTJlMWI0NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Rux0567qbFeDkID6rEcn4QtTFYhVgY7VKSfD-FjM0g)

nwsap is an indirect dependency and requires version locking:

npm use [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)，yarn use [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/)

**Comment by codev911** [comment]
okey

**Comment by bencoveney** [comment]
Fixed in latest version of NWSAPI

**Comment by codev911** [comment]
> Fixed in latest version of NWSAPI

Not work on latest nwsapi, still work using 2.2.13 version

**Comment by domenic** [comment]
This issue does not follow the issue template, by providing a minimal reproduction case that we can run without any third-party software. As such, we'll close it, but if you're able to edit to follow the template, we can consider reopening.
