### ISSUE TITLE
Node.replacechild removes identical elements

### ISSUE THREAD

**Issue by JoshRagem** [jsdom/jsdom#444]
If two references of one element are passed to replaceChild, the element will be removed from the document. 

``` javascript
var el1 = document.getElementByID('blah');
var el2 = el1;
el1.parentNode.replaceChild(el1,el2);
var thisIsUndefined = document.getElementByID('blah');
var h = thisIsUndefined.innerHTML; //this is an error.
```

This happens because the replaceChild method calls insertBefore and then removeChild; the insertBefore has a check, el1===el2, that returns without altering the node list, then removeChild removes the element entirely.

**Comment by pmdartus** [comment]
This is already covered by WPT: https://github.com/web-platform-tests/wpt/blob/master/dom/nodes/Node-replaceChild.html#L279
