### ISSUE TITLE
Massive Memory Leaks, 100 loops

### ISSUE THREAD

**Issue by rauls** [jsdom/jsdom#466]
I basically did a test of 100 loops decoding a 10kb html page, that was simple, and only contained a table and 10 ROWS, with 38 data CELLS.
There is NO CSS, there is NO class names, just plain 1990s html.

Am I doing something wrong? Should I free something? I do need to call this decoder on 1000s of pages, but it barely gets to 500 until the process dies.

node-v0.8 memory results printed every 10 loops:
{ rss: 23052288, heapTotal: 16414464, heapUsed: 11052720 }
{ rss: 44204032, heapTotal: 37286144, heapUsed: 20598328 }
{ rss: 65110016, heapTotal: 57159168, heapUsed: 36111544 }
{ rss: 71761920, heapTotal: 64382720, heapUsed: 35709832 }
{ rss: 78684160, heapTotal: 70574336, heapUsed: 38881408 }
{ rss: 83673088, heapTotal: 74702080, heapUsed: 54306104 }
{ rss: 90898432, heapTotal: 80893696, heapUsed: 57606448 }
{ rss: 97910784, heapTotal: 89149184, heapUsed: 60812848 }
{ rss: 104034304, heapTotal: 94308864, heapUsed: 62109328 }
{ rss: 109240320, heapTotal: 98436608, heapUsed: 78288200 }

Node-v0.6.11 printed every 10 loops;
{ rss: 25526272, heapTotal: 17585280, heapUsed: 10782256 }
{ rss: 40357888, heapTotal: 32112768, heapUsed: 17500296 }
{ rss: 61333504, heapTotal: 53142208, heapUsed: 27617224 }
{ rss: 68038656, heapTotal: 59846400, heapUsed: 30513056 }
{ rss: 75681792, heapTotal: 67359424, heapUsed: 34469968 }
{ rss: 79060992, heapTotal: 70815104, heapUsed: 50902336 }
{ rss: 85581824, heapTotal: 77246912, heapUsed: 55379912 }
{ rss: 92008448, heapTotal: 83784896, heapUsed: 57894512 }
{ rss: 98906112, heapTotal: 90541824, heapUsed: 62839816 }
{ rss: 105295872, heapTotal: 96762560, heapUsed: 67425680 }

The code for my loop as follows;

```
for( var i=0; i< 100; i++ )
{
    jsdom.env( {
        html: htmldata, 
        scripts: [ "../javascript/jquery-min.js" ],             // jQuery JavaScript Library v1.6.2

        done: function(errors,win) {
            var $ = win.$;
            DEBUG( "  Process_New_Data html TR size is " + $("tr").length );
            var values = [];
            $("tr").each(function() 
            {
                $.each(this.cells, function()
                {
                    var v = $(this).text();
                    values.push(v);
                } );
            } );

            var found_link = 0;
            $("a").each(function() 
            {
                if( $(this).html() == '&gt;' ) {
                    found_link = 1;
                    var link = $(this).attr('href');
                    DEBUG("  Getting next new data ... " + link );
                }
            } );
        }
    } );

    if( i % 10 == 0 ) {
        console.log(util.inspect(process.memoryUsage()));
    }
}
```

**Comment by kavyaimversion** [comment]
> Any one any one? Beuller?
> 
> Memory still leaks, even with window.close();

Yup there is memory leak even after window.close

**Comment by TimothyGu** [comment]
@kavyaimversion Please file a new issue. Make sure to follow the issue template while doing so.
