### ISSUE TITLE
error installing jsdom on ubuntu

### ISSUE THREAD

**Issue by peterbarretto** [jsdom/jsdom#545]
I get the below error when i try to run :  npm install jsdom

> contextify@0.1.3 install /var/www/parser/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/nodejs/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/lib/nodejs/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/lib/nodejs/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:297:15)
gyp ERR! System Linux 3.2.0-31-virtual
gyp ERR! command "node" "/usr/lib/nodejs/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/parser/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.8.15
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm WARN optional dep failed, continuing contextify@0.1.3
jsdom@0.3.1 node_modules/jsdom
âââ cssom@0.2.5
âââ cssstyle@0.2.3
âââ htmlparser@1.7.6
âââ nwmatcher@1.3.0
âââ request@2.12.0

**Comment by justkrismanohar** [comment]
Need to run 
sudo apt-get update
sudo apt-get install build-essential
see http://ubuntuforums.org/showthread.php?t=83533
