### ISSUE TITLE
Issue with tagName case-sensitivity when creating SVG content.

### ISSUE THREAD

**Issue by lehni** [jsdom/jsdom#620]
I am using jsdom in paper.js to export SVG content. In order to export gradients, I am using the following command to create a SVG linearGradient node:

```
document.createElementNS('http://www.w3.org/2000/svg', 'linearGradient')
```

This results in a tag <lineargradient> in the output, so with a lowercased tagName, which is then not recognized by SVG parsers.

I assume this is a bug in jsdom?

**Comment by kirjs** [comment]
I could be taking a look at this issue and general SVG rendering is JSDom in one of the upcoming weekends, if anybody wants to pick it up ping me for details.

**Comment by missingdays** [comment]
This is still an issue in 6.5.1. I guess it hasn't been fixed?
Are there any news about proper svg parsing?

**Comment by kirjs** [comment]
I didn't get to it yet, not sure if anybody else did.

**Comment by joshma** [comment]
It looks like jsdom@7.0.2 does the casing correctly, can someone with better knowledge confirm?
```
document.createElementNS('http://www.w3.org/2000/svg', 'textPath').nodeName
// textPath
```
(We're currently on an older version of jsdom, so verifying this is fixed would help for our upgrade path.)

**Comment by domenic** [comment]
Yes, this appears to be fixed as of https://github.com/tmpvar/jsdom/commit/cdb677578e9d2f0e79fac250bcc94fbb43c18d6a! Nice. Will add a test to close this out.

**Comment by lehni** [comment]
This doesn't seem to be fully fixed unfortunately. The following still produces lowercase tag names:

```js
console.log(jsdom.serializeDocument(document.createElementNS('http://www.w3.org/2000/svg', 'textPath')));
```

**Comment by domenic** [comment]
I guess we fixed parsing, but not serialization. (Assuming you are using the latest version.) Will reopen.

**Comment by lehni** [comment]
Apologies for not mentioning the version. Yes this is with jsdom@7.2.2

**Comment by lehni** [comment]
I believe since 24c6f9f56b3e8f8831950cbef71130a3ba95a4dc, the example in https://github.com/tmpvar/jsdom/issues/620#issuecomment-169821043 is now throwing this error. I cannot use the `master` branch for any SVG generation currently.

```js
/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/documentAdapter.js:72
  return Boolean(node.tagName);
                     ^

TypeError: Cannot read property 'tagName' of null
    at Object.exports.isElementNode (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/documentAdapter.js:72:22)
    at Serializer._serializeChildNodes (/Users/lehni/Development/JavaScript/jsdom/node_modules/parse5/lib/serialization/serializer.js:71:34)
    at Serializer.serialize (/Users/lehni/Development/JavaScript/jsdom/node_modules/parse5/lib/serialization/serializer.js:57:10)
    at exports.domToHtml (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom/browser/domtohtml.js:15:25)
    at Object.exports.env.exports.jsdom.env.exports.serializeDocument (/Users/lehni/Development/JavaScript/jsdom/lib/jsdom.js:248:10)
    at Object.<anonymous> (/Users/lehni/Development/JavaScript/paper.js/examples/Node.js/test.js:18:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by lehni** [comment]
And this used to print an `Element`, now it's a `HTMLUnknownElement`:

console.log(document.createElementNS('http://www.w3.org/2000/svg', 'textPath'));

**Comment by Sebmaster** [comment]
This should probably both go in #1316.

**Comment by benwiley4000** [comment]
@domenic assuming parsing is a greater challenge than serialization, could you provide an example of why?

I fall into what is probably a good majority, who find it easier to come up with a use case-suited find-and-replace on the serialized output rather than focus on jsdom's serializer, but I'd also love for this to be fixed.

**Comment by purple-force** [comment]
A little different. When i set the attribute of svg by setAttribute('viewBox', '0 0 1024 1024'), the output is viewbox,it is lowercase and not recoginzed by browers. My jsdom is v14.1.0

**Comment by Sebmaster** [comment]
@purple-force You're setting the tag in the HTML namespace which is case insensitive. You need to set it in the SVG namespace.

Issue from the OP also seems fixed, so closing.
