### ISSUE TITLE
Strange body response

### ISSUE THREAD

**Issue by cytryn** [jsdom/jsdom#648]
Hi I am using this simple code to return the HTML since I was unable to do what I wanted and discovered that the body return was encoded:

``` js
    var jsdom = require("jsdom");
    jsdom.env(
        "http://pensador.uol.com.br/" + category,
        ["http://code.jquery.com/jquery.js"],
        function (errors, window) {
            var $ = window.$;
            console.log($('body').html());
            }
        );
```

Any reason why the response is this?

![screen shot 2013-06-26 at 7 20 19 am](https://f.cloud.github.com/assets/735750/708586/13fe4eba-de4a-11e2-8f94-915d6db548f7.png)

**Comment by OKNoah** [comment]
I ran in to this as well.

**Comment by domenic** [comment]
Not really. It's simpler just to compose with other tools that are well-known to to do the job.

**Comment by OKNoah** [comment]
I ran in to this problem which I didn't get with PhantomJS: https://github.com/tomas/needle/issues/116
