### ISSUE TITLE
Remove automatically added html and body tags from the dom

### ISSUE THREAD

**Issue by reggi** [jsdom/jsdom#710]
If there's `<style>` or `<link>` tags in the html (normally tags that should be in the `<head>`) I believe jsdom injects `<html>` and `<body>` tags into the document. I'm trying to return the edited jquery document without `<html>` and `<body>`, if the given HTML string didn't contain them. Any idea how to do this? 

I tried this in jquery

```
$("html").unwrap();
$("body").unwrap();
```

It gave an error

```
fragment = context.createDocumentFragment(),                               ^
TypeError: Cannot call method 'createDocumentFragment' of null
```

**Comment by atilkan** [comment]
@domenic I need this feature since i should not have body tags on my partial templates. This is required for both PHP and .Net Razor templates.
