### ISSUE TITLE
Checkbox click/change events are not received

### ISSUE THREAD

**Issue by ColemanGariety** [jsdom/jsdom#731]
I'm trying to check a checkbox with JSDOM

```
<input type="checkbox" id="foo" />
```

I assumed I could do it by dispatching two events, change, and click:

```
var clickEvent = new MouseEvent()
clickEvent.initMouseEvent('click', true, true)
document.querySelector('#foo').dispatchEvent(clickEvent)

var changeEvent = new Event()
changeEvent.initEvent('change', false, true)
document.querySelector('#foo').dispatchEvent(changeEvent)
```

This works in Chrome, Safari, and Firefox, the box becomes checked. But in JSDOM, nothing happens.

**Comment by Ugeorgel** [comment]
I spent about one week to trying test checkbox with Jest. My construction with dispatchEvent() didnt work, but you saved me... Thank you!
