### ISSUE TITLE
Cyrillic encoding

### ISSUE THREAD

**Issue by panayotoff** [jsdom/jsdom#747]
Hi, 

I'm trying to get cyrillic text from a webpage. The UTF-8 encoding does not return the proper text, and setting encoding to "Windows-1251" ( cyrillic ) gives me an error. Does somebody knows how to set the proper encoding?

**Comment by alexamy** [comment]
@panayotoff Stumbled upon the same error.  Adding `<meta charset="UTF-8">` in html code file (encoded in utf-8) helped.
