### ISSUE TITLE
require("jsdom") met Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by metrue** [jsdom/jsdom#757]
could someone help me here, I am sure I have installed the jsdom but when I require it, it give me the error message " Could not locate the bindings file. Tried:“

huangmh@peemt380:/remote/us01home41/huangmh# npm ls
/remote/us01home41/huangmh
└─┬ jsdom@0.10.4
  ├─┬ contextify@0.1.7
  │ ├── bindings@1.1.1
  │ └── nan@0.8.0
  ├── cssom@0.3.0
  ├── cssstyle@0.2.11
  ├─┬ htmlparser2@3.7.1
  │ ├── domelementtype@1.1.1
  │ ├── domhandler@2.2.0
  │ ├── domutils@1.4.1
  │ ├── entities@1.0.0
  │ └─┬ readable-stream@1.1.12
  │   ├── core-util-is@1.0.1
  │   ├── inherits@2.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.25-1
  ├── nwmatcher@1.3.3
  ├─┬ request@2.34.0
  │ ├── aws-sign2@0.5.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.1.2
  │ │ ├── async@0.2.10
  │ │ └─┬ combined-stream@0.0.4
  │ │   └── delayed-stream@0.0.5
  │ ├─┬ hawk@1.0.0
  │ │ ├── boom@0.4.2
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.9.1
  │ │ └── sntp@0.2.4
  │ ├─┬ http-signature@0.10.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.2
  │ │ └── ctype@0.5.2
  │ ├── json-stringify-safe@5.0.0
  │ ├── mime@1.2.11
  │ ├── node-uuid@1.4.1
  │ ├── oauth-sign@0.3.0
  │ ├── qs@0.6.6
  │ ├─┬ tough-cookie@0.12.1
  │ │ └── punycode@1.2.4
  │ └── tunnel-agent@0.3.0
  └── xmlhttprequest@1.6.0

huangmh@peemt380:/remote/us01home41/huangmh# node

> require("jsdom")
> Error: Could not locate the bindings file. Tried:
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/build/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/build/Debug/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/out/Debug/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/Debug/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/out/Release/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/Release/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/build/default/contextify.node
>  → /remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/compiled/0.10.26/linux/x64/contextify.node
>     at bindings (/remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:88:9)
>     at Object.<anonymous> (/remote/us01home41/huangmh/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
>     at Module._compile (module.js:456:26)

**Comment by arw180** [comment]
I'm having the same problem on CentOS 6.6 trying to run `newman` (https://github.com/a85/Newman), which in turn has a jsdom/contextify dependency, but doing the `node-gyp rebuild` in `contextify` is not fixing the issue. Also strange is that `contextify.node` does actually exist at one of the locations it claims to be checking (`/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/out/Release/contextify.node`).

My specific error output is:
```
usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/out/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/Debug/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/out/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/Release/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/build/default/contextify.node
 → /usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/compiled/0.10.33/linux/x64/contextify.node
    at bindings (/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/newman/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/newman/node_modules/jsdom/lib/jsdom/browser/index.js:5:21)
    at Module._compile (module.js:456:26)
```

**Comment by BlueVajra** [comment]
@arw180 have you figured out this problem? We have no problem with jsdom locally (not using newman) but CircleCI can't find the binding file...

**Comment by weitenghuang** [comment]
@BlueVajra , on your project's CircleCI build page, click "without cache" to rebuild it.
https://circleci.com/docs/how-cache-works
https://github.com/TooTallNate/node-bindings/issues/17
