### ISSUE TITLE
Memory leak!

### ISSUE THREAD

**Issue by Somebi** [jsdom/jsdom#763]
Oh come oooon mate, took me some time to figure out what is leaking my app.

```
// Get jquery code
var jquery = fs.readFileSync('jquery.js', "utf-8");

jsdom.env({
    html:row,
    src: [jquery],
    done: function (errors, window) {

    }
});
```

This code is leaking.

Throwing after a while:
FATAL ERROR: CodeRange::GetNextAllocationBlock Allocation failed - process out of memory.

I'm parsing a lot of pages.

**Comment by whyer11** [comment]
it still leak till now

**Comment by Somebi** [comment]
Guess no one cares :D I use it in a child process and kill after it have
done what i need
