### ISSUE TITLE
RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.

### ISSUE THREAD

**Issue by guileen** [jsdom/jsdom#769]
jsdom 0.10.5, node 0.11.13

``` js
var jsdom = require('jsdom');

jsdom.env('<p>hello world</p>', [__dirname + '/jquery.js'], function(err, window) {
        if(err) console.log(err.stack);
})
```

> RangeError: The normalization form should be one of NFC, NFD, NFKC, NFKD.
>     at String.normalize (native)
>     at null.src (/Users/gl/workset/hacktool/node_modules/jsdom/lib/jsdom/level2/html.js:222:21)
>     at /Users/gl/workset/hacktool/node_modules/jsdom/lib/jsdom.js:277:18
>     at Array.forEach (native)

**Comment by tugrul** [comment]
same error on node 6.9.4
