### ISSUE TITLE
window.$ is undefined under async code execution

### ISSUE THREAD

**Issue by akhabibullina** [jsdom/jsdom#787]
Hello!

I use mocha test runner under Cygwin and faced a problem loading jquery in any code snippets from README file here: https://github.com/tmpvar/jsdom/blob/master/README.md

For example:

```
// Print all of the news items on hackernews
var jsdom = require("jsdom");

jsdom.env({
  url: "http://news.ycombinator.com/",
  scripts: ["http://code.jquery.com/jquery.js"],
  done: function (errors, window) {
    var $ = window.$;
    console.log("HN Links");
    $("td.title:not(:last) a").each(function() {
      console.log(" -", $(this).text());
    });
  }
});
```

Inside the done() callback I have 'window' but 'window.$' appears undefined. I don't get any errors in console. After some research I came to the idea it is related to async unit tests execution.

Is there(or, are you going to add) async support for jsom.env and other functions?

Thanks in advance,
Anna.

**Comment by dgreene1** [comment]
I'm experiencing this too.

**Comment by Sebmaster** [comment]
@dgreene1 You'll need to provide a sample code, all posted examples in this thread work fine.

**Comment by dgreene1** [comment]
Thanks I'll do that @Sebmaster. I'm currently retesting my code and I'll update afterwards.
