### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by paha77** [jsdom/jsdom#875]
I've installed all the required modules (contextify, etc). to be able to use jsdom.

My "test file" looks like:

```
require('jsdom');
```

And on running "node test.js" I got the following:

```
/home/paha/nodejs/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
```

It's an ubuntu 14.04 LTS and v0.11.14-pre nodejs, 1.4.26 npm.

Thank you.

**Comment by yuniers** [comment]
Recently I installed node v0.12.2 and it error is present. The problem is contextify, I use v0.1.13?
```
/home/sosa/Dev/prueba-agenda/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/sosa/Dev/prueba-agenda/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/sosa/Dev/prueba-agenda/node_modules/jsdom/node_modules/contextify/lib/contextify.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by yuniers** [comment]
All is ok, I re installed jsdom and work fine. The developer of [bindings say it solution.](https://github.com/TooTallNate/node-bindings/issues/17)

**Comment by NickStefan** [comment]
im also getting this issue with 3.1.2 jsdom on node 12.

Im running jsdom in a mocha watcher, odd thing is that I never get this error on the first test run. I only get the error when the tests re-run.

I already tried re-installing jsdom and node 4 is not an option.

ideas?

**Comment by NickStefan** [comment]
okay. so my problem was related to this: https://github.com/sindresorhus/gulp-mocha/issues/86

in my case, im using a webpack watcher to run mocha tests, and have to clear the require cache every run. clearing the require cache except for anything jsdom or contextify related, solved the problem
