### ISSUE TITLE
Implement DOM selection apis

### ISSUE THREAD

**Issue by tolmasky** [jsdom/jsdom#937]
https://developer.mozilla.org/en-US/docs/Web/API/Window.getSelection

Even a nonfunctioning shim would go a long way. Currently I just do the following:

window.document.getSelection = function() { return { addRange: function() {}, removeAllRanges:function() { } } };

Just to avoid "cannot call undefined" when running getSelection().

**Comment by avk** [comment]
Any ideas on how to bake this into how Jest uses jsdom?

**Comment by domenic** [comment]
Not sure myself; @Sebmaster is a bit more familiar with jest, but I think the Jest issue tracker will be your best bet.

**Comment by avk** [comment]
@domenic thanks, got the shim I needed by adding a version of @tolmasky's code in a Jest helper:

```js
// spec/javascripts/helpers/jest-env.js
// window.getSelection isn't in jsdom
// https://github.com/tmpvar/jsdom/issues/937
window.getSelection = function() { 
  return { 
    addRange: function() {}, 
    removeAllRanges:function() {} 
  };
};
```

and linking to the above file via Jest's [config.setupEnvScriptFile](http://facebook.github.io/jest/docs/api.html#config-setupenvscriptfile-string).
